### ISSUE TITLE
Style guide for signatures

### ISSUE THREAD

**Issue by ariddell** [arviz-devs/arviz#1]
Here's the video from SciPy 2015. We are urged to use the following signature:

```
def my_plotter(ax, data, style):
    return artists
```

https://youtu.be/PmDUx62cTTs?t=762

So there's two things:
- argument sequence
- return artists not axes

p.s. It sounds like there are some changes coming in matplotlib that might make working with plots that have a lot of moving parts (e.g., lines + error bars) easier. https://www.youtube.com/watch?v=PmDUx62cTTs

**Comment by ahartikainen** [comment]
I think we follow this format now?

**Comment by canyon289** [comment]
Where are we returning artists?

**Comment by ahartikainen** [comment]
Oh yeah, we return axes, my bad.

**Comment by aloctavodia** [comment]
Nevertheless I think we are OK returning axes.

**Comment by canyon289** [comment]
I think so too. I'm ok closing this issue
