### ISSUE TITLE
Show API link en examples

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1000]
## Tell us about it

Currently each example in the gallery contains: an image, the code used to generate it, and a link to download the code. It would be great to add a link to the API section of the docs corresponding to the function used.

## Thoughts on implementation

This should happen automatically. A new feature should be added to `gallery_generator.py` using a reular expression to get the function name and then writing the corresponding link.

**Comment by percygautam** [comment]
@OriolAbril  I'd like to work on this issue.
