### ISSUE TITLE
Add group argument to plot pair

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1005]
## Tell us about it
Add a group argument (like the one in plot density) to plot pair.

Handling on divergences in this case may require extra modifications to plotting code.

**Comment by percygautam** [comment]
@OriolAbril I'd like to work on this issue. Kindly guide me through it. Can you explain more about the divergence param.

**Comment by ahartikainen** [comment]
`posterior` --> `sample_stats`

`prior` --> `sample_stats_prior`

**Comment by percygautam** [comment]
@ahartikainen Thanks.
