### ISSUE TITLE
Add transform argument 

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#1018]
A transform argument will allow users to pass a function that will be applied to one or more variables. This is related to pymc-devs/pymc3#3420 and pymc-devs/pymc3#3626

**Comment by amukh18** [comment]
I would like to work on this issue

**Comment by amukh18** [comment]
@aloctavodia Could you please give me a brief description of what "transformation of an MCMC sample" means?

**Comment by amukh18** [comment]
@aloctavodia I would also be grateful if you could link me to some resources that may give me an idea of what the transform function should do.

**Comment by ahartikainen** [comment]
Like `np.log` or `np.exp` done for the samples. So basically any transformation which might eat one more "variables" and outputs a new variable / variables.

**Comment by aloctavodia** [comment]
@amukh18 check [this](https://github.com/arviz-devs/arviz/blob/e23665cbda1e9cfcbee87a5aa70b601eeb74031a/arviz/plots/traceplot.py) from an early version of arviz

**Comment by amukh18** [comment]
@ahartikainen  I understand. Thank you!

**Comment by amukh18** [comment]
@aloctavodia So for the new argument would I need to create something like a new `identity_transform` function?

**Comment by ahartikainen** [comment]
I think it could be None by default (==identity_transform) and not do any transformations.
