### ISSUE TITLE
Tuning samples are included in effective sample size

### ISSUE THREAD

**Issue by michaelosthege** [arviz-devs/arviz#1022]
**Describe the bug**
When a PyMC3 trace containing tuning samples (`pm.sample(…, discard_tuned_samples=False)`), and the effective sample size is calculated, the tuning samples are not excluded from that calculation.

All PyMC3 samplers record a sampler stat `"tune"` indicating if a sample is from the tuning phase or not.

**To Reproduce**

```
import pymc3
import arviz

with pymc3.Model():
    x = pymc3.Normal('x', shape=(5,))
    trace = pymc3.sample(
        step=pymc3.Metropolis(),
        tune=1000, draws=1000,
        discard_tuned_samples=False
    )

print(arviz.ess(trace))
print(arviz.ess(trace[1000:]))
```

**Expected behavior**
Tuning samples should not be included in convergence diagnostics.

**Additional context**
ArviZ version is `0.6.1`

**Comment by aloctavodia** [comment]
Hi @michaelosthege 

After an internal discussion we think we should not address this issue and intead we should let the user to directly selects the samples she/he pass to ArviZ. While we can auto-remove the tuned samples (from PyMC3) for diagnostics only this will be inconsistent. Also AFAIK, PyStan and emcee always return samples after tuning, thus this should be a PyMC3-exclusive feature also contributing to inconsistencies from the ArviZ point of view.

**Comment by michaelosthege** [comment]
Hi @aloctavodia,
Good point that they are not present by default.
What do you think about slicing the tuning samples into their own group in `InferenceData` when `arviz.from_pymc3()` is used?

e.g.

```
Inference data with groups:
	> posterior
	> sample_stats
        > tuning_samples
```

Then they would be excluded from the diagnostics (default behavior) but they won't get lost.

**Comment by ahartikainen** [comment]
Then we would also need to add 

    > tuning_posterior
    > tuning_sample_stats
    > tuning_posterior_predictive
    > tuning_prior
    > tuning_sample_stats_prior
    > tuning_prior_predictive

**Comment by michaelosthege** [comment]
Hm. That doesn't look nice either.
The thing is that I definitely have to save the tuning iterations for later debugging, but having to find out the number of tuning steps & slicing the `InferenceData` contents is also super inconvenient.

Is there a recommended way to attach additional metadata? (Package version, duration of sampling, ...)

**Comment by aloctavodia** [comment]
I think it is better to use xarray selection options. 

```python
mask = az_trace.sample_stats.tune.values[0]
tuning_trace = az_trace.sel(draw=mask)
post_tuning_trace = az_trace.sel(draw=~mask)
```

Or something like 

```python
az_trace.sel(draw=slice(1000, 2000))
```

We have a GSoC [project](https://github.com/arviz-devs/arviz/wiki/GSoC-2020-projects#extend-InferenceData-capabilities) that will potentially make these type of selections easier and/or more powerful.

**Comment by michaelosthege** [comment]
Thanks, I'll see how far I can get with this.
