### ISSUE TITLE
arviz.plot_joint does not accept group argument

### ISSUE THREAD

**Issue by Dpananos** [arviz-devs/arviz#1026]
**Describe the bug**
When attempting to pass the `group` argument to `arviz.plot_joint`, an error is given

```python
TypeError: plot_joint() got an unexpected keyword argument 'group'
```

This despite the fact the docs list `group` as a keyword argument.

**To Reproduce**
Using python 3.7

```python
import arviz as az
print(az.__version__)

rugby_data = az.load_arviz_data("rugby")

az.plot_joint(rugby_data, var_names = ['intercept','sd_att'], group ='prior')
```

**Expected behavior**
Plot the joint distribution from the given InferenceData group.

**Comment by Dpananos** [comment]
Oh, don't tell me this functionality was *just* committed three days ago...

**Comment by OriolAbril** [comment]
Yes, it has not been released yet, and currenty docs are built only for development version. Sorry about the misunderstanding
