### ISSUE TITLE
plot_posterior writes auto instead of point estimate name

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1031]
**Describe the bug**
`plot_posterior` should write the name of the point estimate, however it currently writes `auto` if `auto` is passed as point estimate. This can be seen in the [docs example](https://arviz-devs.github.io/arviz/examples/matplotlib/mpl_plot_posterior.html)

**Expected behavior**
It should write the name of the point estimate used (taken from rcParams).

**Additional context**
ArviZ master

**Comment by nitishp25** [comment]
Hi @OriolAbril, I would like to work on this.
