### ISSUE TITLE
matplotlib kwarg de-aliasing helper function

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1041]
## Tell us about it

There are many kwarg arguments in matplotlib that accept an alias, which can get quite messy when ArviZ sets default values for them. I propose to pass the kwarg dicts through this helper function and then always work internally with the complete name.

## Thoughts on implementation

Use a matplotlib internal function if it exists? Otherwise we should create one (or several, see note).

Note: some aliases are not universal like the case of color and c in a scatter plot.

References that may (or not) be useful: [Line2D properties](https://matplotlib.org/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D) and [Collection properties](https://matplotlib.org/api/collections_api.html#matplotlib.collections.Collection)

**Comment by percygautam** [comment]
I'll like to work on this one!

**Comment by percygautam** [comment]
I  found the kwarg normalization in matplotlib [here](https://github.com/matplotlib/matplotlib/blob/85a96fb38b0facd824b52e2ff45899a6b0a071d7/lib/matplotlib/cbook/__init__.py#L1717). This function is then used like this [here](https://github.com/matplotlib/matplotlib/blob/85a96fb38b0facd824b52e2ff45899a6b0a071d7/lib/matplotlib/artist.py#L1077) to set properties.
Are we looking for something like this? I think we can create a helper function which calls this `normalize_kwargs` function from matplotlib and will set properties( as is done in case of matplotlib).

**Comment by ahartikainen** [comment]
Yes, something similar.

**Comment by percygautam** [comment]
Hey, I was working some examples in the [cookbook](https://github.com/percygautam/arviz-examples/blob/master/de-Aliasing%20helper%20function.ipynb). Can you please confirm this is what we are looking for.
Also, Should we create multiple `de-aliaser` dicts or just add all in one ? Even if user add some wrong kwarg, matplotlib can handle the errors.

**Comment by percygautam** [comment]
@ahartikainen Should I make different functions for scatter plots and other plots, or use conditionals in one function?
