### ISSUE TITLE
Cookbook entry for cmdstanpy outdated

### ISSUE THREAD

**Issue by MooersLab** [arviz-devs/arviz#1048]
**Describe the bug**

The "Inference Data Cookbook" is outdated for CmdStanPy.

This no longer works:
```python
from cmdstanpy import Model, StanFit
```

Replace with 

```python
from cmdstanpy import CmdStanModel
```
and then replace in the code below `Model` with `CmdStanModel`.

`StanFit` is no longer needed.

**Comment by amukh18** [comment]
I would like to work on this!

**Comment by pawanakhil** [comment]
Can I work on this ?

**Comment by amukh18** [comment]
@pawanakhil I apologise but I have already been working on this issue. I was fixing some errors in my local repo before making a pull request.

**Comment by pawanakhil** [comment]
@amukh18  Hey buddy I accept  , but  I am new to this world of opensource and want to make by first contribution. So , this open issue found easy for me as it requires only change in InferenceDataCookbook.ipynb and check for errors if any. Can you please allow me to do so ?

**Comment by amukh18** [comment]
@pawanakhil Ok. Please go ahead. And welcome to open source!

**Comment by canyon289** [comment]
@pawanakhil and @amukh18 We're excited that you both want to work on this PR, and @pawanakhil super excited you want to make your first contribution.

Typically though if someone claims and issue and has a PR open the issue has been claimed. @pawanakhil in this case I'm going to reopen @amukh18's pull request. Once his merged you're welcome to pull down master and add on your changes as well!

**Comment by canyon289** [comment]
@pawanakhil A great issue you can work on is adding inline examples to to psislw. It is also a relatively straightforward contribution and I'd be happy to talk you through it. Will create an issue for you to claim if you like! https://arviz-devs.github.io/arviz/generated/arviz.psislw.html#arviz.psislw

**Comment by pawanakhil** [comment]
Oh thank you @canyon289. @amukh18 sorry for the inconvenience. Go ahead with it.

**Comment by amukh18** [comment]
@pawanakhil Not at all!
