### ISSUE TITLE
Explain naming convention in sample_stats

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1053]
The section on sample stats group in [InferenceData scheme](https://arviz-devs.github.io/arviz/schema/schema.html#sample-stats) is missing a description of the naming convention and what does every variable represents. 

The bullet points should be extended with variables still missing and all explanations added/improved. After this is done, it may be interesting to have something like [`SUPPORTED_GROUPS`](https://github.com/arviz-devs/arviz/blob/master/arviz/data/inference_data.py#L14-L26) for sample stats variables.

**Comment by nitishp25** [comment]
Hi @OriolAbril, I found the [PyMC3 sample statistics](https://docs.pymc.io/notebooks/sampler-stats.html) description. Can I update the current descriptions with these ones?

**Comment by OriolAbril** [comment]
This is a good start! Good work, thanks 

There are some things to be noted before starting: different libraries, different samplers and schema specification style. 

First is to use ArviZ names, most will be the same, but some will differ (e.g. `model_logp -> lp`) it is currently not explained anywhere so you'll have to read `io_pymc3` and `io_pystan` to check the name used in ArviZ and that the name convention is coherent (maybe some less used quantities keep different names depending on the original inference library). 

Then, ArviZ also has to account for the multiple samplers available (if you check the end of the page you linked you'll see that Metropolis has some different sample_stats). 

And finally, the schema specification should ideally be clear and concise, thus, I think we should only describe the variable, not explain how is is used/why is it useful (which should be explained in the educational material).

**Comment by nitishp25** [comment]
@ahartikainen can you please explain what ```n_leapfrog``` describes?

**Comment by ahartikainen** [comment]
Hi, see https://mc-stan.org/docs/2_22/reference-manual/hmc-algorithm-parameters.html

NUTS and its Configuration
The no-U-turn sampler (NUTS) automatically selects an appropriate number of leapfrog steps in each iteration in order to allow the proposals to traverse the posterior without doing unnecessary work.

**Comment by nitishp25** [comment]
Thanks for the help!
