### ISSUE TITLE
Add inline example to psislw

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1057]
Add inline docs to psislw. @pawanakhil You're welcome to claim this one first!

https://arviz-devs.github.io/arviz/generated/arviz.psislw.html#arviz.psislw

**Comment by pawanakhil** [comment]
Yeah  , I will work on this .

**Comment by canyon289** [comment]
Great! This PR is a really good example on how to add extra examples to docs. https://github.com/canyon289/cargo_analysis/pull/1

Instructions on how to compile the docs should be in `CONTRIBUTING.md` if you run into issues feel free to reach out!

**Comment by smit-s** [comment]
@canyon289  This issue doesn't seem to have been addressed. Can I work on this?

**Comment by aloctavodia** [comment]
@smit-s I think you can work on this. Thanks in advance!

**Comment by smit-s** [comment]
@aloctavodia  Inline example does not exist for r2_score. Shall I add an example for it as well?

**Comment by OriolAbril** [comment]
Yes! We created independent issues for some functions to make the tasks more accessible, but all functions missing it would welcome an example in the docstring, see #491. (exceptions would probably be `from_xyz` methods if compiling and running the model takes a lot of time as it would slow doc generation)
