### ISSUE TITLE
Automatic Wheel Build in CI for Releases

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1078]
## Tell us about it
When we cut a release branch it would be nice for CI to build us a fresh wheel that we can locally upload to pypi

## Thoughts on implementation
Modify the azure yml file to include a build pipeline that only triggers on release branch merge
Have that pipeline build a wheel that can be downloaded

cc @ahartikainen

**Comment by canyon289** [comment]
@ahartikainen this happened right?

**Comment by ahartikainen** [comment]
https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=2037&view=artifacts&type=publishedArtifacts

**Comment by canyon289** [comment]
Closing
