### ISSUE TITLE
Histogram distribution plot fails on hist, succeeds on KDE

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#1104]
**Describe the bug**
I was plotting posterior data from an InferenceData object, and the KDE worked fine.  But I was interested to see more exactly what the samples looked like, so I tried plotting with a histogram instead.  This errored out, with the backtrace below.

To the extent I can tell, it looks like Arviz grabbed up a multi-dimensional array (`chains` x `samples` x `inputs`, 4 x 500 x 4) and instead of flattening it -- as the KDE seems to have done -- or splitting it out into four plots for the `inputs` dimension), it errored out.

**To Reproduce**
Steps to reproduce the behavior. Ideally a self-contained snippet of code, or link to a notebook or external code. Please include screenshots/images produced with ArviZ here, or the stacktrace including `arviz` code to help.

```
import arviz as az
idata = az.from_netcdf('/Users/rpg/Dropbox/arviz-hist-bug.nc')  
az.plot_dist(idata.posterior['err_sd'])  # works fine
az.plot_dist(idata.posterior['err_sd'], kind='hist')   # error in np.reshape()
```

**Expected behavior**
I expected to get a histogram plot, or possibly four.

Alternatively, if I was using this wrong, I would expect to get an error for the KDE case as well as the basis case.

**Additional context**

* Arviz version was today's `master`.
* NetCDF file to reproduce the error is here: https://www.dropbox.com/s/181nuxivbkqr8ck/arviz-hist-bug.nc?dl=0

# Backtrace

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-c027c32088dc> in <module>
----> 1 az.plot_dist(idata.posterior['err_sd'], kind='hist')

~/src/arviz/arviz/plots/distplot.py in plot_dist(values, values2, color, kind, cumulative, label, rotated, rug, bw, quantiles, contour, fill_last, textsize, plot_kwargs, fill_kwargs, rug_kwargs, contour_kwargs, contourf_kwargs, pcolormesh_kwargs, hist_kwargs, ax, backend, backend_kwargs, show, **kwargs)
    197 
    198     plot = get_plotting_function("plot_dist", "distplot", backend)
--> 199     ax = plot(**dist_plot_args)
    200     return ax

~/src/arviz/arviz/plots/backends/matplotlib/distplot.py in plot_dist(values, values2, color, kind, cumulative, label, rotated, rug, bw, quantiles, contour, fill_last, textsize, plot_kwargs, fill_kwargs, rug_kwargs, contour_kwargs, contourf_kwargs, pcolormesh_kwargs, hist_kwargs, ax, backend_kwargs, show)
     47     if kind == "hist":
     48         ax = _histplot_mpl_op(
---> 49             values=values, values2=values2, rotated=rotated, ax=ax, hist_kwargs=hist_kwargs
     50         )
     51 

~/src/arviz/arviz/plots/backends/matplotlib/distplot.py in _histplot_mpl_op(values, values2, rotated, ax, hist_kwargs)
     93     bins = hist_kwargs.pop("bins")
     94 
---> 95     ax.hist(values, bins=bins, **hist_kwargs)
     96     if rotated:
     97         ax.set_yticks(bins[:-1])

~/.virtualenvs/xplan-dev-env/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1599     def inner(ax, *args, data=None, **kwargs):
   1600         if data is None:
-> 1601             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1602 
   1603         bound = new_sig.bind(ax, *args, **kwargs)

~/.virtualenvs/xplan-dev-env/lib/python3.6/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, density, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, normed, **kwargs)
   6686         input_empty = np.size(x) == 0
   6687         # Massage 'x' for processing.
-> 6688         x = cbook._reshape_2D(x, 'x')
   6689         nx = len(x)  # number of datasets
   6690 

~/.virtualenvs/xplan-dev-env/lib/python3.6/site-packages/matplotlib/cbook/__init__.py in _reshape_2D(X, name)
   1428         return [np.reshape(x, -1) for x in X]
   1429     else:
-> 1430         raise ValueError("{} must have 2 or fewer dimensions".format(name))
   1431 
   1432 

ValueError: x must have 2 or fewer dimensions
```

**Comment by OriolAbril** [comment]
A flatten is missing. To get 4 plots, `plot_posterior` should be used (with `point_estimate=None` and `credible_interval=None` to get a `plot_dist` look).

However, I have just seen that `credible_interval=None` used to be no black line indicating credible interval but became using value in rcParams, so 2 things to get fixed, the flatten in plot_dist and making `"auto"` the default to use rcParams credible interval and `None` to remove line from plot.

**Comment by rpgoldman** [comment]
@OriolAbril Thanks.  That helped.  BTW, I tried using `plot_posterior` instead, and passed it axes, because I wanted to stack the four plots (with `sharex`) for easier comparison.

I find that the Arviz plots put their suptitles way up high, which means it's hard to stack them without them overlapping.  Presumably using `Figure.adjust_subplots()` can fix this, but I haven't been able to figure out a value of `hspace` that does anything useful.

**Comment by smit-s** [comment]
Hi, there  @OriolAbril  @rpgoldman . I am new here and would like to take up this issue. I have already solved half of it locally .I would like to solve it.  Will you assign me this issue please?

**Comment by OriolAbril** [comment]
No need to be assigned, with issues with nobody working on them just say you'll work on it in order to avoid duplicated work. We have a more detailed description on the [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#steps-before-starting-work).

We count you are working on it now, do not hesitate to ask for guidance if you were to need any.

**Comment by smit-s** [comment]
Yes @OriolAbril , I have started working on it.  I have already added the "flatten" and it seems to work fine.
Can you please explain what do you mean by 'making "auto" the default to use rcParams credible interval'. Here, what does 'making "auto" the default' mean?

**Comment by OriolAbril** [comment]
Currently the [`credible_interval` default](https://github.com/arviz-devs/arviz/blob/master/arviz/plots/posteriorplot.py#L25) is `None`, in which case, the value stored in [`rcParams` is used](https://github.com/arviz-devs/arviz/blob/master/arviz/plots/posteriorplot.py#L192). However, this should not be the behaviour, what should happen is:

* `credible_interval="auto"` -> use value in rcParams (default)
* `credible_interval=None` -> keep none and pass it to backend so that no credible interval line is plotted
* `credible_interval=<float in 0-1>` -> use this value
* Otherwise, raise an error.

You'll see in the code that the 2 last cases already behave as desired, however, the 2 first ones do not, this is what should be fixed.

**Comment by smit-s** [comment]
@OriolAbril  , I have made the required changes but, I would like to highlight another possible problem related to this issue as follows-
`import arviz as az
idata = az.from_netcdf('arviz-hist-bug.nc')
idata=az.convert_to_inference_data(idata)
az.plot_posterior(idata.posterior['err_sd'],point_estimate=None,credible_interval=None)
`
When we run above code we get following error:

**Trace**
Traceback (most recent call last):
  File "F:/ppts/gsoc/repro.py", line 5, in <module>
    az.plot_posterior(idata.posterior['err_sd'],point_estimate=None,credible_interval=None)
  File "F:\ppts\gsoc\arvizinst\lib\site-packages\arviz-0.7.0-py3.8.egg\arviz\plots\posteriorplot.py", line 184, in plot_posterior
    data = convert_to_dataset(data, group=group)
  File "F:\ppts\gsoc\arvizinst\lib\site-packages\arviz-0.7.0-py3.8.egg\arviz\data\converters.py", line 170, in convert_to_dataset
    inference_data = convert_to_inference_data(obj, group=group, coords=coords, dims=dims)
  File "F:\ppts\gsoc\arvizinst\lib\site-packages\arviz-0.7.0-py3.8.egg\arviz\data\converters.py", line 126, in convert_to_inference_data
    raise ValueError(
ValueError: Can only convert xarray dataset, dict, netcdf filename, numpy array, pystan fit, pymc3 trace, emcee fit, pyro mcmc fit, numpyro mcmc fit, cmdstan fit csv filename, cmdstanpy fit to InferenceData, not DataArray

Is this correct behaviour?
I think Dataarrays should be allowed. Actually case of dataarray is not handled in file converters.py. I tried converting dataarays to dataset by making changes to converters.py and it seems to work fine and is creating 4 seperate plots as shown
![Figure_1](https://user-images.githubusercontent.com/46646070/76449049-63272780-63f1-11ea-90a6-badeaa9a3fdb.png)
 
What is your opinion on this?

**Comment by ahartikainen** [comment]
It is not supported for now.

There are "problems" for assuming do we have draws + shape or chain + draws +shape.

Does Dataarray contain axis names? And coordinates? I mean if we have a good way handle these, then we should implement these.

**Comment by OriolAbril** [comment]
It would be a good idea to add dataarray case to convert to inference data. It'd be great if you could make a PR for each feature. 

I have two comments on the code above. To plot only err_sd, you should use `plot_posterior(idata, var_names="err_sd",...)` which will give the same result.

The second comment is that even though credible interval is None, the line is still there :thinking:

**Comment by smit-s** [comment]
@ahartikainen  Yes, Dataarray has all these information. You can refer following text which shows structure of dataarray for the data used in this issue.:-
**<xarray.DataArray 'err_sd' (chain: 4, draw: 500, inputs: 4)>
array([[[0.349232, 0.397905, 0.305724, 0.462783],
        [0.351129, 0.355431, 0.321792, 0.45228 ],
        ...,
        [0.341998, 0.380817, 0.327994, 0.457156],
        [0.341984, 0.375206, 0.304112, 0.454296]],

       [[0.347209, 0.404756, 0.313015, 0.481429],
        [0.363504, 0.358405, 0.306595, 0.442791],
        ...,
        [0.350266, 0.387707, 0.299635, 0.467976],
        [0.350385, 0.357717, 0.311677, 0.468736]],

       [[0.359636, 0.36991 , 0.307549, 0.485616],
        [0.345125, 0.393463, 0.312975, 0.442222],
        ...,
        [0.36076 , 0.382268, 0.312243, 0.464333],
        [0.345349, 0.375962, 0.309493, 0.461748]],

       [[0.345877, 0.384308, 0.291982, 0.430833],
        [0.32866 , 0.380016, 0.308015, 0.477437],
        ...,
        [0.332496, 0.379478, 0.326116, 0.461871],
        [0.348474, 0.363466, 0.293123, 0.489218]]])
Coordinates:
  * chain    (chain) int64 0 1 2 3
  * draw     (draw) int64 0 1 2 3 4 5 6 7 8 ... 492 493 494 495 496 497 498 499
  * inputs   (inputs) object '00' '01' '10' '11'**


@OriolAbril I am sorry for posting the wrong image previously. The correct image for that code snippet is 
![Figure_1](https://user-images.githubusercontent.com/46646070/76454561-e6994680-63fa-11ea-9607-74651f353a17.png).

And also, I would like to add support for DataArray if possible. But, first I will make a pull request for existing issue.
Also, for adding dataarray shall I create another issue or should I send a seperate pull request?

**Comment by ahartikainen** [comment]
You can create another PR for Dataarray

**Comment by smit-s** [comment]
Ok, I will create another PR.
