### ISSUE TITLE
Add `Matplotlib` framework classifier to `setup.py`

### ISSUE THREAD

**Issue by hectormz** [arviz-devs/arviz#1108]
`Matplotlib` now has a [trove classifier on pypi](https://twitter.com/matplotlib/status/1235216347925286913). We can add:

```python
classifiers = [
    'Framework :: Matplotlib',
    ]
```
to `arviz`'s `setup.py` to acknowledge that it is part of `Matplotlib` ecosystem.

I believe that `arviz` currently doesn't have any classifiers ([there are many!](https://pypi.org/classifiers/)). We could add something like the following to `setup.py`:

```python
classifiers = [
    'Framework :: Matplotlib',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: Apache Software License'
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Topic :: Scientific/Engineering :: Visualization',
    ]
```

I'm not sure if you would say if `arviz` is:
```
'Development Status :: 5 - Production/Stable',
```
or
```
'Development Status :: 4 - Beta',
```

There may be thoughts on other classifiers to add, but I can quickly put together a PR for this

**Comment by OriolAbril** [comment]
We are definitely still beta! 

Also, we are not as strict as [NEP 29 recommends](https://numpy.org/neps/nep-0029-deprecation_policy.html) but python versions should be 3.6, 3.7 and 3.8


Possible ideas, `Intended Audience :: Education`? I'm not really sure about the scope of the classifiers

**Comment by hectormz** [comment]
@OriolAbril I figured beta, but thought it'd be best for a maintainer to say so!

I realized I wasn't sure which versions `arviz` supports but I grabbed this from `README`:

>ArviZ is tested on Python 3.5, 3.6 and 3.7, and depends on NumPy, SciPy, xarray, and Matplotlib.

Should that be updated to 3.6, 3.7, 3.8 as well?

I don't see why  `arviz` couldn't be filed as Education. There's quite a lot of options if someone is motivated to read through them all. 😀

**Comment by OriolAbril** [comment]
> Should that be updated to 3.6, 3.7, 3.8 as well?

Yes, we recently updated CI builds, we don't run tests on 3.5 anymore

**Comment by hectormz** [comment]
@OriolAbril @canyon289 @ahartikainen @aloctavodia and any others, do you have any additional thoughts on other itemz worth adding here?


Otherwise I can make a PR with additions @OriolAbril and I have discussed.

**Comment by ahartikainen** [comment]
https://pypi.org/search/?c=Topic+%3A%3A+Scientific%2FEngineering+%3A%3A+Mathematics
https://pypi.org/search/?c=Topic+%3A%3A+Scientific%2FEngineering+%3A%3A+Visualization

?

ref. https://pypi.org/classifiers/

**Comment by aloctavodia** [comment]
About the topic, I guess we can have the generic one, and then two specifics

Topic :: Scientific/Engineering   
Topic :: Scientific/Engineering   ::  Mathematics
Topic :: Scientific/Engineering   ::  Visualization

**Comment by hectormz** [comment]
Sure I can draft a PR and see if it's satisfactory
