### ISSUE TITLE
Skip tests relying on absent optional/external libaries

### ISSUE THREAD

**Issue by hectormz** [arviz-devs/arviz#1112]
**Describe the issue**
`Arviz` is meant to use/interact with external libraries that are optional, found in `requirements-external.txt`, `requirements-optional.txt`, with tests found in `/tests/external-tests/`. I'd propose making these tests optional when the other libraries aren't installed, so someone not touching those areas could run tests locally without installing all the packages.

**Suggested change**
In [`pyjanitor`](https://github.com/ericmjl/pyjanitor/blob/dev/tests/spark/conftest.py) we support the use of some optional, external libraries and skip tests if the libraries can't be loaded.

I propose modifying the test files to something like this:
```python
try:
    import emcee
except ImportError:
    emcee= None

@pytest.mark.skipif(emcee is None, reason="emcee tests only required for CI")
def some_emcee_test():
```

CI should still run as is, but it'd be a bit easier for new people to get involved and test without the external libraries. 

One issue with this is at least once instance with this (for `pyro` at least) is when a `skipif` decorator is also checking for `pyro.version` which will cause an error when it is `None` etc.

**Comment by ahartikainen** [comment]
We could probably do that.

I currently run only the testfile. It might be a bit inconvenient.

    pytest arviz/.../pystan_tests_file.py

**Comment by OriolAbril** [comment]
I also like the idea, it'd be great if you can make a PR, in the meantime, another alternative is to use the `k` flag, something like `pytest arviz/tests/ -k "not bokeh and not pyro" ` would skip all tests with bokeh or pyro in name.

**Comment by hectormz** [comment]
@OriolAbril  I wasn't aware of that skip, is that built into `pytest`? nice!

I was looking into the `pytest.mark.skipif` documentation and found there is an option to skip tests based on missing a dependency: [`pytest.importorskip`](https://docs.pytest.org/en/latest/skipping.html?highlight=skipping#skipping-on-a-missing-import-dependency)

Assuming that our tests for external libraries are in separate files, this might work well. In `test_data_pyro.py`, the imports
```python
import torch
import pyro
from pyro.infer import Predictive
```

can be replaced with
```python
torch = pytest.importorskip("torch")
pyro = pytest.importorskip("pyro")
Predictive = pytest.importorskip("pyro.infer.Predictive")
```

I believe the whole file will be skipped if one of those imports fails. No other decorators need to be added to the classes/tests. I think this minimal code change is ideal, as long as the changes to imports are clear/commented well, and `pylint` is silenced about no longer seeing these imports as imports.

**Comment by hectormz** [comment]
I have a working solution for almost all tests. One hiccup is `numba`. Is it unreasonable to move it from `requirements-optional.txt` to `requirements-dev.txt`? It's embedded in 20+ tests across different files. The items in `requirements-dev.txt` are about linting and formatting, but it might be reasonable to include `numba` there as part of developing. Otherwise, we could add decorators to each of those tests.

**Comment by OriolAbril** [comment]
Did #1113 completely fix the issue?

**Comment by hectormz** [comment]
Yes it did (from my perspective). You can close this now if it works for you.
