### ISSUE TITLE
True values in pair_plot

### ISSUE THREAD

**Issue by andersdot** [arviz-devs/arviz#1131]
During testing of a model, it would be nice to be able to over plot the true values in the plot_pair matrix, similar to the over plotting of the point estimates of the samples. This could be a dictionary the user feeds into a keyword argument like `true_values={'var1':0.1, 'var2':5.0}`

**Comment by agustinaarroyuelo** [comment]
Hello! Tank you for opening this issue. Here is an example of what you suggested:
![true_values_example](https://user-images.githubusercontent.com/8028618/78562013-08fe6400-77ef-11ea-9090-f5f8613b0e1f.png)

The red dots are the `true_values`. I'm working on the details right now :)

**Comment by canyon289** [comment]
Thanks for the contribution @agustinaarroyuelo
