### ISSUE TITLE
Just updated arviz to 0.7.0 and now traceplot doesn't seem to work?

### ISSUE THREAD

**Issue by JSenta** [arviz-devs/arviz#1141]
**Describe the bug**
I was having the same issue described in arviz #988, with spurious warnings "Argument backend_kwargs has not effect in matplotlib.plot_dist" showing up when I tried to trace plot. (The traceplots would still appear, but the warnings were getting unwieldy). 

In an effort to fix this, I reinstalled Anaconda from scratch, then used pip to update to the latest arviz 0.7.0.  Now I can't traceplot at all. I get the following error: 
ImportError: cannot import name 'calculate_point_estimate' from 'arviz.plots.plot_utils'
It looks like this error originates with the following line:
from .densityplot import plot_density

Any assistance with this would be much appreciated!

**Comment by ahartikainen** [comment]
Hi, what does this say

    import arviz as az
    print(az.__version__)

**Comment by JSenta** [comment]
Hi, currently that says 0.7.0. I may force a pip reinstall back to 0.6.1 in the meantime so I can use pm.traceplot though.

**Comment by OriolAbril** [comment]
Does installing ArviZ with: `pip install git+git://github.com/arviz-devs/arviz.git` fix the issue?

**Comment by JSenta** [comment]
Hi, thanks! I just did a fresh install using pip install git+git://github.com/arviz-devs/arviz.git and that appears to have fixed the problem!
