### ISSUE TITLE
negative values WAIC and ranking of the models

### ISSUE THREAD

**Issue by aakhmetz** [arviz-devs/arviz#1147]
Dear all,

Recently I have recalculated the WAIC values for one of my model and I obtained negatives. I assume it could be Ok, but I also obtained negative WAIC values in another model and it looks a bit strange, because it is supposed to be rare. 

When I ran the same model several months ago, I obtained positive values, because I recorded them.

**To Reproduce**
The model looks simple
```
    with pm.Model() as model:
        lnβ = pm.Normal('lnβ', -10, 25, testval=-10.)

        k = pm.HalfNormal('k', 10)
        pm.NegativeBinomial('likelihood', tt.exp(lnβ)*df_cases_mvm['value'].values, k, 
                   observed=df_cases_mvm['n'].values+1e-4)

        trace = pm.sample(2500, tune=10000, init='advi', cores=8, target_accept=.96)
```

When I compare two models with different values ```df_cases_mvm['value']``` by calculating their WAIC values, I get:
```
	rank	waic	p_waic   	d_waic	weight	se       	dse  	warning	waic_scale
uniform  	0	-31.1934	1.6926	0	0.936256	3.82451	0	False	log
radiation	1	-35.1037	2.39027	3.91028	0.0637444	4.96992	1.84548	True	log
```
Two months ago it was 62.4 vs 70.2 for the first model versus second, and that time I chose the first. From another side, if WAIC is negative and I need to choose the model with the minimal WAIC value, then the second "radiation" model should be ranked first, not the "uniform". Am I correct?

Another issue is when I compare two models and "staking" method, then the weight is always 0.5. I assume that the staking method should work for comparizon of two models, no?

**Expected behavior**
I would expect positive WAIC values and/or correct ranking.

**Additional context**
I regularly update arviz and pymc3 using github.

**Comment by OriolAbril** [comment]
Hi, in version 0.7.0 we modified the default scale of `waic` and `loo` from `deviance` to `log`, you can see the scale used for in the rightmost column of the result. There are 3 possibilities for scale in ArviZ, as described in the [docs](https://arviz-devs.github.io/arviz/generated/arviz.waic.html#arviz.waic). 

The default was previously set to deviance (-2 * log) for historical reasons. The -2 is quite arbitrary and except in a handful of cases it has no meaning whatsoever. Using log scales makes both waic and p_waic be on the same scale which should ease the interpretation of the results.

We also changed the default in `compare` from `waic` to `loo`. If you rely on the specific defaults, you should either pass them explicitly to the functions or use a custom [`arvizrc`](https://github.com/arviz-devs/arviz/blob/master/arvizrc.template) file.

**Comment by aakhmetz** [comment]
Hi @OriolAbril - many thanks for your response! You saved my soul yesterday!

About question for staking, I will try ask about it on discource
