### ISSUE TITLE
Convert forestplot to xarray

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#115]
Wanted to open an issue, since this is tricky, and I do not want to get too far away from the current implementation while doing this.

I have copied the current version I have below.  Notice that the styling is slightly different: notably there is one subplot for each variable being plotted.  Happy to hear any thoughts, otherwise I am going to keep working on getting all the options from the current version working here!

![image](https://user-images.githubusercontent.com/2295568/42193343-0aa2c5ac-7e3c-11e8-8937-7a1ad3107fdf.png)

**Comment by aloctavodia** [comment]
Probably would look nicer if we use a single plot and instead of using the titles for variables names we use labels on the right or left axis.
