### ISSUE TITLE
Animations in Plot PPC seem to be broken

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1153]
**Describe the bug**
`animated=True` in `plot_ppc` with mpl backend raises an Exception and no animation can be sene

![image](https://user-images.githubusercontent.com/7213793/79677700-09acd800-81a9-11ea-8a84-32272dce1689.png)

**To Reproduce**
```
import matplotlib.pyplot as plt
import arviz as az

az.style.use("arviz-darkgrid")

data = az.load_arviz_data("non_centered_eight")
az.plot_ppc(data, alpha=0.03, figsize=(12, 6), textsize=14, animated=True)
```

**Expected behavior**

**Additional context**
Arviz Version '0.7.0'

**Comment by aloctavodia** [comment]
You need to set `%matplotlib notebook` I will add this to the docstring and see if we can raise a more useful error.
