### ISSUE TITLE
Best practices with plot_kde

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#1157]
## Short Description

I was trying to redo some of the plot_kde plots for the "rat tumor" example of Chapter 5 BDA3, building on the notebooks in [the PyMC3 resources repo](https://github.com/pymc-devs/resources/tree/master/BDA3).  I had a couple of problems, that may be more documentation issues than anything else:

1. It seems that one must label the x and y axes in a separate call -- there doesn't seem to be any way to specify the x and y axis labels in the call to `plot_kde`.  This seems normal enough to want to do that it should be supported.  Perhaps it's supported by one of the keywords arguments, but I couldn't figure out how and the examples in the docs weren't sufficient to figure it out.

2. I tried to use the `contour_kwds` argument to set the number of contours, but that didn't seem to work. Again, an example would have helped.

I had two less specific issues, that may be related:

1. In general I couldn't easily figure out how to use the extra keyword arguments, and I couldn't find examples.

2. The ArviZ plots I did ended up looking significantly uglier than the Seaborn plots that were in the old version of the notebook. I could use some help figuring out how to style the ArviZ plots.

## Code Example or link

From the diagram, here is the seaborn contour plot:

![image](https://user-images.githubusercontent.com/3274/79713372-32110100-8293-11ea-918f-3dacdf72fbc3.png)

and here is the best ArviZ equivalent I could come up with.  It's not very impressive:

![image](https://user-images.githubusercontent.com/3274/79713406-5371ed00-8293-11ea-9f63-58def748b9b6.png)

The seaborn code is as follows:

```
fig, ax = plt.subplots(figsize=(8, 7))
sns.kdeplot(np.log(alpha_trunc /  beta_trunc), np.log(alpha_trunc + beta_trunc),
            cmap=plt.cm.viridis, n_levels=11, ax=ax)
# ax.set_xlim(1.5, 2.1)
ax.set_ylim(1.7, 3.75)
ax.set_xlabel('log(alpha / beta)')
ax.set_ylabel('log(alpha + beta)');
```

and here's what I came up with as an ArviZ alternative:

```
fig, ax = plt.subplots(figsize=(8, 7))

az.plot_kde(values2=idata_10.posterior['log(alpha + beta)'], values=idata_10.posterior['log(alpha / beta)'], ax=ax,
                contour=True, 
                contour_kwargs={'levels': 10,}) # Setting different levels here does not have any effect.
    
# ax.set_xlim(1.5, 2.1)
ax.set_ylim(1.7, 3.75)
ax.set_xlabel('log(α / β)')
_ = ax.set_ylabel('log(α + β)')
```

I'm not sure why it looks so bad. Possibly seaborn's style sheet is messing up the ArviZ plot but... I don't know how styling works with ArviZ.  There's an example in the gallery that uses `az.style`, but `az.style` does not appear in the online API docs page.

I cargo-culted in `az.style.use("arviz-darkgrid")` from the ArviZ gallery, but it didn't change my grayscale contour plot.

For full details of what I was trying to do, see [my fork of BDA3](https://github.com/rpgoldman/resources/blob/version-updates/BDA3/chap_05.ipynb).

ArviZ version: master at 8f1677cfd985b2b553dc52571943a830adc29d1c

**Comment by aloctavodia** [comment]
Hi @Robert, thanks for the report.

The grayscale is weird because Matplotlib's default cmap is viridis, I guess you change it somewhere and thus you are seeing a gray scale.

Below there are a few examples of customizing the plots. Probably we should add a few to the gallery and/or docstring.

```
az.style.use("arviz-darkgrid")
data = {"a":np.random.normal(0, 1, size=1000), "b":np.random.normal(0, 2, size=1000)}
```


```
az.plot_kde(values2=data["a"], values=data["b"], 
                    contour=True, fill_last=False) 
```

![00](https://user-images.githubusercontent.com/1338958/79755907-391a2c80-82f0-11ea-81d6-51020816f6ef.png)


```
az.plot_kde(values2=data["a"], values=data["b"],
                contour=True, fill_last=False, contour_kwargs={"alpha":0})
```
![01](https://user-images.githubusercontent.com/1338958/79756026-636bea00-82f0-11ea-8d4d-e80fd6aef064.png)

```
az.plot_kde(values2=data["a"], values=data["b"],
            contour=True, fill_last=False, 
            contour_kwargs={"colors":None, "cmap":plt.cm.viridis},
            contourf_kwargs={"alpha":0});
```
![02](https://user-images.githubusercontent.com/1338958/79756035-66ff7100-82f0-11ea-8434-20b91ac78626.png)

```
az.plot_kde(values2=data["a"], values=data["b"],
            contour=True, fill_last=False, 
            contour_kwargs={"colors":None,"cmap":plt.cm.viridis,"levels":2},
            contourf_kwargs={"alpha":0.5, "levels":2});
```
![03](https://user-images.githubusercontent.com/1338958/79756343-de350500-82f0-11ea-8397-85d448f1bb06.png)

**Comment by canyon289** [comment]
@rpgoldman is this closed?
