### ISSUE TITLE
Fix Typo in arviz.hpd docs

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1163]
**Describe the bug**
Maximum is spelled incorrectly
https://arviz-devs.github.io/arviz/generated/arviz.hpd.html#arviz.hpd
![image](https://user-images.githubusercontent.com/7213793/79937387-94424100-840e-11ea-8f08-ff6a68f5b5a4.png)

**Comment by AlexAndorra** [comment]
I'm currently working on [a PR modifying this file](https://github.com/arviz-devs/arviz/pull/1154) -- I'll take care of this typo

**Comment by gauraws** [comment]
Hi, I am beginner, can I work on this issue?

**Comment by OriolAbril** [comment]
Yes, we have a [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md) that should guide you through the process, and if it were not the case, please let us know, ask here or on [gitter](https://gitter.im/arviz-devs/community) and we'll try to help.

**Comment by AlexAndorra** [comment]
Hi,
I already took care of this issue in #1154 but you can look at the other beginner-friendly issues on this repo, like #1166 for instance.
Oriol already pointed to the useful references. Thanks and good luck :)

**Comment by AlexAndorra** [comment]
This can be closed thanks to #1154

**Comment by canyon289** [comment]
Closing as this is fixed
