### ISSUE TITLE
Import fails when run using a Bokeh server

### ISSUE THREAD

**Issue by golmschenk** [arviz-devs/arviz#1177]
**Description of bug**
The import of `arviz` errors when running with a [Bokeh server](https://docs.bokeh.org/en/latest/docs/user_guide/server.html).

The resulting error is:
```
output_notebook.__doc__ += "\n\n" + _copy_docstring("bokeh.plotting", "output_notebook") Traceback (most recent call last):
  File "/Users/golmschenk/Code/ramjet/venv/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/Users/golmschenk/Code/ramjet/minimal_example/main.py", line 1, in <module>
    import arviz
  File "/Users/golmschenk/Code/ramjet/venv/lib/python3.7/site-packages/arviz/__init__.py", line 31, in <module>
    from .plots import backends
  File "/Users/golmschenk/Code/ramjet/venv/lib/python3.7/site-packages/arviz/plots/backends/__init__.py", line 195, in <module>
    output_notebook.__doc__ += "\n\n" + _copy_docstring("bokeh.plotting", "output_notebook")
TypeError: can only concatenate str (not "NoneType") to str
```

**To Reproduce**

1. Have `bokeh` and `arviz` installed.
2. Create a Python file which only contains `import arviz`.
3. From the terminal, run `bokeh serve <file_name>.py`.
4. Open the localhost server link in a browser.

**Expected behavior**
`arviz` should be imported without error.

**Additional context**
`arviz` appears to be setting a docstring based off `_copy_docstring("bokeh.plotting", "output_notebook")`, however, in this context, `_copy_docstring("bokeh.plotting", "output_notebook")` is `None`.

Package versions:
```
arviz==0.7.0
bokeh==2.0.1
```

**Comment by golmschenk** [comment]
A workaround for the time being is to explicitly force `output_notebook`'s docstring to be a value before importing `arviz`. For example, the following code allows `arviz` to import without error.
```
from bokeh import plotting
plotting.output_notebook.__doc__ = ''
import arviz
```

**Comment by ahartikainen** [comment]
Thanks for the temporary solution. Let's fix that docstring function to handle None.
