### ISSUE TITLE
Using grayscale style raises exception

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1181]
**Describe the bug**
Trying to use grayscale colormap is causing an exception

**To Reproduce**
```
import matplotlib.pyplot as plt
from matplotlib import style
import arviz as az
from scipy import stats

style.use("https://raw.githubusercontent.com/arviz-devs/arviz/master/arviz/plots/styles/arviz-grayscale.mplstyle")
dist = stats.norm().rvs(100)
az.plot_dist(dist)
```

**Expected behavior**
No exception occurs
![image](https://user-images.githubusercontent.com/7213793/81520579-97d43400-92f9-11ea-860c-b344d4ba0ee7.png)

**Additional context**
matplotlib                3.2.1

**Comment by canyon289** [comment]
Alright some more context. `colorcet` has to be installed and imported. Then it works. i don't know if this is occurring because I'm loading the style sheet over the web install of installing it through ArviZ. Will leave this issue open in the meanwhile until certain that grayscale "easily" works


![image](https://user-images.githubusercontent.com/7213793/81520686-d7028500-92f9-11ea-8af3-329cf4ab14b9.png)

**Comment by ahartikainen** [comment]
Why does it need colorcet to be installed?

**Comment by OriolAbril** [comment]
For the style to work, colormap `cet_grey` has to be available to matplotlib, this is done in ArviZ init iirc to make the style work once ArviZ has been imported, otherwise you have to manually make the colormap available or use colorcet to make the colormap known to matplotlib

**Comment by aloctavodia** [comment]
@OriolAbril is right. if you install arviz from master `cet_grey` and `cet_grey_r` will be available without needing to install colorcet.
