### ISSUE TITLE
Inconsistent capitalization in `plot_hdi` docstring

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1193]
**Describe the bug**
Docs have inconsistent capitalization
![image](https://user-images.githubusercontent.com/7213793/82233398-d020d700-98e4-11ea-812c-588628ed753e.png)

**To Reproduce**
https://arviz-devs.github.io/arviz/generated/arviz.plot_hdi.html#arviz.plot_hdi

**Expected behavior**
Consistency across arg docstrings

**Comment by neha-shah99** [comment]
Hey, I'm new to Open Source and would like to contribute and work on this issue. How can I help?
