### ISSUE TITLE
Pairwise `arviz.compare`

### ISSUE THREAD

**Issue by oscarbranson** [arviz-devs/arviz#1195]
When using `arviz.compare` all models are referenced to a single 'best' model. It would be nice if it were possible to output a matrix comparing a metric of all models to every other model

For example, a hacky implementation developed for the [PyMC3 port of Statistical Rethinking (2nd Edition, Chapter 7)](https://github.com/pymc-devs/resources/pull/86#pullrequestreview-413901756):

```python
import numpy as np
import pandas as pd
import pymc3 as pm

# number of plants
N = 100
# simulate initial heights
h0 = np.random.normal(10, 2, N)
# assign treatments and simulate fungus and growth
treatment = np.repeat([0,1], N/2)
fungus = np.random.binomial(n=1, p=0.5 - treatment * 0.4, size=N)
h1 = h0 + np.random.normal(5 - 3 * fungus, size=N)
# compose a clean data frame
d = pd.DataFrame.from_dict({'h0': h0, 'h1': h1, 'treatment': treatment, 'fungus': fungus})

with pm.Model() as m_6_6:
    p = pm.Lognormal('p', 0, 0.25)
    
    mu = pm.Deterministic('mu', p * d.h0)
    sigma = pm.Exponential('sigma', 1)
    
    h1 = pm.Normal('h1', mu=mu, sigma=sigma, observed=d.h1)
    
    m_6_6_trace = pm.sample()

with pm.Model() as m_6_7:
    a = pm.Normal('a', 0, 0.2)
    bt = pm.Normal('bt', 0, 0.5)
    bf = pm.Normal('bf', 0, 0.5)
    
    p = a + bt * d.treatment + bf * d.fungus
    
    mu = pm.Deterministic('mu', p * d.h0)
    sigma = pm.Exponential('sigma', 1)
    
    h1 = pm.Normal('h1', mu=mu, sigma=sigma, observed=d.h1)
    
    m_6_7_trace = pm.sample()

with pm.Model() as m_6_8:
    a = pm.Normal('a', 0, 0.2)
    bt = pm.Normal('bt', 0, 0.5)
    
    p = a + bt * d.treatment
    
    mu = pm.Deterministic('mu', p * d.h0)
    sigma = pm.Exponential('sigma', 1)
    
    h1 = pm.Normal('h1', mu=mu, sigma=sigma, observed=d.h1)
    
    m_6_8_trace = pm.sample()

def pairwise_compare(dataset_dict, metric='dse', **kwargs):
    """
    Calculate pairwise comparison of the specified metric for all provided models.
    
    Parameters
    ----------
    dataset_dict : dict
        A dict containing two ore more {'name': pymc3.backends.base.MultiTrace}
        items.
    metric : str
        The name of the matric to be calculated. Can be any valid column output
        by `arviz.compare`. Note that this may change depending on the **kwargs
        that are specified.
    kwargs
        Arguments passed to `arviz.compare`
    """
    data_dict = dataset_dict.copy()
    dicts = []
    
    while len(data_dict) > 1:
        c = az.compare(data_dict, **kwargs)[metric]
        dicts.append(c.to_frame(name=c.index[0]))
        del data_dict[c.index[0]]
    
    return pd.concat(dicts, axis=1)  # edit here to remove erroneous .dropna() call.

dataset_dict = {
    'm_6_6' : m_6_6_trace,
    'm_6_7' : m_6_7_trace,
    'm_6_8' : m_6_8_trace
}

pairs_compared = pairwise_compare(dataset_dict, metric='dse', ic='loo', scale='deviance')

print(pairs_compared)

         m_6_7    m_6_8
m_6_8  12.8614        0
m_6_6  15.0681  6.92766
```

**Comment by ahartikainen** [comment]
That sounds one option we could have

**Comment by OriolAbril** [comment]
I [commented](https://github.com/pymc-devs/resources/pull/86#discussion_r423972588) in the PR linked above, I am having trouble following the code, but I think it does not do pairwise comparisons

**Comment by oscarbranson** [comment]
I replied to your comment on the PR, @OriolAbril. I'm pretty sure it's producing pairwise comparisons *as long as the metric that's being compared is symmetric*. It works because the `compare` functions compares all models to a 'best' model, then I remove that 'best' model and re-run `compare` on the remaining models. When only 2 models remain, all pairs have been compared! 

The function above produces output that's identical to the original code suggested by @aloctavodia, and seems to scale correctly to *n* models. In my reply in the PR I've added some comments to the original code so it's hopefully clearer how it works.

**Comment by OriolAbril** [comment]
I am possibly not understanding properly the goal to begin with, sorry. I basically see 2 situations, not sure what I am missing :sweat: 

* for most of the parameters (ic, ic_se, dse) computing `loo`/`waic` (pointwise=True) once and then compare pairwise should be enough right? thus, this approach will call the ic functions `(n-1)!` times more than needed
* for weights, it gets tricky when it comes to normalization, I'm not really sure how to tackle it but with a little care it can be done (I'm not even sure they would make sense as metric though)

If the first point were to actually apply, the solution could be quite straightforward, allowing `compare` to take as input either inference data or ELPDdata (like [plot_elp](https://arviz-devs.github.io/arviz/generated/arviz.plot_elpd.html#arviz.plot_elpd) does) would solve the extra computations

**Comment by oscarbranson** [comment]
Ah yes - I see my misunderstanding. I think my implementation is more coding and less thinking! 

To check I've understood, when you say 'compare pairwise', is it valid to just calculate the difference between all pairs? i.e. for a case where you have three models A, B and C, you would use `compare` once, and then for pairwise comparison just manually calculate `A - B`, `A - C`, `B - C` to get the pairwise stats for your chosen metric?

**Comment by aloctavodia** [comment]
@OriolAbril is right that this could be computed moretomography efficiently. Probably the only interesting thing to compute is the dse pairwise matrix, not the other pairwise quantities, but not sure they are that useful either, other than to reproduce the example in statistical rethinking.

**Comment by AlexAndorra** [comment]
Yeah I'm wondering that too: is there a use case for this in a realistic modeling workflow?
I _think_ we already get this info with the original dse and, most of all, with the `plot_compare`. So I don't see a clear use case right now, but maybe you guys do?

**Comment by aloctavodia** [comment]
Closing as we agree this is generally not that useful in a realistic modeling workflow. Feel free to reopen if you disagree
