### ISSUE TITLE
Mismatch between docs and conda install

### ISSUE THREAD

**Issue by oscarbranson** [arviz-devs/arviz#1196]
**Describe the bug**

I have installed `arviz` using `conda forge`. The output of `conda list arviz` is:

```
# Name                    Version                   Build  Channel
arviz                     0.7.0                      py_0    conda-forge
```

However, a number of capabilities that are listed in the [API docs](https://arviz-devs.github.io/arviz/api.html) for 0.7.0 do not seem to be present.

**Examples**

[**plot_trace**](https://arviz-devs.github.io/arviz/generated/arviz.plot_trace) lists `kind` as a valid argument, but:

```python
az.plot_trace(trace, kind='trace');

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-6f1c4c628a37> in <module>
----> 1 az.plot_trace(trace, kind='trace');

TypeError: plot_trace() got an unexpected keyword argument 'kind'
```

[**plot_pair**](https://arviz-devs.github.io/arviz/generated/arviz.plot_pair) lists `marginals` as a valid argument, but:

```python
az.plot_pair(trace, marginals=True);

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-ebec06bb8769> in <module>
----> 1 az.plot_pair(trace, marginals=True);

TypeError: plot_pair() got an unexpected keyword argument 'marginals'
```

**Additional context**
```
az.__version__

'0.7.0'
```

**Comment by OriolAbril** [comment]
Docs are built on the master branch, not on latest release, I'll close as it is the same as #896, it would be great to have docs for both stable and dev versions
