### ISSUE TITLE
Refactor interface (datastructure)

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#12]
Hi, 

I suggest that we refactor the interface to have a common data structure. I created this issue so we could start working on these.

In pystan we get Ordered dict with

    odict = fit.extract()

and with pymc3

    from itertools import OrderedDict
    odict = OrderedDict()
    for name in trace.varnames:
        odict[name] = trace.get_values(name)

These have a common structure considering only the data. Sample size is on the first axis.

Most of the plots do not need chain number etc (excluding forestplot etc). I have tested these with needed modifications and it works with results from both libraries.

The other "problems" are logp (not a problem) and possibility to extract priors and other information.

Both pystan and pymc3 have a possibility to call logp with a function call so these should be handled. 

Also there are functions from pymc3 that need to be handled.

ps. Some naming conventions

- `trace` vs `traces` / `Multitrace`
- `burn-in` vs `warm-up`

**Comment by twiecki** [comment]
That makes sense to me. Before changing any code here, however, we should copy the most recent plotting code from pymc3 over.

**Comment by ahartikainen** [comment]
Hi,
here are some remarks considering the future.

## Main interface
We should make the main interface to read in correctly created (Ordered)dictionary.
Then we could read also fit objects from pymc3 / pystan.

## External functions
Do we need to implement some general calculations (Rhat, WAIC etc).

## Refactor for the library
I also propose a refactor for the plotting code. The plotting could be a process.
- function that reads in fit object / dictionary and gathers all (meta, xy) data for plotting
  - function that outputs trace specific data (for plotting)
- function that actually plots (could be bokeh or matplotlib)

## Only numpy dependency (optional for matplotlib / bokeh, no scipy)
Can we make a plotting library without a dependency for real plotting library?

## Examples for plotdata generating functions
I have created some examples for plotdata creation functions  (following the current codebase).
- hist
  - calculate with numpy.histogram
  - plot with bar or step functions
- kde
  - calculate with numpy.fft
  - follows fast_kde method
  - plot with lineplot
- violin
   - kde/histogram flipped
   - plot with lineplot
- autocorr / xcorr
   - numpy.fft based calculation
   - plot with lineplot
- forest
    - plot with lineplot / fillplot

Still missing some functionality. 

[see here a jupyter notebook](https://github.com/ahartikainen/mcmcplotlib/blob/ahartikainen_example-data_generating_functions/mcmcplotlib/example_data/function_op_for_mcmcplotlib.ipynb)
[or here a link for the folder](https://github.com/ahartikainen/mcmcplotlib/tree/ahartikainen_example-data_generating_functions/mcmcplotlib/example_data).

## Real-time plotting (pystan/pymc3/others)
Do we want to support real-time plotting?

**Comment by ariddell** [comment]
All of this sounds fine to me in general terms.

re: dependencies. I think we can/must depend on matplotlib (>=2.0). It would be nice to only depend on that and numpy, in my opinion.

re: real-time plotting. I haven't seen any demand for this.

**Comment by ahartikainen** [comment]
current pymc3 codebase supports realtime plotting.

Is this something one could implement with pystan in the future (httpstan?)

**Comment by ariddell** [comment]
Interesting. I'll have to check that out. In principle there's no reason
we couldn't do it. Samples are available as a stream.

**Comment by aseyboldt** [comment]
See also here: https://github.com/mcmcplotlib/mcmcplotlib/issues/4#issuecomment-374933062

**Comment by ahartikainen** [comment]
I think refactor is ready.
