### ISSUE TITLE
Add plot_ecdf

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#1213]
## Tell us about it

It would be nice to have an empirical CDF (ECDF) plot function that isn't tied to `plot_ppc`. As far as information a `plot_ecdf` might display, I'm thinking it would behave pretty similarly to `plot_density`, but with an ECDF. One extra thing you might want to do is specify some quantiles that would be drawn on the plot. The most common style for ECDF is the line visualization.

![ecdf](https://user-images.githubusercontent.com/8673634/83200946-4ac5cf80-a0f9-11ea-8f96-dbd5e5c2a88b.png)

Another style that we might want to support is one that shows the intervals (e.g. see below from https://statisticsglobe.com/empirical-cumulative-distribution-function-ecdf-r)
![R-Basics-the-dim-Function-in-R](https://user-images.githubusercontent.com/8673634/83200030-41d3fe80-a0f7-11ea-9882-48f6877dbc79.png)
However, in my experience, this is only useful for small sample sizes, and in general for posterior samples, the line is cleaner.

## Thoughts on implementation

It's already possible to compute the ECDF (we already have `arviz.plots.backends.matplotlib.ppcplot._empirical_cdf` and
`arviz.plots.backends.bokeh.ppcplot._empirical_cdf`), so this should be pretty straightforward to implement.

**Comment by TrushaT** [comment]
Hello, I would like to try to implement this. Pls assign me this issue. Thank You

**Comment by Rishabh261998** [comment]
@TrushaT Thanks for the comment but I have already opened a PR for this issue.

**Comment by OriolAbril** [comment]
Hi @TrushaT, thanks for your interest in ArviZ. 

As @Rishabh261998 commented, plot_ecdf already has a PR open which will be merged soon so it doesn't make sense for you to work on ecdf plots too. There are other plots that we have on mind to be added to ArviZ if you are interested in contributing new plots. https://github.com/arviz-devs/arviz/issues/1103 would be another example, or [calibration plots](https://github.com/arviz-devs/arviz/wiki/ArviZ-2021-roadmap#plots) which I think don't have an issue open but are on our roadmap.

**Comment by TrushaT** [comment]
Hey @OriolAbril! Yes, I would like to work on #1103. Since I am new here would just need a bit of guidance!

**Comment by OriolAbril** [comment]
I would recommend going over https://arviz-devs.github.io/arviz/contributing/contributing_prs.html and get back to us on #1103 if something is not clear enough, we will be happy to guide you through the process :smile:
