### ISSUE TITLE
plot_density has no filter_vars argument

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1225]
I think it should have the argument. It may be a little more complicated given the multiple idata input but is should still be feasible.

**Comment by nitishp25** [comment]
Given that `var_names` already supports multiple idata inputs, are we looking to separate the filtering for each input dataset?

**Comment by OriolAbril** [comment]
I think `_var_names` must always be a list of strings and it's datasets what can be a list of xarray datasets or a single dataset. Therefore, it does not seem really useful to try and apply different filtering schemes to each dataset given that the var_names will be the same (strings in var_names will not generally be compatible with all filtering schemes). 

I would therefore pass `filter_vars` from `plot_density` to `_var_names` and test it works, I think it should work straight away.

**Comment by nitishp25** [comment]
> I would therefore pass filter_vars from plot_density to _var_names and test it works, I think it should work straight away.

Yeah, it should work. The "complicated" got me thinking about the requirement of separating the filtering and I started thinking about a `dict` based revamp for `_var_names` 😅

**Comment by prahasR** [comment]
Hi @OriolAbril is the issue still open? I would like to work over this.

**Comment by OriolAbril** [comment]
You can work on this @prahasR

**Comment by prahasR** [comment]
Thanks @OriolAbril! I have some questions regarding the issue can you please clarify them. Over https://github.com/arviz-devs/arviz/blob/main/arviz/utils.py I found that `filter_vars` can take only 3 values that are `None`, `like` and `regex`. So one of these values should be passed to `_var_names` as `filter_vars` at https://github.com/arvizdevs/arviz/blob/main/arviz/plots/densityplot.py#L189? Right? 

If this is the case then can you please help me understand that what value of `filter_vars` should be passed to `_var_names`? 

I apologise if the questions were too simple. I request you to please clarify my doubts, its my first time contributing here.

Thank You.

**Comment by OriolAbril** [comment]
`filter_vars` is what should be passed to `_var_names` whatever value it is storing. See for example https://github.com/arviz-devs/arviz/blob/main/arviz/plots/essplot.py#L194. You need to add `filter_vars` as a parameter in the function definition, document it in the docstring and update the call to `_var_names` to pass also `filter_vars`. Then you'll need to test the behaviour manually and add tests on https://github.com/arviz-devs/arviz/blob/main/arviz/tests/base_tests/test_plots_matplotlib.py. 

> I apologise if the questions were too simple. I request you to please clarify my doubts, its my first time contributing here.

No need to apologize, I do have a question if I may. What thing specific to this issue called/interested you and made you decide to chose it before issues labeled beginner friendly? You (like anyone) are free to work on it, I just want to make sure you know what you are getting into before you end up spending too much time on this.

**Comment by prahasR** [comment]
I have been looking at some of issues tagged as beginners to get myself familiar with the source code. As most of them have some of the work already done it helped me a lot. I understood most of the part but still I require more understanding in some of the parts of the code. I thought that it would be both helpful for me and the contributors if I work on issues that I could able to contribute to and the issues that have not much work already done. Also as this issue has not been tagged as beginner I found it little late. 
I have created a PR #1988, please review.
Also can you please help me in understanding the tests part of the repository. I have been learning about pytest and been working on it with my own test_function to get familir with the implementation of pytest . But I am not sure that how do I use the test directory of arviz to run tests?

**Comment by OriolAbril** [comment]
commented there, I believe I answer all the questions in the PR, please ask if I don't.
