### ISSUE TITLE
[FR] Allow plot_forest to not include variable names

### ISSUE THREAD

**Issue by tuchandra** [arviz-devs/arviz#1235]
## Tell us about it
I regularly use az.plot_forest to compare posterior intervals for some RV, both across models and across coordinates. I've found that the default of including the variable name can get cluttered and repetitive when doing this for a lot of models or coordinates.

Here's one example where I was comparing a random variable `p_comp` across four posteriors across coordinates.

![image](https://user-images.githubusercontent.com/11623486/84306935-cffdab00-ab21-11ea-84ce-4ecf812fd476.png)

Having the name `p_comp` appear by every interval doesn't really add anything to the plot; to me, and in this case, it makes more sense in the title. Another example, though not as bad, is the [eight schools example in the docs](https://arviz-devs.github.io/arviz/generated/arviz.plot_forest), where theta is repeated for each case. 

## Thoughts on implementation
I'd love any of the following:
 * to configure whether the variable name appears at all (probably not great, because then multiple variables in the same plot would become indistinguishable)
 * to configure the name of the variable
 * to have the variable (and maybe even coordinates?) appear less frequently, since each cluster of four models will by definition share the same variable name and coordinates (probably pretty hard)

Thank you for your great work on Arviz; it's a wonderful tool.

**Comment by OriolAbril** [comment]
I think we have to rethink the labeling strategy to try and match some list of desired features.

In the case of foresplot, and dreaming big, I think we could abandon completely ticklabels and create an extra axes for the labels. Given the order var_name, coord1, coord_2..., model_name we can write var_name centered and only once, then coord1 once per variable...

**Comment by OriolAbril** [comment]
I think we can consider this fixed now. To begin with, plot_forest now avoids repeating the variable name in multidimensional cases, it is only shown for the first appereance. Moreover, you can use the new [labellers](https://arviz-devs.github.io/arviz/user_guide/label_guide.html) to customize labels, which allows things like avoiding both model and variable name while encoding the model info in the color and showing a legend.
