### ISSUE TITLE
add merge/add group function

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1239]
## Tell us about it
`az.concat` currently raises an error if there are repeated groups which is perfectly fine, however, there are situations where one wants to add the different groups to the original idata object and discard the repeated groups. 

related to #1066 

## Thoughts on implementation

several options, some of them complementary:

1. add an `idata.merge` function so that idata wiht groups post, sample_stats, obs_data can be merged with idata with groups post_pred and obs_data discarding the obs_data in one of the two (could have left/right modes)
2. add an `idata.add_groups` so that we can pass it dicts (calls dict_to_dataset) or datasets as kwargs and they are added to idata (I think kwargs is important to allow special usecases and support any group_name, alternatively a mapping {group_name: ds/dict} could be used)
3. make `idata.concat` check equality of datasets with isclose on both vals and coords (but not on attrs! they will surely have different creation time)

**Comment by OriolAbril** [comment]
tagging @percygautam

**Comment by percygautam** [comment]
The methods `add_groups` and `merge`(tbd) has been implemented in #1300 . I think that will solve this issue. DO we still have to update `concat`(3rd option)? Maybe, we could edit the error message in concat to use merge method in case of repeated groups.

**Comment by OriolAbril** [comment]
I think editing the error message would be great and more than enough to close issue. Unless anyone has more improvements in mind I think we can close the issue. cc @ahartikainen maybe?

**Comment by ahartikainen** [comment]
Yes let's close this.
