### ISSUE TITLE
ArviZ Council Nominees 2020

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1243]
This is our issue to nominate candidates for ArviZ Council. Nominations will be open for 1 week, after which this issue will be closed and we move to the first election phase. The council will be consist of either 5 or 7 seats, the number will be determined in the election.

For nominations please comment with one name per comment to make things easier to track. Nominations must be accepted by nominee. Emoji like is acceptable!

The list of eligible contributors for this nomination round are listed below. 
https://github.com/arviz-devs/arviz/pull/1226
* Oriol Abril-Pla (@OriolAbril) 
* Alex Andorra (@AlexAndorra)
* Seth Axen (@sethaxen)
* Colin Carroll (@ColCarroll)
* Robert P. Goldman (@rpgoldman)
* Ari Hartikainen (@ahartikainen)
* Ravin Kumar (@canyon289)
* Osvaldo Martin (@aloctavodia)
* Mitzi Morris (@mitzimorris)
* Du Phan (@fehiepsi)
* Aki Vehtari (@avehtari)

Schedule for nomination and election
https://github.com/arviz-devs/arviz/blob/master/elections/ArviZ_2020.md#nominations-for-council-june-14th

**Comment by canyon289** [comment]
I nominate @sethaxen, who built the julia integration!

**Comment by AlexAndorra** [comment]
I nominate @OriolAbril, for his amazing work -- and his unique way of explaining Spanish politics and way of life

**Comment by AlexAndorra** [comment]
I nominate @ahartikainen, for his amazing work -- and his beautiful pictures of the Finnish countryside!

**Comment by AlexAndorra** [comment]
I nominate @canyon289, for his amazing work -- and his mind-blowing joyful efficiency !

**Comment by AlexAndorra** [comment]
And finally, I nominate @aloctavodia, for his amazing work -- and his skilfulness at slow-cooking meat!

**Comment by OriolAbril** [comment]
I nominate @ColCarroll

**Comment by OriolAbril** [comment]
and I also nominate @AlexAndorra

**Comment by ahartikainen** [comment]
I nominate @mitzimorris

**Comment by aloctavodia** [comment]
I nominate @rpgoldman

**Comment by aloctavodia** [comment]
I nominate @fehiepsi

**Comment by fehiepsi** [comment]
I nominate @ahartikainen

**Comment by fehiepsi** [comment]
and also nominate @OriolAbril

**Comment by OriolAbril** [comment]
Thank you so much @fehiepsi ! 

@canyon289 already commented but I wanted to extend the explanation just in case. The election process is divided into two steps:
1. Council nominations. We decided they would be public and happen in this issue. Any Core Contributor can be nominated (or self-nominated) and then has to accept by liking the comment with their nomination. Everyone who accepts is then a candidate for council and their name will be considered in the next step. This is basically to make sure that only people who want to be on ArviZ's council are considered when voting.
1. Voting council members. In this second step Core Contributors vote for the candidates. Voting is anonymous and mediated by NumFOCUS, following the guidelines in governance doc. 

Now all eligible people have been nominated, however, only those who accept the nomination will be considered when voting. If you would like to be part of the council you have to accept the nomination. I hope the process is more clear now

**Comment by canyon289** [comment]
Thanks @OriolAbril. Since everyone is nominated I'll close the acceptances at approximately at 6/20 7pm PST so NumFOCUS can handle the election from there

**Comment by canyon289** [comment]
Just to bluntly ask the question. Is anyone else planning on confirming their nomination? Asking because if we have 6 nominees, I'm going to propose a change to next steps in the process but want to confirm the count of nominees first :)

**Comment by avehtari** [comment]
I feel my contribution has been so small that I would prefer other nominated persons to be prioritized and thus haven't accepted my nomination.

**Comment by canyon289** [comment]
> I feel my contribution has been so small that I would prefer other nominated persons to be prioritized and thus haven't accepted my nomination.

I would disagree that your contribution is "small". A lot of arviz is ideas programmed straight from papers and work, rank plots for instance! And for myself reading your work gives me the fundamental understanding. But appreciate the quick response as it helps reduce my uncertainty on what to propose for election next steps. Will wait for a couple more responses :)

**Comment by mitzimorris** [comment]
like Aki,  I feel my contribution has been minimal and thus thanks, but no thanks, I don't feel qualified to be on the council.

**Comment by canyon289** [comment]
Since we have 7 confirmed nominee and, 2 people that will not become nominees and either 5 or 7 slots for council seats I have the following proposal.

***If its the case by Sunday that no one else wants to be a nominee for the a council seat*** would anyone be opposed to forgoing the election and just confirming all 7 people to the council? While we could run an election it seems like the likely outcome is all seven people just end up filling the likely 7 slots.

I would say if we all unanimously agree on this, then lets change the plan and forgo the election, but if one person dissents we should continue with our written plan and have the election. Any thoughts for or against?

**Comment by AlexAndorra** [comment]
Thanks @canyon289, I agree with you: unless someone has a strong preference for a 5-member Council or really dislikes a nominee, I think we can forego the election and proceed with a 7-member Council.

**Comment by canyon289** [comment]
We had a discussion in slack. We'll be faithful to the election process, because even if it leads to the same outcome we can be certain it was the group decision

**Comment by canyon289** [comment]
This issue will close in approximately ~32 hours, at which point I'll send NumFOCUS the list of nominees and emails of folks that can vote. 

The specific timing of the voting will depend on when NumFOCUS gets around to it but would expect the form to go on Monday or Tuesday (CST time zone) and voting to be open for a week.

**Comment by avehtari** [comment]
> I would disagree that your contribution is "small". A lot of ArviZ is ideas programmed straight from papers and work, rank plots for instance! And for myself reading your work gives me the fundamental understanding (so thank you for that). 

Thanks for the kind words. This encourages me to to be more active in the future.

**Comment by canyon289** [comment]
> > I would disagree that your contribution is "small". A lot of ArviZ is ideas programmed straight from papers and work, rank plots for instance! And for myself reading your work gives me the fundamental understanding (so thank you for that).
> 
> Thanks for the kind words. This encourages me to to be more active in the future.

I missed a two key words here. A lot of ArviZ is *your* ideas, programmed straight from *your* papers and work. Not just anybody's. 

For bookkeeping closing this in ~6 hours and sending to Nicole. So far we have confirmed candidates

* @sethaxen 
* @ahartikainen 
* @aloctavodia 
* @AlexAndorra 
* @ColCarroll 
* @OriolAbril 
* @canyon289 

If anyone else wants to confirm or I missed anyone please comment here

**Comment by canyon289** [comment]
Nominees confirmed as above.  The template ballot has been sent to Numfocus. They'll make a copy and send out the official version soon (I hope)!

https://forms.gle/NsYAgWFjeDqXwZwo8
