### ISSUE TITLE
HPD plot shows values over each other

### ISSUE THREAD

**Issue by drachimera** [arviz-devs/arviz#1262]
Hey All,

I am trying to figure out how to change the plot_posterior function to show the actual values.  In one of my plots, where it is small, I get numbers writing over each other.  Any help/advice?

![image](https://user-images.githubusercontent.com/605973/85463990-c71ec780-b56c-11ea-95f6-3706e6ef72a1.png)

**Comment by aloctavodia** [comment]
Hi  @drachimera , thanks for taking the time to report this problem. I am not sure there is a good solution from your side. Let me try to fix it.

**Comment by ahartikainen** [comment]
For a quick fix, I think one can move those labels in interactive (qt4?) window. Not sure if this is true, and we have a fix on the way.

**Comment by drachimera** [comment]
Thanks so much!  Love the toolkit!
