### ISSUE TITLE
High Dimensional Examples of ArviZ

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1268]
Using this issue ticket as a forum to connect @michaelosthege  and @sethaxen 

@michaelosthege Seth is looking for examples of ArviZ use on high dimensional models. I remember you posting that large pairplot in the PyMC slack the other way so wanted to connect you two :)

**Comment by michaelosthege** [comment]
Hi @sethaxen,
Yes, I use ArviZ to plot_pair with 20-30 dims from time to time. Mostly to understand correlations...
What are you interested in specifically?

**Comment by kyleabeauchamp** [comment]
I've hit issues with plot_forest where it's basically impossible to show all the data for that dimension, so instead I ended up sorting the trace by the mean value of that parameter, then showing the top 10 and bottom 10 rows, as well as 10 randomly select values from the middle.

**Comment by kyleabeauchamp** [comment]
Not sure if that's what's being implied in this ticket, but those are some of the tricks I've had to do for high dimensional data.  

FWIW, the human genome has 23 chromosomes and ~20,000 genes, while modern cancer sequencing panels include ~500 genes, so those are some of the numbers I'm talking about.

**Comment by michaelosthege** [comment]
Well with 20_000 subplots, or even 20_000 kde plots you might be "hitting" the limits of Matplotlib.
The CPU time for the kdes could be a problem too.

**Comment by kyleabeauchamp** [comment]
Yeah, I would want to merge them onto a single figure (e.g., https://arviz-devs.github.io/arviz/generated/arviz.plot_forest) but needing to reduce the number of rows on the figure.

**Comment by kyleabeauchamp** [comment]
E.g., what would we plot in the 8 schools example if instead we had 500 schools---IMHO, we would want to plot the theta distribution for `k` largest values, `k` smallest values, and `k` intermediate values, where `k` is something like 5 or so.

**Comment by michaelosthege** [comment]
> E.g., what would we plot in the 8 schools example if instead we had 500 schools---IMHO, we would want to plot the theta distribution for `k` largest values, `k` smallest values, and `k` intermediate values, where `k` is something like 5 or so.

A heat map? Probability density as color/intensity instead of a 2D polygon.

**Comment by canyon289** [comment]
Closing this issue as part of issue  cleanup
