### ISSUE TITLE
Multiple "stacked" density plots

### ISSUE THREAD

**Issue by mberaha** [arviz-devs/arviz#1285]
Is there an easy way to produce a plot similar to the one shown in this stackoverflow question https://stackoverflow.com/questions/58899156/plotly-violin-plot-add-trace-cannot-add-names ?

I saw in the example gallery that it is possible to have several density plots in the same axis, but none shows if it's possible to translate the different plots on the y axis

**Comment by OriolAbril** [comment]
Does this [example](https://arviz-devs.github.io/arviz/examples/matplotlib/mpl_plot_forest_ridge.html) work for what you had in mind? Maybe with a lower alpha to get more transparency

**Comment by mberaha** [comment]
Yes, that was I was looking for, thank you!

However, when using my own algorithm to generate the samples and then using `az.convert_to_inference_data`, I get the following error:

> ~/.local/lib/python3.8/site-packages/arviz/utils.py in _vaz.plot_trace(az.convert_to_inference_data(np.random.normal(size=1000)))ar_names(var_names, data)
     56         existent_vars = np.isin(var_names, all_vars)
     57         if not np.all(existent_vars):
---> 58             raise KeyError(
     59                 "{} var names are not present in dataset".format(
     60                     np.array(var_names)[~existent_vars]

> KeyError: "['defs'] var names are not present in dataset"

Here is a MWE:

this works:
```az.plot_trace(az.convert_to_inference_data(np.random.normal(size=1000)))```
but this doesn't:
```
axes = az.plot_forest(
    {"s1": np.random.normal(size=1000), "s2": np.random.normal(size=1000)},
    kind="ridgeplot",
    var_names=["defs"],
    linewidth=4,
    combined=True,
    ridgeplot_overlap=1.5,
    colors="blue",
    figsize=(9, 4),
)
```

Is there a way to fix this?
