### ISSUE TITLE
Error in numeric utils

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#1287]
**Describe the bug**

(Line 191 in numeric utils)[https://github.com/arviz-devs/arviz/blob/c5edec458316501b6a9b22a718e09aa06c7fd0ff/arviz/numeric_utils.py#L191] is as follows:

    width = np.round(np.max([1, bins_sturges, bins_fd])).astype(int)

When I ran this as part of running the PyMC3 getting started notebook, 

    round(np.max([1, bins_sturges, bins_fd]))

evaluated to 1, and, apparently `1.astype(int)` raises an `AttributeError`:

    AttributeError: 'int' object has no attribute 'astype'

I don't, unfortunately, know how to reproduce this: when I set values for these variables and run the code outside ArviZ and PyMC3, it works fine.  This works:

```
    import numpy as np
    bins_sturges = 1.2598237927692393
    bins_fd = 0.27849533001676674
    width = np.round(np.max([1, bins_sturges, bins_fd])).astype(int)
```

Is there, perhaps, some state of numpy or the python interpreter that is set and causes this to break?  It seems like somehow the value of the `np.round()` expression ends up being a python-native int, instead of a numpy value, but I don't know how this could happen.

**Additional context**

arviz  0.8.3
pandas 1.0.5
numpy  1.19.0
pymc3  3.9.2
last updated: Sun Jul 12 2020 

CPython 3.7.7
IPython 7.16.1
watermark 2.0.2

**Comment by OriolAbril** [comment]
I remember things breaking with a new release of numpy due to ArviZ having `round` but changing to `np.round` fixed it, it is weird this is coming up again :thinking:

**Comment by aloctavodia** [comment]
Super weird. Is the error in the PyMC3 getting started notebook reproducible?

**Comment by rpgoldman** [comment]
> Super weird. Is the error in the PyMC3 getting started notebook reproducible?

My attempt to create a MWE by copying the values of `bins_sturges` and `bins_fd` out of the debugger, assigning them, and making a standalone python script does _not_ replicate the error:

``` python
import numpy as np
bins_sturges = np.float64(1.2598237927692393)
bins_fd = np.float64(0.27849533001676674)
width = np.round(np.max([1, bins_sturges, bins_fd])).astype(int)
```

So I'm not sure -- is there some setting that could cause `np.round` to return a native python float instead of a numpy value? That's definitely what is going wrong here, but I have no idea why I get this error running the notebook and don't get it running this little snippet in the same virtual environment.

Could it be something in either PyMC3's configuration, or in theano's configuration that could cause this?

**Comment by rpgoldman** [comment]
... but it does happen to me every time I try to run the notebook.

**Comment by aloctavodia** [comment]
So we can just learn to live with the doubt and change the code to:

`int(round(max([1, bins_sturges, bins_fd])))`

**Comment by aloctavodia** [comment]
BTW I tried to reproduce it, running the notebook with two numpy versions. no luck.
