### ISSUE TITLE
Add code for rugby example to examples repo

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1294]
Add the code used to generate the rugby dataset to https://github.com/arviz-devs/arviz_example_data.

The rugby example is taken from [this notebook](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/rugby_analytics.ipynb).

**Comment by sudip-padhye** [comment]
Hey Oriol,

I am new to the arviz. I was a little curious about what exactly you mean by "add the code used to generate the radon dataset" because the notebook link contains all the code already. 

Thank You!

**Comment by OriolAbril** [comment]
We want to have all the code used to generate the examples in `load_arviz_data` for both pedagogical reasons and to ease updating these examples if necessary. It is true the notebook has the whole model and data, however the notebook serves a different purpose to explain how to build the model, analyze its results even predict results. The goal here is only to generate the inference data object. This is why we expect a `.py` file to be enough in most cases and thus the examples repo accepts both formats.

You'll notice for example that running the notebook with latest ArviZ generated an InferenceData object with more groups than the ones in available via `load_arviz_data`. This is because we we extended inference data capabilities with new groups but still have not updated the datasets.

**Comment by sudip-padhye** [comment]
Hey Oriol,

Can I take this if it is still unassigned to anyone?

Thank You!

**Comment by OriolAbril** [comment]
that would be great, thanks @sudip-padhye
