### ISSUE TITLE
Add code for school examples to examples repo

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1295]
Add code used to generate the `centered_eight` and `non_centered_eight` examples to https://github.com/arviz-devs/arviz_example_data.

The code is available at https://arviz-devs.github.io/arviz/notebooks/Introduction.html#Plotting-with-PyMC3-objects and at https://arviz-devs.github.io/arviz/notebooks/InferenceDataCookbook.html#From-PyMC3

**Comment by sudip-padhye** [comment]
If it is still available shall I pick this up?

**Comment by OriolAbril** [comment]
It is still available, I have assigned it to you. 

The [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md) and the readme in https://github.com/arviz-devs/arviz_example_data should guide you through the process and always feel free to ask questions :)
