### ISSUE TITLE
Add helper methods for azsummary

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1298]
## Tell us about it
Adding median and median absolute deviation would be to ArviZ summary would be nice, particular as in Regression and Other Stories those are the two summary statistics used most often.

See this ticket from Bambi
https://github.com/bambinos/bambi/issues/223

https://github.com/bambinos/bambi/issues/223
![image](https://user-images.githubusercontent.com/7213793/87624032-8e8d8c00-c6db-11ea-80cd-d184645c3928.png)

## Thoughts on implementation
Maybe we add a module thats like convenient functions or something? Whatever code we use would either go into the summary method below, or be located somewhere else. Open to ideas

https://github.com/arviz-devs/arviz/blob/master/arviz/stats/stats.py#L1153

**Comment by ahartikainen** [comment]
We could add some predefined but optional stats.

Have you tried `stat_funcs` kw?

But for example mad is already defined for ess / mcse then we could have option to spit out mad stats only

We could have options for the following

    mean stats --> mean, sd, ess_mean, ess_sd, mcse...
    quantile stats --> quantiles (list input), ess_quantiles, mcse_q...
    mad stats --> median, mad, (iqr?)...

**Comment by AlexAndorra** [comment]
Adding the median seems nice, especially to easily spot potentially skewed distribution. 
I'm not sure about adding MAD though, as the HDI is already in `summary` IIRC, and the latter is more robust to distributional assumptions and interpretable even when we're not working with Normal distributions -- unlike MAD estimates, IIUC

**Comment by canyon289** [comment]
Only proposing MAD because its the main metric used in ROS to characterize variation in parameters, but am not strongly tied to it myself

**Comment by aloctavodia** [comment]
I like @ahartikainen proposal.

**Comment by virajone** [comment]
Hey, I'd like to know if I can pickup this issue ?

**Comment by OriolAbril** [comment]
I think the goal here would be to add a new argument to `az.summary` to set which statistics and diagnostics to use. 

Users can already use the `stats_funcs` like in the code from the first comment to do this, but some of the combinations are common enough that having a more convenient way to get a custom summary would be a valuable feature.

I think that there is still some loose ends to tie before being able to implement it such as the argument name and the combinations to add, @ahartikainen already started with a proposal above which should be a great start, from here on we should define all the columns of each of the alternatives

**Comment by virajone** [comment]
@OriolAbril Thanks a lot for the details. As there are still some items related to the issue that need to be discussed, I shall start working considering @ahartikainen 's proposal above as the base idea. In the meantime, maybe we have the combinations and the argument name finalized ?

**Comment by aloctavodia** [comment]
HI @virajone, you can start working on ahartikainen' proposal.

**Comment by prahasR** [comment]
Hi @OriolAbril @ahartikainen  is the issue still open? I would like to contribute to this. 
Also as you said that we have to add a new argument to `az.summary` so like currently `az.summary` is giving `mean`,`sd`,` hdi_3%`,`  hdi_97% `,` mcse_mean`,`  mcse_sd `,` ess_bulk`,`  ess_tail `,` r_hat` so does the argument should define which stats to output or should it do something else? Can you please clarify this. 

Also can you please clarify that what do you mean by `spit the mad stats only` here? 

> But for example mad is already defined for ess / mcse then we could have option to spit out mad stats only

**Comment by OriolAbril** [comment]
Now summary reports the summarizing statistics and diagnostics that correspond to the mean, however, the mean is not always a good summary. The functions computed by summary can be modified with `stat_funcs`, but it means users need to update _all_ of them if using the median for example.

The goal here is to make it easier to switch the "focus" of summary from the mean to other common summaries like the median. 

The first step is choosing the API we want for this, which we should discuss here. Then if you are interested you can send a PR implementing it.

One possible API is having `stat_funcs` take strings too in addition to lists or dicts, and if that is the case, expand that to a dictionary. If we do that early enough, no changes will be needed to the function, as it already works with dictionaries as stat_func.

One "expansion" could be for example converting `"median"` to something in the lines of:

```
{
    "median": np.median,
    "mad": scipy.stats.median_abs_deviation,
    # use equally tailed intervals instead of HDI
    "mcse_median":
    "mcse_mad":
    "ess_bulk":
    "r_hat":
}
```

**Comment by prahasR** [comment]
> One possible API is having `stat_funcs` take strings too in addition to lists or dicts, and if that is the case, expand that to a dictionary.

Can you please help me finding about what could be the possible string inputs to `stat_funcs` and their possible mapping functions. I think if there are only few valid string inputs possible then we can add the cases such as:
```
if stat_funcs=="median" : 
       #change stat_funcs to the dictionary       
```

**Comment by OriolAbril** [comment]
I have seen now I missed the notification on this issue. I think that as a starting point we can use `mean+hdi` (current behaviour), `median` and `mean+eti` as options.
