### ISSUE TITLE
ppc_stat from bayesplot looks pretty nice

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1308]
## Tell us about it
`ppc_stat` from bayesplot looks pretty fancy! Would be great of ArviZ had something similar

![image](https://user-images.githubusercontent.com/7213793/87886808-b11dee80-c9d4-11ea-8f2b-d21d0b4e5870.png)
https://mc-stan.org/bayesplot/reference/PPC-test-statistics.html

## Thoughts on implementation
Add another plotting method called `plot_ppc_stat` most likely

**Comment by OriolAbril** [comment]
I think `plot_bpv` can be used to plot this: https://arviz-devs.github.io/arviz/examples/matplotlib/mpl_plot_bpv_tstat.html. Not sure about it though, because I like to live dangerously and have not read bayesplot docs :no_mouth: 

Tangentially related issue, `plot_bpv` has no api section.

**Comment by aloctavodia** [comment]
Exactly, `plot_bpv` is intended for this type of plot and two more, including a loo-pit-like plot, but without using loo.
Notice that `plot_bpv` still needs some more love.

**Comment by ahartikainen** [comment]
> Notice that plot_bpv still needs some more love

Conditional or unconditional?
