### ISSUE TITLE
Broken link in CONTRIBUTION.md

### ISSUE THREAD

**Issue by ari-hacks** [arviz-devs/arviz#1311]
**Describe the bug**
I noticed on step 4 the virtualenvs link is broken here: https://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/

I believe this is the correct link: https://python-guide-cn.readthedocs.io/en/latest/dev/virtualenvs.html

With the go-ahead, I can put a quick PR in for that 🙂

**Comment by canyon289** [comment]
Go ahead!

**Comment by canyon289** [comment]
Fixed. Thanks @ari-hacks!
