### ISSUE TITLE
Add better documentation for how to build hosted documentation

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1314]
Copying from another issue ticket, we can improve our static documentation for how to build our generated documentation

The only thing that might be more helpful is updating the instructions a bit under **Building documentation with Docker** to let contributors know they have to rebuild with the `--docs` command after changes and the index.html file has to be dragged and dropped into the browser.

_Originally posted by @ari-hacks in https://github.com/arviz-devs/arviz/issues/1155#issuecomment-662350572_

**Comment by OriolAbril** [comment]
Also instrucctions on building docs locally can be improved.

**Comment by collinsuzebu** [comment]
If this issue haven't been taken, I'd like to resolve it.

**Comment by canyon289** [comment]
Not taken! Please go ahead

**Comment by canyon289** [comment]
@collinsuzebu Any interest? If not I'll remove your assignment to this issue so someone else can work on it

**Comment by collinsuzebu** [comment]
@canyon289 apologies for the delay in getting this done. I was unable to get the project running on my windows machine. My initial intention was to set it up once my Linux machine is restored by following @ari-hacks steps and properly documenting the sections that were not clear.  I'm still interested in fixing this issue. Would it be advisable to get it done without first running the project locally.

**Comment by collinsuzebu** [comment]
@canyon289 apologies for the delay in getting this done. I was unable to get the project running on my windows machine. My initial intention was to set it up once my Linux machine is restored by following @ari-hacks steps and properly documenting the sections that were not clear.  I'm still interested in fixing this issue. Would it be advisable to get it done without first running the project locally?

**Comment by ari-hacks** [comment]
Hey @collinsuzebu , are you still interested in taking this on? I can tackle it if you are unavailable. 

> The only thing that might be more helpful is updating the instructions a bit under Building documentation with Docker to let contributors know they have to rebuild with the ```--docs``` command after changes and the index.html file has to be dragged and dropped into the browser.

Under [building docs](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#building-documentation-with-docker) I would just make a note about the changes listed above.

**Comment by canyon289** [comment]
@ari-hacks its yours.

 @collinsuzebu Apologies I missed your original message

**Comment by ahartikainen** [comment]
If user add `[docs]` to PR title, then CI will upload the docs, which can be downloaded to user computer.

It can be found under `artifacts` in the main CI page

e.g. https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3560&view=results <-- this CI run did not create docs

**Comment by ari-hacks** [comment]
> If user add `[docs]` to PR title, then CI will build and upload the docs, which can be downloaded to user computer.
> 
> It can be found under `artifacts` in the main CI page (it looks like "Published n")
> 
> e.g. https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3560&view=results <-- this CI run did not create docs

Hey, @ahartikainen should this be a separate issue?

**Comment by ahartikainen** [comment]
I think it is already documented. I just wanted to share the info, so you are aware of this.

**Comment by ari-hacks** [comment]
@canyon289 and @ahartikainen I've made this update but I'm also unable to build the docs (nothing generates under `docs/build` dir). The above CI run indicates a possible linting issue? 

When I attempt to build this is the error I'm getting: 
<img width="934" alt="Screen Shot 2020-10-22 at 2 16 28 PM" src="https://user-images.githubusercontent.com/36749814/96882105-dceabd80-1476-11eb-8400-782e1e7b24e9.png">

**Comment by ahartikainen** [comment]
Interesting, maybe there is a problem with sharing your local folder.

**Comment by OriolAbril** [comment]
Maybe its due to the doc reorganizations :thinking: I'll check

**Comment by OriolAbril** [comment]
> Maybe its due to the doc reorganizations thinking I'll check

Indeed, https://github.com/arviz-devs/arviz/blob/master/scripts/container.sh#L38 should be:

    "if [ -d ./doc/build ]; then python -msphinx -M clean doc/source doc/build; fi && sphinx-build doc/source doc/build -b html"

The conf.py file used to be on `doc/` but was moved to `doc/source` so now it's not found anymore by the script because it's still looking at the old location. 

Azure CI script was updated https://github.com/arviz-devs/arviz/blob/master/.azure-pipelines/azure-pipelines-docs.yml#L60-L61 and can serve as an example to compare against when things don't work

**Comment by ari-hacks** [comment]
@OriolAbril - ah I see , thanks! Should I go ahead and update that line with this PR or should that be a separate issue?

**Comment by OriolAbril** [comment]
I think we can do it in the same PR, but I don't have strong preferences on this
