### ISSUE TITLE
How do you plot just some dimensions of a variable?

### ISSUE THREAD

**Issue by seantalts** [arviz-devs/arviz#1328]
## Short Description

e.g. az.plot_trace(fit, var_names=["z.2.73", "z.2.84"]) to get traceplots for two particular elements of a z matrix. I tried that and "z[2,73]" and couldn't get anything to work. "like" and "regex" filter_vars options also don't seem to know about the individual elements of z.

**Comment by ahartikainen** [comment]
Hi, good question.

I'm not sure if we currently have a good way to do that. We certainly should have that option.

@OriolAbril maybe isel could handle this before we have a better way to do it?

**Comment by seantalts** [comment]
Hi! Thanks for the quick response :) 

Dang. Anyone have a quick workaround for CmdStanPy?

**Comment by ahartikainen** [comment]
For quick (and small example) assuming 1-based indexing.

You can insert a dictionary if you want. First two dims are `chain` and `draw`

    az.plot_trace({
        "z.2.73" : idata.posterior.a[:, :, 2-1, 73-1], 
        "z.2.84" : idata.posterior.a[:, :, 2-1, 84-1],
    })

**Comment by seantalts** [comment]
oh nice! Thank you :)

**Comment by OriolAbril** [comment]
I think `coords` argument (or `sel`/`isel` which generally behave the same) can be used too. Assuming that no costume dimension names are provided when creating the inferencedata, something like this may work:

    az.plot_trace(idata, var_names="z", coords={"z_dim=0": 2-1, "z_dim_1": [73-1, 84-1]})

**Comment by ahartikainen** [comment]
that works

**Comment by canyon289** [comment]
This issue looks resolved. If its not we can reopen
