### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Hvass-Labs** [arviz-devs/arviz#1332]
Before I write my issue here, I just wanted to make sure that I am protected in case of harassment and violence from the other forum users. Because words are violence, and silence is violence, it is very important that I feel protected and safe when posting here. So I read your [Code of Conduct](https://github.com/arviz-devs/arviz/blob/master/CODE_OF_CONDUCT.md) which states that: **"If you feel your safety is in jeopardy or the situation is an emergency, we urge you to contact local law enforcement before making a report."**

The problem is that due to the recent (and mostly peaceful) BLM protests, my local police department has been defunded and closed down, so now I just get an answering machine when I call them. In fact, the answering machine stopped half-way through the message with a weird hizzing sound, probably because the police station was being burned to the ground during the (mostly peaceful) BLM protests.

So I am very nervous about posting an issue here, because I don't know what to do in case of a serious emergency where my personal safety is in jeopardy from the other forum users.

Please update your Code of Conduct with the new procedure for getting help in such dangerous situations, now that we cannot call the police anymore, so we can all feel safe when posting our issues here.

Thank you!

**Comment by ColCarroll** [comment]
ArviZ adopts the NumFOCUS code of conduct. Feel free to open PR there if you think you can improve it.
