### ISSUE TITLE
plot_forest; HPD not visible with kind="ridgeplot"

### ISSUE THREAD

**Issue by orbidder** [arviz-devs/arviz#1339]
Not sure if a bug or just not a feature that's available, but in using plot_forest() I'm able to see the HPD when using kind="forestplot" but not with kind="ridgeplot". One of the things I liked about bayesplot in R was being able to see the the HPD of the marginal posteriors with the mcmc_areas() function. Is that possible with plot_forest(kind="ridgeplot")? Specifying hdi_prob seems to have no effect with the ridgeplot.

(Appreciate the development effort on arviz btw, been a huge help since switching over to Python for my bayesian modeling)

**Comment by aloctavodia** [comment]
Thanks for taking the time to report this. I had the impression this was implemented, even more I remember working on this. It seems I never push the changes, haha. I will do it. 

And glad to hear you find ArviZ useful!
