### ISSUE TITLE
Doc builds are failing on master

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1340]
Seems like something in khat bokeh is causing issues. Will look into it if no one beats me to it. Adding a better picture

![image](https://user-images.githubusercontent.com/7213793/89737459-fbb7e700-da25-11ea-8967-4c415408092d.png)

https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3176&view=logs&j=5e60a62b-366f-55f7-ec2d-5209191ccb17&t=d329c065-fdc0-50e4-eb39-ac3f74121b84&l=1099

**Comment by ahartikainen** [comment]
My monster or fixes this.

**Comment by ahartikainen** [comment]
Nope, it did not fix it, only part of it.
