### ISSUE TITLE
Improve layout of plots with DateTimeIndex

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#1360]
## Tell us about it

Plots with dates on their x axis can be typeset poorly.  Here is an example from https://docs.pymc.io/notebooks/getting_started.html

<img width="524" alt="image" src="https://user-images.githubusercontent.com/3274/90904396-d798c600-e394-11ea-8867-9d5c69f97db4.png">

The x coordinate here is a `DateTimeIndex`:

```
{'date': DatetimeIndex(['2008-05-02', '2008-05-05', '2008-05-06', '2008-05-07',
                '2008-05-08', '2008-05-09', '2008-05-12', '2008-05-13',
                '2008-05-14', '2008-05-15',
                ...
                '2019-11-01', '2019-11-04', '2019-11-05', '2019-11-06',
                '2019-11-07', '2019-11-08', '2019-11-11', '2019-11-12',
                '2019-11-13', '2019-11-14'],
               dtype='datetime64[ns]', name='Date', length=2906, freq=None)}
```

Looking at the web, I see that there are techniques for better formatting such axes: https://www.delftstack.com/howto/matplotlib/how-to-rotate-x-axis-tick-label-text-in-matplotlib/#fig-autofmt-xdate-rotation-to-rotate-xticks-label-text

Revised using a rotation argument for the xticklabels:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/3274/90905185-6c032880-e395-11ea-9a41-cfa6cfa2c600.png">

## Thoughts on implementation

We look at the label of the x axis, and if it is a `DateTimeIndex`, we automatically use one of these techniques.

Note: this advice applies only to the matplotlib back-end -- I don't know enough about bokeh to know if there is a corresponding technique there.

**Comment by OriolAbril** [comment]
Hi @abhisht51! Are you searching for matplotlib related issues? Or more general plotting issues? ArviZ has both matplotlib and bokeh backends. If you prefer we can also talk in [Gitter](https://gitter.im/arviz-devs/community).
