### ISSUE TITLE
loading cmdstanpy csv output

### ISSUE THREAD

**Issue by reznida** [arviz-devs/arviz#1368]
Hello,
I am trying to load a pretty big (1.1GB) cmdstanpy csv output file using arviz with:
data = az.from_cmdstan(posterior="path-to-csv")
or with
data = az.from_cmdstan(posterior=["path-to-csv", "parameter-name"])
both ways take more than an hour and use many GB of memory (at this point even 20gb is not enough and python process crushes).
Is there a more efficient way to load the sampling output data?

This issue was also discussed here - https://discourse.mc-stan.org/t/loading-cmstanpy-output-in-python/17828

arviz - the current master version (0.9.0)
cmdstanpy - 0.9.63
cmdstan - 2.24.1
python - 3.7.0
centOS7

**Comment by ahartikainen** [comment]
Hi, thanks for the issue, yes we should have a tooling to read huge csv files.

Hi, how long does it take to download 1 csv with pandas

    df = pd.read_cvs("path_here")

Do you have multidimensional outputs?

First hack that comes to mind, is to read csv to dataframe --> convert to dictionary --> `from_dict` for each chain.

Then use `az.concat` to concat idata against chains.

Your data would still be in "flat" format, so making it ndimensional needs a bit of work.

**Comment by ahartikainen** [comment]
I think in arviz we should have a `dask` based procedure for reading and converting input to inference data.

**Comment by reznida** [comment]
Thanks for answering! 
I tried loading the file with pandas as well, but got the following error:
`pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 40, saw 1053202`

I am not sure what you mean multidimensional -- I am fitting multiple subjects over 12 time points with some missing data.

**Comment by ahartikainen** [comment]
Sorry, typo in the read_csv, add `comment`

    df = pd.read_cvs("path_here", comment="#")

**Comment by reznida** [comment]
I am getting the same thing as with `arviz` - it loads the file until memory limit is reached (now is 20GB) and then it crushes.

**Comment by reznida** [comment]
I will increase the memory limit to 45GB now to see if this helps. But still I feel like these must be a better way of doing it.

**Comment by nitishp25** [comment]
> I think in arviz we should have a dask based procedure for reading and converting input to inference data.

I think dask replicates pandas functions like `read_csv` which can useful for this case

**Comment by ahartikainen** [comment]
@nitishp25  that sounds great

**Comment by reznida** [comment]
Update - 45GB limit failed as well. Could you point please to the other interfaces you have in mind?

**Comment by ahartikainen** [comment]
Could you share your csv details?

How many columns, how many rows (how many csv do you have?)

**Comment by reznida** [comment]
It's size is 1.08GB, it has 449 rows and for some reason I am unable to calculate the number of columns. But I have ~25k parameters. It is one csv file.

**Comment by ahartikainen** [comment]
with open(path, "rb") as f:
    for line in f:
        if line.startswith("#"):
            continue
        print(len(line.split(",")))
        break

**Comment by reznida** [comment]
Thanks! The file was opening in a byte mode by default, I guess this is why I couldn't calculate before.
Running your code gives me `1053202`.

**Comment by reznida** [comment]
Also I am not sure if it helps, but the Stan model was run with `reduce_sum`

**Comment by ahartikainen** [comment]
Yes, bytemode needs bytes when checking line.

reduce_sum should not affect this at all (only that you were able to get results faster)

**Comment by reznida** [comment]
Thanks! I increased the memory limit even more and it still crushes....

**Comment by ahartikainen** [comment]
How many decimals do you have in the numbers?

I tested with similar dimension with 18digits --> 11gb

**Comment by reznida** [comment]
Some values have 6 decimals, some have 9.

**Comment by ahartikainen** [comment]
I'm now testing with that 11gb file.

Can you try to read your file with this

    df = pd.read_cvs("path_here", comment="#", dtype=np.float64)

If that doesn't help there is always option to read your file in parts. Let me see a code for it.

**Comment by ahartikainen** [comment]
Ok, here is one example, I hope you can read your output with this.

```
from itertools import takewhile, repeat
import numpy as np
import pandas as pd
from tqdm import tqdm


def line_count(filename):
    # https://stackoverflow.com/questions/845058/how-to-get-line-count-of-a-large-file-cheaply-in-python
    with open(filename, 'rb') as f:
        bufgen = takewhile(lambda x: x, (f.raw.read(1024*1024) for _ in repeat(None)))
        linecount = sum( buf.count(b'\n') - buf.count(b'\n#') for buf in bufgen )
    return linecount


def read_large_csv(path, draws=None):
    nrows = line_count(path)
    df = None
    with tqdm(total=nrows+1) as pbar:
        with open(path, "rb") as f:
            # read until header
            for line in f:
                if line.startswith(b"#"):
                    continue
                header = line.decode("utf-8").split(",")
                pbar.update(1)
                break
            # create df
            df = pd.DataFrame(index=np.arange(nrows), columns=header, dtype=float)
            i = 0
            for line in f:
                if line.startswith(b"#"):
                    continue
                df.iloc[i, :] = np.array(line.split(b","), dtype=float)
                i += 1
                pbar.update(1)
    return df

df = read_large_csv("./test_file.csv")
```

After the dataframe is read, please save it with parquet (test saving dataframe with parquet first), because you probably don't want to do that another time.

After df is created, we can start to think how to create inference data. Notice that our codes work with numpy array, so you can call `az.rhat` for individual columns, but to have chain information, you would need to stack the arrays together.

**Comment by ahartikainen** [comment]
That took my computer 8 mins to read 11gb file with 500 draws, 100k parameters

**Comment by reznida** [comment]
Yes! Thanks so much. This code reads my file in a few mins.
I saved the df as parquet file with pyarrow.
But is there a straightforward way to convert it back to `arviz` to get the posterior data?

**Comment by ahartikainen** [comment]
If you can manage to use only a subset of columns, I think you could save that subset back to csv and try to read it in as cmdstan.

You might want to add the comment field from the start of the file, but I think they are optional (if not, I will need to make them optional).

For future, I think dask based solution is optimal.

**Comment by ahartikainen** [comment]
Also, if you can create a subset of data, then you could manually split your table to multiple csv and read each part in to idata and finally concat/merge different parts.

cc @OriolAbril @percygautam know a bit more about merging

**Comment by reznida** [comment]
Thanks! Is this dask based solution something I can use?

**Comment by reznida** [comment]
Update - I got what you meant about using only a subset of columns and looks like it works just fine. Thanks! For the future, I think it might be helpful to have in `arviz` the functionality of reading large csv files.

**Comment by ahartikainen** [comment]
Sounds great. Yes, we definitely need a way to read huge CSV in future.
