### ISSUE TITLE
Nominating Agustina for Core Contributor 

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1376]
Hi,
I'd like to nominate @agustinaarroyuelo to be a core contributor of ArviZ

Per our rules in the [governance doc](https://github.com/arviz-devs/arviz/blob/master/GOVERNANCE.md#core-contributor-nominations-and-confirmation-process) @agustinaarroyuelo let us know if you accept this nomination. Assuming acceptance there will be a [council vote](https://github.com/arviz-devs/arviz/blob/master/GOVERNANCE.md#voting-process) afterward!

**Comment by agustinaarroyuelo** [comment]
Thank you @canyon289 I accept this nomination :)

**Comment by canyon289** [comment]
@agustinaarroyuelo So excited you accepted!!! Our rules say were supposed to vote at the start of each month so dont worry if nothing is happening for a bit :)

**Comment by canyon289** [comment]
@agustinaarroyuelo Super excited to announce youre an ArviZ Core Contributor! You should put that into your PyMCon bio :D
