### ISSUE TITLE
Nominating at Piyush to be a core contributor

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1377]
Hi,
I'd like to nominate @percygautam  to be a core contributor of ArviZ

Per our rules in the [governance doc](https://github.com/arviz-devs/arviz/blob/master/GOVERNANCE.md#core-contributor-nominations-and-confirmation-process) @percygautam let us know if you accept this nomination. Assuming acceptance there will be a [council vote](https://github.com/arviz-devs/arviz/blob/master/GOVERNANCE.md#voting-process) afterward!

**Comment by percygautam** [comment]
Thanks, @canyon289 for the role. I gladly accept the nomination.

**Comment by canyon289** [comment]
Yessss!!!!

**Comment by canyon289** [comment]
Per rules we'll vote on October 1st! Just want to give you a heads up so youre not worried between then and now

**Comment by canyon289** [comment]
@percygautam Youre confirmed as a core contributor! Congratulations!
