### ISSUE TITLE
`utils.trace_to_dataframe` fails on `pymc3.MultiTrace` input.

### ISSUE THREAD

**Issue by MFreidank** [arviz-devs/arviz#138]
Hello everyone,

I just noticed that `trace_to_dataframe` may fail on entirely valid `pymc3.MultiTrace` objects, this is due 
to the following code:
`if type(trace).__name__ == "MultiTrace"`. 

I get the intention, I believe, one wants to avoid a dependency on `pymc3`. 
However, if I import `pymc3` as `import pymc3 as pm` and then use `pm.backends.base.MultiTrace` to construct a trace I will get an error as:
`type(trace).__name__` will return `"pm.backends.base.MultiTrace`. 

I suggest the following approach:
```
try:
    from pymc3.backends.base import MultiTrace
except ImportError:
    pass   # this still avoids a dependency on pymc3
else:
    is_multitrace = isinstance(trace, MultiTrace) 
```
This avoids a dependency and handles arbitrary ways to import `MultiTrace`.
I have code ready for this, if you agree with me on the way forward I'm willing to provide a pull request.

Best,
MFreidank

**Comment by aloctavodia** [comment]
A pull request is more than welcome! Thanks!
