### ISSUE TITLE
NumFOCUS donation link

### ISSUE THREAD

**Issue by lisamartin72** [arviz-devs/arviz#1384]
Hi Arviz project!

Attached is the URL and the code for your NF donation button. Most of our sponsored projects have one on their websites for donations. 

Please reach out if you have any questions. Have a great day.

https://numfocus.salsalabs.org/donate-to-arviz

```
<a href="https://numfocus.salsalabs.org/donate-to-arviz" target="_blank" style="background:#FFA500;padding:10px;margin:10px 0px;text-align:center;text-decoration:none;font-size:12pt;color:#222222;font-family:Arial, Helvetica, sans-serif;display:inline-block;">Donate Now!</a>
```

**Comment by OriolAbril** [comment]
Thanks!

I have added it to the `.github` repo: https://github.com/arviz-devs/.github/pull/1 will add it to the docs and the readme tomorrow if I have time unless someone gets to it before.
