### ISSUE TITLE
test against xarray master branch

### ISSUE THREAD

**Issue by dcherian** [arviz-devs/arviz#1388]
## Tell us about it

Can Arviz test against xarray's master branch? We do something similar with pandas+numpy+etc to catch issues prior to release.
(https://github.com/pydata/xarray/blob/1155f5646e07100e4acda18db074b148f1213b5d/ci/azure/install.yml#L15-L55)
## Thoughts on implementation

This would've caught #1387 more than a month ago when https://github.com/pydata/xarray/pull/4297 was merged

Thanks!

**Comment by ahartikainen** [comment]
Hi, thanks for the tip.

I think we could add one runner with the gh master.

**Comment by ahartikainen** [comment]
Fixed by #1391
