### ISSUE TITLE
plot_rank ignores backend_kwargs

### ISSUE THREAD

**Issue by jsevo** [arviz-devs/arviz#1396]
Using `plot_rank` on many a trace with many coefficients can require changing the line widths and marker sizes (e.g. when using `kind="vlines"`). 

This usage however has no effect:

`az.plot_rank(many_coefficient_trace, backend_kwargs={'linewidth':0.5, 'markersize':1, 's':1})`

The docstring says 

> These are kwargs specific to the backend being used. For additional documentation check the plotting method of the backend.

, which seems to suggest passing this dictionary is the correct usage. How can this be changed to accept kwargs, or could an example usage be added?

**Comment by OriolAbril** [comment]
Hi, `backend_kwargs` are related to figure/axes generation. They are passed to https://docs.bokeh.org/en/latest/docs/reference/plotting.html#bokeh.plotting.figure or to https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots.html. The kwargs used to customize the drawing are generally passed as `plot_kwargs`, `line_kwargs`... in `plot_rank` however, these do not seem to be available. 

If it's ok, I'll change the title of the issue to `plot_rank` is missing plot customization kwargs so we remember to add them. We should look at the code and see which customization kwargs would make sense here then add them to the funcion
