### ISSUE TITLE
Add input core dims to plot_hdi doc strings

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1400]
**Describe the bug**
`input_core_dims` doc string is missing even though its documented below in the examples in both `az.hdi` and `az.plot_hdi`

https://arviz-devs.github.io/arviz/generated/arviz.plot_hdi.html#arviz.plot_hdi
https://arviz-devs.github.io/arviz/generated/arviz.hdi.html#arviz.hdi

**Suggested fix**
Add to both documentation strings

**Comment by OriolAbril** [comment]
It's a keyword argument passed as `**kwargs`, it's not only `input_core_dims` that can be used but any of the arguments accepted by `wrap_xarray_ufunc` which is referenced and linked in the dosctring. 

I think it would be better to extend the explanation in the example that uses it to make this clear.

**Comment by abhisht51** [comment]
Can you provide some example of what needs to be added here.

**Comment by OriolAbril** [comment]
## hdi
in `hdi` doc, we could change the 

``` 
If we want to calculate the HDI over specified dimension of dataset, we can pass input_core_dims by kwargs:
```

like with something like

```
By default, ``hdi`` is calculated over the ``chain`` and ``draw`` dimensions. We can use the 
``input_core_dims`` argument of :func:`~arviz.wrap_xarray_ufunc` to change this. In this example 
we calculate the HDI also over the ``school`` dimension:
```

and also change the code right below from `az.hdi(data, input_core_dims = [["chain"]])` to 

```
az.hdi(data, input_core_dims = [["chain", "draw", "school"]])
```

## plot_hdi
Change 

```
Precalculate HDI interval per chain and plot separately:
```

to

```
``plot_hdi`` can also be given precalculated values with the argument ``hdi_data``. This example 
shows how to use :func:`~arviz.hdi` to precalculate the values and pass these values to ``plot_hdi``. 
Similarly to an example in ``hdi`` we are using the ``input_core_dims`` argument of :func:`~arviz.wrap_xarray_ufunc` 
to manually define the dimensions over which to calculate the HDI.
```

What do you think @canyon289 ?

@abhisht51 if this were clear now, would you like to work on this issue?

**Comment by abhisht51** [comment]
I have understood what needs to be modified in the docs. I would be issuing a pull request soon!!

**Comment by abhisht51** [comment]
Hi, 
I think I have made the necessary PR however I would like to point out that the "Hacktoberfest" label added by @percygautam does not counts as a valid one as hacktoberfest has made my PR ineligible. I believe the topic should have been "hacktoberfest" instead. I am new to this so I don't really know.

**Comment by percygautam** [comment]
Hi @abhisht51, Thanks for the PR. We have decided to opt-out of the #hacktoberfest after their [announcement](https://twitter.com/digitalocean/status/1312220884665536512?s=20) on Oct 3rd. I believe that's why this PR is ineligible. Sorry, I forgot to remove the labels. 
As for the PR, someone will review it soon(It usually takes around a week). Thanks for showing interest in ArviZ.

**Comment by abhisht51** [comment]
No worries!!
