### ISSUE TITLE
Typo in plot_dist

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1413]
**Describe the bug**
One of the errors in `plot_dist`  says use `xarray.Dateset.` Should be dataset
https://github.com/arviz-devs/arviz/blob/master/arviz/plots/distplot.py#L166

**Expected behavior**
Should read as as `xarray.Dataset`

**Comment by JoanRosell** [comment]
Hi, could I pick this one up?

**Comment by ahartikainen** [comment]
Yes.

**Comment by OriolAbril** [comment]
I no dubtis en preguntar aquí o a [gitter](https://gitter.im/arviz-devs/community) si tens cap dubte!

**Comment by virajone** [comment]
Hey, has this one been fixed yet ?

**Comment by OriolAbril** [comment]
Hi @virajone, thanks for your interest in ArviZ! 

The issue has not been fixed yet, but work on it has already started. Therefore, as stated in our [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#steps-before-starting-work) in order to prevent duplicated work, you should find other contributions to work on.

I see you have already commented on a second issue but I still want to say that we can also help in finding issues/features that fit your interests

**Comment by virajone** [comment]
@OriolAbril , thanks a lot for your response. I would surely like to contribute and I appreciate your help. I am looking for an issue that's beginner friendly and relatively easy given that I'm new to the project.  Would be great if you can assign / assist me finding one. :)

**Comment by OriolAbril** [comment]
In my opinion, the lowest hanging fruits currently are #1188 and #956 (the issue description may be very clear but I can work on that). They affect multiple files but I woule encourage to tackle them 1-2 files per PR. #681 could also be a good candidate. 

I also consider #1318 to be low hanging fruit but it requires knowing about benckmarking, something similar to [numba's notebook](https://arviz-devs.github.io/arviz/notebooks/Numba.html). kde calls many utilities and I think some of them won't need any change in their code to benefit from numba. I can help id the candidates so the task would be to try and experiment with the benchmarcks to see if this vanilla numba can speed up our kde function

**Comment by JoanRosell** [comment]
Sorry for the late reply, I opened #1414 that will close this issue. I'm new to open source so I don't know if I should link the issue to the PR in this way 😕

**Comment by OriolAbril** [comment]
> I don't know if I should link the issue to the PR in this way

#1414 is great. Provided that like in this case a PR aims to close an open issue, the recommended way to link PR and issue is mentioning the issue from the PR description with [one of these keywords](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references), `fixes` is one of them so you can already see above the 

> JoanRosell linked a pull request that will _close_ this issue 6 hours ago 

Thanks to these keywords, GitHub will close the issue once the PR is merged
