### ISSUE TITLE
to_dataframe release timeframe

### ISSUE THREAD

**Issue by avivajpeyi** [arviz-devs/arviz#1420]
Thanks for this awesome piece of software! 

`InferenceData.to_dataframe()` is present in the docs but I think is currently unreleased. I was wondering, is there a tentative timeframe planned for a new `arviz`?  

Thanks!

**Comment by ahartikainen** [comment]
Hi, we have some things still needing a bit of fixing, but I would say we are probably going to create a new release in the following weeks.
