### ISSUE TITLE
Add an examples of coords argument in documentation

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1436]
**Describe the bug**
There's this fancy coords argument but not a great explanation on how to use it in the code examples below
https://arviz-devs.github.io/arviz/api/generated/arviz.plot_posterior.html

![image](https://user-images.githubusercontent.com/7213793/97931298-2adaad80-1d22-11eb-9e97-3e46ed2f9650.png)

**To Reproduce**
Look at the doc, notice the lack of coords documentation in the code example

**Expected behavior**
Theres an example in the code below

**Comment by Spandyie** [comment]
@canyon289 I would like to take on this issue, do you mind assigning it to me ?

**Comment by OriolAbril** [comment]
Assigned it to you! Thanks for your interest, let us know if you have any questions about the contributing process :smile:

**Comment by vardaan-raj** [comment]
Hello! I am very much interested and would like to start off. Is it open and if so ,can you assign it to me ?

**Comment by canyon289** [comment]
@vardaan-raj It is open and I will assign it to you right now!

**Comment by Rishabh261998** [comment]
Hi @canyon289, as this issue is not active for more than 2 weeks so can it be assigned to me?. Thank You

**Comment by OriolAbril** [comment]
I will assign it to you @Rishabh261998
