### ISSUE TITLE
Automatically set `divergences=False` when trace does not contain dvergences

### ISSUE THREAD

**Issue by rlouf** [arviz-devs/arviz#1439]
## Short Description

I am trying to plot the trace obtained with a Metropolis Hastings sampler. Since `divergence` is a notion that only exists for the HMC family, I initialize `InferenceData` with `diverging = None`. However, when I plot the trace I have to specify `divergences = None` which can cumbersome.

Maybe I am doing something wrong. Otherwise, would it be possible to disable this option automatically when the value of `diverging` in `sample_stats` is set to None? I don't mind doing the change myself.

**Comment by ahartikainen** [comment]
It should do that already.

What is it saying when with default settings?

**Comment by rlouf** [comment]
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-57-7c3f6fe9d699> in <module>
----> 1 az.plot_trace(trace);

~/.virtualenvs/mcx/lib/python3.7/site-packages/arviz/plots/traceplot.py in plot_trace(data, var_names, filter_vars, transform, coords, divergences, kind, figsize, rug, lines, circ_var_names, circ_var_units, compact, compact_prop, combined, chain_prop, legend, plot_kwargs, fill_kwargs, rug_kwargs, hist_kwargs, trace_kwargs, rank_kwargs, axes, backend, backend_config, backend_kwargs, show)
    236 
    237     plot = get_plotting_function("plot_trace", "traceplot", backend)
--> 238     axes = plot(**trace_plot_args)
    239 
    240     return axes

~/.virtualenvs/mcx/lib/python3.7/site-packages/arviz/plots/backends/matplotlib/traceplot.py in plot_trace(data, var_names, divergences, kind, figsize, rug, lines, circ_var_names, circ_var_units, compact, compact_prop, combined, chain_prop, legend, plot_kwargs, fill_kwargs, rug_kwargs, hist_kwargs, trace_kwargs, rank_kwargs, plotters, divergence_data, axes, backend_kwargs, backend_config, show)
    329 
    330                 for chain, chain_divs in enumerate(divs):
--> 331                     div_draws = data.draw.values[chain_divs]
    332                     div_idxs = np.arange(len(chain_divs))[chain_divs]
    333                     if div_idxs.size > 0:

IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by ahartikainen** [comment]
So you have `idata.sample_stats.diverging` `None` or array with None?

I don't think you should have it like that.

**Comment by rlouf** [comment]
It is set to `None`. What do you suggest instead?

**Comment by ahartikainen** [comment]
You should not have that there.

I don't think setting attributes to None in `xarray.Dataset` is the correct way to handle missing values.

**Comment by ahartikainen** [comment]
So, when you create the InferenceData, you shouldn't set variables to None. Of if you do that, then filter them out before you create the xarray.Dataset.

**Comment by rlouf** [comment]
How do you handle missing value? What's the alternative?

**Comment by ahartikainen** [comment]
Not creating that attribute.
