### ISSUE TITLE
How to change rcParams

### ISSUE THREAD

**Issue by NA-Dev** [arviz-devs/arviz#1440]
## Short Description

I am trying to increase max_subplots for az.plot_trace() from 15 to 30, but I can't get it to use my override settings. When I print the setting it has been updated, but the plot still cuts off at 15 and gives me the warning. "python3.8/site-packages/arviz/plots/traceplot.py:191: UserWarning: rcParams['plot.max_subplots'] (15) is smaller than the number of variables to plot (30), generating only 15 plots"

## Code Example or link
I have tried...
```
az.rcParams['plot.max_subplots'] = 30 
with logistic_model:
    az.plot_trace(trace_main, var_names=['beta0','beta'])
```
or
```
with logistic_model, az.rc_context({"plot.max_subplots": 30}):
    az.plot_trace(trace_main, var_names=['beta0','beta'])
```

## Relevant documentation or public examples

I followed each option in this documentation https://oriolabril.github.io/oriol_unraveled/python/arviz/2020/06/19/rcParams.html#Customizing-ArviZ

**Comment by aloctavodia** [comment]
Hi @NA-Dev I am not able to reproduce your problem. This is what  I get.

a = np.random.normal(0, 1, 100)
trace = {"a":a, "b":a,"c":a,"d":a,"e":a,"f":a} 

az.rcParams['plot.max_subplots'] = 2
az.plot_trace(trace)

![index](https://user-images.githubusercontent.com/1338958/98936394-aaefd880-24c3-11eb-9232-06a1a165b0db.png)


az.rcParams['plot.max_subplots'] = 30
az.plot_trace(trace)
![index2](https://user-images.githubusercontent.com/1338958/98936407-af1bf600-24c3-11eb-8e9a-c6dbad389cc6.png)

**Comment by aloctavodia** [comment]
Ohh I see now, If you have 30 variables then you need to set `az.rcParams['plot.max_subplots'] = 60` as `plot_trace` uses 2 subplots per variable.

**Comment by NA-Dev** [comment]
Oh that is easy enough, thank you so much!
