### ISSUE TITLE
Repeated warning in summary() when only one chain is sampled

### ISSUE THREAD

**Issue by twiecki** [arviz-devs/arviz#1441]
Sometimes I sample just one chain (yeah I know, call the Bayesian police on me). When then calling `az.summary()` I get tons of: `arviz.stats.stats_utils - WARNING - Shape validation failed: input_shape: (1, 2000), minimum_shape: (chains=2, draws=4)` one for each RV, which can be a lot. I think that warning could just be dropped, if only one chain is present I would for example not assume an Rhat value to be calculated but I would still like to see the rest of the summary.

**Comment by aloctavodia** [comment]
Chain on you Thomas! ;-)
I agree it can be very annoying. It should be reported just one.
