### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by karink520** [arviz-devs/arviz#1457]
Hi folks! Thanks for making arviz awesome!

**Describe the bug**
The link to the quickstart from the usage page in the docs (https://arviz-devs.github.io/arviz/usage.html) is broken - it sends you to https://arviz-devs.github.io/arviz/notebooks/Introduction.html.

(Fun fact: If you try to keep navigating through the menus after going through this broken link, things only get more messed up!)

**To Reproduce**
From https://arviz-devs.github.io/arviz/usage.html, click on the "quickstart" link under the Quickstart heading.

Happy to help fix if useful. I'm not super familiar with Sphinx, but if you send me a pointer to the right file, I'll see what I can do!

**Comment by ahartikainen** [comment]
Hi, thanks for the issue.

I think the correct page is https://arviz-devs.github.io/arviz/getting_started/Introduction.html that we probably missed when we refactored the docs.

To fix this, you need to change the link found in https://github.com/arviz-devs/arviz/blob/master/doc/source/usage.rst

**Comment by ahartikainen** [comment]
Yep, we should use relative links here, not the html.

If you want, you can create the PR and add `[doc]` to the title so it will upload the compiled docs to CI (Artifacts)

**Comment by OriolAbril** [comment]
As Ari says, I think the ideal fix would be first adding an anchor to the quickstart notebook and then changing the text in `usage` page to link to the anchor.

As we are using [MyST](https://myst-parser.readthedocs.io/en/latest/), anchors can be created in notebooks too using the extensions that myst adds to markdown using:

    (anchor_name)=

the [cookbook](https://github.com/arviz-devs/arviz/blob/master/doc/source/getting_started/InferenceDataCookbook.ipynb) has an example of markdown anchor.

Which can then be referenced from `usage.rst` with 

    :ref:`text to be shown <anchor_name>`
