### ISSUE TITLE
Implement `distplot` equivalent

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#146]
There are a few places where we would like to use `arviz.kdeplot` if a variable is continuous, and a histogram if not (traceplots, for example).  

This might involve implementing a `histplot` first and then having `distplot` just inspect the `dtype`.

(happy if someone wants to change the names of any of these...)

**Comment by aloctavodia** [comment]
Right, this will be very helful, distplot sounds like a good name.

**Comment by Dpananos** [comment]
I'd be up to contribute.

**Comment by ahartikainen** [comment]
Is `plot_density` what you were hoping for?

https://github.com/arviz-devs/arviz/blob/master/arviz/plots/densityplot.py

**Comment by ColCarroll** [comment]
Not exactly -- much like `plot_kde` accepts a raw numpy array, and lets us call it from other plots, I want a plot that I can call with a numpy array that _either_ calls `plot_kde` or some discrete version, so we can use it everywhere else (I think there are a few corners cut with discrete plots, still!)

**Comment by aloctavodia** [comment]
if @Dpananos does not have the time to work on this I will be happy to take it.
