### ISSUE TITLE
Posterior predictive check (plot_ppc) with dataframe encoding. 

### ISSUE THREAD

**Issue by sperezconesa** [arviz-devs/arviz#1461]
Hello everyone!

I have a model which has two cases enconded in df['membrane_enc'], so this should give two indepently modelled likelyhoods and posteriors. I train the model in this fashion:
```python
shape = df['membrane_enc'].unique().shape
with pm.Model() as my_model:
    tau = pm.HalfNormal('tau', sigma=1.,shape =shape)
    tau_0 = pm.TruncatedNormal('tau_0', mu = min_val, sigma = 1, lower = 0, upper = min_val, shape =shape)
    like = DensityDist('like', logp_exp_lag(tau_0[df['membrane_enc']],tau[df['membrane_enc']]), observed=df['tpore'], random=custom_random, shape = (2,180))
with my_model:
    my_model_trace = pm.sample(4000, tune=3000,  random_seed=RANDOM_SEED)
    ppc = pm.sample_posterior_predictive(my_model_trace, var_names = ['like'],  random_seed=RANDOM_SEED)
    my_model_trace = az.from_pymc3(trace=my_model_trace, model=my_model, posterior_predictive=ppc)
    my_model_trace.to_netcdf(model_path)
```
The model converges nicely and gives reasonable posteriors for the two encodings. The problem comes when I try to plot the posterior predictive. I cannot find the way to plot the two distinct ppc's in two graphs:
```python
az.plot_ppc(my_model_trace, random_seed=RANDOM_SEED, var_names = ['like'], flatten = [])
```
This code fails and I am not sure which dimension I should flatten since there is only one in `my_model_trace`, `like_dim_0` and it doesn't work. All this code works nicely if you only work with one dimension. 

Can someone please help me make this plotting work?

By the way, I am using arviz 0.10.0.

Thank you very much in advance!
Best,
Sergio

**Comment by OriolAbril** [comment]
Hi! 

Can you share the netcdf file or some code to generate fake data with the same/similar dims? I think I have a vague idea of the issue but I'd like to be sure before diving in.

**Comment by sperezconesa** [comment]
Hello,
I think I narrowed down where the problem is. The problem is that in my_model_trace.observed_data and my_model_trace.posterior_predictive the data is 1d. plot_ppc does not know how to split it into chunks according to a label array. I made this quick hack but it is far from ideal:
```python
    fig, ax = subplots(n_rows, n_cols, figsize=(sizex,5.5*n_rows), sharex=False, sharey=False)
    ax = ax.flatten()
    for i in range(n_plots):
        trace.observed_data['ppc'] = trace.observed_data[key][array(label_array) == i]
        trace.posterior_predictive['ppc'] = trace.posterior_predictive[key][:,:,:,i]
        plot_ppc(trace, var_names = 'ppc', legend=False, ax=ax[i], **plot_kwargs)
        ax[i].set_xlabel(f'ppc var {enc_dic[i]}')
    ax[0].legend()
    if n_rows > 1:
        if n_plots % 4 != 0:
            for i in range(4 - n_plots % 4):
                fig.delaxes(ax[-i-1])
    fig.tight_layout()
    trace.posterior_predictive = trace.posterior_predictive.drop('ppc')
    trace.observed_data = trace.observed_data.drop('ppc')
```
for every label it generates a new 1-d data set in trace with values where the mask is true and NaN elsewhere. This new data set is fed to plot_ppc axes.

Maybe a better data structure or a modification of plot_ppc could be added to future releases so this can be done automatically.
Best,
Sergio

**Comment by OriolAbril** [comment]
Still not sure what is the structure of the data, sorry. I understand you want to get something like the 3rd and 4th examples in https://arviz-devs.github.io/arviz/api/generated/arviz.plot_ppc.html but `flatten=[]` nor other flatten combinations work. Is that right? 

`flatten` should take care of these cases, but it's possible yours escapes its current capabilities and it needs to be improved. CAn you post the results of `print(idata.observed_data)` and `print(idata.posterior_predictive)`?

**Comment by sperezconesa** [comment]
Yes, like those examples. I have tried a lot of combinations and none seem to work.
Here is the output:
![image](https://user-images.githubusercontent.com/27727343/103655398-777f7680-4f67-11eb-98ef-1870e6b8e7ec.png)
Although I have changed a bit how I generate the data:
```python
shape = df['membrane_enc'].unique().shape
with pm.Model() as my_model:
    tau = pm.HalfNormal('tau', sigma=5.,shape =shape)
    tau_0 = pm.TruncatedNormal('tau_0', mu = min_val, sigma = 1, lower = 0, upper = min_val, shape =shape)
    like = DensityDist('like', logp_exp_lag(tau_0[df['membrane_enc']],tau[df['membrane_enc']]), observed=df['tpore'], random=random)
with my_model:
    my_model_trace = pm.sample(4000, tune=3000,  random_seed=RANDOM_SEED)
    ppc = pm.sample_posterior_predictive(my_model_trace,  random_seed=RANDOM_SEED, samples=40, size=1000)
    my_model_trace = az.from_pymc3(trace=my_model_trace, posterior_predictive=ppc)
    print('Done infering.')
    spc_os.remove(model_path)
    my_model_trace.to_netcdf(model_path)
```

**Comment by OriolAbril** [comment]
Your `like_dim_0` in `observed_data` and your `like_dim_0` and `1` in `posterior predictive` are all ranges, unlike in the example in the docs, there is no information available to have ArviZ group the data the way you want it to be grouped. This is why to group the data in your manual plotting code you need to index using masks based on `label_array`, ArviZ however has no access to this information. 

If you study closely the example in the documentation, you'll see that before calling `plot_ppc` we edit the coordinates of our data so that this labeling information is updated. This is done in these lines of code:

```
obs_county = data.posterior["County"][data.constant_data["county_idx"]]
data = data.assign_coords(obs_id=obs_county, groups="observed_vars")
```

Before doing that, `obs_id` was only and arange with the observation id, after that, the coordinate values indicate the county in which the observation was taken and thus, ArviZ can group by county if told to do so via the flatten argument. In your case it will probably be trickier because `observed_data` and `posterior_predictive` have different shapes but you should be able to get the desired result anyways using `flatten`. Note that you may need to use [xarray's `assign_coords`](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.assign_coords.html#xarray.Dataset.assign_coords) to both observed and pp data instead of ArviZ's convenience oneliner [`assign_coords`](https://arviz-devs.github.io/arviz/api/generated/arviz.InferenceData.assign_coords.html#arviz.InferenceData.assign_coords)

**Comment by sperezconesa** [comment]
Thanks for the pointers, now the code looks like:
```python
my_model_trace = my_model_trace.assign_coords(like_dim_0=df['membrane_enc'].to_numpy(),
                                              groups='observed_data')
my_model_trace.posterior_predictive = my_model_trace.posterior_predictive.rename({'like_dim_1':'membrane_enc'})
my_model_trace.observed_data = my_model_trace.observed_data.rename({'like_dim_0':'membrane_enc'})
az.plot_ppc(my_model_trace,  flatten=['draw', 'chain', 'like_dim_0']) # flatten all dimension except the one we are interested in
```
I have added labels to `like_dim_1' and renamed the coordinates that represent the encoding. Now I get the result I was looking for:
![image](https://user-images.githubusercontent.com/27727343/103910664-610f2180-5105-11eb-841a-7310ae5eb413.png)
Thanks a lot for your help!

**Comment by OriolAbril** [comment]
Glad I could be of help!
