### ISSUE TITLE
Fix badge icons for CI and Coverage status in docs

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1465]
**Describe the bug**
Badge display in docs is not correct
![image](https://user-images.githubusercontent.com/7213793/102139117-3daccb80-3e12-11eb-9b82-cedffe461ca7.png)

**To Reproduce**
https://arviz-devs.github.io/arviz/

**Expected behavior**
We want nice badge images like this one in the README 
https://github.com/arviz-devs/arviz
![image](https://user-images.githubusercontent.com/7213793/102139244-6fbe2d80-3e12-11eb-9e17-9fec4d8b323b.png)

**Comment by vedantd** [comment]
Hey, I would like to take up the issue. I'm new to opensource and see this as a good starting beginner issue.

**Comment by canyon289** [comment]
@vedantd I appreciate you taking initiative and wanting to fix this issue. Unfortunately ( or fortunately maybe), I just checked and the issue seems to have resolved itself. As is such I'm closing this ticket. If you are still interested in contributing to ArviZ though let me know and I can find another ticket for you.

**Comment by vedantd** [comment]
Hey, I do want to make contributions but would appreciate it if you can
assign me and guide me through some beginner level issues as I am a bit
inexperienced and have never made prior open source contributions but want
to begin somewhere.
