### ISSUE TITLE
from_cmdstan should accept observed_data in json or as variable

### ISSUE THREAD

**Issue by jsevo** [arviz-devs/arviz#1466]
The below fails when providing a path to the data in `.json` format used by `cmdstan` itself. Per docstring, only data in `Rdump` format can be used. `Rdump` is not an ideal default data format.

`from_cmdstan` is lacking documentation; I could not find a workaround.

```
idata = az.from_cmdstan(posterior="trace.csv",
                                           obeserved_data="data.json"
                             )
```

**Comment by ahartikainen** [comment]
Hi, yes we should update our `from_cmdstan` functionality. Would you be interested in adding a json support?

For short term solution I recommend you get posterior with `from_cmdstan` and then add data manually.

    import json
    with open("data.json", "w") as f:
        data_dict = json.load(f)
    idata_data = az.from_dict(observed_data=data_dict)
    idata_cmdstan = az.from_cmdstan(posterior="trace.csv")
    idata = az.concat((idata_cmdstan, idata_data))

cc. @percygautam & @OriolAbril did we have option to use merge too?

**Comment by OriolAbril** [comment]
We added an [`add_groups`](https://arviz-devs.github.io/arviz/api/generated/arviz.InferenceData.add_groups.html#arviz.InferenceData.add_groups) not long ago which I think will be convenient in this case. 

Something like the code below should work.

```
import json
with open("data.json", "w") as f:
    data_dict = json.load(f)
idata = az.from_cmdstan(posterior="trace.csv")
idata.add_groups(observed_data=data_dict)
```

**Comment by OriolAbril** [comment]
closed by 1762
