### ISSUE TITLE
Switch to `compact=True` by default in our plots

### ISSUE THREAD

**Issue by AlexAndorra** [arviz-devs/arviz#1468]
I see a lot of people confused by `plot_trace` failing, because they have lots of parameters in their model but are expecting the old PyMC behavior (which was to plot compact by default). It's true that plotting more than ~10 parameters separately easily becomes cumbersome.

Switching to `compact=True` by default should be easy enough and be more user friendly. Feel free to comment if you want to take on this issue 🖖

**Comment by Justin-1993** [comment]
Hello, I would like to take on this Issue.  This would be my first open source contribute if that is ok
