### ISSUE TITLE
Is there a better way to show Rope in relation to HDP for PosteriorPlot?

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#147]
Hey all,
Open ended issue here. I feel like the ROPE visualization right now would be better if it didn't hide the HDP. See the plot of mu below.

Proposals I have are
1. Move the HDP line above the ROPE Line since the HDP line is smaller
2. Plot ROPE as a vertical line like Kruschke does in this blog post http://doingbayesiandataanalysis.blogspot.com/2013/08/how-much-of-bayesian-posterior.html
3. Give ROPE and opacity/alpha/transparency value lower than 1

![image](https://user-images.githubusercontent.com/7213793/43406344-dde3f46e-93d0-11e8-94fa-a54412606ab4.png)

I can provide mockups of any of these if people want. 

Alternatively if this behavior is desired do nothing, sort of like accepting the null hypothesis if you know what I mean :) (Sorry I had to)

**Comment by aloctavodia** [comment]
Hi, the ROPE used to have an alpha value lower than 1, 0.35 I think. Something happen at some point! Haha. 

So I would suggest implementing the third option.

**Comment by ColCarroll** [comment]
thanks for this -- I'll try to push some semi-working code tonight and maybe implement the above.  Probably also changing the z-ordering (option 1).

**Comment by canyon289** [comment]
@ColCarroll Busy week for you! If you want to pass any of this onto me I'd be happy to oblige.

thanks for all the feedback during my deepdive on posteriorplots

**Comment by ColCarroll** [comment]
@canyon289 will let you close this if you're ok with the new appearance of ROPE, or please experiment with it more if you'd like to improve it!

**Comment by canyon289** [comment]
It looks great! Thank you very much

**Comment by canyon289** [comment]
Rereading this I realize the comment was probably not directed at me. If I closed this but wasn't supposed I apologize

**Comment by ColCarroll** [comment]
Comment was definitely directed at you! 😄 You seemed to have good ideas about styling for these plots, and I only wanted to close this issue if you were ok with it.
