### ISSUE TITLE
Deprecate the use of `from_pymc3` outside the model context

### ISSUE THREAD

**Issue by AlexAndorra** [arviz-devs/arviz#1470]
When people give PyMC's `MultiTrace` objects to ArviZ functions outside the model context, this raises a `FutureWarning` because it calls `az.from_pymc3` under the hood, which is supposed to stop working without a model context.

As this warning has been there for a while now, we should actually go ahead and deprecate this possibility, especially as [PyMC is going to switch](https://github.com/pymc-devs/pymc3/issues/4372) to returning `InferenceData` by default in 4.0.0.

Feel free to comment if you want to take on this issue 🖖

**Comment by OriolAbril** [comment]
Closing this as we moved the converter to pymc3 codebase and the model context is already required in the v4 version
