### ISSUE TITLE
Master Branch builds failing again due to installation problems

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1471]
**Describe the bug**
Master branch builds failing due to some change in downstream packages. Looks like something changed with TFP and/or PyMC3

**To Reproduce**
https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3680&view=logs&j=af9a1d3a-ff8f-5483-6823-86518c773a9b&t=91d5999d-c3e7-502d-15b0-1abfa51eab6f&l=14

**Expected behavior**
CI Passes

**Comment by canyon289** [comment]
Rerunning pipeline to see if PyMC3 install error persists. IT was some clone error so I hope its a one off.

https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3681&view=results

**Comment by AlexAndorra** [comment]
Thanks for dealing with this @canyon289 !
It seems like #1473 [encountered this error too](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3690&view=logs&j=c386d60b-d885-573f-0dc9-50acbfdb69a9&t=c10daa47-4c46-5692-7e81-5600bbd0e0b2&l=15) -- does this help a bit with the diagnosis?

**Comment by canyon289** [comment]
@AlexAndorra I merged https://github.com/arviz-devs/arviz/issues/1471 which should fix. Rebase your PR and you should be good to go
