### ISSUE TITLE
Arviz Docs Website down?

### ISSUE THREAD

**Issue by CloudChaoszero** [arviz-devs/arviz#1482]
**Describe the bug**

* Is the Arviz Docs website down? https://arviz-devs.github.io

I tried both HTTPS & HTTP, and receive same results

![Screen Shot 2020-12-28 at 2 58 05 AM](https://user-images.githubusercontent.com/19514362/103209726-9ec7ab00-48b8-11eb-8c6c-27acbc95352b.png)

I can assume that maybe it wasn't fully rebuilt, but unsure.

**Comment by ColCarroll** [comment]
Can confirm that https://arviz-devs.github.io/arviz/ is down.

Here are [some logs](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3713&view=logs&j=5e60a62b-366f-55f7-ec2d-5209191ccb17&t=3b19a6af-f535-5ba4-1e9a-379fb7d07d81), and it looks like the most suspicious line is 

```
Handler <function main at 0x7f2c6d3259d0> for event 'builder-inited' threw an exception (exception: Bokeh was not loaded in time. Something may have gone wrong.)
```

**Comment by ahartikainen** [comment]
Site works for me?
'https://arviz-devs.github.io/arviz/

**Comment by aloctavodia** [comment]
It was down, I re-built the docs (or maybe some else did some magic) and it seems it is working again. Thanks @CloudChaoszero for the report.
