### ISSUE TITLE
Error message with az.plot_trace(trace_)

### ISSUE THREAD

**Issue by Jacques2101** [arviz-devs/arviz#1483]
Hi, I tried the simple code but get an error message that I do not understand. 

Any ideas ? 
Thx 

## Code
```
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy as np
import pandas as pd
import seaborn as sns
import pymc3 as pm
import arviz as az

np.random.seed(123)
trials = 1000
theta_real = 0.35  # unknown value in a real experiment
data = stats.bernoulli.rvs(p=theta_real, size=trials)

with pm.Model() as our_first_model:
    # a priori
    θ = pm.Beta('θ', alpha=1., beta=1.) 
    # likelihood
    y = pm.Bernoulli('y', p=θ, observed=data)
    trace = pm.sample(1000, random_seed=123, tune=1000)

az.plot_trace(trace)
```

## Error message 
```
/Users/jacques/opt/anaconda3/envs/bayes/lib/python3.8/site-packages/arviz/data/io_pymc3.py:87: FutureWarning: Using `from_pymc3` without the model will be deprecated in a future release. Not using the model will return less accurate and less useful results. Make sure you use the model argument or call from_pymc3 within a model context.
  warnings.warn(
```

## Versions and main components
* PyMC3 Version:  3.8 
* Theano Version:  1.0.4   
* Arviz: 0.10.0
* Python Version: 3.8.5
* Operating system: macOS Big Sur 1.1

**Comment by OriolAbril** [comment]
Hi @Jacques2101 the message you posted is only a warning, you should still get the plot generated, if you don't please share the whole error message as there may be something else happening. 

When you call `plot_trace` with a `pm.MultiTrace` object, ArviZ first converts the data to [InferenceData](https://arviz-devs.github.io/arviz/getting_started/XarrayforArviZ.html) (see also this [blogpost](https://oriolabril.github.io/oriol_unraveled/python/arviz/pymc3/xarray/2020/09/22/pymc3-arviz.html) for extra pymc3-arviz guidance). In some cases, the MultiTrace object is enough to convert to InferenceData, but in many cases the Model object is also needed. 

The warning is letting you know that in a future ArviZ release, you will always need to pass not only the MultiTrace but also the Model object to make sure the conversion does not return an incorrect InferenceData. 

I would personally recommend using the `return_inferencedata` argument in `pm.sample`, which will also in future PyMC3 releases become the default to get directly an InferenceData object as output of `pm.sample`.

**Comment by OriolAbril** [comment]
Closing as I see @Jacques2101 is now using `return_inferencedata=True` in #1485
