### ISSUE TITLE
ExecutableNotFound: failed to execute ['dot', '-Tsvg']

### ISSUE THREAD

**Issue by Jacques2101** [arviz-devs/arviz#1485]
Hi, any help needed. I get this error message with my code. 
I found some site that try to solve this problem but not helping me solve this error message. I tried to add for example: 
```
import os
os.environ["PATH"] += os.pathsep + "/Users/jacques/opt/anaconda3/envs/bayes/lib/graphviz"
```
at the beginning of the packages import. 

**Describe the bug**
got an error message with the code below 
`ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH`

**To Reproduce**
```
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc3 as pm
import scipy.stats as stats
import seaborn as sns

with pm.Model() as model:
    mu = pm.Normal("mu", mu=0, sigma=1)
    obs = pm.Normal("obs", mu=mu, sigma=1, observed=np.random.randn(100))

    idata = pm.sample(2000, tune=2000, return_inferencedata=True)

pm.model_to_graphviz(model)
```

**Expected behavior**
Graph of the model

**Additional context**
- PyMC3 Version: 3.10
- Theano Version: 1.0.4
- Python Version: 3.8.2
- Graphviz: 2.40.1 
- Operating system: macOS Big Sur 1.1

**Comment by OriolAbril** [comment]
I think this issue should be opened in graphviz, ArviZ does not have graphviz as dependency nor uses it anywhere. PyMC3 uses it in `pm.model_to_graphviz` which is what is triggering the error, but the root issue does not seem to be with this pymc function. It looks like an installation issue with graphviz. Maybe [this](https://github.com/conda-forge/graphviz-feedstock/issues/15#issuecomment-306341806) could help?

I'll close the issue as we can't do more about this on ArviZ side
