### ISSUE TITLE
Write installation guide

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1487]
## Tell us about it
Write a page about ArviZ installation that covers the basic pip and conda commands and extends with installation of optional dependencies, when should they be installed and a link to dedicated docs about using the capabilities of these optional dependencies (if necessary) for example to the [Numba](https://arviz-devs.github.io/arviz/user_guide/Numba.html) page. See #1331 for extra info and an overview of the documentation revamp

## Thoughts on implementation
The README should link to this page after its installation section.

**Comment by arungrace88** [comment]
Hello,
I would like to contribute on this issue. Just to let you know that I am a beginner in this open-source contribution journey.

**Comment by OriolAbril** [comment]
Hi! Welcome! Thanks for taking on this issue. Let us know if you need any help.

**Comment by OriolAbril** [comment]
Similarly to what I said in #1490, let's wait a couple days to give @arungrace88 time to share any work done already on that, we want everyone to enjoy contributing to ArviZ and use their time profitably. We are all working together to build a cool library, not competing to see who works more or who works faster. 

As always, either @arungrace88 or @Rishabh261998 let us know if you need any help with the issue, choosing where to work, understanding the structure of the library... we are here

**Comment by arungrace88** [comment]
Hi @OriolAbril, 
Thanks for the time. I have documented the installation steps (pip & conda forge) along with the required and optional dependencies, and saved in .rst format. Is the output expected in any other format?. Thanks.

**Comment by OriolAbril** [comment]
Thanks, rst is great! Given our current sphinx configuration using myst, the source of our docs can be either rst or markdown, both formats get rendered nicely.

**Comment by madhucharan** [comment]
Hi @OriolAbril , If it is still open to document a particular guide or something, please let me know. I am looking forward to working on it.

**Comment by OriolAbril** [comment]
@madhucharan take a look at https://github.com/arviz-devs/arviz/issues/1331, there are more ideas about guides and pages to add to the documentation. Let me know if some of the ideas there seem interesting to write.

Some of these like the developer guide pages will be really challenging though because the content that should be written there are unwritten tricks, things discussed in private chats between developers...

**Comment by Grasin98** [comment]
Hi @OriolAbril I would like to take on this on going issue and implement few ideas about guides and pages. Also, I am new to this, so would be great if you could guide me.

**Comment by OriolAbril** [comment]
Hi @Grasin98 definitely, if you don't mind, let's move the conversation to #1331 so we can close this (same goes for @madhucharan), the installation guide has already been added and the discussion on other guides to add to the docs is at #1331
