### ISSUE TITLE
Write plotting with ArviZ guides

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1488]
## Tell us about it

Write a guide (one per backend) about plotting with ArviZ. It should not be about what to plot (what to plot would be in the educational resources) and focus on _how_. It should at least cover the following:

* [x] ~Sorting subplots. This [PyMC3 discourse topic](https://discourse.pymc.io/t/control-the-order-of-coordinates-in-arviz-inferencedata/4812?u=oriolabril) has many options~ This is independent of the backend, so it doesn't make much sense here. It is also independent of plotting (and useful for `az.summary` too for example). And probably the most important point, it is already covered in https://python.arviz.org/en/latest/user_guide/label_guide.html
* [ ] Defining axes manually. 
* [ ] Combining plots (both combining multiple arviz plots, arviz plots with "manual" plots and overlaying "manual" plots on top of ArviZ ones), synomym to use of `ax` argument.
* [ ] Customizing the look of the plots, titles, ticks... This section should be very simple and short and only show how working on arviz plots is basically the same as working on "manual" plots, the bulk of the section should be links to matplotlib/bokey guides.
* [ ] Use of `show`, `backend_kwargs` arguments. 
  * (matplotlib only) For `show` related to https://github.com/arviz-devs/arviz/pull/1768 and https://github.com/arviz-devs/arviz/issues/1767. It is a convenience function that calls `plt.show()` behind the scenes it has no effect on how the figure and axes are instatiated (when necessary) which is always with `plt.subplots(...)`.
* [ ] (bokeh only) bokeh tricks when in a jupyter-like environment
* [ ] (bokeh only) server mode?
* [x] ~Maybe also how to use coords? All plots work the same. See #1436~ Similar comments to the sorting point, this is independent of the backend and of plotting, and should be covered in a different guide, see https://github.com/arviz-devs/arviz/issues/1645 for tracking of the coords and dims guide. This two plotting guides can be seen as integration with matplotlib and bokeh, the coords and dims is more of a integration with xarray one.

**Comment by symeneses** [comment]
I would like to work on this issues 🙋🏽‍♀️
