### ISSUE TITLE
Multidimensional traceplot with Pystan and xarray

### ISSUE THREAD

**Issue by Bonnevie** [arviz-devs/arviz#149]
I realize that this is undergoing development at the moment, but what is the intended method for constructing a simple traceplot for a Pystan fit object with 2-dimensional array variables? The following [line](https://github.com/arviz-devs/arviz/blob/c58e0b779309997da5315c2dc91df6147d891791/arviz/utils/xarray_utils.py#L458) seems to discard variables that are 2-dimensional? I get an error saying that `pars` is empty if I try to just call `traceplot` directly on the Pystan fit object:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-101-28cd15193e9c> in <module>()
----> 1 arviz.traceplot(samples)

~/anaconda3/envs/stan-dev/lib/python3.6/site-packages/arviz/plots/traceplot.py in traceplot(data, var_names, coords, figsize, textsize, lines, combined, kde_kwargs, trace_kwargs)
     37     axes : matplotlib axes
     38     """
---> 39     data = convert_to_xarray(data)
     40 
     41     if coords is None:

~/anaconda3/envs/stan-dev/lib/python3.6/site-packages/arviz/utils/xarray_utils.py in convert_to_xarray(obj, coords, dims, chains)
     73         return obj
     74     else:
---> 75         return get_converter(obj, coords=coords, dims=dims, chains=chains).to_xarray()
     76 
     77 

~/anaconda3/envs/stan-dev/lib/python3.6/site-packages/arviz/utils/xarray_utils.py in get_converter(obj, coords, dims, chains)
     37         return DictToXarray(obj, coords, dims, chains=chains)
     38     elif obj.__class__.__name__ == 'StanFit4Model':  # ugly, but doesn't make PyStan a requirement
---> 39         return PyStanToXarray(obj, coords, dims)
     40     elif obj.__class__.__name__ == 'MultiTrace':  # ugly, but doesn't make PyMC3 a requirement
     41         return PyMC3ToXarray(obj, coords, dims)

~/anaconda3/envs/stan-dev/lib/python3.6/site-packages/arviz/utils/xarray_utils.py in __init__(self, fit, coords, dims)
    389             The coordinates are those passed in and ('chain', 'draw')
    390         """
--> 391         super().__init__(fit, coords=coords, dims=dims)
    392 
    393     def to_xarray(self):

~/anaconda3/envs/stan-dev/lib/python3.6/site-packages/arviz/utils/xarray_utils.py in __init__(self, obj, coords, dims)
     80         self.obj = obj
     81         # pylint: disable=assignment-from-none
---> 82         self.varnames, self.coords, self.dims = self.default_varnames_coords_dims(obj, coords, dims)
     83         self.verified, self.warning = self.verify_coords_dims()
     84 

~/anaconda3/envs/stan-dev/lib/python3.6/site-packages/arviz/utils/xarray_utils.py in default_varnames_coords_dims(obj, coords, dims)
    451         for varname in varnames:
    452             if varname not in dims:
--> 453                 vals = obj.extract(varname, permuted=False)[varname]
    454                 if len(vals.shape) == 1:
    455                     vals = np.expand_dims(vals, axis=1)

stanfit4template_f63d55caee4d725d95ec10b01b4500a0_1018734232036915966.pyx in stanfit4template_f63d55caee4d725d95ec10b01b4500a0_1018734232036915966.StanFit4Model.extract()

~/anaconda3/envs/stan-dev/lib/python3.6/site-packages/pystan/misc.py in _check_pars(allpars, pars)
    805 def _check_pars(allpars, pars):
    806     if len(pars) == 0:
--> 807         raise ValueError("No parameter specified (`pars` is empty).")
    808     for par in pars:
    809         if par not in allpars:

ValueError: No parameter specified (`pars` is empty).
```

Has the final shape of the expected xarray been settled? When calling traceplot, can you still specify variables using the names of vector/matrix parameters, or  do you need to specify the variables with the `flatnames` (i.e. unfolded array variables, scalars with names like `X_dims_1_2`)?

**Comment by ColCarroll** [comment]
Thanks for kicking the tires! If you have a reproducible example of a stan model that causes this, I'd be happy to add it to the test suite, and could take a closer look.

@ahartikainen will probably have something more productive to say about the pystan conversion code, but we are expecting the data from a univariate distribution to be 2 dimensional: `draws x chains`.  Any additional dimensions are given names.  

You may be able to get around this by converting the stan fit object outside of the plotting function.  Something like

```python
data = arviz.convert_to_xarray(samples, coords={'coord_1': np.arange(N)}, dims={'X': ['coord_1']})
```

I'd guess that won't work, because `convert_to_xarray` shouldn't throw errors like this in the first place!

**Comment by ahartikainen** [comment]
Hi, how do you call the plot?

It should work with e.g. `theta`, not `theta[1]`.

A working example would be great.

**Comment by Bonnevie** [comment]
The Stan code used was a bit complex, but I'll see if I can make a MWE.

**Comment by ahartikainen** [comment]
Hi, 

yes, this is probably bug in somewhere in the arviz code. 

I think we need to call `pystan.misc.remove_empty_pars` (or something similar) at some point, probably before loop. Or test dim before extract.

**Comment by Bonnevie** [comment]
@ahartikainen it appears to already crash in Pystan alone, i.e. doing `fit['B']` yields the same error. It is the `extract`call that is problematic. (as an aside, you write `obj.extract(varname, permuted=False)[varname]`, but in the docs you write that `pars` is ignored when `permuted=False`, so there might be some redundancy?)

**Comment by ahartikainen** [comment]
Ok, you need to use latest pystan from github.

Arviz will work pystan 2.18 onwards. I could do a custom patch for earlier version.

    pip install git+https://github.com/stan-dev/pystan

**Comment by ahartikainen** [comment]
I still need to test with empty pars.

**Comment by ahartikainen** [comment]
If user only wants some variables (e.g. discarding 10k variables from generated quantities)

**Comment by ahartikainen** [comment]
But yes, I can do some testing for this.

**Comment by Bonnevie** [comment]
Even then, couldn't you call `extract` with the full list `self.varnames` instead of looping over it? Seems like that should do the same, unless a str input is handled very differently from the list of str.

**Comment by ahartikainen** [comment]
Yes, that is a reasonable way to do it.

I made a PR.

**Comment by ColCarroll** [comment]
I think this just got fixed -- thanks for reporting!
