### ISSUE TITLE
Make exception consistent between plot_pair and plot_parallel

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1507]
## Tell us about it
Both `plot_pair` and `plot_parallel` require two variables. The warning message indicating so is inconsistent however. It would be nice if they could be made the same, both in Exception type and in verbiage.

https://github.com/arviz-devs/arviz/blob/master/arviz/plots/parallelplot.py#L119
https://github.com/arviz-devs/arviz/blob/master/arviz/plots/pairplot.py#L238

Screenshots of both are below
![image](https://user-images.githubusercontent.com/7213793/105097781-07d8b380-5a5e-11eb-9b58-b52a10cfec47.png)
![image](https://user-images.githubusercontent.com/7213793/105097835-1a52ed00-5a5e-11eb-9d33-19a04c1313f5.png)

PyMC3 example

```
with pm.Model() as model:
    sd = pm.HalfNormal("sd", 10)
    y = pm.Normal("y", mu=0, sd=sd, observed=[1,2])
    trace = pm.sample()
az.plot_parallel(trace)
az.plot_pairtrace)
```

**Comment by alex-ivanoff** [comment]
Hi, I am a beginner. In the contributing guidelines it says to confirm that no one else is working on this. If no one is, I'd love to help.

**Comment by OriolAbril** [comment]
Hi @alex-ivanoff welcome to ArviZ!

Nobody is working on this yet, you are welcome to do so. I will assign the issue to you to make it clear. Don't hesitate to ask here or on gitter if you have any question

**Comment by alex-ivanoff** [comment]
Hi @OriolAbril!

Thank you! Just submitted my first pull, it probably has a (lot of) mistake(s) but I'm here to learn and contribute. When running tests, I received an Error message "ImportError: attempted relative import with no known parent package", so not completely confident.

**Comment by OriolAbril** [comment]
As you saw in the PR, all tests passed, so I am guessing that it is probably an issue with installing all the dependencies necessary to build the docs. These should be `requirements.txt`, `requirements-docs.txt`, `requirements-dev.txt` and `requirements-optional.txt` plus some extra dependencies (that cannot be installed with pip) to save bokeh images as png, see [step 4](https://arviz-devs.github.io/arviz/contributing/contributing.html#steps) for more details. 

Alternatively, we also provide a [docker image and instructions](https://arviz-devs.github.io/arviz/contributing/contributing.html#developing-in-docker) to make sure everything is properly installed without messing any of your personal libraries.

I am closing the issue to indicate that after the PR was merged it has been solved, but you can still comment if something is not clear or try to reach out in gitter.
