### ISSUE TITLE
Variable names in element labels for `plot_forest` should be optional

### ISSUE THREAD

**Issue by fonnesbeck** [arviz-devs/arviz#1524]
Currently, creating a forest plot with `plot_forest` uses `<var name> <coordinate name>` as the scheme for labels on the y-axis. This creates a slew of repeated variable names in the labels, which I would guess is almost always undesirable (particularly when you have nice element labels as coordinates in the dataset):

<img width="508" alt="Screen Shot 2021-01-27 at 1 02 58 PM" src="https://user-images.githubusercontent.com/81476/106040982-d6389b80-60a0-11eb-9f8a-be4a4a579062.png">

There should be excluded by default, and turned on with a `include_var_names=True` (or similar) argument. 

Alternatively, the first coordinate could include the variable name, and then exclude it for subsequent ones.

**Comment by AlexAndorra** [comment]
What would probably be even better is if we displayed the var_name + coords
only once and then only the coords. Not sure how much harder that would be
🤔

**Comment by fonnesbeck** [comment]
Yeah, that's what I meant by the second comment. If there is only one variable it should probably only use the coord names.

**Comment by fonnesbeck** [comment]
How about something like this (using the `mpl_plot_forest_ridge` example):

<img width="897" alt="Screen Shot 2021-01-27 at 10 23 03 PM" src="https://user-images.githubusercontent.com/81476/106089777-4ae5f700-60ee-11eb-8a84-5a343ff99827.png">

here is the current behavior:

![Figure_1](https://user-images.githubusercontent.com/81476/106090062-de1f2c80-60ee-11eb-80e8-20962e5db01a.png)

Got a PR ready to go if this works for everyone.

**Comment by ColCarroll** [comment]
I like it!

**Comment by fonnesbeck** [comment]
... and in Bokeh

<img width="562" alt="Screen Shot 2021-01-27 at 10 37 21 PM" src="https://user-images.githubusercontent.com/81476/106090662-55a18b80-60f0-11eb-8419-cc51bcddacda.png">
