### ISSUE TITLE
from_pyro fails when MCMC is run on GPU

### ISSUE THREAD

**Issue by chrhck** [arviz-devs/arviz#1529]
When MCMC is performed on a GPU, from_pyro fails, as the sites returned by
`trace = pyro.poutine.trace(self.model).get_trace(*self._args, **self._kwargs)` can be tensors that still live on the GPU. 
This will cause this line to break: 
https://github.com/arviz-devs/arviz/blob/1f3b8fd0eaafcf58aad09a80d309b2a4b40dd191/arviz/data/io_pyro.py#L231

Since there is currently no easy way of transferring a pyro MCMC object to the cpu, a workaround is adding a `.cpu()`to this line:
https://github.com/arviz-devs/arviz/blob/1f3b8fd0eaafcf58aad09a80d309b2a4b40dd191/arviz/data/io_pyro.py#L111

**Comment by ahartikainen** [comment]
That sounds ok solution.

Is there a way to see if the trace is on cpu or gpu? And should we unpack data from gpu in one step or one-by-one (when numpy array is creates)

**Comment by fonnesbeck** [comment]
Calling the `cpu()` method on data that's already on the `cpu()` will just be ignored, so no need to check. I will submit a PR for this now.
