### ISSUE TITLE
plot_pair axis labels no longer include coords

### ISSUE THREAD

**Issue by lhelleckes** [arviz-devs/arviz#1531]
**Describe the bug**
Using `plot_pair` with a selection of `coords`, I got a plot where the axis labels only show `var_names`, so different `coords` get the same label.

**To Reproduce**
```
test_idata = arviz.from_dict(
    posterior = dict(a=numpy.random.rand(1, 10, 3), b=numpy.random.rand(1 ,10, 1)),
    dims={'a':['a_dim',]},
    coords=dict(a_dim=['test_A', 'test_B', 'test_C'])
)
arviz.plot_pair(
    test_idata, 
    coords=dict(a_dim=['test_A', 'test_B']),
    kind='kde'
);
```

![grafik](https://user-images.githubusercontent.com/45510988/106592082-56527b80-654f-11eb-95ed-c9041188c4c0.png)

**Expected behavior**
Axis labels should also include the `coords` to be unique (in this case a_test_A or similar).

**Additional context**
arviz_version : 0.11.0

**Comment by OriolAbril** [comment]
I will look into it asap. This is completely unexpected :/. Does this already happen with 0.11 or on development version? (both will show 0.11 as version)

**Comment by lhelleckes** [comment]
I tested it with the 0.11 release. Thanks for looking into it!
