### ISSUE TITLE
`from_cmdstanpy` - better use of metadata

### ISSUE THREAD

**Issue by mitzimorris** [arviz-devs/arviz#1546]
CmdStanPy PR https://github.com/stan-dev/cmdstanpy/pull/346 will add structured metatdata to the CmdStanMCMC object.  Investigate how to use this when importing the fit.

related to issue https://github.com/arviz-devs/arviz/issues/1445
also related to issue https://github.com/arviz-devs/arviz/issues/1489

**Comment by OriolAbril** [comment]
Closing this as the metadata attribute is public, but the class it returns is not, so it is not a good idea to rely on that. Related to #2278.
