### ISSUE TITLE
plot_posterior and plot_density give a mode outside of the hdi

### ISSUE THREAD

**Issue by gdindi** [arviz-devs/arviz#1549]
## Short Description

I am plotting densities and I ask for a point estimate as 'mode'. The value of the mode is outside of the HDI.

## Code Example or link

az.plot_posterior(inference_data, point_estimate = 'mode', hdi_prob = 0.9, var_names = ('a', 'b', 'c', 'sigma_lai'), figsize=(10,5), grid=(2,2))

The result looks like this https://postimg.cc/K4RpK4gg

az.__version__
Out[88]: '0.11.1'

**Comment by aloctavodia** [comment]
HI @gdindi thanks for taking the time to report this issue.  I am not able to reproduce this error, could you share your data or share a minimal working example?

**Comment by gdindi** [comment]
Hi,

Here goes a minimal working example:

```
# get the data file here
# https://upload.disroot.org/r/7cWwZ7y7#vbkqLUsIKbTmTaCDYhNkt4xfRG/d0qSOeY84aD1JpbQ=
import arviz as az
import matplotlib.pyplot as plt
inf_data = az.from_netcdf("posterior_1.netcdf")
az.plot_posterior(inf_data.posterior, point_estimate = 'mode', hdi_prob = 0.9, var_names = ('a', 'b', 'c', 'sigma_lai'), figsize=(10,5), grid=(3,2))
plt.savefig("test.png")
```

Thank you.

**Comment by aloctavodia** [comment]
Thanks. I find the problem and I will fix it later today.

**Comment by gdindi** [comment]
Thank you. I am using arviz from conda-forge. What is the recommended way to be able to use the fixed code?

**Comment by aloctavodia** [comment]
@gdindi To install the version from master use `pip install git+https://github.com/arviz-devs/arviz`
