### ISSUE TITLE
Make pickle files work for different systems

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#155]
They should probably be marked with a system name and a 32/64 for floating point.  As an alternative, maybe just a `try/except`, and rebuild the pickles if there's a problem? This would be easier and not very time-consuming (the pickles are mostly for travis' benefit).

Even though everything will eventually work with netCDF files, this is important since making sure pystan/pymc3 objects convert correctly is important.

**Comment by ahartikainen** [comment]
I don't believe the pickled files are the problem. They should be cross-platform safe with `"wb"/"rb"`. At least on py3, not sure about py2.

PyStan transforms Stan-code to C++ which is compiled with platform specific way to python module.

Is theano doing similar things?

**Comment by ColCarroll** [comment]
Closing this since I think the pickle cache is pretty stable.
