### ISSUE TITLE
Rope values are not rounded

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1561]
The following snippet:

```
import arviz as az
data = az.load_arviz_data('centered_eight')
az.plot_posterior(data, var_names='mu', rope=(-1.23498745325, 1), show=True)
```

generates:

![image](https://user-images.githubusercontent.com/23738400/107867192-178ac280-6e79-11eb-9d66-a5a4ef3bf4ff.png)

I think rope values should go through the same significant digits formatter as point values.

**Comment by MgeeeeK** [comment]
Hey, I am interested to take up this issue. If you can assign it to me that would be great!

**Comment by OriolAbril** [comment]
Great, let us know if you need any help!

**Comment by arc12** [comment]
I just added another RoPE-related issue, if you are keen, @MgeeeeK 
#1567
