### ISSUE TITLE
Show legend in ppc plot (backend bokeh)

### ISSUE THREAD

**Issue by MarcoGorelli** [arviz-devs/arviz#1563]
## Tell us about it

xref https://github.com/arviz-devs/arviz/pull/1559#issuecomment-778762939

The matplotlib plots have legend, making it clear what each line/colour type represents. The bokeh plots don't seem to have them, and adding them would make the meaning of the plot clearer

**Comment by Rishabh261998** [comment]
Hey can I take this issue? Thanks

**Comment by OriolAbril** [comment]
yep, assigning it to you
