### ISSUE TITLE
Include estimate of probability within RoPE when plotting

### ISSUE THREAD

**Issue by arc12** [arviz-devs/arviz#1567]
In cases such as `az.plot_posterior(inference_data, rope=(0.45, 0.55))`, it would be useful to include an estimate of the probability within the rope. (as an option, I suspect)

For Kruschke's version, see: http://doingbayesiandataanalysis.blogspot.com/2013/08/how-much-of-bayesian-posterior.html

we could extent this idea, in a similar way to how `ref_val` works to show probabilities for the Rope and both upper and lower tails.

**Comment by Rishabh261998** [comment]
Can I take this issue? Thank You
