### ISSUE TITLE
Add interactive legend to bokeh forestplot

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1572]
## Tell us about it
plot_density with bokeh backend has a super cool legend that allows to hide lines by clicking on the corresponding element in the legend. plot_forest could do the same.

## Thoughts on implementation
I guess searching for the PR that added the legend for plot_density will be a good starting point. Will try to extend and add more info at some point, but if someone has time to browse the history and track down the relevant pieces of code it would be great

**Comment by ahartikainen** [comment]
https://github.com/arviz-devs/arviz/blob/3d788cc7157b764130ee6f84bb2f42021e5ab258/arviz/plots/backends/bokeh/densityplot.py#L114

**Comment by Rishabh261998** [comment]
Would like to work on this @OriolAbril, can you assign it to me?

**Comment by OriolAbril** [comment]
Done, thanks!

I don't know how complicated it will be to have the legend affect multiple lines at once (I think the one in density plot does not do that)

**Comment by OriolAbril** [comment]
Also, wait until #1201 is merged to start working on it, there is no legend yet in either bokeh nor matplotlib it will be added by #1201

**Comment by ahartikainen** [comment]
If I remember correctly plots need to use CDS/CDSview and legend needs to be handled correctly too.

https://github.com/arviz-devs/arviz/pull/976/files

There are also bokeh docs about this

**Comment by Rishabh261998** [comment]
Hey @OriolAbril can I start working on this issue? as #1201 is merged. Thanks

**Comment by OriolAbril** [comment]
Yes, you can work on this issue, thank you! Having interactive legend with forestplot would be great

**Comment by Rishabh261998** [comment]
@OriolAbril I was looking into this but I found that currently Bokeh does not support interactive legends on multiple glyph. They explicitly mentioned it here https://docs.bokeh.org/en/latest/docs/user_guide/interaction/legends.html

**Comment by OriolAbril** [comment]
Oh, then it's probably not worth it to make the legend interactive at all, plain legend is enough.
