### ISSUE TITLE
Enable pylint use-a-generator check

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1578]
I guess that latest pylint has added a `use-a-generator` check that did not use to exist. I disabled it in #1577 from `.pylintrc` but maybe we should enable the check and either fix the code or disable on a line per line basis. 

Same for `consider-using-generator`

Steps to fix the issue:

1. Remove these two checks from the list of disabled checks in pylintrc: https://github.com/arviz-devs/arviz/blob/main/.pylintrc#L75-L76
2. Run pylint on arviz (or what is the same, run [`scripts/lint.sh`](https://github.com/arviz-devs/arviz/blob/main/scripts/lint.sh))
3. Go to each of the files and lines where pylint shows a warning and try to fix the issue. There is also the possibility of false positives, I expect most occurences to be valid complains, but some may have to still be ignored. This ignores should be done on a line basis, not from `pylintrc`

**Comment by MgeeeeK** [comment]
Hey @OriolAbril , I'd like to work on this issue... thanks, for the steps as well.

**Comment by OriolAbril** [comment]
Great, just assigned you to the issue, as usual, let us know if you need any help
