### ISSUE TITLE
Breaking change in version 0.11.2

### ISSUE THREAD

**Issue by richardARPANET** [arviz-devs/arviz#1589]
It looks like there has been a breaking change introduced in version 0.11.2. Is this project following [semver](https://semver.org/) or something else?

```
../../../.pyenv/versions/3.8.0/envs/algo-jb-bayes/lib/python3.8/site-packages/pymc3/__init__.py:13: in <module>
    from .stats import *
../../../.pyenv/versions/3.8.0/envs/algo-jb-bayes/lib/python3.8/site-packages/pymc3/stats/__init__.py:32: in <module>
    geweke = map_args(az.geweke)
E   AttributeError: module 'arviz' has no attribute 'geweke'
```

**Comment by OriolAbril** [comment]
We are following semver, but this is still a beta package. We try to distinguish between patch and non-patch releases anyways, but it's not a guarantee, neither on our side nor on semver's side. 

We also don't have the resources to maintain multiple versions of ArviZ (there is no backporting of any kind) nor to maintain compatibility with muliple versions of the supported inference libraries (again, we try to make the converters general to support multiple versions, but we only test on their latest release and their development version)
