### ISSUE TITLE
from_cmdstanpy uses posterior in place of prior when both provided

### ISSUE THREAD

**Issue by jburos** [arviz-devs/arviz#1594]
**Describe the bug**
I'm seeing some odd behavior on a branch of arviz when using `from_cmdstanpy`. Basically, if I fit a model twice using cmdstanpy & construct the az.InferenceData object using both the prior & the posterior samples, I see that the posterior draws are in both the prior & posterior groups. 

In other words, say I construct my arviz InferenceData object as follows:

```py
idata = az.from_cmdstanpy(posterior_fit, 
    prior = prior_fit, 
    coords = dict(school=["A", "B", "C", "D", "E", "F", "G", "H"]), 
    dims = dict(
        theta=["school"],
        y=["school"],
        log_lik=["school"],
        y_hat=["school"],
        theta_tilde=["school"],
    ),
    posterior_predictive = ["y_hat"],
    prior_predictive = ['y_hat'],
    log_likelihood = ["log_lik"])
```

The draws for the prior & posterior are identical.

```py
all(idata.prior == idata.posterior)
> True
```

Notably, this is not the case for the predicted quantities:

```py
all(idata.prior_predictive == idata.posterior_predictive)
> False
```

**To Reproduce**
I have set up a reproducible example here: https://gist.github.com/jburos/b8839b7919455d6a0019d7ce33394c2f

**Expected behavior**
The prior draws should be saved in the prior group.

**Additional context**

I had installed `arviz` from the `cmdstanpy` branch, due to previous bugs. I was on commit d95e9763b19611fcdeefa7b9aecb2746d5534fc9, according to my Pipfile.lock.

My system:

```py
In [3]: sys.version
Out[3]: '3.8.7 (default, Feb  3 2021, 06:31:03) \n[Clang 12.0.0 (clang-1200.0.32.29)]'
In [5]: arviz.__version__
Out[5]: '0.11.2'

**Comment by ahartikainen** [comment]
Thanks for the info. There were couple of typos.

https://github.com/arviz-devs/arviz/pull/1595

**Comment by jburos** [comment]
Linking to a [comment on the PR](https://github.com/arviz-devs/arviz/pull/1595#issuecomment-790933424), i'm still seeing this bug on a fit from the `main` branch. I'm on cmdstanpy v 0.9.68.

There is one more typo that needs to be resolved.

**Comment by OriolAbril** [comment]
Thanks for double checking!
