### ISSUE TITLE
Fix ess/rhat plotting in plot_forest

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1596]
Due to the new labelling capabilities, labels don't need to be unique anymore. This is generally not an issue, but it can be in some cases such as with plot_forest. `BaseLabeller` does always generate unique labels, so I suggest using `BaseLabeller` to generate keys of dict/sets that track the objects that have already been plotted and use the user provided labeller to generate the actual plot labels so we can take advantage of custom labeling and special cases like legend or not repeating variable names. cc @Rishabh261998

seen in #1591

**Comment by Rishabh261998** [comment]
Thanks @OriolAbril will start working on this, btw we also need to align the ess/rhat dots with the hdi plot in Bokeh

**Comment by OriolAbril** [comment]
true, @ahartikainen may know how to align multiple bokeh axes, all other plots have their axes aligned, it could be a typo in the current code or having the height and width swapped. I don't expect significant changes to be needed regarging subplot alignment

**Comment by ahartikainen** [comment]
We can share the limits
