### ISSUE TITLE
Possible bad loop in arviz.utils._subset_list()

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#1597]
Reading this function to try to understand the filtering, I see this:

       if excluded_items:
            if filter_items in ("like", "regex"):
                for pattern in excluded_items[:]:
                    excluded_items.remove(pattern)
                    if filter_items == "like":
                        real_items = [real_item for real_item in whole_list if pattern in real_item]
                    else:
                        # i.e filter_items == "regex"
                        real_items = [
                            real_item for real_item in whole_list if re.search(pattern, real_item)
                        ]
                    if not real_items:
                        not_found.append(pattern)
                    excluded_items.extend(real_items)

This iterates over `excluded_items` while also modifying it (if I am reading this correctly). Does this need a rewrite?

**Comment by OriolAbril** [comment]
I think it iterates over a copy (`excluded_items[:]` is a copy iiuc) and modifies the base object for posterior use.

**Comment by OriolAbril** [comment]
It iterates over a copy, here are some experiments:

```
In [1]: l = [2,4,3,5,6]

In [2]: l is l
Out[2]: True

In [3]: l is l[:]
Out[3]: False

In [4]: for i in l[:]:
   ...:     l.remove(i)
   ...: 

In [5]: l
Out[5]: []

In [6]: l = [2,4,3,5,6]

In [7]: for i in l:
   ...:     l.remove(i)
   ...: 

In [8]: l
Out[8]: [4, 5]
```

**Comment by rpgoldman** [comment]
Got it -- I didn't realize the slicing did that.  In another life, I would rewrite that as

   for i in copy(l):

... since that makes the meaning quite clear -- it says what it is doing, whereas the slicing ... less obvious to the reader.
