### ISSUE TITLE
errors in importing some functions

### ISSUE THREAD

**Issue by Hossein-1990** [arviz-devs/arviz#1603]
## Short Description

I am using arviz for the calculation of HDI intervals.  There are two main functions for this purpose: 1) arviz.hdi 2) arviz.plot_hdi. When I've applied these functions in my codes in Jupyter, it shows an error which is: 'module 'arviz' has no attribute 'hdi''. But these are available on the site!! What is the problem??!

## Code Example or link

with pm.Model():
    m = pm.Uniform('m',0,33) # m = prior
    likelihood = pm.Normal('likelihood',mu = m,sigma=3.3,observed=-5.4)
    step = pm.Metropolis()
    trace = pm.sample(20000,step)

az.hdi(trace)

Notes:
1) I already import arviz as az
2) I installed this library recently!

**Comment by OriolAbril** [comment]
Can you share your arviz version? You can see which one is it with `az.__version__`

**Comment by Hossein-1990** [comment]
> Can you share your arviz version? You can see which one is it with `az.__version__`

it's 0.7.0. Apparently the latest version is 0.11.2! 
How can I update that?

**Comment by ahartikainen** [comment]
`python -m pip install arviz -U`

**Comment by Hossein-1990** [comment]
> `python -m pip install arviz -U`

I've updated my arviz with pip command (in Command Prompt) and it is now 0.11.2
But in my anaconda environment, it's still 0.7.2!! How shoud I fix that?!!

**Comment by ahartikainen** [comment]
You need to first activate your anaconda environment if you use command prompt. (check if there is anaconda prompt)

If you use jupyter notebooks (or ipython) you can do the following

    !python -m pip install arviz -U

**Comment by Hossein-1990** [comment]
> You need to first activate your anaconda environment if you use command prompt. (check if there is anaconda prompt)
> 
> If you use jupyter notebooks (or ipython) you can do the following
> 
> ```
> !python -m pip install arviz -U
> ```

Thank you very much. It has worked
