### ISSUE TITLE
Remove compare warning

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1604]
I think we can already remove the following warning from `az.compare`:

```
/home/oriol/miniconda3/envs/arviz/lib/python3.8/site-packages/arviz/stats/stats.py:146: UserWarning: The default method used to estimate the weights for each model,has changed from BB-pseudo-BMA to stacking 
```

**Comment by madhucharan** [comment]
Hi @OriolAbril, I went through the function, is it because users get used to the new default method so that no need to specifically mention it? and just for clarifying, we just need to remove the warning right? do we need to update anything else?

**Comment by OriolAbril** [comment]
exactly, it has been around for a while and is no longer needed. It should be removed and nothing else.
