### ISSUE TITLE
Upgrade to mypy>=0.800

### ISSUE THREAD

**Issue by obi1kenobi** [arviz-devs/arviz#1609]
#1528 was unable to use the latest `mypy` version due to what appears to be a bug in handling of `mypy.ini` configuration: https://github.com/python/mypy/issues/10192

Once that issue is resolved, upgrade to the latest `mypy` and run `typing_copilot init --overwrite` to create a new `mypy.ini` file suitable for the new `mypy` version. We'd use `typing_copilot`'s `init` command rather than `tighten` because it's possible that the new version of `mypy` detects new issues within the codebase. The `tighten` command would error out in such a circumstance since it would assume that the newly reported issues are due to code edits and not due to a `mypy` upgrade.

**Comment by obi1kenobi** [comment]
Based on discussion in python/mypy#10192 I think the change in `mypy` 0.800 is intentional and here to stay, and `typing_copilot` will sadly just have to work around it by making its config generation algorithm more complex.

**Comment by OriolAbril** [comment]
We removed mypy from CI a while back as it was giving issues and failing builds we weren't able to solve given our time
