### ISSUE TITLE
Check for InferenceData input on from_pymc3

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1617]
`pymc3.sample` has a keyword argument that makes the function return an InferenceData object, `from_pymc3` is called under the hood by pymc3. This can generate confusion when doing also posterior predictive checks or similar postprocessing, and it is common to end up calling `from_pymc3` manually again but using the `InferenceData` as `trace` argument, which does not work nor should it work.

We should check for InferenceData input on io_pymc3 to make sure the input is not an inferencedata and if it is raise an error pointing people out to https://arviz-devs.github.io/arviz/api/generated/arviz.InferenceData.extend.html#arviz.InferenceData.extend.

**Comment by MgeeeeK** [comment]
Hi @OriolAbril I'd like to work on this... can you assign this to me?

**Comment by MgeeeeK** [comment]
Hey @OriolAbril , sorry for the delay, I got stuck somewhere else.

Anyways, even though you described it perfectly I just wanted to make sure that I need to enable type checking for `io_pymc3`'s input and if in case it's of type `InferenceData`, it should raise the error as you mentioned... Am I missing anything here?

**Comment by OriolAbril** [comment]
That is all.
