### ISSUE TITLE
invert the order of links in sampling wrapper docstrings

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1623]
https://arviz-devs.github.io/arviz/api/generated/arviz.SamplingWrapper.html#arviz.SamplingWrapper has a link to the api section corresponding to all the wrappers and a link to the user guide section about the wrappers. The temptation to click on the first link and be done with it is strong, so I think I'd be better to invert the order and get the readers to the user guide by "default" instead of the api docs.

Note: the source of the page of the docs linked above is at https://github.com/arviz-devs/arviz/blob/main/arviz/wrappers/base.py#L15

**Comment by Grasin98** [comment]
I would like to contribute here but since I am new to this, could you guide me?

**Comment by OriolAbril** [comment]
Yes, have you read the [contributing guide](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md)? There is an step by step guide to set up your fork and getting started editing the source code. Let me know if any of the steps are not clear enough.

**Comment by AnimeshRy** [comment]
Hey, I did the changes as described in this issue. I'm new to open source and would like feedback on anything I did wrong. 
Here is the [PR](https://github.com/arviz-devs/arviz/pull/1636). Thanks

**Comment by OriolAbril** [comment]
Hi @AnimeshRy, welcome to ArviZ! 

Thanks for the PR, and I am happy to see you taking initiative, however, you have to keep in mind that we are a lot of people working on ArviZ which is why we have defined some rules and guidelines on our [contributing guide](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#steps-before-starting-work) to ensure smooth collaboration between all contributors. To make sure you don't end up doing duplicated work and also ensure you have your PRs accepted you should follow the contributing guide.

**Comment by AnimeshRy** [comment]
I think you can close the issue now @OriolAbril

**Comment by OriolAbril** [comment]
I have been a bit busy lately and have not had time to merge all the finished PRs, I'll do so now, and in doing so, the issue will be closed automatically when merging the PR, this is the reason why I edited your initial PR description. Thanks for the remainder anyways :smile: and thanks a lot for the PR
