### ISSUE TITLE
dtypes with cmdstanpy

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1630]
We should take a look at how we handle dtypes in `from_cmdstanpy` (or directly on cmdstanpy). See https://github.com/teddygroves/figure_skating/pull/1 for an example. 

Note this is more of an issue _candidate_ for now. I will try to play around a bit and see where things are going wrong, but I am posting anyways because 1) someone may already know the answer and I will not need to look into this and 2) maybe someone beats me into looking, I can't promise to look into this soon and we may want to fix this before the next release.

**Comment by ahartikainen** [comment]
io_cmdstan uses explicit dict 

https://github.com/arviz-devs/arviz/blob/main/arviz/data/io_cmdstan.py

io_pystan access model_code to infer dtypes.

**Comment by ahartikainen** [comment]
CmdStanPy does not handle dtypes.
