### ISSUE TITLE
have get_bins distinguish between float and int data

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1639]
[get_bins](https://github.com/arviz-devs/arviz/blob/main/arviz/stats/density_utils.py#L923) currently assumes that `values` passed to it are always integer values, it therefore enforces a minimum bin width of 1. There are some cases however where we may want to use a histogram for continuous data and we do have a `kind` argument in order to override the default continuous->kde, discrete->hist, so it should work.

We should look at the dtype of the input values and act accordingly. if the dtype is a discrete type, we should keep the exact same code and return the same number of bins, otherwise, we can either keep a similar version of the code without the specifics of discrete variables or call https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html with `bins="auto"`

**Comment by ahartikainen** [comment]
We probably want higher bin count than auto gives.

rcparams could work? Then a few examples with rccontext?

**Comment by OriolAbril** [comment]
I think our custom way to get the bins that we currently use for int data will do that (provided we remove the bin_width>=1 constraint)
