### ISSUE TITLE
Make summary() less verbose

### ISSUE THREAD

**Issue by twiecki** [arviz-devs/arviz#1640]
I think the default output of `az.summary()` is too verbose. I don't even know what `mcse_mean` means and why I should look at it. I think just having `mean`, `sd`, and the `hdi`s is enough for most people and produces output that's easier to read and less daunting. For people who want more maybe `az.summary(x, sampler_stats=True)` could be added.

**Comment by OriolAbril** [comment]
It looks like you want `az.summary(idata, kind="stats")`

**Comment by twiecki** [comment]
Thoughts on making that the default?

**Comment by OriolAbril** [comment]
I personally use summary more for its diagnostics than for its stats, so I'd argue against changing the default. Do you think better documentation so it's easier to know about `kind="stats"` would be enough? 

Other options that come to mind are adding an `rcParam` for that, or even a `summary_stats` what wraps `summary` setting the default to `kind="stats"`

**Comment by AlexAndorra** [comment]
Agree with @OriolAbril, I use the diagnostics a lot in `summary`, especially `r_hat` and `ess`. A wrapper could be interesting because it makes people aware that they are only looking at a subset of the info

**Comment by twiecki** [comment]
What about dropping `mcse_mean` and `mcse_sd`?

**Comment by AlexAndorra** [comment]
I indeed rarely use that (but maybe that's on me). If it's not that important, we could make that optional?

**Comment by twiecki** [comment]
I think that's more old-school, I can't find that recommended in any recent
texts.

**Comment by ahartikainen** [comment]
I think our summary follows more or less R `posterior` package.

@avehtari @jgabry @paul-buerkner

FWIW mcse is good when estimating the mcmc accuracy for the parameter (did I get my terminology wrong here)

**Comment by OriolAbril** [comment]
The default method to compute `mcse` shown in `summary` are the ones in https://arxiv.org/abs/1903.08008, which also recommends checking it's small enough.

**Comment by twiecki** [comment]
OK, sounds like people see good reasons to keep it, just wanted to open the discussion.
