### ISSUE TITLE
Expose skip_dims/flatten argument

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1644]
All density plots (except plot_ppc) reduce the chain and draw dimensions, some have a combined argument to avoid reducing the chain dimension,  but in some cases this is not enough, and similarly to plot_ppc behaviour, we would like to choose at will which dimensions to reduce. I think we should support that. 

## Thoughts on implementation
Exposing skip_dims argument from xarray_var_iter should do the trick. This is basically what plot_ppc does with its flatten argument

**Comment by ericch99** [comment]
@OriolAbril Hi, this is my first contribution -- how difficult do you anticipate this issue being? If it's not too difficult, I'd like to take a stab at it. Thanks!

**Comment by OriolAbril** [comment]
Hi @ericch99, this should be a good first contribution, it's mostly a matter of adding this argument and making sure it gets passed downstream to the right `xarray_var_iter`, `xarray_to_ndarray` (the function in `sel_utils` called by the plotting function. 

The main question on that is on our side actually, before that we should define the _name_ of this argument! Give us ~1 day to think about this a bit and I'll get back to you. In the meantime, you can read the source code of one of the plots to see how the argument should be passed down and see if you have any questions.

**Comment by OriolAbril** [comment]
@ericch99 you should use `combine_dims` for the argument name, even if it's eventually passed to `skip_dims` in `xarray_var_iter`. I am assigning the issue to you now, thanks for reaching out :smile:

**Comment by ericch99** [comment]
Hi @OriolAbril, sorry for the late response -- school's been a little busy! That said, I have a couple of comprehension-type questions to make sure I'm on the right track. 

1) I suppose that `ppcplot` already has the functionality we want -- in that case, am I correct in assuming that `combine_dims` will be analogous to / the same thing as `flatten`? (i.e., a list)

2) The correct approach is to simply implement this functionality for each separate plotting function.

I appreciate your help!

**Comment by ericch99** [comment]
As a follow-up, I am a little confused as to which plots are supposed to implement this functionality; I'd assume that the plotting functions that don't call `xarray_var_iter` or `xarray_to_ndarray` can be left alone, but `plot_dist_comparison` does call `xarray_var_iter`, and it's not obvious to me what we are reducing over -- in the example given in the documentation, would the desired behavior be to plot each country (`match`) on the same axis? 

Once again, I appreciate that you're willing to guide me through this!

**Comment by OriolAbril** [comment]
> I suppose that ppcplot already has the functionality we want -- in that case, am I correct in assuming that combine_dims will be analogous to / the same thing as flatten? (i.e., a list)

Yes, list, tuple, array, set... It needs to be converted to a set down the line, so as long as this is possible it should probably work.

> The correct approach is to simply implement this functionality separately, for each relevant plotting function.
> As a follow-up, I am a little confused as to which plots are supposed to implement this functionality; I'd assume that the plotting functions that don't call xarray_var_iter or xarray_to_ndarray can be left alone, but plot_dist_comparison does call xarray_var_iter, and it's not obvious to me what we are reducing over -- in the example given in the documentation, would the desired behavior be to plot each country (match) on the same axis?

Yes, all functions using `xarray_var_iter` or `xarray_to_ndarray` should have this `combine_dims` added and pass it to `xarray_...` as `skip_dims`. The goal is that users will then be able to choose what gets plotted in a given axes. In the rugby case, using `combined_dims={"team"}` will combine all samples from all teams in a single array and plot the kde of that. 

In this particular example, this doesn't make much sense. But in many other cases it doesn't make much sense to not do this. Consider for example an experiment in a lab where they test multiple drugs and doses on the same culture, and to get better accuracy, each dose and drug combination is replicated `n` times. By design we would expect replications to show the same behaviour, so in general one would want to combine all replications and see a combination of drug+dose in each subplot, not one subplot per replication+drug+dose.

**Comment by Tsai-Ni** [comment]
Hi @OriolAbril! I'm currently working on this issue with @ericch99. I noticed that unlike `xarray_var_iter`, which already has a `skip_dims` argument, `xarray_to_ndarray` does not have any variables that can be assigned `combine_dims`. However, would implementing a `skip_dims` in `xarray_to_ndarray` be out of scope?

**Comment by OriolAbril** [comment]
Ideally, that would be in scope and a great addition, I actually missed completely that `xarray_to_ndarray` doesn't have this capability when writing the issue. 

Now that you say it, it does make sense that it doesn't. There can be repeated labels, in which case, the number of samples for each "column" of the ndarray would not be the same for all columns. I think the code would have to be updated to use `xarray_var_sel` internally in plot_pair for this to work. This is more work, but I think we'll be better off on the long run if we stop using `xarray_to_ndarray` so that plots can also be dask compatible.

I think we should give a bit more thought to that, do you already have a clear path forward on this end? Or only for unique coordinate values case?

**Comment by ericch99** [comment]
@OriolAbril just wanted to confirm Tsai-Ni's comment! 

I also have an additional question about scope -- I noticed in the original description of the issue, it specified that density plots in particular (such as `distcomparisonplot`) needed this functionality. Should we also implement this for other plots like `autocorrplot`? In that case, implementation is not as straightforward, since it looks like we are getting dimension mismatches -- specifically, for the `centered_eight` data given in the [documentation](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_autocorr.html), adding `combine_dims` results in a `ValueError`  where one array cannot be broadcast to another shape (a screenshot is attached below). I believe the same problem is happening with `pairplot`. How would you recommend we handle this?

![image](https://user-images.githubusercontent.com/55517473/115627877-54ce5f00-a2c5-11eb-831c-bc445b52e8b6.png)

**Comment by OriolAbril** [comment]
Indeed, we should probably have defined the scope better, sorry about that. Not all plots should have this `combine_dims` argument. I copied all the plotting functions from the docs and tried to organize them below.

some of these are for the parameters, others are for observations/predictions, diagnostics and others like model comparison related plots. Moreover there are some lower level plots that take only arrays as inputs, not InferenceData for which it makes no sense to add `combine_dims`, those are `plot_kde`, `plot_dist` and `plot_hdi`.

The ones that will benefit from that and are in scope are the ones for parameters or observations/predictions:

```python
    arviz.plot_bpv  # already has flatten, no need for combine_dims
    arviz.plot_density
    arviz.plot_dist_comparison
    arviz.plot_forest  # se note below
    arviz.plot_joint  # deprecated, no need to work on it
    arviz.plot_pair
    arviz.plot_posterior
    arviz.plot_ppc  # already has flatten, no need for combine_dims
    arviz.plot_violin
```

`plot_forest` can also show rhat and ess, which should only be valid when `combine_dims` is None, not sure if we want a warning or an error though. 


The diagnostics plots should _not_ have this feature, even if some use `xarray_var_iter`. The main reason for that is that as far as I understand, ess, rhat, autocorr... are defined per variable, I am not sure the result we'd get from treating a multidim variable as a scalar one would make any sense. Those are:

```
    arviz.plot_autocorr
    arviz.plot_energy
    arviz.plot_ess
    arviz.plot_mcse
    arviz.plot_parallel
    arviz.plot_rank
```

The model comparison plots are a whole different topic and I think none of them uses `xarray_var_iter` but in any case, those should not have this either:

```
    arviz.plot_compare
    arviz.plot_elpd
    arviz.plot_khat
```

And last, the ones I don't know, which probably should not have it are `plot_trace` and `plot_separation`. `plot_trace` has both compact and combined, and I think compact is enough to put multidim variables in the same axis but having each it's own density. It is different from `combine_dims` therefore as the draws are not combined into a single density, but it is somewhat similar and combining the two will probably be a nightmare. I don't work with binary outcomes and have therefore not used `plot_separation` nor I know much about it, this one could go both ways really.

**Comment by Tsai-Ni** [comment]
> I think we should give a bit more thought to that, do you already have a clear path forward on this end? Or only for unique coordinate values case?

@OriolAbril We are working on the straightforward plots you listed. As for unique coordinate values case, can you please elaborate on what you mean?

**Comment by Tsai-Ni** [comment]
As a followup, 

> `plot_forest` can also show rhat and ess, which should only be valid when `combine_dims` is None, not sure if we want a warning or an error though.

FOLLOWUP:
1. Pair Plot: We are running into errors because adding `combine_dims` results in a `ValueError` where 2 arrays cannot be concatenated -- specifically, for the centered_eight data given in the documentation.
2. Forest Plot: Given that this file does not use any xarray functions, how would you suggest we go about adding the `combine_dims` functionality?
3. Testing: How do you suggest we add formal tests? So far, we have been using test_plots_bokeh.py's functions as a structure, but those are only testing whether the graph is generated. Here's an example of what we did:
<img width="710" alt="Screen Shot 2021-04-22 at 1 03 27 PM" src="https://user-images.githubusercontent.com/47158456/115658297-24410080-a36b-11eb-80d0-c596469bb270.png">
We have also been testing informally by running and creating plots based off of the documentation examples and seeing if specifying combine_dims gives sensible results. How should these tests be incorporated, if at all?

**Comment by OriolAbril** [comment]
> As for unique coordinate values case, can you please elaborate on what you mean?

I have now realized that this is already an issue, so adding the `combine_dims` won't introduce this problem (it won't solve it either but this is fine). Here is what I mean:

```python
import arviz as az 
data = az.load_arviz_data("radon")
obs_county = data.posterior["County"][data.constant_data["county_idx"]]
data = data.assign_coords(obs_id=obs_county, groups="observed_vars")
gen = az.sel_utils.xarray_var_iter(data.posterior_predictive, combined=True)
for d in gen:
     l = list(d)
     l[-1] = l[-1].shape
     print(l)
# Output
# ['y', {'obs_id': 'AITKIN'}, {'obs_id': 0}, (4, 500, 4)]
# ['y', {'obs_id': 'ANOKA'}, {'obs_id': 1}, (4, 500, 52)]
# ['y', {'obs_id': 'BECKER'}, {'obs_id': 2}, (4, 500, 3)]
# ['y', {'obs_id': 'BELTRAMI'}, {'obs_id': 3}, (4, 500, 7)]
# ...
```

Which is expected behaviour, values with the same label are added to the same "pack". So while `xarray_var_iter` works in this case and therefore most plots do work with that, `xarray_to_ndarray` does not, the shapes are different, so `plot_pair` for example doesn't work unless all coordinate values are unique. But again, this can happen with or without `combine_dims` so it's a different issue altogether, no need to fix this here.

> Pair Plot: We are running into errors because adding combine_dims results in a ValueError where 2 arrays cannot be concatenated -- specifically, for the centered_eight data given in the documentation.

This is the same issue I was talking above actually. So while in the no `combine_dims` pairplot sees 10 variables to plot (8 thetas, mu and tau) each with shape chain, draw and can then flatten and generate a 2d array with shape (n_samples, n_vars), this is no longer possible in the `combine_dims` case as it sees 3 vars, mu and tau have shape `chain, draw` but `theta` has shape `chain, draw, school` so they can't be flattened and concatenated. 

As a workaround, you should be able to test the correct behaviour of `combine_dims` by using the `non_centered_eight` dataset and plotting only vars theta and theta_tilde, which will result in a 2 var pairplot with 1 axes only.

> Forest Plot: Given that this file does not use any xarray functions, how would you suggest we go about adding the combine_dims functionality?

It has to use `xarray_var_iter` somewhere I think, otherwise the `labeller`s would not work and they do. It may be much more hidden than in other plots and complicate things. I think the best way to go forward on that is for you to submit a PR so we can comment on specific pieces of code there directly. 

> Testing: How do you suggest we add formal tests? So far, we have been using test_plots_bokeh.py's functions as a structure, but those are only testing whether the graph is generated. Here's an example of what we did:

Checking that the function call does not error out is generally enough, we could also add a test to check the right number of axes are returned. Agan, this is better to comment on a PR. Also, from the code sample it looks like you are passing `combine_dims=[]`, does it behave lilke `flatten`? The default for the plots should not be modified, in `plot_ppc` it makes sense to have multidim variables combined into a single kde as a default, but for the other plots it does not, so the default should still be a plot per school, and only get a combined plot of all schools if we set `combine_dims={"school"}`

**Comment by ericch99** [comment]
Hi @OriolAbril, thanks -- that was incredibly helpful input! Per your suggestion, we have opened a preliminary pull request as that may be easier to comment on. Please let us know if you have any questions on what we did, and we're looking forward to your feedback!
