### ISSUE TITLE
Auto-scaling figures

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#165]
It would be nice to have a good general solution to autoscale the figure size (and fontsize, markersize, etc) as a function of the number of subplots.  Our current implementation is not general enough and needs special care for each type of plot.

**Comment by ColCarroll** [comment]
As an example, this plot is tiny:

```python
with pm.Model() as model:
    a = pm.Normal('a', 0, 1)
    trace = pm.sample()

az.autocorrplot(trace, combined=True);
```
![image](https://user-images.githubusercontent.com/2295568/43995045-4f70688a-9da7-11e8-92ca-c5d52ca1db23.png)

**Comment by MFreidank** [comment]
Anyone knows of some sort of reference implementation for this? I would be interested in it (I have a lot of code that does manual rescaling) but I am not quite sure how a good general solution would look.

**Comment by aloctavodia** [comment]
Not really I was just thinking of a very empirical approach. Starting from matplotlib defaults parameters for a single plot and then scale plot-elements accordingly, paying special attention if they scale linearly, quadratic or otherwise. Maybe matplolib-devs can offer us some guidance.
