### ISSUE TITLE
Implement simultaneous confidence bands for ECDF of PIT 

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#1663]
This is related to the paper https://arxiv.org/abs/2103.10522 and the R code is https://github.com/TeemuSailynoja/simultaneous-confidence-bands

**Comment by OriolAbril** [comment]
cc @Rishabh261998

**Comment by Rishabh261998** [comment]
@OriolAbril should I start working on this now? as I have included this in the GSoC timeline. As of now, I was thinking of looking into this #1574, as it has been idle for a long time.

**Comment by OriolAbril** [comment]
No need to work on this now, just wanted you to be aware of all the relevant issues.
