### ISSUE TITLE
Pylint 2.8.1 fails arviz/stats/density_utils.py

### ISSUE THREAD

**Issue by wm1995** [arviz-devs/arviz#1677]
**Describe the bug**
Pylint 2.8.1 has added some new checks, one of which (`R1731: consider-using-max-builtin`) fails on the existing [`arviz/stats/density_utils.py`](https://github.com/arviz-devs/arviz/blob/79a9fd78cdca90bf401397c47ed1fe737e957606/arviz/stats/density_utils.py#L404)

**To Reproduce**
Run the linting checks with the latest version of Pylint (I ran mine in the Docker container)
```
$ python -m pylint arviz/
************* Module arviz.stats.density_utils
arviz/stats/density_utils.py:404:4: R1731: Consider using 'grid_len = max(grid_len, 100)' instead of unnecessary if block (consider-using-max-builtin)

------------------------------------
Your code has been rated at 10.00/10
```

**Expected behavior**
Would expect no errors from Pylint

**Additional context**
I found this error when working on #1665, I've added a commit in that that should fix it, but it'd be an easy thing to change on its own: here's an example patch

```patch
diff --git arviz/stats/density_utils.py arviz/stats/density_utils.py
index 4651442..ba3c2c9 100644
--- arviz/stats/density_utils.py
+++ arviz/stats/density_utils.py
@@ -401,9 +401,7 @@ def _get_grid(
         Maximum value of the grid
     """
     # Set up number of bins.
-    if grid_len < 100:
-        grid_len = 100
-    grid_len = int(grid_len)
+    grid_len = int(max(grid_len, 100))
 
     # Set up domain
     if custom_lims is not None:
```

**Comment by ColCarroll** [comment]
Thanks for the catch! 

Do you want to submit the patch, or it is easy enough for me to.

**Comment by wm1995** [comment]
I've put it in #1665 but it may be more appropriate in a standalone PR? Happy to be guided by you on this - please let me know if I can do anything else to help

**Comment by OriolAbril** [comment]
#1665 is already ready to merge so I think it's not necessary to split that into another PR.

**Comment by ahartikainen** [comment]
Hi, didn't remember that there was discussion about this, I fixed this issue today (because I want to keep main branch working)
