### ISSUE TITLE
Posterior plot errors with boolean array

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#1694]
When passed a boolean array, `plot_posterior` fails with the following error because `np.histogram` assumes that subtraction is defined on the array:
```python
TypeError('numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.')
```

This example reproduces the error:

```python
import numpy as np
import arviz as az

data = np.random.choice(a=[False, True], size=(4, 100))
az.plot_posterior(data)
```

**Comment by OriolAbril** [comment]
Just to be clear, the expected output would be a histogram with two bins, one around 0 and another around 1 (in which case we can add an `astype(int)` before the histogram and be done with it)? Or should the labels be `True` and `False`?

**Comment by sethaxen** [comment]
I'd expect the second, even though the first option is easier.

**Comment by OriolAbril** [comment]
Then I think it should be something like:

1. Evaluate and store condition of whether or not the dtype is boolean
2. If True, do the `astype(int)` for histogram to work
3. (plotting should not require changes, just here for completeness)
4. If True, change the plot labels from 0 and 1 to False and True. Then reset the variable storing the condition

**Comment by ahartikainen** [comment]
We should use bar graph with counts for bool data, not hist.

**Comment by utkarsh-maheshwari** [comment]
> 3\. plotting should not require changes, just here for completeness

I guess this means plots/posteriorplot.py need to be edited and not plots/backends/matplotlib/posteriorplot.py .. ?

**Comment by ahartikainen** [comment]
User api should not change. Feel free to edit backend files.

**Comment by utkarsh-maheshwari** [comment]
Do we need `**bar_kwargs` plot bar plots?

**Comment by utkarsh-maheshwari** [comment]
@OriolAbril Can you please assign this issue to me?
I have added some lines of code and submitting a pr to discuss the problems.

**Comment by OriolAbril** [comment]
done, in practice, especially with gsoc coming, you can already consider yourself assigned if you are the first to comment on the issue that you'll work on it, even if we take some time to assign you via the gitub assign feature. We already have a couple lines on that on the [contributing guide](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#if-an-issue-ticket-exists) for agility when it comes to contributing.
