### ISSUE TITLE
plot_posterior doesn' accept label as kwarg

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1703]
I think this is related to how we pass kwargs downstream to plot_dist or plot_kde... will look into it at some point unless someone beats me to it. My hunch is that plot_dist and plot_kde have a `label` argument and pass it explicitly to matplotlib instead of doing `setdefault` so if a label is passed via kwargs too it becomes a duplicated argument and errors out

Fixing this would allow using plot_posterior to overlay multiple distributions while having a legend.

**Comment by utkarsh-maheshwari** [comment]
https://github.com/arviz-devs/arviz/blob/bd0b786e6ab6ea5767110cf46fe0650c869d02f2/arviz/plots/backends/matplotlib/posteriorplot.py#L311-L321

As label is not added here, it will be considering default value of label (i.e. None).
Would None value of label still be conflicting with label passed via kwargs?

**Comment by OriolAbril** [comment]
`plot_posterior` does not set the label but `plot_kde` does:

https://github.com/arviz-devs/arviz/blob/1997afe0cf92d32e6ee71a94226fc458ace22313/arviz/plots/backends/matplotlib/kdeplot.py#L147

it should be set as `setdefault` to `plot_kwargs` or `fill_kwargs` or the corresponding kwargs (which one may depend on the type of plot so be careful here). Otherwise, if label is passed via kwargs, matplotlib gets two different instances of the same keyword argument and errors out.

**Comment by utkarsh-maheshwari** [comment]
Done, Thank you so much 🙇🏼‍♂️
