### ISSUE TITLE
label guide is broken

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1709]
The code in https://arviz-devs.github.io/arviz/user_guide/label_guide.html has not executed properly. It looks like an indentation issue in the first code cell.

**Comment by nk3843** [comment]
I want to help fix this? Please guide. This will be my first attempt at open source contribution. Thanks!

**Comment by OriolAbril** [comment]
Hi, welcome! You have to follow the steps described on the contributing guide to fork the repo, edit and send a PR, there is no need to build the documentation locally though, it can be generated by Azure from the PR so you can download it as a zip and see how it looks.

As for the changes themselves, there are two to be done:

1. Move the ipython directive https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/label_guide.rst#L14 a few lines down. It should be right before the code (like in the rest of examples) instead of having a section title in the between.
2. Fix the see also directive in https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/label_guide.rst#L58. There should be no dash and it should be indented 3 spaces.

**Comment by nk3843** [comment]
Hi,

Resolved the issues and sent a pull request. Please review.

Best,
Nikhil
