### ISSUE TITLE
Council restatement of commitment 

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1711]
Per our governance doc the council needs to restate their commitment each year on April 7th. We collectively forgot about this deadline so are carrying out this restatement today. 

@OriolAbril 
@ColCarroll
@AlexAndorra 
@sethaxen 
@ahartikainen 
@aloctavodia 

Please reconfirm you'll lead the community and uphold what we've laid out in the governance document for another year. In the event we don't get a reaffirmation in a reasonable amount of time we'll vacate your seat and hold an election.

https://github.com/arviz-devs/arviz/blob/main/GOVERNANCE.md

**Comment by canyon289** [comment]
Since I'm a council member here's my affirmation. Happy to lead ArviZ for another year! Thrilled we've made it one year with this governance process and everyone seems happy!

**Comment by ahartikainen** [comment]
Yes

**Comment by sethaxen** [comment]
I also affirm! (has it already been 1 year?)

**Comment by OriolAbril** [comment]
Also happy to continue one more year

**Comment by ColCarroll** [comment]
I'm still committed!

**Comment by AlexAndorra** [comment]
I also affirm Sir!

**Comment by aloctavodia** [comment]
Aye!

**Comment by ColCarroll** [comment]
Closing for 2021.
