### ISSUE TITLE
Remove testing dependency on http download for radon  dataset

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1716]
**Describe the bug**
Loading radon dataset is causing network failures in tests. We should remove this dependency anyway since we want our tests to be as isolated as possible.

https://github.com/arviz-devs/arviz/blob/main/arviz/tests/base_tests/test_stats.py#L607

**To Reproduce**
See CI pipeline here
https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=4434&view=logs&j=e9e5789a-ef7e-54d7-c525-bfdc535bcf80&t=85614d98-b825-523f-f666-d210d5fbfe6e&l=359

Reference PR where we first noticed this https://github.com/arviz-devs/arviz/pull/1710

**Expected behavior**
We test  `def test_loo_pit_multi_lik():` without need for external radon dataset

**Additional context**

**Comment by canyon289** [comment]
@utkarsh-maheshwari assigning this to you for now so you have first right of refusal

**Comment by utkarsh-maheshwari** [comment]
I think task is to create `inferencedata` with multiple log_likelihood variables, without using any external datasets. 
However, internal datsets like https://github.com/arviz-devs/arviz/blob/4d9caca88a9a3b4043062609cb9a401e3f08804d/arviz/tests/helpers.py#L181 can be called inside `test_loo_pit_multi_lik()` and then adding to it an extra `log_likelihood` variable with random values would do our work.

**Comment by utkarsh-maheshwari** [comment]
Also, size of the new variable doesn't matter. It could be anything.

**Comment by utkarsh-maheshwari** [comment]
But I didn't actually understand the significance of this test.
