### ISSUE TITLE
`from_tfp()` now using no-longer-supported TF indioms

### ISSUE THREAD

**Issue by michaelquinn32** [arviz-devs/arviz#1724]
**Describe the bug**
Hi team!

There have been some updates to tfp/ edward2 that break the data from tfp converter .

1. edward2 is no longer a tfp module. It can be imported with `import edward2 as ed`. See https://github.com/google/edward2
2. edward2 no longer has the interceptor context manager
3. It looks like a lot of the approach to generating data still relies on tf v1 concepts, and this would be a lot easier if we could just use tf v2 always-eager execution.

**To Reproduce**
Install tfp nightly and most recent version of edward2.

Thanks!

**Comment by michaelquinn32** [comment]
cc @junpenglao

**Comment by OriolAbril** [comment]
Cc @ColCarroll too who I think is already working on it

**Comment by OriolAbril** [comment]
closed in favour of https://github.com/arviz-devs/arviz/issues/1890.
