### ISSUE TITLE
Gallery plot for violintraceplot

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#174]
Could use an example of `violintraceplot`.  Possibly @canyon289 ?

See http://arviz-devs.github.io/arviz/examples/index.html for other gallery examples, and see, for example https://github.com/arviz-devs/arviz/blob/master/examples/traceplot.py for where that is generated. You can (probably?) build docs locally with 

```bash
cd doc/
make html

# on linux:
# google-chrome _build/html/index.html

# on OSX:
open _build/html/index.html 
```

**Comment by canyon289** [comment]
I can take this on. Will get to it this weekend

**Comment by canyon289** [comment]
Just in general I'm (very) happy to add documentation to every plot, trying
to figure out how much  I should do now, or wait until the interface
settles (dataframe vs xarray vs netcdf) and then write all the docs.

**Comment by canyon289** [comment]
I will do this after this https://github.com/arviz-devs/arviz/pull/173 is merged. It'll be a good excuse for me to take your new code for a spin :)
