### ISSUE TITLE
arviz.plot_ppc does not allow for a non-black observed data plot

### ISSUE THREAD

**Issue by isosphere** [arviz-devs/arviz#1755]
## Short Description

I'm using a dark theme for my plots, and the default black colour for observed data does not show enough contrast when using arviz.plot_ppc. There does not appear to be an option to supply a different colour to use, only the colour and alpha of the posterior.

## Code Example or link
Arviz 0.11.2

```
import arviz as az
from jupyterthemes import jtplot

jtplot.style(theme='monokai', context='notebook')

az.plot_ppc(data, observed=True)
```

## Relevant documentation or public examples

https://arviz-devs.github.io/arviz/api/generated/arviz.plot_ppc.html

**Comment by isosphere** [comment]
I'm being sneaky and using your issue tracking system to share how I addressed this for myself, so others can find the same.

```
import arviz as az
from jupyterthemes import jtplot
import matplotlib.pyplot as plt

jtplot.style(theme='monokai', context='notebook')

fig, ax = plt.subplots()
az.plot_ppc(data, observed=True, ax=ax)
ax.get_lines()[1].set_color("yellow")
plt.legend() # update legend colour

```

**Comment by ahartikainen** [comment]
We need add a way to access that while calling the `plot_ppc`
