### ISSUE TITLE
ArviZ uses `constrained_layout=True` even when disabling it in `az.rcParams`

### ISSUE THREAD

**Issue by tomicapretto** [arviz-devs/arviz#1763]
I'm using the `"arviz-darkgrid"` style and I'm getting a constrained layout even when I attempt to disable it via 

```python
az.rcParams["plot.matplotlib.constrained_layout"] = False
```

**The code**

```python
import arviz as az
import matplotlib.pyplot as plt

az.style.use("arviz-darkgrid")
az.rcParams["plot.matplotlib.constrained_layout"] = False

fig, axes = plt.subplots(1, 2)

axes[0].scatter([1, 2], [1, 2])
axes[1].scatter([1, 2], [1, 2])
fig.subplots_adjust(bottom=0.2)
```

**The result**

![image](https://user-images.githubusercontent.com/25507629/130510985-e1a52568-afb2-4625-9fbc-a73268aa7b32.png)

**The environment**
```python
%load_ext watermark
%watermark -n -u -v -iv -w
```

```
Last updated: Mon Aug 23 2021

Python implementation: CPython
Python version       : 3.8.5
IPython version      : 7.18.1

matplotlib: 3.4.3
arviz     : 0.11.2
json      : 2.0.9

Watermark: 2.1.0
```

**Comment by aloctavodia** [comment]
We are setting constrained_layout twice, and that is causing this bug. 

In the meantime you can disable it using `plt.rcParams['figure.constrained_layout.use'] = False`
