### ISSUE TITLE
fix plot_lm docstring examples

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1765]
The examples in https://arviz-devs.github.io/arviz/api/generated/arviz.plot_lm.html are not correctly rendered in the docs. This looks like an issue with the rST syntax, the `plot` directive needs two dots, space, plot and then two colons -> `.. plot::` but the 2nd colon is missing in most examples.

**Comment by roshnaeem** [comment]
@OriolAbril,  are you referring to `Implot.py` because I checked it and could not find any missing colon.

**Comment by ahartikainen** [comment]
Fixed by #1778

**Comment by OriolAbril** [comment]
I fixed some of the issues with the docstring but not all of them. There are still some hyperlinks not working properly like in y_hat_fill_kwargs or in backend_kwargs. Sorry I wasn't very clear with the issue. @Akshat1331 if you are interested in fixing those, that would be great. You should find guidance on how to fix those at https://arviz-devs.github.io/arviz/contributing/developer_guide.html#hyperlinks
