### ISSUE TITLE
az.plot_dist missing values in KDE

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1786]
**Describe the bug**
`az.plot_kde` seems to be missing values in x axis

**To Reproduce**
![image](https://user-images.githubusercontent.com/7213793/132256179-580c0839-ad84-4f97-9c8c-cf72fbedb437.png)

**Expected behavior**
That 6 is not cut off

**Additional context**
11.2

**Comment by canyon289** [comment]
Ah nevermind I see that its binning

**Comment by aloctavodia** [comment]
The bandwith is only for the kde, for the histogram you can pass the bins. If the dataset is that small using a kde or histogram will be misleading. You should plot all the data.

**Comment by canyon289** [comment]
Thanks
