### ISSUE TITLE
Update doc- Refitting PyStan (3.0+) models with ArviZ

### ISSUE THREAD

**Issue by roshnaeem** [arviz-devs/arviz#1795]
## Tell us about it
The doc section [Refitting PyStan (2.x) models with ArviZ](https://arviz-devs.github.io/arviz/user_guide/pystan2_refitting.html) and [Refitting PyStan (3.0+) models with ArviZ](https://arviz-devs.github.io/arviz/user_guide/pystan_refitting.html) consists of the same text. The first one has been updated and the latter needs to be updated. 

## Thoughts on implementation

Update the [Refitting PyStan (3.0+) models with ArviZ](https://arviz-devs.github.io/arviz/user_guide/pystan_refitting.html) the same way as other has been changed in #1794.

## Source file
File: https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/pystan_refitting.ipynb

**Comment by anthony-aleman** [comment]
Hey I am new to contributing to open source projects, but I'd like to help out with this issue. How exactly can I help?

**Comment by roshnaeem** [comment]
Hello @anthony-aleman, this issue is related to the documentation of ArviZ. You need to update the Source file given in the issue body the same way as it has been updated in PR #1794.

**Comment by roshnaeem** [comment]
Hello, @anthony-aleman, are you working on this issue?
