### ISSUE TITLE
Add docs references to plot_autocorr

### ISSUE THREAD

**Issue by roshnaeem** [arviz-devs/arviz#1809]
Add links to the related functions and classes to all the places where they are mentioned in the [plot_autocorr](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_autocorr.html) doc.

## Source File
Source file: https://github.com/arviz-devs/arviz/blob/main/arviz/plots/autocorrplot.py

## How to add links
Add the links in the docstring of doc. You can also check the docstring by going to the `[source]`. 

* Add links to the ArviZ functions and classes using [Cross-referencing with Sphinx](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html).
* Add links to the xarray functions and classes using [Intersphinx](https://docs.readthedocs.io/en/stable/guides/intersphinx.html).
* Add the rest of the external links using this [syntax](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-external-web-pages).

## See also section
Add the following functions in the "See also" section:
1. [arviz.autocorr](https://arviz-devs.github.io/arviz/api/generated/arviz.autocorr.html)

See [Adding "see also" section](https://github.com/arviz-devs/arviz/wiki/ArviZ-Hacktoberfest-2021#adding-see-also-section) for more details. 

## Checking the preview of docs
For checking the preview of docs, you don't need t set up the project on your local machine. Just follow the [checking the preview guide](https://github.com/arviz-devs/arviz/wiki/ArviZ-Hacktoberfest-2021#how-to-check-the-preview-of-docs).

**Comment by OriolAbril** [comment]
I would not make any reference to this `doc/source/api/generated/.` folder and would assume and recommend that people working on that don't build docs locally but wait to check on rtd. No need to update this issue, but for the other issues you'll create
