### ISSUE TITLE
Add docs references to plot_posterior docstring

### ISSUE THREAD

**Issue by roshnaeem** [arviz-devs/arviz#1825]
Add links to the related functions and classes to all the places where they are mentioned in the [plot_posterior](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_posterior.html) docstring.

## Sample PR:
You can see https://github.com/arviz-devs/arviz/pull/1816 for the function, `plot_autocorr`. 

## Source File
Source file: https://github.com/arviz-devs/arviz/blob/main/arviz/plots/posteriorplot.py

## How to add links
Add the links in the docstring of doc. You can also check the docstring by going to the `[source]`. 

* Add links to the ArviZ functions and classes using [Cross-referencing with Sphinx](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html).
* Add links to the xarray functions and classes using [Intersphinx](https://docs.readthedocs.io/en/stable/guides/intersphinx.html).
* Add the rest of the external links using this [syntax](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-external-web-pages).

## `backend_kwargs` and `kwargs`
For adding `backend_kwargs` as they have been added in #1816, see [Adding backend_kwargs guide](https://github.com/arviz-devs/arviz/wiki/ArviZ-Hacktoberfest-2021#adding-backend_kwargs). Follow the same process for `kwargs`. 

## See also section
Add the following functions in the "See also" section:
1. [plot_dist](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_dist.html)
2. [plot_density](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_density.html)
3. [plot_forest](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_forest.html)

See [Adding "see also" section](https://github.com/arviz-devs/arviz/wiki/ArviZ-Hacktoberfest-2021#adding-see-also-section) for more details. 

## Checking the preview of docs
For checking the preview of docs, you don't need t set up the project on your local machine. Just follow the [checking the preview guide](https://github.com/arviz-devs/arviz/wiki/ArviZ-Hacktoberfest-2021#how-to-check-the-preview-of-docs).

**Comment by Divyateja04** [comment]
I would like to work on this, can you please assign this to me?

**Comment by Divyateja04** [comment]
Sent a PR for this too, can you check?

**Comment by Divyateja04** [comment]
Is this PR correct?
