### ISSUE TITLE
List sponsors and institutional partners somewhere

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#1827]
We have briefly discussed in two lab meetings the idea of listing sponsors/institutional partners somewhere in our documentation. One inspiration is NumPy, which lists these at https://numpy.org/about/ and gives strict definitions for what constitutes an institutional partner at https://numpy.org/devdocs/dev/governance/governance.html#institutional-partners-and-funding:

The working definitions for these categories
- sponsor: directly funds the project
- institutional partner: supports the project by employing people that contribute to the project as part of their job

If we add these, we might also want to add a bit to our governance defining these terms and any special privileges sponsors/institutional partners can have.

**Comment by OriolAbril** [comment]
as a reference, numpy: https://numpy.org/about/#sponsors, jupyter: https://jupyter.org/about#sponsors and pymc https://github.com/pymc-devs/pymc/blob/main/GOVERNANCE.md#institutional-partners-and-funding (in progress) follow the same pattern. However, I can't find anything on numpy nor jupyter governance on sponsors, in fact, sponsors don't even seem to be listed at all anywhere in the jupyter governance page: https://jupyter.org/governance/people.html#institutional-partners nor https://jupyter.org/governance/governance.html#institutional-partners-and-funding have them, only institutional partners.

**Comment by OriolAbril** [comment]
Got the reference for numpy: https://numpy.org/neps/nep-0046-sponsorship-guidelines.html

**Comment by OriolAbril** [comment]
giving a shot at this in https://github.com/arviz-devs/arviz_governance/pull/3

**Comment by OriolAbril** [comment]
closed by https://github.com/arviz-devs/arviz/pull/2119
