### ISSUE TITLE
Update governance to include Recurring Contributors

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#1828]
Our [governance](https://github.com/arviz-devs/arviz/blob/main/GOVERNANCE.md) currently lists 3 categories of contributors:
- General Contributors
- Core Contributors (of which Council members are also a part of)
- 7 Person steering council (Random Variables Council)

We informally have a 4th category somewhere between General Contributors and Core Contributors. These are individuals who have been invited to our Slack workspace and thus get to contribute to internal discussions about the project but have not yet been given the permissions of Core Contributors.

At the last lab meeting, it was suggested to call this category Recurring Contributors and formally add this 4th level of contributor to the governance, stipulating their responsibilities and privileges.

**Comment by OriolAbril** [comment]
giving a shot at this at https://github.com/arviz-devs/arviz_governance/pull/3

**Comment by OriolAbril** [comment]
was closed by https://github.com/arviz-devs/arviz-project/pull/3
