### ISSUE TITLE
Delete elections folder

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#1829]
At the last lab meeting, it was suggested to move the governance to its own repo, since it applies to all repos in the organization, not just this one. This is particularly relevant for ArviZ.jl.

**Comment by canyon289** [comment]
This sounds good to me

**Comment by canyon289** [comment]
https://github.com/arviz-devs/arviz_governance

**Comment by canyon289** [comment]
We can get approval on this one. If it merges I'll delete the files from this repo https://github.com/arviz-devs/arviz_governance/pull/1

**Comment by OriolAbril** [comment]
we can close the issue when removing the files from this repo. A couple notes in case it helps: there are muliple links to the governance doc, i.e. in the about us page in the documentation that should be updated; it is probably better to not delete the governance completely, but instead leave the file there with the link to the governance repo and one sentence only. the elections things can be deleted completely.

**Comment by OriolAbril** [comment]
the governance file  and other pages are updated, only the election folder needs to be removed to close the issue.

**Comment by tuhinmallick** [comment]
Is this issue still available?

**Comment by OriolAbril** [comment]
Yes

**Comment by shark-21** [comment]
can you assign it to me

**Comment by OriolAbril** [comment]
go ahead @shark-21
