### ISSUE TITLE
Need help in adding "See also" section - Stats

### ISSUE THREAD

**Issue by roshnaeem** [arviz-devs/arviz#1868]
## Short Description

For adding a "See also" section in docstrings, I need help to be sure about which functions should be added in this section for each function. 

## Code Example or link
An example of the "See also" section can be found at [compare](https://arviz-devs.github.io/arviz/api/generated/arviz.compare.html) page.

Related to https://github.com/arviz-devs/arviz/issues/1188
## Relevant documentation or public examples
I am adding the list of functions here. Comment your suggestions here for the "see also" section of these functions.
I'll keep updating the list here so in case if someone has already commented for one function, there won't be an extra effort. 

## Functions List 
- [x] [arviz.apply_test_function](https://arviz-devs.github.io/arviz/api/generated/arviz.apply_test_function.html) (none?)
- [x] [arviz.compare](https://arviz-devs.github.io/arviz/api/generated/arviz.compare.html)
- [x] [arviz.hdi](https://arviz-devs.github.io/arviz/api/generated/arviz.hdi.html)
- [x] [arviz.kde](https://arviz-devs.github.io/arviz/api/generated/arviz.kde.html) (plot_kde, plot_dist)
- [x] [arviz.loo](https://arviz-devs.github.io/arviz/api/generated/arviz.loo.html)  (waic, compare, compare_plot, plot_loo_pit, plot_elpd, plot_k_hat)
- [x] [arviz.loo_pit](https://arviz-devs.github.io/arviz/api/generated/arviz.loo_pit.html) (loo, plot_elpd, plot_k_hat)
- [x] [arviz.psislw](https://arviz-devs.github.io/arviz/api/generated/arviz.psislw.html) (loo)
- [x] [arviz.r2_score](https://arviz-devs.github.io/arviz/api/generated/arviz.r2_score.html) (None?)
- [x] [arviz.summary](https://arviz-devs.github.io/arviz/api/generated/arviz.summary.html) (loo, waic, ess, r_hat, mcse)
- [x] [arviz.waic](https://arviz-devs.github.io/arviz/api/generated/arviz.waic.html) (loo, compare, compare_plot)

**Comment by aloctavodia** [comment]
I added a few options between parentheses.
