### ISSUE TITLE
Dreprecated "stan_var_cols" when creating InferenceData from cmdstanpy

### ISSUE THREAD

**Issue by mberaha** [arviz-devs/arviz#1904]
**Describe the bug**
When creating an `InferenceData` from a CmdStanPy fit, the output gets flooded with warnings

```
WARNING:cmdstanpy:Property "stan_vars_cols" has been deprecated, use "metadata.stan_vars_cols" instead.
```

**Additional context**

I'm running a MacOs ARM, arviz==0.11.4, cmdstanpy==0.9.68

**Comment by tomicapretto** [comment]
According to this comment https://github.com/stan-dev/cmdstanpy/issues/693 `"metadata.stan_vars_cols"` is also removed so it doesn't make sense to keep this issue open. Also, the PR https://github.com/arviz-devs/arviz/pull/2278 that responds to the issue https://github.com/arviz-devs/arviz/issues/2276 covers the problem reported here.
