### ISSUE TITLE
FYI - CmdStanPy v1.0.0rc1 - removing deprecated methods, properties, names

### ISSUE THREAD

**Issue by mitzimorris** [arviz-devs/arviz#1907]
CmdStanPy v1.0.0rc1 is up on both PyPi and conda-forge, and announcement is here:  https://discourse.mc-stan.org/t/cmdstanpy-1-0-0rc1/24973

We've removed everything that previously gave a "deprecated" warning.
I've got a Jupyter notebook that runs CmdStanPy and then uses Arviz to visualize, and `fromCmdStanPy` seems to be working fine (although at one point, I did run across this: https://github.com/arviz-devs/arviz/issues/1904) -

notebook and files are available here:  https://github.com/maxbiostat/StanConnect2021_Biostatistics/tree/main/talk_1

**Comment by ahartikainen** [comment]
I think everything works.
