### ISSUE TITLE
Split default names to multiple lines in titles

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#192]
Currently plotting matrix /nD object can produce long names with default settings.

I think we could wrap them to multiple lines in titles.

![image](https://user-images.githubusercontent.com/13161958/44973738-3aa1b000-af66-11e8-82a9-114c05bdf5d0.png)

**Comment by canyon289** [comment]
Per discussion in https://github.com/arviz-devs/arviz/pull/214 another suggestion from @ahartikainen is to split dim and coords

**Comment by ColCarroll** [comment]
Closed by #227
