### ISSUE TITLE
MAP from samples

### ISSUE THREAD

**Issue by gdindi** [arviz-devs/arviz#1934]
Hi,

I would like to compute the MAP estimate of a joint posterior from samples generated by MCMC. I was wondering if there is a way to do that for a joint distribution with more than 2 variables. The joint plots are useful but since they use pairs of variables, they don't provide what I need.

I think I could use numpy's histogramdd to build the density from the samples, but maybe there is a straightforward way wit arviz.

Thanks.

**Comment by ahartikainen** [comment]
What you probably can do (with some estimation method) is to calculate posterior mode, but calculating MAP from posterior samples is not possible.

I recommend using posterior mean value, unless you have multimodal posterior in which case there are probably big problems with your model.

Is there some use-case why do you want to have MAP?

**Comment by gdindi** [comment]
Thanks for your answer. 
I need a point estimate and I thought that max a posteriori would be the way to go.

**Comment by ColCarroll** [comment]
generally a MAP estimate will be much faster and more straightforward to generate than MCMC samples -- i'd be interested if there was a situation in which this wasn't the case!

Note that there is a bad way of doing this: namely taking the draw with the largest likelihood. I've attached an example of doing this with 1,000 draws from a 10d gaussian. Notice that the MAP estimate is (0, 0, 0,..., 0), but this method finds a point that is not particularly close to there.

![image](https://user-images.githubusercontent.com/2295568/145487556-f2e76dc4-a303-4be2-85e0-9e73fb2cb1ce.png)
