### ISSUE TITLE
Consistent, good documentation

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#194]
A good way for this to be done is 

```bash
$ pydocstyle --convention=numpy arviz | wc -l
352
```

this could be added to the travis build as well.  Note that right now each violation is 2 lines, so there are "only" 176 violations. 

I'm working on this now, but it should not effect any code.

**Comment by canyon289** [comment]
If were gonna do this, we should add pydocstyle to requirements-dev :)
