### ISSUE TITLE
Change order of regularization in psislw

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#1941]
The [PSIS paper](https://arxiv.org/abs/1507.02646) is ambiguous as to whether the regularization of the shape parameter of the generalized Pareto distribution (in appendix C) should be performed before or after the scale parameter is estimated. ArviZ currently does it before, while loo does it afterwards. On Slack, @avehtari said:

> loo package implementation is intentional, and based on my experiments produces better results than the alternative. The joint distribution has strong dependency, which is further exaggerated by the use of profile likelihood and point estimates. It seems it's better to let the prior affect only k.

So I believe all we need to do is swap these two lines:

https://github.com/arviz-devs/arviz/blob/045ddd3b7c3f7ff3ab082cfc0f207e09dce9e629/arviz/stats/stats.py#L955-L956

**Comment by OrchiDorchi** [comment]
I am new to open source environment, can you assign me to this isssue for my first issue? 
Thanks. :)

**Comment by sethaxen** [comment]
Sure! Thanks!

**Comment by OrchiDorchi** [comment]
Will it be merged?
