### ISSUE TITLE
Getting files or other output

### ISSUE THREAD

**Issue by S3j5b0** [arviz-devs/arviz#1942]
Hi, I'm using arviz 0.11.
I need to use the function "plot_posterior" for a project, which I can't get to work.
I found this example in your docs:

```
import arviz as az 
data = az.load_arviz_data('centered_eight') 
az.plot_posterior(data)
```
But if I run it, nothing happens, nothing is output and no files are created.
the examples I have seen so far have been in jupyter notebook, and it looks like the images are just shown there. 
I run it in vs code, how do I get it to output a file or something like that?

**Comment by ahartikainen** [comment]
import matplotlib

....
plt.show()


I think we even might have a show keyword in plot_posterior (az.plot_posterior(..., show=True) )

https://arviz-devs.github.io/arviz/api/generated/arviz.plot_posterior.html

This is how matplotlib works so more info on their docs.

**Comment by ahartikainen** [comment]
To save them to a file, you can use plt.savefig for the latest figure
