### ISSUE TITLE
loo, waic, psis & model comparison interface

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#195]
For loo, we need to have `log_lik`, which is calculated for each data point.

Currently, the easiest (robust) way for Stan users is to manually calculate `log_lik` variable. Until Stan has some automatic way to output `log_lik`, I think Stan users can input `log_lik` as a variable in the fit object.

For PyMC3 you can do the calculation post sampling, so the user only needs original data and model. So easiest (robust) way to do it in PyMC3 is let automatic algorithm to do the calculation.

Could loo function accept `Inference object` with a variable that contains `log_lik`, PyStan fit --> Inference object, PyMC3 Trace --> automatic calculation.

    loo(inference_object, log_lik_var="log_lik")

Or should loo only accept Inference objects that have a special `log_lik` parameter.
Then we would need a function to create and populate it either from posterior or calculate based on the posterior.

Other helper values can be extracted from the `Inference.sample_stats`?

https://cran.r-project.org/web/packages/loo/vignettes/loo2-with-rstan.html

https://docs.pymc.io/notebooks/model_comparison.html

http://www.stat.columbia.edu/~gelman/research/unpublished/VehtariGelmanGabry_PSIS_2017.pdf

**Comment by ahartikainen** [comment]
I think if we have good helper functions for `log_lik`, accepting only Inference objects would be the easiest way to handle the interface.

Also, what values do we want to output in the default "summary", also should it print something?

**Comment by junpenglao** [comment]
In PyMC3 the data `log_lik` is computed automatically, but only given that the model object is provided. I think it is likely gets complicated if we are to save model object - it would require us to work out the compatibility of different Probabilistic language model framework (e.g., make sure we have access to the data log_lik function conditioned on the posterior sample for pystan, pymc3, tensorflow probability etc). 

I think it might be simpler to always require the data log_lik and have a unified loo etc computation

**Comment by ahartikainen** [comment]
This is now implemented.
