### ISSUE TITLE
Spacing of subplots is too small, titles of subplots overlap with tick labels

### ISSUE THREAD

**Issue by corneliusroemer** [arviz-devs/arviz#1955]
**Describe the bug**
Whenever I make an arviz plot using `az.plot_trace(data,compact=True)` the title of subplots overlap with tick labels of the respective subplot above.

See plot below, the spacing between subplots seems wrong, don't know why:
![hierarchical_numpyro_trace](https://user-images.githubusercontent.com/25161793/147490316-5af98a94-659c-4263-b31d-54d4af6d0d07.png)

**Additional context**
arviz 0.11.4
macOS 12.1
Python 3.10.1
IPython 7.30.1
VSCode 1.63.2

**Comment by ahartikainen** [comment]
Hi could you check what matplotlib version do you have?

I think there are couple of ways to handle that situation

Old one was to call 

    plt.tight_layout()

But I think that is not recommended (and could fail from time to time).

I think current correct way is to call `constrained_layout` or something similar, but I don't remember what it was. (cc @OriolAbril )

**Comment by corneliusroemer** [comment]
Sorry, I forgot to mention:
`matplotlib=3.5.1=py310h2ec42d9_0`

Sweet, `plt.tight_layout()` works, but it's a bit of a shame that it needs to be called manually.

**Comment by OriolAbril** [comment]
I think you'll want to use `constrained_layout` which can be set as an rcParam that is then used for all plots. Here is the relevant guide: https://matplotlib.org/stable/tutorials/intermediate/constrainedlayout_guide.html. If you are using a custom style, you can add that to the style too, or consider using [one of the styles provided by arviz](https://arviz-devs.github.io/arviz/examples/styles.html). `arviz-white` for example is very similar to matplotlib default theme but with constrained_layout set to true, bigger text and a colorblind friendly color cycle. Here is the [source](https://github.com/arviz-devs/arviz/blob/main/arviz/plots/styles/arviz-white.mplstyle) if you want to check exactly what is modified.

**Comment by corneliusroemer** [comment]
Thanks for the tips!

Is there a reason why I need to custom set these parameters? Are my defaults messed up for some reason or does every user have to do this?

If it's just me, then we can close this issue, but if it affects others, would it be possible to fix this within arviz?

**Comment by OriolAbril** [comment]
constrained layout is still experimental so matplotlib doesn't set it to true as a default (yet?). I'm not sure there is a way to fix this within ArviZ. We do provide those opinionated extra themes, but we rely on matplotlib styles so using those changes the look of any matplotlib/seaborn/... plot, so loading one of those at import on our side would probably be confusing. plots would change appearance with no apparent reason to many users importing arviz. 

we have some ideas for new pages in the documentation related to plotting (https://github.com/arviz-devs/arviz/issues/1488) covering how to overlay plots for example. we could have a section on constrained_layout/tight_layout. Or maybe faq page with common questions on plotting, stats, inferencedata...?

**Comment by corneliusroemer** [comment]
Thanks for explaining. I guess at least there's now an issue that people can find if they google "labels smash into each other when plotting with arviz" or something like this.

**Comment by ahartikainen** [comment]
I'm not 100% sure, but I think also OS and backend has some affect which settings are on by default. (e.g. I don't think I have that problem by default)
