### ISSUE TITLE
Setting coords on data vars in InferenceData

### ISSUE THREAD

**Issue by sokol11** [arviz-devs/arviz#1959]
Hi. I am trying to assign the time index for my data, after creating an InferenceData object from a dict of numpyro samples, like so:
```
idata = az.from_dict(posterior_predictive=samples_predictive)
```
The resulting object is:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/35613945/148697354-dec15039-9aa6-47b9-a7a7-95a7a63eba7d.png">

When I try to manually set the `time` coord, like `idata = idata.assign_coords({'time': time_index.values})`, I get:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/35613945/148697542-1bcc949a-9659-4b32-9cec-1a4c16a82b76.png">

However, the set time coord does not propagate to variable `y`, which I need for downstream functionality, e.g., plotting `y` vs. `time`.

Any help or clarification would be greatly appreciated. Thank you!

**Comment by hardik-bit** [comment]
I want to Contribute 
Please someone guide me

**Comment by ahartikainen** [comment]
Have you tried checking https://arviz-devs.github.io/arviz/getting_started/CreatingInferenceData.html

I think you need to update your input dimensions (chain, draw, time) so in your case create a new first dimension before creating idata.

    az.from_dict(arr[None, ...])

Also I recommend adding time coord and dim in this step

**Comment by sokol11** [comment]
Thanks @ahartikainen . Yep, I figured out how to specify it between the Arviz and Xarray docs. Closing this.
