### ISSUE TITLE
Update documentation for InferenceData

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#196]
A lot of the docstrings read 

>     data : xarray, or object that can be converted (pystan or pymc3 draws)
>       Posterior samples

but I believe this should be changed to 
>    data : xarray, or object that can be converted InferenceData

https://github.com/arviz-devs/arviz/blob/master/arviz/plots/posteriorplot.py#L18

**Comment by ColCarroll** [comment]
Yeah, maybe with "see `convert_to_inference_data` for details" or similar

**Comment by canyon289** [comment]
I'll wait for https://github.com/arviz-devs/arviz/pull/198 to merge before working on this!

**Comment by canyon289** [comment]
Closed by https://github.com/arviz-devs/arviz/pull/257
