### ISSUE TITLE
Use lru_cache

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#197]
I think `lru_cache` with suitable default memory limit could be good idea.

Let's assume, user is working with bare fit/trace objects and does multiple different /same plots, removing them and redoing them again.

Some functions are in really heavy use, e.g. transforming object to Inference object, calculation of summary values.

Also probably some plots could benefit from `lru_cache`, so "interactive" creation and destroying would be faster.

We would also need a setting to turn it off and change the memory limits.

https://docs.python.org/3/library/functools.html

**Comment by MFreidank** [comment]
Is someone already working on this? I have an idea on how to implement it and would start, if the interest is still there and it is not already half-implemented by someone.

**Comment by canyon289** [comment]
I don't believe anyone is working on this

**Comment by ahartikainen** [comment]
Yes, you can work with this.

**Comment by MFreidank** [comment]
I have started to work on this. I will soon open a PR to facilitate talking about design decisions for this feature.

**Comment by kyleabeauchamp** [comment]
Have we done any benchmarking?  E.g., I wonder if we ought to do benchmarking before optimization.

**Comment by aloctavodia** [comment]
Any update on this?

**Comment by rohitsanj** [comment]
@aloctavodia @OriolAbril 
I'd like to look into this issue.

I think it is a great idea to use `lru_cache` to speed up repetitive func calls.

**Comment by aloctavodia** [comment]
Any update on this?

**Comment by ahartikainen** [comment]
I think lru_cache is not something we really need. Usually fjnction is called once per data and mcmc data changes from sample to sample
