### ISSUE TITLE
`plot_pair` marginals have inconsistent axes

### ISSUE THREAD

**Issue by wm1995** [arviz-devs/arviz#1981]
**Describe the bug**
When plotting a `plot_pair` with marginal distributions, the tick marks do not fall in locations consistent with the joint distribution plots beneath, and there are no axis labels so it's impossible to tell what the marginal should look like. If the axes are generated using `plt.subplots` with `sharex='col'`, the axis tick marks are aligned correctly, but all of the labels are absent.

**To Reproduce**
```python
import arviz as az
import matplotlib.pyplot as plt
import numpy as np

# Generate some random data from a multivariate normal
rng = np.random.default_rng(42)
data = rng.multivariate_normal([0, 0, 0], cov=np.diag([0.1, 1, 1]), size=(1, 2000))

# Naive plot_pair
az.plot_pair(data, kind="kde", marginals=True)
plt.savefig("naive.png")

# plot_pair with shared x axis in each column
fig, ax = plt.subplots(3, 3, sharex="col")
az.plot_pair(data, kind="kde", marginals=True, ax=ax)
plt.savefig("sharex.png")
```

The first plot has inconsistent x axes between the joint distribution plots and the marginal distribution plots - note how the tick marks are displaced in the leftmost and central marginal distribution plots relative to the joint plots beneath them:
![naive.png](https://user-images.githubusercontent.com/30499074/154265594-089955cf-90e3-49ff-bc49-0984d109353d.png)

The second plot has consistent x axes but no x axis labels:
![sharex.png](https://user-images.githubusercontent.com/30499074/154265600-9f8a64bd-2c13-4528-a773-811b910db655.png)

**Expected behavior**
I'd expect the first plot to have consistent axes for all subplots including the marginals, or at least provide axis labels for the subplots that have different axes. I'd definitely expect the second result to not get rid of axis labels.

**Additional context**
```
# pip freeze
arviz @ git+https://github.com/arviz-devs/arviz@5af74712950c99d486cc0f62db66537670e3bfcc
black==22.1.0
cftime==1.5.2
click==8.0.3
cycler==0.11.0
fonttools==4.29.1
kiwisolver==1.3.2
matplotlib==3.5.1
mypy-extensions==0.4.3
netCDF4==1.5.8
numpy==1.22.2
packaging==21.3
pandas==1.4.1
pathspec==0.9.0
Pillow==9.0.1
platformdirs==2.5.0
pyparsing==3.0.7
python-dateutil==2.8.2
pytz==2021.3
scipy==1.8.0
six==1.16.0
tomli==2.0.1
typing-extensions==3.10.0.2
xarray==0.21.1
```
Running Python 3.10.1 on macOS Monterey 12.1

I'd be happy to contribute to a PR to fix this, but I couldn't find where the issue lies on a cursory scan of the source code, so I'd probably need a nudge or two in the right direction from someone more experienced.

As an aside, I'd argue that the y axis on marginal distributions shouldn't have ticks/tick labels, as it's only the relative height that is important - cf. [corner.py](https://corner.readthedocs.io/en/latest/pages/quickstart.html) or [GetDist](https://getdist.readthedocs.io/en/latest/plot_gallery.html) - but that's a separate matter.

**Comment by wm1995** [comment]
I've identified [the lines of code](https://github.com/arviz-devs/arviz/blob/9d74000d3d0a1599b017a5dc612388a0663d2f36/arviz/plots/backends/matplotlib/pairplot.py#L327-L338) that cause this issue in matplotlib - more than happy to submit a PR to fix this if it's desired, just give me the go-ahead and I'll start working on it.

**Comment by wm1995** [comment]
I also checked whether this was an issue in bokeh but there's no similar `sharex` argument (as far as I can see), and by default all axes labels are shown in bokeh.

**Comment by ahartikainen** [comment]
For bokeh axis can be synced manually.

**Comment by wm1995** [comment]
I've gone ahead and started on a PR to fix this, partly because I have the time at the moment and partly in the interest of resolving the issue quickly.
