### ISSUE TITLE
Nominating ndmlny-qs for Recurrent Contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1982]
I'd like to nominate @ndmlny-qs to be a recurrent contributor at ArviZ. 

Per our rules in the [governance doc](https://arviz-governance.readthedocs.io/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process) let us know if you accept the nomination. Assuming acceptance there will be a [council vote](https://arviz-governance.readthedocs.io/en/latest/governance/processes.html#voting-process) afterwards. 

As the recurrent contributor role is new, here is the [link](https://arviz-governance.readthedocs.io/en/latest/governance/community_architecture.html#recurrent-contributor-description) to its description. Given how @ndmlny-qs together with @zaxtax is working on bokeh dashboards with ArviZ and how to integrate them with ArviZ itself, I think we should add them as recurrent contributors to coordinate our work on this end.

Note: I noticed you don't have your name in your github profile. We list contributors in the [website](https://arviz-governance.readthedocs.io/en/latest/our_team.html#recurrent-contributors), let us know if you prefer we use your github handle or your name.

**Comment by ndmlny-qs** [comment]
I've updated my profile with my name, and I accept the nomination.

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome! 

Can you reach out to `arvizdevs (at) gmail (dot) com` with the email you'd like us to use when adding you to the ArviZ slack?
