### ISSUE TITLE
Nominating Ero for Recurrent Contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1983]
I'd like to nominate @erocarrera to be a recurrent contributor at ArviZ. 

Per our rules in the [governance doc](https://arviz-governance.readthedocs.io/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process) let us know if you accept the nomination. Assuming acceptance there will be a [council vote](https://arviz-governance.readthedocs.io/en/latest/governance/processes.html#voting-process) afterwards. 

As the recurrent contributor role is new, here is the [link](https://arviz-governance.readthedocs.io/en/latest/governance/community_architecture.html#recurrent-contributor-description) to its description. They have been quite active lately and I think it would be interesting to coordinate via slack, especially on pystan/cmdstanpy converters and documentation.

**Comment by erocarrera** [comment]
Thank you @OriolAbril, I accept the nomination.

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome! 

Can you reach out to `arvizdevs (at) gmail (dot) com` with the email you'd like us to use when adding you to the ArviZ slack?
