### ISSUE TITLE
Error in az.plot_lm  y_model_mean_kwargs is not an argument

### ISSUE THREAD

**Issue by I-Mohiuddin** [arviz-devs/arviz#1991]
Version: 0.11.4
starting in the example that is on the examples page:

```
idata = az.load_arviz_data('regression1d')
x = xr.DataArray(np.linspace(0, 1, 100))
idata.posterior["y_model"] = idata.posterior["intercept"] + idata.posterior["slope"]*x
az.plot_lm(
    idata=idata, y="y", x=x, y_model="y_model", kind_pp="hdi", kind_model="hdi"
)
```

Despite trying several times, there is no way to change the line from the gold color that it chooses as a default.
I imagine that this is something that would be controlled via the `y_model_mean_kwargs` argument, but on my version of 0.11.4 this is not within the list of kwargs.

Inspecting the function:  

```
inspect.getfullargspec(az.plot_lm)
```
yields 
args=['y', 'idata', 'x', 'y_model', 'y_hat', 'num_samples', 'kind_pp', 'kind_model', 'xjitter', 'plot_dim', 'backend', 'y_kwargs', 'y_hat_plot_kwargs', 'y_hat_fill_kwargs', 'y_model_plot_kwargs', 'y_model_fill_kwargs', 'backend_kwargs', 'show', 'figsize', 'textsize', 'axes', 'legend', 'grid']

**Comment by ahartikainen** [comment]
Hi, it is probably in our github but not updated yet to pypi.

Do

    pip install git+https://github.com/arviz-devs/arviz

**Comment by OriolAbril** [comment]
`y_model_mean_kwargs` was added in 0.12.0:

* https://python.arviz.org/en/v0.12.0/api/generated/arviz.plot_lm.html has the keyword documented
* https://python.arviz.org/en/v0.11.4/api/generated/arviz.plot_lm.html does not list it.

The docs with the `latest` flag don't match any version on pypi but the development version in GitHub.
