### ISSUE TITLE
arviz.concat fails if a variable is named "shift"

### ISSUE THREAD

**Issue by jt-lab** [arviz-devs/arviz#1993]
**Describe the bug**
If I concatenate two traces, arviz.concat fails if a variable is named "shift" with the error message:
"'function' object has no attribute 'dims'". 

I have traced the issue down to the following problem: concat uses getattr(group_data, var).dims to get the dimensions of variables. Apparently the group_data object contains a method called "shift" and instead of the variable this method is returned by getattr.

Once I rename my variable to something else, it works.

Since "shift" is not an unlikely name for a variable, it might be good to have something to safeguard against this. Perhaps data groups have further functions that could conflict with other variable names.

**To Reproduce**
To reproduce, concatenate two InferenceData objects that contain a variable named "shift".

**Expected behavior**
Successful concatenation of InferenceData regardless the name of the variables.

**Additional context**
Arviz 0.11.2

**Comment by ahartikainen** [comment]
Hi,

yeah, sounds like a bug.

I think we should change our code a bit to fix this.

https://github.com/arviz-devs/arviz/blob/4544dd0bceb2d85496d3ff962db009f93abfa768/arviz/data/inference_data.py#L1995

**Comment by jt-lab** [comment]
I have already thought about how to handle this but have no good idea so far.
Prepending any variable names internally with some string before concatenating could work. Or perhaps making sure the data group's functions have uncritical names (but perhaps they inherit some). Using another mechanism to access attributes that can ignore functions would be great.

**Comment by OriolAbril** [comment]
does `group_data[var].dims` work? I think the issue is that getattr is not the way to subset variables in a dataset and fails if the variable has the same name as one of its methods (I'd expect the same to happen for `mean`, `quantile`, `dims`... which should all be valid variable names from the xarray side)

**Comment by jt-lab** [comment]
Yes, `group_data[var].dims` works. Was there a reason to use `getattr` in the first place? Is it faster?

**Comment by ahartikainen** [comment]
No real reason (just a bad habid), looking a git blame I see myself there so :D

**Comment by OriolAbril** [comment]
I might have been a lapsus between dataset variable retrieval and inferencedata group retrieval, especially with the attr retrieval some lines below. Not sure speed is relevant on this operation, we have many other places where we should look at optimizations before considering any analysis or benchmark here

**Comment by OriolAbril** [comment]
I see now @ahartikainen already answered, @jt-lab do you want to send a PR with the fix?

**Comment by jt-lab** [comment]
OK!
