### ISSUE TITLE
Specify Sample Size a Bit More Clearly 

### ISSUE THREAD

**Issue by ParadaCarleton** [arviz-devs/arviz#2000]
The current phrasing contains the same information but is a bit harder to interpret:
```
Computed from 4000 by 262 log-likelihood matrix
```
ParetoSmooth.jl is more explicit about this, with a phrasing that mentions "n observations and m posterior samples." I've found this prevents mistakes -- it's very common for users to accidentally misspecify what it is they want to leave out, e.g. by placing all their observations in one multivariate normal, which causes confusion when the whole dataset is left out. I think this might be a more useful message.

**Comment by OriolAbril** [comment]
Sounds good, do you want to open a PR with the fix? 

You'll need to update https://github.com/arviz-devs/arviz/blob/eadc170082340a20939b2a0ebc75bdba7e43abc8/arviz/stats/stats_utils.py#L442, I don't think we have test covering the specific wording, but if something fails in CI we can update it later.

**Comment by elusenji** [comment]
Just got started with open source contribution- if this is still open, I'd love to work on this.

**Comment by OriolAbril** [comment]
That would be great @elusenji, it is still open!

**Comment by elusenji** [comment]
Great! I noticed the link to the 'development workflow' under the 'contribution guidelines' seems broken. Is it supposed to point [here?](https://python.arviz.org/en/latest/contributing/contributing_prs.html)

**Comment by OriolAbril** [comment]
> I noticed the link to the 'development workflow' under the 'contribution guidelines' seems broken. Is it supposed to point [here?](https://python.arviz.org/en/latest/contributing/contributing_prs.html)

I think so, not really sure what was the message trying to be sent there. The main and most important message is go to the docs: https://python.arviz.org/en/latest/contributing and subsections inside there (available from the left sidebar) depending on your needs.

**Comment by yanhong-zhao-ef** [comment]
Stumbled upon this issue but this seems to be fixed already @OriolAbril please close issue
