### ISSUE TITLE
Changing the order of plotting and file load seems to cause netcdf errors

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#202]
For some reason it seems that changing the order of plotting and loading data causes failures, not entirely sure why yet. This is only occurring for me on Ubuntu 16.04 with the latest version of arviz. It does not occur on my osx laptop

Load, Load, Plot, Plot doesn't work. Stack trace attached
[stack_trace.txt](https://github.com/arviz-devs/arviz/files/2349232/stack_trace.txt)

```
import arviz as az
az.style.use('arviz-darkgrid')

non_centered = az.load_arviz_data('non_centered_eight')
centered = az.load_arviz_data('centered_eight')
az.violintraceplot(non_centered, var_names=["mu", "tau"], textsize=8)
az.violintraceplot(centered, var_names=["mu", "tau"], textsize=8)
```

Load, Plot, Load, Plot works

```
import arviz as az
az.style.use('arviz-darkgrid')

non_centered = az.load_arviz_data('non_centered_eight')
az.violintraceplot(non_centered, var_names=["mu", "tau"], textsize=8)

centered = az.load_arviz_data('centered_eight')
az.violintraceplot(centered, var_names=["mu", "tau"], textsize=8)
```

**Comment by canyon289** [comment]
I've been debugging using this command. Would debug more but also need to run to work :(

> strace -e trace=open,close,read,write,connect, -o violinplot.txt  python violinplot.py

By searching for strings like */home/testuser/repos/arviz/arviz/data/non_centered_eight.nc"* its easier to see where the program is at before failures stat happening

Sample log attached
[violinplot.txt](https://github.com/arviz-devs/arviz/files/2349131/violinplot.txt)

**Comment by ColCarroll** [comment]
Any suggestions @shoyer (we can also open a similar issue there if that is helpful)?

For a little context, `az.load_arviz_data` is calling 

```
xarray.open_dataset(filename=filename, group=group, autoclose=True)
```

There is also an iterator that ends up throwing the exception [here](https://github.com/arviz-devs/arviz/blob/master/arviz/plots/plot_utils.py#L162), which "flattens" an xarray dataset over dimensions and variables.

**Comment by shoyer** [comment]
Please file an xarray bug if you can reduce this to a minimal reproducible example.

The only thing in xarray that should change if you alter the order of variables in a netCDF file is the order over which it is iterated.
