### ISSUE TITLE
Make netcdf4 dependency optional

### ISSUE THREAD

**Issue by twiecki** [arviz-devs/arviz#2028]
netcdf is used in only two methods (loading and saving to netcdf) and is a heavier dependency, could we make that optional?

background: I'm playing around with pyscript and the netcdf4 dependency makes arviz not work with micropip.

**Comment by ColCarroll** [comment]
Isn't it transitively pulled in by xarray?

**Comment by twiecki** [comment]
@ColCarroll it doesn't seem to be a dependency of xarray either (and it's not used for creating an `InferenceData` object.

**Comment by twiecki** [comment]
It's only in extras: https://github.com/pydata/xarray/blob/main/setup.cfg#L84

**Comment by OriolAbril** [comment]
> could we make that optional?

Yes, it is possible and should not be too complicated. 

It is also part of the longish term plan too already: making arviz have most dependencies as optional or even splitting the library in data+stats+plots. It should not be necessary to install netcdf if you want to use zarr to serialize the files nor if you don't want to serialize them at all, the same with matplotlib/bokeh or if you don't want to plot (i.e. run a model in cloud and save results only, then download and analyze locally, or pymc ci for example probably doesn't need matplotlib either)

**Comment by twiecki** [comment]
The main motivation here was to be able to install arviz through pyodide, with #2122 this seems possible now, so closing.
