### ISSUE TITLE
plot_dot 

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#2031]
**Describe the bug**
plotdot fig size doesn't behave the way I expect, in that when I set `figsize` in an axes that triple a previous one its not triple the size. There also are some minor bugs where the dots seem to be overlapping some

**To Reproduce**
```
samples = stats.beta(2,2).rvs(100)

width = 10
fig, ax = plt.subplots(figsize=(width, 10))
az.plot_dot(samples, ax=ax)
ax.set_title(f"Width: {width}")
ax.set_xlim(0,1)
```

Then try this, but see that figure is not three times the width
```
width = 30
fig, ax = plt.subplots(figsize=(width, 10))
az.plot_dot(samples, ax=ax)
ax.set_title(f"Width: {width}")
ax.set_xlim(0,1)
```

![image](https://user-images.githubusercontent.com/7213793/168452674-b1a38bf9-db25-459e-85b0-cd61348283cd.png)
![image](https://user-images.githubusercontent.com/7213793/168452677-1410fd7b-7208-4045-ac8d-cbc52c0595dd.png)

**Expected behavior**
Figsize from `plt.subplots` is respected

**Additional context**
Arviz '0.12.0'

**Comment by sethaxen** [comment]
The overlapping stacks appears to be an issue with `wilkinson_algorithm`:

```python
>>> values = stats.beta(2,2).rvs(100)

>>> values.sort()

>>> binwidth = 0.07

>>> stack_locs, stack_count = az.plots.dotplot.wilkinson_algorithm(values, binwidth)

>>> np.diff(stack_locs) > binwidth  # should all be True
array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False])
```

**Comment by sethaxen** [comment]
Ah, okay, overlapping stacks is actually not a bug. This is possible and intended behavior. e.g. suppose we have the data `[1, 1.9, 2.1, 2.1, 3.2]` and use a `binwidth=1`. Then the bins would be `[[1, 1.9], [2.1, 2.1], [3.2]]`, the bin centers would be `[1.45, 2.1, 3.2]`, and the bin edges would be `[[0.95, 1.95], [1.6, 2.6], [2.7, 3.7]]`, so the first and second stacks will overlap. Not allowing overlap would require the first or second stack be further from the underlying data.

This is how `ggplot2::geom_dotplot` behaves:

```R
> x <- c(1, 1.9, 2.1, 2.1, 3.2)
> df <- data.frame(x)
> ggplot(df, aes(x=x)) + geom_dotplot(binwidth=1)
```
![tmp](https://user-images.githubusercontent.com/8673634/168462211-6609ecf9-9ecd-4aa1-b99b-835c21570b86.png)

**Comment by ahartikainen** [comment]
Good to know this. Then PR should only fix aspect

**Comment by canyon289** [comment]
Wow what an indepth analysis. Thanks @sethaxen
