### ISSUE TITLE
Latex label compatibility issues while using Bokeh as backend

### ISSUE THREAD

**Issue by Huzaifg** [arviz-devs/arviz#2042]
**Describe the bug**
I want to use latex for my labels and so I use the following line of code.
```
import arviz.labels as azl
labeller = azl.MapLabeller(var_name_map={"Cxf": r"$\C_{xf}$","Cxr": r"$C_{xr}$"})
`
```
However, when I plot the posterior using "Bokeh" as backend using 
`ax_post = az.plot_posterior(idata,backend = "Bokeh",figsize = (12,8),labeller=labeller)`
I get this 
![bug_post](https://user-images.githubusercontent.com/64803446/172056370-adc405d8-d1a4-4960-ad61-b59b9406601b.png)

**To Reproduce**
The bug can be reproduced with the attached data file and the above lines of code. 
https://drive.google.com/file/d/1Kld1u4VaGWYVz5Yq9GClUFaGDhFIfLhF/view?usp=sharing

**Expected behavior**
This problem does not exist when I use matplotlib as my backend. See plots below
![bug2_post](https://user-images.githubusercontent.com/64803446/172056162-be032b66-b9f0-49c0-92c0-c7547d537266.png)

**Additional context**
arviz version - 0.12.0
bokeh version - 2.4.2

**Comment by ahartikainen** [comment]
Hi,

This is a good question. I'm not sure how supports latex. Maybe we should first find out is there a way to use it with bare bokeh.

(You can probably even access bokeh figure object from arviz return and try with it)

**Comment by OriolAbril** [comment]
I think for latex in bokeh you need to use different delimiters like double dollar sign. Can you try it?

More info at https://docs.bokeh.org/en/2.4.3/docs/user_guide/styling.html#latex

**Comment by ahartikainen** [comment]
https://docs.bokeh.org/en/latest/docs/user_guide/styling.html?highlight=latex#adding-mathematical-notations

**Comment by Huzaifg** [comment]
Thank you for the speedy response @OriolAbril and @ahartikainen. 
Seems like using `$$ $$` dosent work as well. The following code
```
labeller = azl.MapLabeller(var_name_map={"Cxf": r"$$C_{xf}$$","Cxr": r"$$C_{xr}$$"})
ax_post = az.plot_posterior(idata,figsize = (8,6),backend = "Bokeh",var_names = ['Cxf','Cxr'],labeller=labeller)
```
gives
![bug2](https://user-images.githubusercontent.com/64803446/172086971-420a72e4-968e-4deb-b7cb-8949fb39c667.png)
Same with the other delimiter options as well. 
1) Using `\(\)` 
Line of code
```
labeller = azl.MapLabeller(var_name_map={"Cxf": r"\(C_{xf}\)","Cxr": r"\(C_{xr}\)"})
ax_post = az.plot_posterior(idata,figsize = (8,6),backend = "Bokeh",var_names = ['Cxf','Cxr'],labeller=labeller)
```
gives 
![bug3](https://user-images.githubusercontent.com/64803446/172087123-721fa0c5-4392-49da-986c-f59a0a45d407.png)

2) Using `\[\]` 
Line of code
```
labeller = azl.MapLabeller(var_name_map={"Cxf": r"\[C_{xf}\]","Cxr": r"\[C_{xr}\]"})
ax_post = az.plot_posterior(idata,figsize = (8,6),backend = "Bokeh",var_names = ['Cxf','Cxr'],labeller=labeller)
```
gives
![bug4](https://user-images.githubusercontent.com/64803446/172087204-265a6b9a-97b9-4b1e-973d-c14ce355eee1.png)

However, I think this is more of a problem with bare Bokeh as @ahartikainen  suggested. See example below:
```
from bokeh.plotting import figure, show
labeller = azl.MapLabeller(var_name_map={"Cxf": r"\[C_{xf}\]","Cxr": r"\[C_{xr}\]"})
ax_post = az.plot_posterior(idata,figsize = (8,6),backend = "Bokeh",var_names = ['Cxf','Cxr'],labeller=labeller)
p = ax_post[0][0] #get figure object of left subplot
p.title = r"\(C_{xf}\)" #change its title 
show(p)
```
produces 
![Screenshot from 2022-06-05 22-07-18](https://user-images.githubusercontent.com/64803446/172087909-35c58f26-8c92-47d6-9f9c-9174db7b1081.png)
Will probably open an issue there. Thanks for all your help!

**Comment by OriolAbril** [comment]
Do the examples from https://docs.bokeh.org/en/2.4.3/docs/user_guide/styling.html#latex work for you when you execute them locally?

**Comment by Huzaifg** [comment]
Hmm. Surprisingly all the examples from the link work. Does that mean its something to do with arviz's handling of bokeh figures?

**Comment by Huzaifg** [comment]
Has there been any solution for this?

**Comment by OriolAbril** [comment]
@agustinaarroyuelo and I (but mostly Agustina) investigated the issue. Bokeh 2.x only supports latex rendering on the elements explicitly listed in [the documentation](). That is:

> _(emphasis mine)_ Currently, you can use LaTeX and MathML notations with **axis labels** and **tick labels** using major_label_overrides(). You can also use LaTeX with **div** or **paragraph** widgets.

The examples in the docs restrict to these elements, but in your case you want to use latex rendering in a Title element, which doesn't work. 

This has already been fixed in the next release candidate for bokeh 3.0, at least for **Title** and **Label** elements (done in https://github.com/bokeh/bokeh/pull/11708), but as bokeh 3.0 is still at the release candidate stage, you'll need to do `pip install bokeh --pre` to try it out. It is also a major version which probably has some backward incompatible changes, so some of the bokeh code in ArviZ might not work with it. I will be closing the issue as it is nothing to be fixed on our side, but feel free to let us know how it goes if you try this. We'll test ArviZ with bokeh 3.0 once the api is final and a release is made.
