### ISSUE TITLE
`plot_ppc` modifies `coords` argument

### ISSUE THREAD

**Issue by erocarrera** [arviz-devs/arviz#2047]
If this is the expected behavior it'd probably be good to mention it in the docstring. However I am inclined to think that the dictionary passed as `coords` should be left unmodified, it seems to be the behavior of a handful of `plot_*` functions that I've checked.
https://github.com/arviz-devs/arviz/blob/f4a8d6654328b06e417c6377741c32ef4ee8143d/arviz/plots/ppcplot.py#L298

**Comment by OriolAbril** [comment]
They should not be modified, we should copy them before modifying, like we do with kwargs before we add default values

**Comment by tspeng** [comment]
Hi @erocarrera and @OriolAbril, I am a new contributor. Based on your suggestions, I think it could be fixed by modifying the if statement in lines 270-271, so the original mutable object coords will not be modified. Since line 298 is an assignment operation, shallow copy should be enough.

    if coords is None:
        coords = {}
    else:
        coords = coords.copy()

**Comment by OriolAbril** [comment]
Yes,  that sounds good,  thanks!
