### ISSUE TITLE
Supporting multiple posterior predictive draws for each posterior draw

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#2048]
For each posterior draw $n \in \{1, \ldots, N\}$, a user may want to generate and store $M$ posterior predictive draws in `InferenceData`. To support this, we should:
- decide how these should be stored, e.g. probably the $M$ draws should be stored as an additional dimension, but should we specify the name of that dimension?
- make sure that all functions that use posterior predictive draws do the right thing. In some cases, this might mean using one of the draws for each posterior draw and warning the user. In other cases, this might mean plotting all draws by default and allowing the user to select a subset of the draws to plot. In other cases, it might mean averaging over the draws.

**Comment by OriolAbril** [comment]
Echoing my comments on slack. Very much agree with this, and with `combine_dims` it won't generally be an issue for plots. It will be for loo_pit though. 

Do you have a proposal for the name?
