### ISSUE TITLE
Turn off dark mode default in docs

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#2051]
**Describe the bug**
The docs don't look good in dark mode. Is there some setting to ensure it defaults to light mode initially?
![image](https://user-images.githubusercontent.com/7213793/174446804-3b241001-d482-4a47-bf46-59ba9df988c0.png)

**To Reproduce**
I'm not sure but I'm thinking its reading from my system or browser setting

**Expected behavior**
Light mode always

**Additional context**
Versions of `arviz` and other libraries used, operating system used, and anything else that may be useful.

**Comment by Autoclitic** [comment]
https://github.com/pydata/pydata-sphinx-theme/issues/458

The same question was issued here, and the commenter mentioned changing the html_context for the sphinx setup:
```html_context = {
   # ...
   "default_mode": "light"
}```

**Comment by OriolAbril** [comment]
We should pin the pydata-sphinx-theme to `<0.9.0` in https://github.com/arviz-devs/arviz/blob/main/requirements-docs.txt. 

The introduction of the dark theme (which defaults to whatever theme your browser is using but can be changed as pointed out by @Autoclitic and as explained in [the theme docs](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#configure-default-mode)) is quite secondary imo. The version has also changed how the layout works, so our trick from https://github.com/arviz-devs/arviz/blob/main/doc/_templates/layout.html no longer works, both sidebars appear and overlay with the content of the homepage which looks awful in both modes.

I think we should pin the theme and then whenever we can open a PR to update the `layout` trick to remove all sidebars from the homepage
