### ISSUE TITLE
plot_ppc  no different colors for posterior predictive and the mean

### ISSUE THREAD

**Issue by tigerbine** [arviz-devs/arviz#2063]
**Describe the bug**
plot_ppc shows the posterior predictive mean in blue color (instead of orange)

**To Reproduce**
az.plot_ppc(data_ppc, data_pairs={"y":"y"})
same problem as noted here: https://discourse.pymc.io/t/plot-ppc-with-multiple-colors/8449

**Expected behavior**
plot should look like in the examples of https://python.arviz.org/en/latest/api/generated/arviz.plot_ppc.html#arviz.plot_ppc

**Additional context**
- Ubuntu
- conda 4.13.0
- Python 3.8.13,
- pymc3
- arviz 0.12.1

**Comment by OriolAbril** [comment]
What matplotlib style are you using?

The plots in the docs are generated executing the code every time the documentation is built (with every commit to the library). The defaults for `plot_ppc` colors are `C0, k, C1`, that is, the first color of the matplotlib default color cycle, black and the 2nd color in the matplotlib default color cycle.

**Comment by OriolAbril** [comment]
@tigerbine we haven't been able to reproduce the issue and it continues to work in the docs. We'll close this, feel free to reopen if you have a reproducible example.
