### ISSUE TITLE
Remove deprecated arguments from `plot_pair()`

### ISSUE THREAD

**Issue by agustinaarroyuelo** [arviz-devs/arviz#2073]
`plot_kwargs` is an argument of `plot_pair()` yet it is not described in the [documentation](https://python.arviz.org/en/latest/api/generated/arviz.plot_pair.html#arviz.plot_pair) for this function.

**To Reproduce**
Go to the link and search for the description of `plot_kwargs`

**Expected behavior**
A complete docstring were `plot_kwargs` usage and behaviour is described.

**Comment by OriolAbril** [comment]
It might also be possible it is not even used at all, in which case it should be removed instead of documented

**Comment by agustinaarroyuelo** [comment]
You are right, we planned to deprecate `plot_kwargs` (see [here](https://github.com/arviz-devs/arviz/blob/161eb5f9d2acc8680bca62cb5e8f5a6565d0c9d6/arviz/plots/pairplot.py#L196)) Maybe we can move forward with it instead of documenting

**Comment by OriolAbril** [comment]
Let's remove it then and update the issue to remove the deprecated arguments in plot_pair. I am also adding it to the v0.13 milestone.
