### ISSUE TITLE
`compare` weight miscalculation

### ISSUE THREAD

**Issue by cfonnesbeck** [arviz-devs/arviz#2077]
I'm comparing 2 models that have very similar LOO/WAIC values (dLOO of only 0.14), yet the weights end up being zero and one for the worse and better model, respectively:

<img width="876" alt="Screen Shot 2022-07-27 at 2 30 31 PM" src="https://user-images.githubusercontent.com/96543055/181356431-1c978994-ea20-4f53-8c26-fc4445b55018.png">

The same thing occurs for WAIC.

So, it appears that the weight is being miscalculated somehow.

For a reproducible example:

```python
import arviz as az
model_compare = az.compare({'Centered 8 schools': az.load_arviz_data('centered_eight'),
                 'Non-centered 8 schools': az.load_arviz_data('non_centered_eight')})
model_compare
```
Which results in:
<img width="950" alt="Screen Shot 2022-07-27 at 2 35 48 PM" src="https://user-images.githubusercontent.com/96543055/181357189-ba9e6223-7b7b-48c6-bec3-56cf33b970f4.png">

Running version 0.12.1 on MacOS

**Comment by aloctavodia** [comment]
This seems the expected behavior when using stacking as the method to compute weights, if two models make very similar predictions there is no gain into adding the second one to the mix. On the other hand if you use `method="BB-pseudo-BMA"` or `method="pseudo-BMA"`, the weights will be distributed more evenly.

**Comment by OriolAbril** [comment]
Moreover, with stacking it is also possible for the weights to define a different order than the elpd based rank for this same reason. Model 3 alone might be worse than 1 and 2 but if 2 is a subset of 1 it "adds nothing" when averaging models whereas 3 might be more different and thus get a higher weight than 2 as it "adds more" when averaging the models.

**Comment by cfonnesbeck** [comment]
Thanks! I had assumed the weights only depended on the `d_loo`; clearly they do not. I need to read up on it.
