### ISSUE TITLE
Bug: to_netcdf does not save attrs

### ISSUE THREAD

**Issue by twiecki** [arviz-devs/arviz#2109]
When I store meta data in `attrs` and call `to_netcdf()` and then load it subsequently, the meta-data is lost (`attrs` is empty). Is this expected? Is there a format to save this in so that they stay?

**Comment by ahartikainen** [comment]
They should stay.

Which level is the attrs located?

**Comment by ahartikainen** [comment]
I think it is a bug. idata.attrs is never accessed.

I wonder do we need to save the attrs as an empty Dataset with attrs defined.

**Comment by twiecki** [comment]
> I think it is a bug. idata.attrs is never accessed.

How do you mean, never accessed?
