### ISSUE TITLE
Pairplot example should get updated

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#212]
Currently uses old API: https://arviz-devs.github.io/arviz/examples/pairplot.html

Something like this should work, but the gaps between plots is funny:

```python
import arviz as az

az.style.use('arviz-darkgrid')

centered = az.load_arviz_data('centered_eight')
az.pairplot(centered, var_names=['theta'], divergences=True)
```

![image](https://user-images.githubusercontent.com/2295568/45227638-f1679e00-b28e-11e8-906e-a45edd5926da.png)

**Comment by canyon289** [comment]
Working on this
