### ISSUE TITLE
RGB to hexadecimal color code

### ISSUE THREAD

**Issue by Farhan-2222** [arviz-devs/arviz#2128]
## Tell us about it

The more specific the better. You can assume you have access to any combination of datasets defined in the schema. When considering an implementation, keep in mind that

- models in ArviZ can have one, or lots, of random variables,
- each random variable can have very few or millions of draws,
- each random variable can have 0 or many dimensions.
The code doesn't have a RGB to hexadecimal converter. I would like to add it.
## Thoughts on implementation
I will use pure python programming to achieve the target.
Not required, but if you have thoughts on how to implement the feature, that can be helpful! In case there are academic references, we welcome those here too.

**Comment by ahartikainen** [comment]
Hi, we currently use

    from matplotlib.colors import to_hex

Not sure if there is a need for our own implementation.

**Comment by Farhan-2222** [comment]
OK, no problem. Go on with it.
