### ISSUE TITLE
Make exception for invalid coords more user friendly

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#213]
I think it'd be nicer if it suggested to the user they need to fix the coords argument which is hard to suss out from the exception 6 layers deep in the stack

```
import arviz as az
data = az.load_arviz_data('non_centered_eight')
az.traceplot(data, var_names=('theta_t'), coords={'theta_t_dim_0_t': [0, 1]})
```

<img width="1025" alt="screen shot 2018-09-07 at 6 33 02 pm" src="https://user-images.githubusercontent.com/7213793/45248990-488c6380-b2cd-11e8-8833-0560625e06b9.png">

**Comment by ColCarroll** [comment]
Fixed by #236
