### ISSUE TITLE
az.plot_lm() triggers VisibleDeprecationWarning

### ISSUE THREAD

**Issue by mattiasthalen** [arviz-devs/arviz#2139]
**Describe the bug**
Calling `az.plot_lm()` triggers a `VisibleDeprecationWarning`

**To Reproduce**
```python
centered_eight = az.load_arviz_data('centered_eight')
_ = az.plot_lm(idata = centered_eight, y = 'obs')
```

**Expected behavior**
No warnings raised.

**Additional context**
arviz 0.12.1
numpy 1.21.5
python 3.10.4

**Comment by michaelraczycki** [comment]
It's not reproducible, code above produces an error, not a deprecation warning:
<img width="1114" alt="Zrzut ekranu 2023-02-15 o 11 07 39" src="https://user-images.githubusercontent.com/119355382/218997751-a4520f29-0cdd-40f6-bf90-6ec822642143.png">

**Comment by OriolAbril** [comment]
Which numpy version are you using? My first guess would be the deprecation became an error between 1.21 and the version you are using
