### ISSUE TITLE
Renormalization step in `psislw` creating different behaviour to `loo::psis` in R

### ISSUE THREAD

**Issue by cmgoold** [arviz-devs/arviz#2148]
**Describe the bug**
I am not sure if this is a bug or an implementation detail, but `arviz.psislw` results in quite different results to `loo::psis` in R. I have narrowed this down, I believe, to the renormalization step, which in `arviz` is done [here](https://github.com/arviz-devs/arviz/blob/main/arviz/stats/stats.py#L1002) and in `loo` is done [here](https://github.com/stan-dev/loo/blob/master/R/psis.R#L232). 

**To Reproduce**
In Python:

```python
import numpy as np
from arviz.stats import psislw
delta = 0.01
x = np.arange(-10, -1 + delta, delta)
lw, _ = psislw(x, reff=1)
np.mean(lw)
-9.110043830003992
```

in R:

```r
require(loo)
x <- seq(-10, -1, 0.01)
lw <- psis(x, r_eff=1)
mean(lw$log_weights)
-5.497537
```

In R, if we instead renormalize the weights as it's done in `arviz` by taking the `logsumexp` of the normalized, smoothed weights, then they are largely equivalent:

```r
logsumexp <- function(x){
  xx <- x - max(x)
  return(max(x) + log(sum(exp(xx))))
}

psislw <- lw$log_weights
psislw_normalized <- psislw - max(x)
psislw_logsumexp <- psislw_normalized - logsumexp(psislw_normalized)
mean(psislw_logsumexp)
-9.123375
```

**Expected behavior**
The same outputs for the same inputs, I would have thought, apart from slight differences in the GPD fit. 

**Additional context**
`loo` version 2.5.1 and `arviz` version `0.11.4`. 

As I said, I don't know if this is really a bug. I haven't delved into the math for long enough to decide why they are using different implementations. Is it meant to be `x = x + logsumexp(original_log_weights)`?

**Comment by dehorsley** [comment]
I think the preferred way to access the weights in `loo` is with `weights(lw)`. That indeed gives the same as ArviZ:

with loo v2.6.0:

```R
require(loo)
x <- seq(-10, -1, 0.01)
lw <- psis(x, r_eff=1)
mean(weights(lw)
# [1] -9.123375
pareto_k_values(lw)
# [1] -0.5903575
```

ArviZ v0.14.0
```python
import numpy as np
from arviz.stats import psislw
x = np.linspace(-10,-1,901)
lw, k = psislw(x, reff=1)
np.mean(lw)
# -9.123375053677302
k
# array(-0.59035748)
```

**Comment by OriolAbril** [comment]
I will add a note on the psislw function docstring that the returned log weights are normalized. I think it is a difference in behaviour as the [R loo library](http://mc-stan.org/loo/reference/psis.html#value) has a clearer description of the returned values:

> Vector or matrix of smoothed (and truncated) but unnormalized log weights. To get normalized weights use the [weights()](http://mc-stan.org/loo/reference/weights.importance_sampling.html) method provided for objects of class "psis".
