### ISSUE TITLE
Styling in lmplot

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#2183]
Can we update the basic mpl kws  in arviz/arviz/plots/backends/matplotlib/lmplot.py.

This is such a common operation in modeling and the baseline kws are so visually jarring that I honestly find it  preferable to just do the whole thing in matplotlib manually. 

For example:
```
y_model_mean_kwargs.setdefault("color", "y") 
```
is a  really poor choice in my opinion.  

I think it would be much more aesthetically pleasing if we changed the baseline kws to have the mean line as black 
the y_model fill and the y hat fill to follow some basic color gradient (similar to the the bayesplot color schemes in R).  

Similarly I think setting the marker face color to none, making the marker  size a bit smaller and setting the marker edge color to black would do a lot for improving the utility of the function.

_Originally posted by @I-Mohiuddin in https://github.com/arviz-devs/arviz/issues/2108#issuecomment-1345776489_

**Comment by ColCarroll** [comment]
Thanks for opening an issue -- I'd be happy to review changes that make this look better. I like your suggestions, but I'd love to see a side-by-side comparison. Also, I would suggest changing the explicit colors (`y_model_plot_kwargs.setdefault("color", "k")`, `y_model_fill_kwargs.setdefault("color", "k")`, `y_model_mean_kwargs.setdefault("color", "y")`) to use themed colors (something like `C2` and `C3`), so that users could choose a theme. 

If I had unlimited wishes, I'd also ask for an example added to the example gallery!

**Comment by OriolAbril** [comment]
+1 on using theme colors as defaults. There already is an example in the gallery: https://python.arviz.org/en/stable/examples/plot_lm.html, but a 2nd showing a different style would be very welcome too.

**Comment by arshm06** [comment]
I would like to take this up!

**Comment by tomicapretto** [comment]
Could this be closed because of #2271?

**Comment by ColCarroll** [comment]
thanks for pointing that out -- feel free to reopen @I-Mohiuddin , but thanks to @arshm06 in any case!
