### ISSUE TITLE
Documentation example of plot_lm() method returns Value Error

### ISSUE THREAD

**Issue by channelgrubb** [arviz-devs/arviz#2212]
## Short Description

Following the example for az.plot_lm appears to not work as written and returns a Value Error.

## Code Example or link

I'm following [the example for .plot_lm on the ArviZ documentation](https://python.arviz.org/en/stable/api/generated/arviz.plot_lm.html)

Here is the code taken directly from the documentation:
```
import arviz as az
import numpy as np
import xarray as xr
idata = az.load_arviz_data('regression1d')
x = xr.DataArray(np.linspace(0, 1, 100))
idata.posterior["y_model"] = idata.posterior["intercept"] + idata.posterior["slope"]*x
az.plot_lm(idata=idata, y="y", x=x)
```

This code as written returns the following value error:
```
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.
```
I'm using Arviz version 0.14.0

## Relevant documentation or public examples
+ Link included above is to the ArviZ documentation for the .plot_lm() method

## Other notes
I have verified the data labels per the documentation for the observed data ("y") and the posterior ("y_model"). I have tried to use outputs from other PyMC models to get this plotting method to work but each time I get the same kind of value error

**Comment by OriolAbril** [comment]
Does it still happen with ArviZ 0.15.0?

I think I fixed that but it might be a different error to the one I remember. numpy recently changed its behaviour from casting these types of unhomogeneous arrays to arrays of object dtype with array elements to erroring out.

**Comment by channelgrubb** [comment]
Ah, thanks for the background and the response. Yes, v15.0 resolved the issue!

**Comment by channelgrubb** [comment]
Ah, thanks for the background and the response. Yes, v15.0 resolved the issue!
