### ISSUE TITLE
Regarding GSOC 2023

### ISSUE THREAD

**Issue by MatrixX-X** [arviz-devs/arviz#2221]
HI
I am Abdul Mateen computer science undergrad I have just entered my 4th year. I am new to open-source contributions, but I know python and different visualization libraries. I am interested in arviz dashboard project.
I would love to contribute to your organization but could you please tell me how to get started?
I am not seeing any chat medium for this organization, is this organization active?

**Comment by OriolAbril** [comment]
Hi, if you don't have any familiarity with Bayesian statistics yet I'd recommend starting with git+github (and open source contributions) and Bayes. https://dataorigami.net/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/ or https://bayesiancomputationbook.com/welcome.html can be good resources to get into a Bayesian mindset.

We generally coordinate via Gitter as mentioned in the gsoc idea list, where we have a channel that is dedicated to gsoc (and therefore doesn't get any activity the rest of the year). You should join too if interested, feel free to ask any other questions either here or at gitter (edit while writing, I see you have joined already).

**Comment by MatrixX-X** [comment]
Hi, @OriolAbril 
 I have finished more than half the book you recommended https://www.amazon.in/Bayesian-Methods-Hackers-Probabilistic-Addison-Wesley/dp/0133902838 i have more than a basic idea of Bayesian Model.
I am interested in the arviz dashboards will I be able to do this project
if Yes, than i will start preparing for the proposal, and if no let me what i need to read more and if this project is possible for me
i am willing to learn more, let me know what action i should take
Thanks in advance

**Comment by MatrixX-X** [comment]
@OriolAbril @aloctavodia @ndmlny-qs @ahartikainen 
I have experience in python, NumPy, and SciPy. I am willing to learn the rest to fulfill general requirements.
As for specific requirements, i will look into panel and arviz
could u help me understand the project as in what i have to do in the project besides the dashboard some links, references, and documentation will be helpful.

**Comment by OriolAbril** [comment]
closing as gsoc 2023 already passed
