### ISSUE TITLE
Make Gallery Appealing

### ISSUE THREAD

**Issue by Nancy9ice** [arviz-devs/arviz#2223]
The gallery section as attached to this issue doesn't look appealing on the readme. It's best to show users what Arviz can do by showing the visualizations upfront and making it clickable to direct them to click to go to the documentation on how to create that particular viz. 

## Thoughts on implementation

A thumbnail can be made for each visualisations comprising the gallery. Then it will also be indicated as a subheading that one can click any image to be directed on how to create them with Arviz. I can take my time to do this if it's accepted.

![image](https://user-images.githubusercontent.com/103530451/225063520-0f9f8277-461f-41e9-aba4-7eeea69a256f.png)

**Comment by OriolAbril** [comment]
Is this GitHub? PyPi? Both? We already have thumbnails and they are generated automatically when we build the docs, but we have focused on the website: https://python.arviz.org/en/latest/examples/index.html. You can use these images (it might boil down to fixing the path to the images even).

Seeing the screenshot it might also be nice to add  an extra row to the table with some text along the lines of "and many more..." that links to the example gallery on the website

**Comment by barisAytekin** [comment]
I've opened a PR on this issue. I reckon it solves the problem.
