### ISSUE TITLE
Beanmachine tests failing in CI

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#2226]
See https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=6406&view=logs&j=7f538728-4589-5563-0e87-d0823eb40420. cc @zaxtax

**Comment by OriolAbril** [comment]
Specific line with the error (I think the one that breaks the CI job): https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=6406&view=logs&j=7f538728-4589-5563-0e87-d0823eb40420&t=fbb72fb7-9c37-5b5b-ebd2-fe739594f5e4&l=119

**Comment by zaxtax** [comment]
Yep, already figured out the cause. BeanMachine needs to be upgraded to work with pytorch 2.0 

https://github.com/facebookresearch/beanmachine/issues/1829
