### ISSUE TITLE
replace pkg_resources with importlib.metadata or equivalent

### ISSUE THREAD

**Issue by michaelraczycki** [arviz-devs/arviz#2231]
Arviz's dependency on pkg_resources causes deprecation warnings with every import for python 3.9+
switching it would allow much stricter testing policies in other repositories

**Comment by michaelraczycki** [comment]
@OriolAbril do you see any reason agains it? 
If not I can just quickly make the changes and create the PR

**Comment by ahartikainen** [comment]
Btw why do we use pkg_resources and not importlib.resources?

**Comment by msaad7777** [comment]
I want to contribute to this project, can I have any issue assigned ?

**Comment by michaelraczycki** [comment]
hey @msaad7777, good to have you here. In arviz the contributors can go through the issue list, and when they find something interesting for them, just comment under the issue saying "I'd like to work on that" and that's it. Then everyone else knows not to work on that issue (we don't assign the issues, if you'd realise that for any reason you won't be able to provide a solution, you can just write under the issue again, to signalise that the task is free for taking again. Good luck!

**Comment by OriolAbril** [comment]
adding to @michaelraczycki comment, we also have general advise and resources, even a recent webinar on contributing to ArviZ at https://python.arviz.org/en/stable/contributing/index.html. As I commented on the webinar, assigning issues at random doesn't generally work, but if you let us know what are your interests and background we can help you find an issue that is a good match for you.

Also, note this particular issue already has a PR open to fix it: https://github.com/arviz-devs/arviz/pull/2232
