### ISSUE TITLE
az.compare giving me error message - "You can only assign a scalar value not a <class 'tuple'>"

### ISSUE THREAD

**Issue by PPatty666** [arviz-devs/arviz#2242]
**Describe the bug**
I am learning **Bayesian Analysis with Python - 2nd Edition**. In the code example from chapter 5 - Model Comparison, _az.compare_ give me an error message saying "You can only assign a scalar value not a <class 'tuple'>". 

I attached an pdf with the codes, error messages and my notes. Thank you very much for helping me with this!

**To Reproduce**
I downloaded the code from here --
  
  https://github.com/aloctavodia/BAP

and installed pymc3 to run the codes.

**Expected behavior**
I want to have a table like --
![image](https://github.com/arviz-devs/arviz/assets/126918272/c9e5f03e-e7e9-4a40-8254-57e9ce707655)

**Additional context**
For pymc3 installation, I followed the **Method 1** from here --
  
  https://github.com/pymc-devs/pymc/issues/4937

(Method 2 in that link worked for me before but doesn't work now just FYI.)

from my **conda list**, I have --
  **arviz 0.12.1**
  **pymc3 3.11.5**

Thank you so very much again. Greatly appreciate it!
[az.compare_error_Patty-20230509.pdf](https://github.com/arviz-devs/arviz/files/11432765/az.compare_error_Patty-20230509.pdf)

**Comment by OriolAbril** [comment]
what is your pandas version?

**Comment by PPatty666** [comment]
> what is your pandas version?

Hello! I have "pandas 2.0.1" listed on my conda list.

**Comment by OriolAbril** [comment]
Can you try if the error persists with pandas<2 and if it still doesn't work with pandas 1.4.2 (which is the version released around the months previous to arviz 0.12)

**Comment by PPatty666** [comment]
> Can you try if the error persists with pandas<2 and if it still doesn't work with pandas 1.4.2? (1.4.2 is the version released around the months previous to arviz 0.12)

Hello! I just tried and it worked! Thank you so so much 👍
