### ISSUE TITLE
np.product is deprecated in numpy v1.25

### ISSUE THREAD

**Issue by michaelquinn32** [arviz-devs/arviz#2248]
**Describe the bug**
np.product is deprecated in v1.25.
https://github.com/numpy/numpy/releases/tag/v1.25.0rc1

There are a few instances currently in arviz. See [here](https://github.com/search?q=repo%3Aarviz-devs%2Farviz%20np.product&type=code)

**To Reproduce**
N/A

**Expected behavior**
np.product can be replaced by np.prod

**Comment by Surya-Narayan** [comment]
Hey @michaelquinn32, I would love to work on this repository issues, starting with this one. Can you please assign this to me?

**Comment by OriolAbril** [comment]
@Surya-Narayan it would be great if you can submit a PR for this!

We have guidance on contributing at https://python.arviz.org/en/stable/contributing/index.html, but don't hesitate to ask any doubt you may have over here.

**Comment by nilanjan2002** [comment]
Hey Surya-Narayan, I'm so sorry but I have already solved the issue! I am new to open-source too so I didn't know about the dos and donts. Cheers!
