### ISSUE TITLE
Can't actually override some default settings

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#226]
The way we've implemented default settings means that users can't actually override them.
Not knowing if this is desired I haven't thought through a solution fully, but if it is I propose we switch to a pattern that is something like, where defaults are populated, and then if user values are provided they're overridden.

```
# _plot_kwargs is the default values
_plot_kwargs = {"s":markersize}

# plot_kwargs is what the user wants
if plot_kwargs is not None:
    _plot_kwargs.update(plot_kwargs}
```
Example where I want to override markersize
```
import arviz as az
az.style.use('arviz-darkgrid')
centered = az.load_arviz_data('centered_eight')
coords = {'school': ['Choate', 'Deerfield']}
az.pairplot(centered, var_names=['theta', 'mu', 'tau'], coords=coords, plot_kwargs={"s": 1})
```
![image](https://user-images.githubusercontent.com/7213793/45276948-0d7b6300-b47a-11e8-96f1-3c76ab2695c7.png)

**Comment by aloctavodia** [comment]
Is this still an issue?

**Comment by ahartikainen** [comment]
I have the same question?

But there are things where we need actually need to add some logic

    lw, linewidth, linewidths

**Comment by canyon289** [comment]
This is fixed
