### ISSUE TITLE
Add a `__delitem__` method to InferenceData

### ISSUE THREAD

**Issue by Dekermanjian** [arviz-devs/arviz#2293]
I would like to be able to do something like this:
```
del idata["prior"]
```
At the moment I get the error:
```
TypeError: 'InferenceData' object does not support item deletion
```

**Comment by Dekermanjian** [comment]
Never mind, I found the way to do it. Just for anyone searching how to do this.

```
idata.__delattr__(group = <group name>)
```

**Comment by OriolAbril** [comment]
it looks like we have a `__delattr__` method but not a `__delitem__` one. You shouldn't call either directly though. To delete a group you should do:

```
del idata.prior
```

which will call `__delattr__` under the hood. We need to add a `__delitem__` method that calls the `__delattr__` one. Do you want to send a PR for this?

**Comment by Dekermanjian** [comment]
@OriolAbril Hey, I am sorry for some reason I did not get alerted to your message until just now. Thank you for taking care of adding that in.
