### ISSUE TITLE
MCMC diagnostics with all samples or only accepted samples. Misleading Rhat?

### ISSUE THREAD

**Issue by Qiustander** [arviz-devs/arviz#2294]
Hi all , this is just a usage question. I want to do MCMC diagnostics with for a parameters running with multiple chains. For example, 100 independent chains with N =10000 samples each chain.
Then I can do:
1. find the only accepted samples of each chain, and the minimum accepted number M of all chain, then extract M number from the accepted samples of each chain for alignment. Then call az.summary.
2. Run az.summary with all samples. When the proposal is rejected, then use the last accepted samples. That mean, the overall samples have many repentances.

So I get different R^hat for two situations. For the first situation, R hat is about 1.05 showing non-convergence. However, the Rhat is 1.0 in the second case. So is  there any problem? Thanks all!

**Comment by junpenglao** [comment]
you should not do 1, because in general doing this will violate the detail balance of a MCMC algorithm, which gives you a biased posterior.

**Comment by Qiustander** [comment]
> you should not do 1, because in general doing this will violate the detail balance of a MCMC algorithm, which gives you a biased posterior.

Ah, got it, thanks!

**Comment by OriolAbril** [comment]
closing as the question seems resolved
