### ISSUE TITLE
Port log_post_trace to use xarray

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#231]
I can not quite figure out what is going on here - it looks like the information is not currently exported as a sample_stat in PyMC3, but maybe @aloctavodia has some information on how to compute it (and how to extract it from `pystan`). 

Leaving this here for myself or others to possibly catch up on LOO:
https://www.youtube.com/watch?v=hpr8pxqkCH8&index=10&list=PLuwyh42iHquU4hUBQs20hkBsKSMrp6H0J&t=0s

![image](https://user-images.githubusercontent.com/2295568/45396242-6416a780-b608-11e8-879a-38250f9b97b7.png)

**Comment by ahartikainen** [comment]
`lp` and `log_lik` are different things. `lp` is the log probability/density for joint distribution and loo needs log likelihood elementwise for the data. Currently, in PyStan user needs explicitly create a `log_lik` variable.

```
generated quantities {
    vector[N] log_lik;
    for (n in 1:N) {
        log_lik[n] = normal_lpdf(y[n] | m * x[n] + b);
    }
}
```

for a model like in https://gist.github.com/ahartikainen/8e7b1a6e4b7083920b212dcafa130015

The end result is (chains, draws, N)

**Comment by canyon289** [comment]
Ah this makes more sense now to me

**Comment by ColCarroll** [comment]
A temporary strategy might be to add it to `sample_stats` - I think I can do that for pymc3 using @aloctavodia's existing function.

**Comment by ahartikainen** [comment]
What about PyStan?

If we assume there is only one way to calculate `log_lik` we could read it from the posterior samples and transfer to `sample_stats`. Not sure if this is going to be very robust.

**Comment by ColCarroll** [comment]
Could you change

```python
def pystan_to_inference_data(*, fit=None, prior=None, posterior_predictive=None,
                             observed_data=None, coords=None, dims=None):
```

to something like

```python
def pystan_to_inference_data(*, fit=None, prior=None, posterior_predictive=None,
                             observed_data=None, likelihood_var=None, coords=None, dims=None):
```

And then use
```python
if likelihood_var is not None:
    likelihood = fit.extract(pars=[likelihood_var])[likelihood_var]
```

to attach the likelihood to the `sample_stats`?  This is a little awkward, but it seems like model comparison is something people care about, so we should work to make sure at least pystan and pymc3 are well supported. Open to other ideas, too!

**Comment by ahartikainen** [comment]
Sounds good. I can do that.

**Comment by ahartikainen** [comment]
I made a PR.

`sample_stats` now will have `log_likelihood` parameter if `log_likelihood` is defined.

A user can either give a string, which is assumed to be a parameter in fit. Also, numpy array is a possibility which assumes then same dimensions as fit.extract gives, depending on the pystan version.

**Comment by ColCarroll** [comment]
We now expect libraries to attack a `log_likelihood` object to `sample_stats` (which is implemented in pymc3 and pystan converters).
