### ISSUE TITLE
arviz not compatible with pre-releases

### ISSUE THREAD

**Issue by Zethson** [arviz-devs/arviz#2330]
**Describe the bug**

> import arviz as az
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/init.py:34: in
> from .plots import *
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/plots/init.py:2: in
> from .autocorrplot import plot_autocorr
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/plots/autocorrplot.py:7: in
> from .plot_utils import default_grid, filter_plotters_list, get_plotting_function
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/plots/plot_utils.py:15: in
> from ..stats.density_utils import kde
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/stats/init.py:3: in
> from .density_utils import *
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/stats/density_utils.py:8: in
> from scipy.signal import convolve, convolve2d, gaussian # pylint: disable=no-name-in-module
> E ImportError: cannot import name 'gaussian' from 'scipy.signal' (/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/scipy/signal/init.py)

**To Reproduce**
Found it in my CI. Probably one just needs to install `arviz` with the `--pre` flag.

**Comment by OriolAbril** [comment]
Thanks for reporting, we had already seen it in our pre-release CI check but hadn't had time to fix it. Should be fixed already on GitHub, we'll make a release soon after testing with numpy 2.0

**Comment by Vital-Fernandez** [comment]
Has there been any progress for arviz to be compatible with numpy 2.0?

**Comment by OriolAbril** [comment]
the version on github should already be compatible, and there is an open PR to publish a new release that will be compatible.

**Comment by OriolAbril** [comment]
Release announcement: https://github.com/arviz-devs/arviz/releases/tag/v0.19.0 is should be on PyPI on a few minutes and on conda-forge in several hours - a day.
