### ISSUE TITLE
Why is arviz.from_numpyro so slow? 

### ISSUE THREAD

**Issue by virajpandya** [arviz-devs/arviz#2367]
## Short Description

First, thanks for making this great package -- I've loved using it with PyMC and want to use it with numpyro. 

I have a numpyro model with only 4 free parameters and the output ("obs") of every iteration is a 192-element jax Array. I'm using a simple Gaussian likelihood with Uniform priors on the 4 parameters. I ran 4000 warmup/burn-in and 4000 sampling draws with 60 chains = 240K warm-up + 240K samples. I want to convert the resulting numpyro mcmc object to an arviz InferenceData object, make arviz trace/pair plots, and save as a netcdf file. 

However az.from_numpyro is taking absurdly long (1+ hour) to finish. Why so long just to package up the 240K sampling draws (each with only 4 scalar free parameter values and a 192-element jax "obs" Array) into an InferenceData object? A single evaluation of my numpyro model for all 60 walkers takes ~4 sec which is pretty slow, and I don't know if az.from_numpyro is trying to call numpyro.infer.Predictive itself under the hood. So following https://python.arviz.org/en/latest/getting_started/CreatingInferenceData.html#from-numpyro I tried pre-generating 4K prior samples and the 240K posterior_predictive samples myself in a parallelized way and feeding those dicts to az.from_numpyro(mcmc, prior=prior_samples, posterior_predictive=posterior_predictive) as in the documentation.  But az.from_numpyro is still taking 1+ hour to finish even with the predictive dicts already given. (Note: I didn't provide "dims" and "coords" since I figured they'd be self-parsed from the prior and posterior_predictive dict keys...) This is all on a very fast 96-core supercomputer node with no other jobs running.

Any ideas why az.from_numpyro is so slow even if we feed prior and posterior_predictive to it? Any ways to speed it up? I guess I could thin the 240K posterior samples but that should be unnecessary... 

I'm using the latest jax/jaxlib/numpyro/arviz versions as of today.

**Comment by OriolAbril** [comment]
Does using `from_numpyro(..., log_likelihood=False)` change anything?

I don't really know why it is so slow and none of the devs are currenly using `from_numpyro` as far as I know, so it is possible there are things in the converter that are now outdated and don't make much sense. It would be great to get some extra help and testers on that end

**Comment by virajpandya** [comment]
That worked thanks! The runtime dropped from ~80 min to ~0.6 sec. I still need the log-likelihood but I can compute that separately like I do for the prior/posterior predictive samples and feed it as an input to az.from_numpyro.
