### ISSUE TITLE
Add "xarray 101" documentation and link in exception

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#239]
Create "xarray 101" documentation and add link to xarray related exceptions

Per conversation in PR https://github.com/arviz-devs/arviz/pull/236 xarrays can be confusing, and since arviz does a lot of xarray indexing under the hood, it may be difficult for users to figure out what's going on.

**Comment by canyon289** [comment]
I'm on this. Will branch from this PR https://github.com/arviz-devs/arviz/pull/244

**Comment by canyon289** [comment]
Here's my first attempt. Once we merge https://github.com/arviz-devs/arviz/pull/250, I'll create a branch and add to the docs

https://gist.github.com/canyon289/3ca84922cae29f706a36dab3b21ac065

**Comment by ColCarroll** [comment]
Thanks, @canyon289!
