### ISSUE TITLE
`plot_pair` drops variables when number of variables is >= 9 

### ISSUE THREAD

**Issue by nwilliams-kobold** [arviz-devs/arviz#2396]
**Describe the bug**
`plot_pair` is expected to create an `(n-1) x (n-1)` grid of plots for `n` variables when `marginals=False` and `n x n` plots when `marginals=True`. This is true in practice up to n=8, but above that the output is limited to 8x8, regardless of whether marginals are plotted. Additional variables are just ignored. If this is desired behaviour, then an error or warning should be raised, but I expect most users would want to see all plots, and then make a decision how to proceed if the plot is unreadable.

**To Reproduce**
Example based on issue [#1981](https://github.com/arviz-devs/arviz/issues/1981)
```
import arviz as az
import matplotlib.pyplot as plt
import numpy as np

# Number of variables: works as expected up to n=8, but variables are missing for n=9 and up.
n = 10

# Generate some random data from a multivariate normal
rng = np.random.default_rng(42)
data = rng.multivariate_normal(rng.normal(size=n), cov=np.diag(rng.random(size=n)), size=(1, 2000))

# Naive `plot_pair`
az.plot_pair(data, kind="kde", marginals=True)

# `plot_pair` with supplied axes - same results, but may be slightly easier to read
fig, ax = plt.subplots(n, n)
az.plot_pair(data, marginals=True, kind="kde", ax=ax);
```
## When using n=3
Correctly recovers a 3x3 plot with marginals, as expected. Variables x0, x1, x2 all present.
### Default axes
![image](https://github.com/user-attachments/assets/c2646e9a-a432-4283-8447-b14e9cde3e15)
### User-supplied axes
![image](https://github.com/user-attachments/assets/057e869f-a18f-41b1-b8f3-465e571b7a30)

## When using n=10
Erroneously recovers an 8x8 plot with marginals, when a 10x10 plot is expected. Variables x0, ... x7 all present, but x8, x9 are missing. When the user supplies the correct number of axis subplots the last 2 rows and columns are left blank.
### Default axes
![image](https://github.com/user-attachments/assets/0a065b7b-8094-43a6-935e-8b40cf09bca2)
### User-supplied axes
![image](https://github.com/user-attachments/assets/0bc97f22-fb97-4c9f-8e2b-eec9e815061b)

**Expected behavior**
The n=3 plots are perfect (and also for n=2,...,8). The n=10 plots are missing the last 2 variables which would be plotted in the last 2 rows and columns. All n>=9 show the same limit of 8x8.

**Additional context**
- `arviz 0.20.0`
- `matplotlib 3.9.2`
- `numpy 1.26.4`

**Comment by nwilliams-kobold** [comment]
Ok, thanks. I reset my logger levels and do get a warning, and can override with a context manager. Sorry for the bother.

**Comment by aloctavodia** [comment]
Don't worry. Happy it's working for you.
