### ISSUE TITLE
Inconsistent auto generated dimension names in `numpy_to_data_array`

### ISSUE THREAD

**Issue by lucianopaz** [arviz-devs/arviz#2397]
**Describe the bug**
This was originally reported in pymc-devs/pymc#7572. The problem is that `arviz.data.numpy_to_data_array` does not yield consistent dimension names when there are `default_dims` and `dims` that also match some of these.

**To Reproduce**
```python
import numpy as np
from arviz.data import numpy_to_data_array

generated_dims = []
for dims in [None, ["chain", "draw"], ["chain", "draw", None]]:
    out_dims = numpy_to_data_array(
        np.empty((4, 500, 7)),
        var_name="a",
        dims=dims,
        default_dims=["chain", "draw"]
    ).dims
    generated_dims.append(out_dims)

assert all(dims == generated_dims[0] for dims in generated_dims)
```

Specifically:

```python
>>> generated_dims
[('chain', 'draw', 'a_dim_0'),
 ('chain', 'draw', 'a_dim_2'),
 ('chain', 'draw', 'a_dim_2')]
```

**Expected behavior**
The result that one gets when `dims = None` should be the same as when the chain and draw dimension are also specified.

**Additional context**
Current `arviz` main

**Comment by OriolAbril** [comment]
closed by #2395
