### ISSUE TITLE
Add more fitted models

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#242]
figshare (https://figshare.com/) seems like a possibility that I think scikit-learn uses. In terms of size, [the radon example here](https://docs.pymc.io/notebooks/multilevel_modeling.html) generates a netCDF file of about 15MB, which is not so bad.

Perhaps it could even be hosted in a separate github repo?

**Comment by ahartikainen** [comment]
Could we do simple linear regression with 100 datapoints? Could help to move forward regression plots.

Also multivariate example would be nice.
