### ISSUE TITLE
Actually use `attrs` to describe xarray datasets in convert functions

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#243]
`attrs` are json metadata attached to xarray datasets - we could even put whole stan programs in there, and maybe pymc3 ones, using `inspect` if we're clever.

**Comment by ColCarroll** [comment]
Whatever settles this should also have a special mark for ensemble samplers - `from_emcee` puts non-independent chains into the `posterior` group, which may be misleading.

**Comment by ahartikainen** [comment]
Also cmdstan/pystan has sampler stats that are not currently parsed / extracted. E.g. inits, seeds etc should live in there, right?
