### ISSUE TITLE
Turn diagnostics into proper ufuncs

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#246]
See https://docs.scipy.org/doc/numpy-1.15.0/reference/ufuncs.html

For a bunch of functions I "faked" a ufunc to allow xarray to broadcast calculations correctly, but careful rewriting should make cleaner, faster implementations of `effective_n`, `hpd`, `rhat`, to name a few.

**Comment by canyon289** [comment]
After finishing the intro docs I'd like to give these a try

**Comment by canyon289** [comment]
I don't quite understand this one. It looks like u_funcs are already used for effective_n. Is this implementation incorrect?

https://github.com/arviz-devs/arviz/blob/master/arviz/stats/diagnostics.py#L56

**Comment by ColCarroll** [comment]
Despite opening the issue, I do not know much about this.

- I am not confident that the current implementation will work for higher dimensions, and automatically broadcast. 
- I am not even sure that a ufunc can require a 2d input and return 1d output. 
- The linked documentation is all Cython - I could not find anything on writing ufuncs in python. Do we gain a lot implementing it in Cython?

**Comment by aloctavodia** [comment]
What about [Numba](https://numba.pydata.org/numba-doc/dev/user/vectorize.html)?

**Comment by canyon289** [comment]
Hm for whoever takes a go at this, I would be really interested in understanding the details, and would be especially thrilled if someone would be willing to mentor me through implementing one of these myself!

Not required but figured I could ask

**Comment by ColCarroll** [comment]
For what it is worth, I ported `bfmi` to a numba ufunc, and on a 4 x 500 energy array, I see about a 3x speedup.

Here is the code:

```python
@guvectorize([(float64[:], float64)], '(n)->()')
def bfmi(energy, res):
    n_rows = energy.shape[0]
    # moments
    first, second = 0, 0    
    squared_diff, trailing = 0, energy[0]
    
    for row in range(n_rows):
        first += energy[row]
        second += np.power(energy[row], 2)
        squared_diff += np.power(energy[row] - trailing, 2)
        trailing = energy[row]
    first = np.power(first, 2) / n_rows
    
    res = (n_rows * squared_diff) / ((n_rows - 1) * (second - first))
```

For reference, the current implementation is
```python
def bfmi(energy)
    energy_mat = np.atleast_2d(energy)
    return np.square(np.diff(energy_mat, axis=1)).mean(axis=1) / np.var(
        energy_mat, axis=1
    )
```

**Comment by canyon289** [comment]
3x is nothing to scoff at. This syntax is really interesting. Thanks for the example

**Comment by ColCarroll** [comment]
nogil doesn't work for this, for whatever reason, but nopython=True does. Also, for larger datasets, the speedup is greater.

Are we ok adding numba as a dependency? It is not light (~16mb?), it is a little new still, and pystan already requires Cython (so Cython wouldn't be a brand new dependency). That said, I have had fun working with numba so far, like having the code be in Python and not require extra `setup.py` stuff.

**Comment by ahartikainen** [comment]
Nogil would probably need some extra work with threading.

**Comment by ahartikainen** [comment]
How is numba for pip users?

It could be optional dependency?

The point with Cython/PyStan was that our users already go through some dependency "hell"

**Comment by ahartikainen** [comment]
(Also PyStan takes a few hundred MB)

**Comment by aloctavodia** [comment]
ohhh nice to see I am not the only confused one, haha.

I think numba has improved a lot recently (including the installation process) and we should seriously consider using it.

**Comment by springcoil** [comment]
I'm a big fan of numba. I think it'd be good for the python community to use it here.

**Comment by OriolAbril** [comment]
I think this is mostly fixed using `make_ufunc` and `wrap_xarray_ufunc`, only `hpd` is missing (related to #855

**Comment by ColCarroll** [comment]
I'm going to close this, then, since it is an old issue. Feel free to reopen!
