### ISSUE TITLE
Fix plot_forest - cutting points

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#270]
rhat values close to 1 are sometimes cutted. Either we let it plot outside the fig (there is a kw for that) or rescale axis.

**Comment by canyon289** [comment]
I think this was covered by https://github.com/arviz-devs/arviz/pull/308. Can someone let verify it meets their expectations?
https://github.com/arviz-devs/arviz/pull/308

**Comment by ColCarroll** [comment]
Nope.  This is on master -- see the right hand effective_n cut off:

![image](https://user-images.githubusercontent.com/2295568/46296874-5e5a1500-c569-11e8-8f51-3271178222b1.png)

**Comment by ahartikainen** [comment]
This could be fixed with adding `clip_on=False` to line 294 and 305, but this is not general solution.
    
     ax.plot(n_eff, y, 'o', color=color, markersize=markersize, markeredgecolor='k', clip_on=RULE_HERE)

We could test if the point lies inside the xlim region or "nearby" and use `clip_on=False` for them, but if user then is going to move the xlimits, it will be painful to reset all the needed points.

**Comment by ahartikainen** [comment]
I made a PR. I think we are more or less safe with touching n_eff only, which only forces xlim(left=0) so this problem will manifest atleast with one point, but rhat is static and my guess is that the probability for one being on the edge of the plot is much smaller.

**Comment by ColCarroll** [comment]
Now it is fixed #312
