### ISSUE TITLE
Fix numpy slicing

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#271]
Change all ndarray slicings to tuple slicing. We need to hunt down all the cases. At least stats has some of them.

From

    idx = np.array(...)
    ary_sliced = ary[idx]

To

    idx = np.array(...)
    ary_sliced = ary[tuple(idx)]

**Comment by canyon289** [comment]
Is this only in regards to Ellipsis slicing? If so I can only find one example
https://github.com/arviz-devs/arviz/blob/master/arviz/stats/stats.py#L670

or is this in regards to any ndarray slicing at all?
Like here
https://github.com/arviz-devs/arviz/blob/master/arviz/stats/stats.py#L305

or here
https://github.com/arviz-devs/arviz/blob/master/arviz/stats/stats.py#L447

**Comment by canyon289** [comment]
Copying @ahartikainen's helpful answer here

> Multidimensional indexing with anything but a tuple is deprecated. This means that the index list in ind = [slice(None), 0]; arr[ind] should be changed to a tuple, e.g., ind = [slice(None), 0]; arr[tuple(ind)] or arr[(slice(None), 0)]. That change is necessary to avoid ambiguity in expressions such as arr[[[0, 1], [0, 1]]], currently interpreted as arr[array([0, 1]), array([0, 1])], that will be interpreted as arr[array([[0, 1], [0, 1]])] in the future.

https://docs.scipy.org/doc/numpy/release.html
