### ISSUE TITLE
Do not use pyplot

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#274]
This is considered an anti-pattern, and the axes handling can get messed up with the global namespace.

**Comment by junpenglao** [comment]
Is there a page for current best practice?

**Comment by canyon289** [comment]
I've found these docs/posts to be useful
http://pbpython.com/effective-matplotlib.html
https://matplotlib.org/tutorials/introductory/lifecycle.html
https://matplotlib.org/faq/usage_faq.html
