### ISSUE TITLE
Use constrained layout

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#275]
Matplotlib has a new constrained layout engine that may help us quite a bit with fitting and scaling large figures. It looks like this _precisely_ solves this.

https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html

**Comment by ahartikainen** [comment]
3.0?

**Comment by canyon289** [comment]
Closed by https://github.com/arviz-devs/arviz/issues/233
