### ISSUE TITLE
Possible to get to all codepaths in ForestPlot.py?

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#292]
Trying to figure how how to test for these code paths, but I'm not entirely sure how to get there. Any advice?

https://github.com/arviz-devs/arviz/blob/master/arviz/plots/forestplot.py#L444
https://github.com/arviz-devs/arviz/blob/master/arviz/plots/forestplot.py#L453

**Comment by ahartikainen** [comment]
numpy array of size 1?

**Comment by canyon289** [comment]
Works! Implemented here. I'll close this issue when the PR is merged

https://github.com/arviz-devs/arviz/pull/300
