### ISSUE TITLE
Test suite is no longer closing figures

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#295]
The travis builds are complaining about more than 20 open figures again: https://travis-ci.org/arviz-devs/arviz/jobs/434573224

I know there's a `finalizer` added, but it appears not to be working.

**Comment by canyon289** [comment]
To centralize conversation, it only runs once per module, so in our case after ~100 plots have been opened. 
@ColCarroll's PR will fix it https://github.com/arviz-devs/arviz/pull/296

**Comment by canyon289** [comment]
Closed by https://github.com/arviz-devs/arviz/pull/308
