### ISSUE TITLE
Pairplot does not actually accept grid/axis argument

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#301]
This example I would expect to have two different scatter plots on each axis, but it only plots the first one:

```
import arviz as az

centered = az.load_arviz_data('centered')

axes, gridspec = az.plot_pair(
    centered.posterior, 
    var_names=['theta', 'mu'], 
    coords={'school': ['Choate', 'Deerfield']}, 
    plot_kwargs={'c': 'C0'})

az.plot_pair(
    centered.prior, 
    var_names=['theta', 'mu'], 
    coords={'school': ['Choate', 'Deerfield']}, 
    ax=axes, 
    gs=gridspec, 
    plot_kwargs={'c': 'C1'})
```

![image](https://user-images.githubusercontent.com/2295568/46247390-b6addd00-c3d8-11e8-8291-1ee34ffa467d.png)

**Comment by ColCarroll** [comment]
Three reasonable solutions here: 
- Remove those arguments, which would simplify the internal code a bit
- Accept a list of models, and plot them all
- Make the above example work (this would mean the code trusts the axes you pass in are the right shape - might not work, since some axes get deleted)

**Comment by MFreidank** [comment]
I think I'll quickly fix this, settling for your first option above (remove those arguments). 
Three appears to be dangerous (as it will be hard to distinguish cases where axes are deleted etc, and that might lead to fairly hard-to-debug bugs), two might be added in the future, but essentially will also come down to first implementing the first option as far as I can tell.

**Comment by agustinaarroyuelo** [comment]
Hi! @MFreidank did you get to try anything about this?

**Comment by andy6975** [comment]
Is this issue open for work? I would like to work on it. Thanks!

**Comment by ColCarroll** [comment]
Thanks for checking -- I just reran the initial code, and it now works with a little tweak:

```python
centered = az.load_arviz_data('centered_eight')

axes = az.plot_pair(
    centered.posterior, 
    var_names=['theta', 'mu'], 
    coords={'school': ['Choate', 'Deerfield']}, 
    plot_kwargs={'c': 'C0'}, figsize=(15, 8))

az.plot_pair(
    centered.prior, 
    var_names=['theta', 'mu'], 
    coords={'school': ['Choate', 'Deerfield']}, 
    ax=axes, 
    plot_kwargs={'c': 'C1', 'alpha': 0.7})
```

![image](https://user-images.githubusercontent.com/2295568/66245273-9f778e80-e6c1-11e9-8349-016a48aaa285.png)
