### ISSUE TITLE
Nicer layout for `az.summary`

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#327]
We should present az.summary in a nice 2d dataframe instead of an xarray. This will probably involve a convention for the variable names - `theta[Choate]` or `theta_Choate` (i.e., `theta[coord1][coord2][...]` or `theta_coord1_coord2_...`) seem reasonable?

**Comment by ahartikainen** [comment]
`format=long`

`format=wide`

**Comment by canyon289** [comment]
@ahartikainen Did this one get closed by https://github.com/arviz-devs/arviz/pull/335?

**Comment by ahartikainen** [comment]
I think it did.
