### ISSUE TITLE
Add logging to ArviZ

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#331]
Getting good logging in now will make our lives easier when debugging or trying to help users with ArviZ later

Area that might benefit from logging/capturing logs from other packages
1. Which matplotlib backend is being used
2. Logs during testing, which we can instruct users to run locally and then send to use for debugging
3. Capturing logs about which packages versions are being used

**Comment by canyon289** [comment]
If taking on this pull request please don't use BasicConfig, and instead app to instantiate handlers manually. The reasoning for this is that while BasicConfig "does a lot for you" for this long term library the extra controls will come in handy down the line

**Comment by riddell-stan** [comment]
You might look at what pymc3 and pystan do for this. They do the same 
thing; both avoid BasicConfig.

Logging is configured at the bottom of pymc3's __init__.py file: 
https://github.com/pymc-devs/pymc3/blob/35fa41d0fc48ce7fc919ad4e44504dd3d2d96365/pymc3/__init__.py
