### ISSUE TITLE
summary for circular variables

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#339]
Summary used to have a `circ_var_names` argument in order to specify for which variables to compute circular statistics instead of the regular ones (#45). This argument was replaced by `include_circ`, this accept booleans, when `True` it will compute the regular statistics plus the circular statistics for all variables. I think we should revert this and have `circ_var_names` again, or maybe some other alternative.

The ideal behavior will be to automatically compute the proper statistics based on the variable type, but at least for the moment that information is not available for ArviZ

**Comment by andy6975** [comment]
Is this issue open for work? I would like to work on this. Thanks!

**Comment by aloctavodia** [comment]
Yeah, this is still an issue. Thanks for your offer.

**Comment by smit-s** [comment]
@aloctavodia  If this issue is still open, can I work on it please?

**Comment by aloctavodia** [comment]
Is still open, I think @agustinaarroyuelo  was planning to work on this as part of the GSoC (but she also is proposing many other tasks).

**Comment by smit-s** [comment]
No problem at all. I will pick up regression plot and time-series.
