### ISSUE TITLE
Add api docs for plot_forest

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#350]
https://arviz-devs.github.io/arviz/generated/arviz.plot_forest.html#arviz.plot_forest

See Posterior Docs for example
https://arviz-devs.github.io/arviz/generated/arviz.plot_posterior.html#arviz.plot_posterior

**Comment by kishan3** [comment]
@canyon289 Sorry, I want to pick this but not sure what to do. The link you shared has already explained the function. Can you explain what is to be done?

**Comment by canyon289** [comment]
Same instructions as here https://github.com/arviz-devs/arviz/issues/351#issuecomment-428910514
