### ISSUE TITLE
Add API docs for plot_parallel

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#351]
https://arviz-devs.github.io/arviz/generated/arviz.plot_parallel.html#arviz.plot_parallel

See Posterior Docs for example
https://arviz-devs.github.io/arviz/generated/arviz.plot_posterior.html#arviz.plot_posterior

**Comment by kishan3** [comment]
@canyon289 Sorry, I want to pick this but not sure what to do. The link you shared has already explained the function. Can you explain what is to be done?

**Comment by canyon289** [comment]
Hey Kishan! Thanks for wanting to take this on

In the source code for `posteriorplot` you'll see code blocks like the one below. These code blocks are Sphinx directives that generate documentation. We would like all major functionality to be documented 

The steps will be
1. Add sphinx directive in documentation
2. Verify documentation by running `make html` in the `docs` directory to generate the documentation. It will appear under `_build`.

Let me know if this helps!

https://github.com/arviz-devs/arviz/blob/master/arviz/plots/posteriorplot.py#L103-L106
```
 .. plot::
        :context: close-figs

        >>> import arviz as az
        >>> data = az.load_arviz_data('centered_eight')
        >>> az.plot_posterior(data)
```

**Comment by kishan3** [comment]
Hey @canyon289! thanks for taking the time to explain this. I will be glad to help.
