### ISSUE TITLE
Add API docs for plot_ppc

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#355]
https://arviz-devs.github.io/arviz/generated/arviz.plot_ppc.html#arviz.plot_ppc

See Posterior Docs for example
https://arviz-devs.github.io/arviz/generated/arviz.plot_posterior.html#arviz.plot_posterior

**Comment by mattboggess** [comment]
I was just thinking the other day how much Python needed a library like this and then I found arviz. This looks great, thanks for creating this!

I was hoping to help contribute and figured I'd start with one of these. Ok if I take this one up?

**Comment by ahartikainen** [comment]
Yes, you can take it.

**Comment by canyon289** [comment]
Hey @mattboggess If it helps I wrote some more detailed instructions for someone else here.

https://github.com/arviz-devs/arviz/issues/351
