### ISSUE TITLE
Rename arviz.gelman_rubin -> arviz.rhat and use the same Rhat as in Stan

### ISSUE THREAD

**Issue by avehtari** [arviz-devs/arviz#361]
Dear Arviz developers,

1) Could you consider renaming arviz.gelman_rubin to arviz.rhat? The problem with gelman_rubin is that it refers to the paper Gelman & Rubin (1992), which has different equation than Brooks and Gelman (1998), which has different equation than BDA2, which has different equation than BDA3, which has the equation used in Stan (and there will be in next half year a new version of Rhat which will be again different). Based on the personal communication with Andrew Gelman, he doesn't like naming things by author names and would also prefer name Rhat.

2) Could you consider using the latest Rhat version? Currently Arviz documentation https://arviz-devs.github.io/arviz/generated/arviz.gelman_rubin.html#arviz.gelman_rubin
refers to Brooks and Gelman (1998), Gelman and Rubin (1992), so it also seems that you are using a different version than Stan. It would be nice to have the same updated diagnostic, especially as Split-Rhat is better diagnostic than non-split-version used by Brooks and Gelman (1998).

Edit: You can find description of differences in Rhat versions in https://stats.stackexchange.com/questions/348984/stan-hatr-versus-gelman-rubin-hatr-definition/350727#350727

ps. Arviz looks really great!

**Comment by aloctavodia** [comment]
Hi @avehtari, thanks for your suggestion and comments. Just yesterday we were discussing about this so your comments are very timely. We will rename the function and also use the newest version of Rhat.

**Comment by ColCarroll** [comment]
Very interested in this intuition from the stackexchange link, and want to call it out to use in the docstring:

> In cases where you want to use split-R̂  convergence diagnostic, you should use at least 4 chains split and thus have M=8. You may use less chains, if you already know that in your specific cases the convergence and mixing is fast.

Also, maybe a silly question, but inspired by https://avehtari.github.io/rhat_neff/rhat_neff.html, is there any benefit to including "historical" versions of algorithms? 

From an API perspective it would be a nightmare to support (and so please don't view this as a feature request), but it seems somewhat interesting to be able to compare the Gelman and Rubin (1992) version, with the Brooks and Gelman (1998) version, with the split-rhat version.

**Comment by avehtari** [comment]
>  is there any benefit to including "historical" versions of algorithms?

Not really. Only if you would be writing a comparison paper, and even then I would be better not to expose those to users to not cause confusion which one to use.

Difference between Gelman and Rubin (1992)  and Brooks and Gelman (1998) is mostly seen with small m, which would in the non-recommended cases, and mostly this difference would just affect the relative difference from 1, but both would eventually go to 1, if chains are mixing well. Split-Rhat is more sensitive to common trend in several chains, which is rare but possible phenomenon with dynamic HMC.

**Comment by canyon289** [comment]
@ColCarroll Is this the correct url? The one above leads to a 404 https://avehtari.github.io/rhat_reff/rhat_reff.html

**Comment by avehtari** [comment]
Sorry, my fault as I've changed the file name from rhat_neff to rhat_reff.

**Comment by canyon289** [comment]
Closed by https://github.com/arviz-devs/arviz/pull/477

Thanks @ahartikainen
