### ISSUE TITLE
plot_ppc fixes & improvements

### ISSUE THREAD

**Issue by mattboggess** [arviz-devs/arviz#375]
As I was looking through the plot_ppc function, a lot of fixes and improvements came to mind that I thought would help improve the plot. I'd be happy to work on any/all of them that you think would be worthwhile and want to add. There's a lot here and will likely want to be partitioned into multiple PRs/issues, but I wanted to get everything listed.

DOC:

- data_pairs default behavior is not described (assumes observed and pp variables have the same name)
- use a multi-observed variable model to showcase the auto grid feature of the function in an api example (I think it auto-grids right?). this would actually be the eight schools dataset with the fix in the first bullet point under functionality.
- alpha and kind do not specify default behavior (these are obvious from the function declaration, but it might be good to just list in the description as well since some other obvious parameters have the default listed)
- data is not really 'array-like'? It should have a matching description as in plot_posterior referencing InferenceData convertability
- document passing extra arguments on to matplotlib

Style:
- extend the kdes out to the edges of the x-axis
- add an axes parameter
- add parameters to customize color
- the current automatic x-axis labeling is potentially confusing with the legend labeling (it confused me at least). I would either recommend labeling the x-axis with the observed parameter name (as done currently), but make the legend labels not reference parameter names. Or I would not label the x-axis and keep the legend with parameter name references.
- make the observed & pp mean lines solid, thicker, and bolder so they stand out from the pp KDEs more.

Fixes & New Features:
- Fix grouped/vectorized parameter flattening:
  - observed variables that are vectorized should have the option to not be flattened across dimensions and instead plotted in a grid? This is why I think the eight school examples look kind of "wonky" since it's a mixture of multiple distributions with one observed data point each?
  - add a var_names parameter to support subsets in multi-observed variable plots.
- Provide sub-sample and uncertainty plotting options to reduce long plotting time with lots of generated predictions:
  - add a "sub-sample" parameter that would plot a random sub-sample of the posterior predictive distributions. This would be nice when there are a lot of generated predictions, but a subset would suffice for visualization.
  - add a parameter to allow plotting pp uncertainty shading with the pp mean instead of all of the KDEs.

**Comment by ColCarroll** [comment]
The docs would be welcome additions. Here is what I was thinking about for multi-dimensional observations. In case of the radon dataset, note this would be 89 plots, each with a few observations!

![image](https://user-images.githubusercontent.com/2295568/47328310-a804bf80-d63e-11e8-9967-326ee0b73ae0.png)
![image](https://user-images.githubusercontent.com/2295568/47328403-016cee80-d63f-11e8-808b-a9600b71ef96.png)

**Comment by mattboggess** [comment]
Yeah that looks good! I wasn't thinking about models with such few observations, but that's what the examples are. This is more complicated than I thought. One option would be to have a threshold for number of observations to switch from a 1d scatter to a KDE for the observed data? You could just pool the pp samples for a single pp kde up until that threshold as well?

Radon is an example of why I think adding a var_names parameter to support subsets of the observed variables would be nice. I would often wrap with ipywidgets interact to move through plots interactively if there were too many observed variables to be visualized all at once which a var_names parameter also supports.

I'd be happy to open a PR for the doc points besides the multi-dimensional example point.

**Comment by ColCarroll** [comment]
Here's the code for the above, using some of the machinery from arviz, in case that helps https://gist.github.com/ColCarroll/19e7b35aad55b265968b8e92fda8294b

Still not sure a good approach on API. Probably will take someone making a PR and playing with a few examples. Maybe including a `marker` argument? Or a `ppc_style` and `observed_style` dict? It might even make sense to break it up into a few different plots, instead of having one try to do everything.

Regardless of approach, I think adding `var_names` is a good idea, though if I understand your intent, we have been using the argument `coords` for this. In the above example, I might pass `var_names = ['obs']` and `coords={'school': ['Hotchkiss', 'Mt. Hermon']}` This matches the xarray API of `data[var_names].sel(**coords)`.

**Comment by mattboggess** [comment]
Thanks for the example! I'll start working on a PR unless you or someone else on the dev team would prefer to work on it.

The var_names and coords combination is perfect, thanks!
