### ISSUE TITLE
Write helper method for tests in ArvizTestData

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#390]
There are numerous test functions `test_data.py` that have multiple asserts to check everything was loaded up properly.

It would be better to turn this into an iterator rather than line the asserts up linearly

Example
https://github.com/arviz-devs/arviz/blob/master/arviz/tests/test_data.py#L426

Possible Solution
https://github.com/arviz-devs/arviz/pull/388#discussion_r230570675

**Comment by ahartikainen** [comment]
Fixed by #624
