### ISSUE TITLE
Signature conventions

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#391]
From an internal discussion, helpfully curated by @canyon289 :

In a Python 3.x program, there are 4 types of arguments:
```python
def foo(a, b=None, *, c, d=None):
```
we might call these: required positional, optional positional, required keyword, optional keyword

ArviZ uses a few of these right now:

(Positional required, Keyword optional)
https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_emcee.py#L91
https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_pyro.py#L82

(Keyword optional)
https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_cmdstan.py#L546-L555
https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_pymc3.py#L145
https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_pystan.py#L326

@canyon289 suggests:
`from_xyz` use all optional or required keywords arguments, because ArviZ is mapping to objects that it doesn’t define control this is the most brittle interface

`az.plots` and `az.stats` use (required positional, optional keyword) to make getting an initial plot easy. Also because plots and stats use `az.InferenceData` internally once in the method we can expect consistency

**Comment by ColCarroll** [comment]
So for the `io_emcee` and `io_pyro`, I used a required keyword, since each of those can only be initialized with the given argument. The other three right now return an empty `InferenceData` object when nothing is passed. I guess the equivalent requirement would be that *one* of a few objects be given.

I'm ok with making `from_xyz` be all optional, and consistently return an empty object if something like `my_data = az.from_pymc()` is called.

**Comment by ahartikainen** [comment]
Should all the `from_xyz` follow the same format?

`az.from_xyz(*, posterior=None, posterior_predictive=None, prior=None, prior_predictive=None, ...)`

**Comment by ahartikainen** [comment]
I think this is fixed by #490
