### ISSUE TITLE
Arviz incompatible with PyMC3 trace subsetting

### ISSUE THREAD

**Issue by mfansler** [arviz-devs/arviz#395]
After upgrading to Arviz 0.2.1 from 0.1.0, I found that many of my PyMC3 trace objects are no longer compatible with Arviz.  In particular, failure happens in models where I subsetted the variables being traced during sampling. It seems that the conversion from a PyMC3 trace object to Arviz's InferenceData object ultimately expects some internal variables to be traced, whereas PyMC3's trace subsetting excludes all but those listed.

## Example
```
import numpy as np
import pymc3 as pm
import arviz as az

observed = np.random.binomial(500, p=0.4, size=30)

with pm.Model() as model:
    mu = pm.DiscreteUniform('mu', lower=100, upper=1000)
    p = pm.Beta('p', alpha=1, beta=1)
    N = pm.Binomial('N', n=mu, p=p, observed=observed)

    trace = pm.sample(trace=[mu, p])

az.plot_trace(trace)
```
### Result
> TypeError: Missing required input: p_logodds__

One might hope that restricting the trace plot to only a variable of interest might get beyond it, e.g.

    az.plot_trace(trace, var_names=['mu'])

but this fails just as above.  The stack trace notably includes `from_pymc3`, and calling this directly on the trace object will also fail.

### Commentary
Certainly, in this toy model one has no problem tracing everything, but in large complex models, tracing all variables can be wasteful and unnecessary.  Perhaps an alternative is for PyMC3 to still keep those internal variables in the trace, even when a subset is requested.  Moreover, since `pm.sample` expects a list of actual variables and not just strings (e.g., `[mu, p]` above) for the `trace` argument, I don't see any way to tell the sampler to continue saving those internal variables, e.g. `'p_logodds__'` that are still relevant to the ones being included.

## Full Error Result

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-f1462efd3db0> in <module>()
----> 1 az.plot_trace(trace)

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/plots/traceplot.py in plot_trace(data, var_names, coords, figsize, textsize, lines, combined, kde_kwargs, hist_kwargs, trace_kwargs)
     72         >>> az.plot_trace(data, var_names=('theta_t', 'theta'), coords=coords, lines=lines)
     73     """
---> 74     data = convert_to_dataset(data, group='posterior')
     75 
     76     if coords is None:

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/converters.py in convert_to_dataset(obj, group, coords, dims)
    118     xarray.Dataset
    119     """
--> 120     inference_data = convert_to_inference_data(obj, group=group, coords=coords, dims=dims)
    121     dataset = getattr(inference_data, group, None)
    122     if dataset is None:

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/converters.py in convert_to_inference_data(obj, group, coords, dims, **kwargs)
     55         return from_pystan(fit=obj, coords=coords, dims=dims, **kwargs)
     56     elif obj.__class__.__name__ == 'MultiTrace':  # ugly, but doesn't make PyMC3 a requirement
---> 57         return from_pymc3(trace=obj, coords=coords, dims=dims, **kwargs)
     58     elif obj.__class__.__name__ == 'EnsembleSampler':  # ugly, but doesn't make emcee a requirement
     59         return from_emcee(obj, coords=coords, dims=dims, **kwargs)

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/io_pymc3.py in from_pymc3(trace, prior, posterior_predictive, coords, dims)
    147         posterior_predictive=posterior_predictive,
    148         coords=coords,
--> 149         dims=dims).to_inference_data()

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/io_pymc3.py in to_inference_data(self)
    132         return InferenceData(**{
    133             'posterior': self.posterior_to_xarray(),
--> 134             'sample_stats': self.sample_stats_to_xarray(),
    135             'posterior_predictive': self.posterior_predictive_to_xarray(),
    136             'prior': self.prior_to_xarray(),

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/base.py in wrapped(cls, *args, **kwargs)
     22                 if getattr(cls, prop) is None:
     23                     return None
---> 24             return func(cls, *args, **kwargs)
     25         return wrapped
     26 

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/io_pymc3.py in sample_stats_to_xarray(self)
     77             name = rename_key.get(stat, stat)
     78             data[name] = np.array(self.trace.get_sampler_stats(stat, combine=False))
---> 79         log_likelihood, dims = self._extract_log_likelihood()
     80         if log_likelihood is not None:
     81             data['log_likelihood'] = log_likelihood

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/base.py in wrapped(cls, *args, **kwargs)
     22                 if getattr(cls, prop) is None:
     23                     return None
---> 24             return func(cls, *args, **kwargs)
     25         return wrapped
     26 

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/io_pymc3.py in _extract_log_likelihood(self)
     52         for chain in self.trace.chains:
     53             log_like = (log_likelihood_vals_point(point) for point in self.trace.points([chain]))
---> 54             chain_likelihoods.append(np.stack(log_like))
     55         return np.stack(chain_likelihoods), coord_name
     56 

~/anaconda/envs/bml36/lib/python3.6/site-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    345 
    346     """
--> 347     arrays = [asanyarray(arr) for arr in arrays]
    348     if not arrays:
    349         raise ValueError('need at least one array to stack')

~/anaconda/envs/bml36/lib/python3.6/site-packages/numpy/core/shape_base.py in <listcomp>(.0)
    345 
    346     """
--> 347     arrays = [asanyarray(arr) for arr in arrays]
    348     if not arrays:
    349         raise ValueError('need at least one array to stack')

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/io_pymc3.py in <genexpr>(.0)
     51         chain_likelihoods = []
     52         for chain in self.trace.chains:
---> 53             log_like = (log_likelihood_vals_point(point) for point in self.trace.points([chain]))
     54             chain_likelihoods.append(np.stack(log_like))
     55         return np.stack(chain_likelihoods), coord_name

~/anaconda/envs/pymc3/lib/python3.6/site-packages/arviz/data/io_pymc3.py in log_likelihood_vals_point(point)
     43             log_like_vals = []
     44             for var, log_like in cached:
---> 45                 log_like_val = log_like(point)
     46                 if var.missing_values:
     47                     log_like_val = log_like_val[~var.observations.mask]

~/anaconda/envs/pymc3/lib/python3.6/site-packages/pymc3/model.py in __call__(self, *args, **kwargs)
   1118     def __call__(self, *args, **kwargs):
   1119         point = Point(model=self.model, *args, **kwargs)
-> 1120         return self.f(**point)
   1121 
   1122 compilef = fastfn

~/anaconda/envs/pymc3/lib/python3.6/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    884                     raise TypeError("Missing required input: %s" %
    885                                     getattr(self.inv_finder[c], 'variable',
--> 886                                             self.inv_finder[c]))
    887                 if c.provided > 1:
    888                     restore_defaults()

TypeError: Missing required input: p_logodds__
```

**Comment by ahartikainen** [comment]
Is this still an issue?

**Comment by mfansler** [comment]
> Is this still an issue?

@ahartikainen, yes. As of PyMC 3.7 and ArviZ 0.4.1, the same errors are thrown.

**Comment by mfansler** [comment]
@canyon289 Should this issue be migrated to PyMC3? To me it seems like `pymc3.sample()` should just make sure to not exclude internal trace variables.

**Comment by OriolAbril** [comment]
Modifying the variables in the trace should result in no log likelihood data (because `logp_elemwise` cannot be called) and a warning instead of raising an error like happens now.

**Comment by OriolAbril** [comment]
@mfansler Bug should be fixed in ArviZ master!

```
import numpy as np
import pymc3 as pm
import arviz as az

observed = np.random.binomial(500, p=0.4, size=30)

with pm.Model() as model:
    mu = pm.DiscreteUniform('mu', lower=100, upper=1000)
    p = pm.Beta('p', alpha=1, beta=1)
    N = pm.Binomial('N', n=mu, p=p, observed=observed)

    trace = pm.sample(trace=[mu, p])
    idata = az.from_pymc3(trace, log_likelihood=False)

az.plot_trace(idata)
```

Seems to work fine for me. Can you confirm?

**Comment by mfansler** [comment]
@OriolAbril Confirmed!

**Comment by nanditakhetan** [comment]
Hi, I am using PyMC3 3.8 and arviz 0.6.1. I am new to pymc3.  I want to calculate WAIC for a hierarchical model but using pm.waic(trace) gives me the following error:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-c72c4ebad635> in <module>
     18 logp = trace['model_logp']
     19 #help(trace)
---> 20 pm.waic(trace)

~/anaconda3/lib/python3.7/site-packages/pymc3/stats/__init__.py in wrapped(*args, **kwargs)
     22                 )
     23                 kwargs[new] = kwargs.pop(old)
---> 24             return func(*args, **kwargs)
     25 
     26     return wrapped

~/anaconda3/lib/python3.7/site-packages/arviz/stats/stats.py in waic(data, pointwise, scale)
   1162             )
   1163     if "log_likelihood" not in inference_data.sample_stats:
-> 1164         raise TypeError("Data must include log_likelihood in sample_stats")
   1165     log_likelihood = inference_data.sample_stats.log_likelihood
   1166 

TypeError: Data must include log_likelihood in sample_stats`
```
But the trace_sample_stats contains the `model_logp`. I think arviz is not happy with this name. Please help with this.
Thank you.

**Comment by nanditakhetan** [comment]
Hi @OriolAbril ,
Thanks for your answer.  I have two observed variables. Below is my code:
`# X1, X2, X3, mod = observed features/data for the  sample 1 
# eX1, eX2, eX3, emod = their observed errors
# Y1, Y2, Y3 = same data fields as Xs observed for the sample 2
# eY1, eY2, eY3 = their observed errors
# mB1 (e1), mB2(e2) = also observed data(errors) for sample 1 and sample 2 respectively
# P0, P1, P2, P3, H0 = model parameters
# z = observed feature of sample 2

# contants
c = 299792.458
q0 = -0.55

with pm.Model():
    # priors
    P0 = pm.Uniform('P0', lower = -30, upper = 30)
    P1 = pm.Uniform('P1', lower = -5, upper = 5)
    P2 = pm.Uniform('P2', lower = 0, upper = 15)
    P3 = pm.Uniform('P3', lower = -2, upper = 2)
    H0 = pm.Uniform('A0', lower = 40, upper = 100)
    ext1 = pm.HalfCauchy('ext1', 5)            # extra scatter in sample 1
    ext2 = pm.HalfCauchy('ext2', 5)            #extra scatter in smaple 2
    

    
    
    # model
    mu1 = P0 + P1*(X1) + P2*(X2) + P3(X3) + mod
    mu2 = P0 + P1*(Y1) + P2*(Y2) + P3(Y3) + 5*np.log10((c*z/H0)*(1 + 1/2*(1- q0)*z)) + 25
    
    # sigma
    sigma1 = np.sqrt(e1 ** 2 + ext1**2 + emod**2 + (P1*eX1)**2 + (P2*eX2)**2 + (P3*eX3))
    sigma2 = np.sqrt(e2 ** 2 + ext2**2 + (P1*eY1)**2 + (P2*eY2)**2 + (P3*eY3))
    
    # likelihood
    like0 = pm.Normal('like0', mu1, sigma1, observed = mB1)
    like1 = pm.Normal('like1', mu2, sigma2, observed = mB2)
    
    
    Nsamples = 1000  # final number of samples
    Ntune = 2000  # number of tuning samples

    # perform sampling
    trace = pm.sample(Nsamples, tune=Ntune, discard_tuned_samples=True, cores=4,target_accept=0.9); 

    print(pm.summary(trace))
    
# mod is equivalent to the func(H0, z). `

I updated the arviz to 0.8.3 and now I get the error that you mentioned-
`TypeError: Found several log likelihood arrays ['results0', 'results1'], var_name cannot be None`

For the log likelihood, I think I got confused being a novice. This page  [https://docs.pymc.io/notebooks/sampler-stats.html](url) mentions
 model_logp: The model log-likelihood for this sample.
Can you help me how I can get likelihood values for hierarchical models and calculate BIC or WAIC. 
Thanks a lot.
