### ISSUE TITLE
use pandas.DataFrame, as interface between sampling library and mcmcplotlib

### ISSUE THREAD

**Issue by Volodymyrk** [arviz-devs/arviz#4]
Since DataFrames are simply indexed and labelled numpy arrays (from memory and performance point of view, at least), why don't we use DFs as interface between tracing library and plotting?

e.g. the code might look like this:

```
import pymc3 as pm
import mcmcplotlib as mcp

with pm.Model() as model:
  .. 
  trace = pm.sample(2000..)

trace_df = trace.as_df(varnames=['Intercept', 'x', 'sigma'])

mcp.plot_trace(trace_df, varnames=['x', 'sigma']) #e.g. we are not interested in plotting intercept
```

So that mcmcplotlib don't have to know about library-specific trace object(s).
And we don't have to pass a list of numpy arrays + list of varnames for plotting.

I believe it is a safe assumption that most users of pymc, pystan and emcee have pandas installed.

**Comment by ariddell** [comment]
If we can avoid the dependency (or have a fallback), I'd strongly prefer that. There are many (probably not a majority) users of pystan/pymc/emcee which will not have pandas installed.

**Comment by twiecki** [comment]
I think `pandas` is a perfectly reasonable dependency these days.

**Comment by Volodymyrk** [comment]
(strong personal opinion warning)
I believe the whole PyData ecosystem is somewhat crippled by reluctance to use pandas as standard way to access (panel) data. IMO, Scikit-learn should be tightly integrated with pandas, as well as other libraries. And since pandas can act as interface, while something like dask can be an engine, we should embrace it. I like patsy, since it can reduce the amount of boiler plate and does not afraid to be dependant on pandas. In this regard, R has an edge, since dataframes is a standard data interface (as far as I know).

The purpose of mcmcplotlib is to be used in interactive environment, like jupyter, where anaconda is normally used. pystan/pymc/emcee can be used in pure server-side code or ETL, where pandas might not be as relevant, but the output is probably just data, not pretty charts..

I am generally against backward compatibilities, if that means more code to support or (go forbid) more boiler plate for user to write.

**Comment by aloctavodia** [comment]
I agree Pandas is a very reasonable dependency nowadays. I think the same
goes for seaborn.

**Comment by Volodymyrk** [comment]
I do agree that we should not re-implement stuff that is available in seaborn already (even though I don't like 200+ lines functions in seaborn).
I don't like that seaborn imports it's style by default, and I don't want to change users mpl default when importing mcmcplotlib, if we can avoid it. Also, seaborn is not installed with anaconda by default atm.

**Comment by ahartikainen** [comment]
seaborn without style changes

> import seaborn.apionly as sns

**Comment by aseyboldt** [comment]
If we want to go for labeled data (and I think especially for plotting labels are super important), we could also represent the trace as a xarray dataset. Using pandas isn't all that straight forward, as it doesn't have multidimensional dataframes, but the output from mcmc always always has more than 2 dimensions. (see also https://discourse.pymc.io/t/use-xarray-for-traces/73)
xarray is mentioned as the official replacement for pd.Panel in the pandas docs.
I've been using xarray to store traces for some time now in various projects, and this turned out to be really useful.

**Comment by twiecki** [comment]
+1 on using xarray as the central interface.

**Comment by ahartikainen** [comment]
+1 for xarray

Which interface?
- xarray
- list of xarrays (xarray.name(?) parameter)
- (o)dict of xarrays (key=parameter name)?

Can xarray handle scalars, vectors and matrices in the same object?

**Comment by aseyboldt** [comment]
@ahartikainen 
A trace can be represented by a `xr.Dataset` very well. It acts a lot like a dict from varname to `xr.DataArray`, so it is already similar to our current trace object in many ways. See http://xarray.pydata.org/en/stable/data-structures.html

**Comment by aloctavodia** [comment]
Closing as we have adopted xarray as interface
