### ISSUE TITLE
Plot PyMC3 prior?

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#401]
Is this possible in the current version of Arviz?  It looks like the answer is something like "no, but almost."  There doesn't seem to be any way for me to tell plot_density to plot the `prior` instead of the `posterior`.  I don't know if that would be enough to make this work.
The PyMC3 repo says that plotting the prior should be left to Arviz in a closed issue there, but I wasn't able to find a corresponding ticket here.
Thanks!

**Comment by ahartikainen** [comment]
Hi, Inference data has a field for `prior`/`prior_predictive`, but currently it is not defined which group should be used for plotting. 

One could send InferenceData.prior to the function, but I think we should add a keyword to accept which groups should be used.

**Comment by rpgoldman** [comment]
TBQH, I don't fully understand the `plot_density` function.  It _seems_ like I could just add `group="posterior"` to the arguments and replace use of `"posterior"` with `group`.

But there an oddity of trying to convert the `data` argument in lines 84-88 that I don't get.  I think part of the problem is that I don't understand the distinction between a `dataset` and an `InferenceData`.  There are two functions, `convert_to_dataset` and `convert_to_inference_data`.  Reading the docstrings, I see that The former returns an `xarray.Dataset` and the latter and `InferenceData`, but the former also says that if its argument is an `InferenceData` object, it will be returned unchanged.

**Comment by ahartikainen** [comment]
convert will give you InferenceData which defaults to posterior group.

**Comment by rpgoldman** [comment]
Please have a peek at #403 (assuming it passes tests), and let me know if this does the job, thanks!

**Comment by rpgoldman** [comment]
`black` didn't like my formatting, but otherwise it looks like my change passes the tests.  I have force-pushed an update.

**Comment by ColCarroll** [comment]
Marking this as closed from your contribution #403, but there are a few more places where we might do that same thing.
