### ISSUE TITLE
Question about plot_density docs

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#404]
The `plot_density` docstring has the following:

```
    data : obj
        Any object that can be converted to an az.InferenceData object
        Refer to documentation of az.convert_to_dataset for details
    data_labels : list[str]
        List with names for the samples in the list of datasets. Useful when
        plotting more than one trace.
```
I'm confused by this because the `data` entity seems to be a _singleton_, but then the docstring for `data_labels` refers to "the list of datasets."  Would it be possible to clarify this?

I'm asking because I *think* the `data_labels` parameter lets us (indirectly) control the subplots layout (which otherwise cannot be controlled, I believe), and the default layout isn't working for me.

Specifically, I have 3 sets of 4 variables each, which I would like to line up so I can visually scan between the corresponding variables.  But arviz wants to lay them out in 4 rows of three, which puts them out of sync.  The only way I know to give the variables is as one 12 length list, so I don't see how to give `plot_density` an indication of how I would like these plotted.

Any advice welcome!

**Comment by rpgoldman** [comment]
@canyon289 I misinterpreted the `data_labels` -- they _do_ let us control the layout, but only for the case of having multiple data sets, *not* multiple selections of variables from a single data set.

I _think_ for what I would like I should take a single dataset and break it into multiple data sets, each with a different set of variables in it.

Unfortunately, it's not obvious to me how to make this kind of down-selection (probably because I have never used `xarray`s).  Maybe this can be done with the `coords` or `dims` arguments to `convert_to_dataset`, but I don't know how.

Would it be reasonable to extend `convert_to_dataset` to support selection of a subset of variables?  Or is there some easier way to do this?

If this were possible, I could get the result I want as follows:
```
# varsets are all of the same length...
ds1 = convert_to_dataset(data, group='prior', vars=varset1)
ds2 = convert_to_dataset(data, group='prior', vars=varset2)
ds3 = convert_to_dataset(data, group='prior', vars=varset3)
plot_density([ds1,ds2,ds3], ['plate 1', 'plate 2', 'plate 3'])
```
and the layout would work out as I like.

**Comment by canyon289** [comment]
@rpgoldman was this fixed by https://github.com/arviz-devs/arviz/pull/403?

**Comment by rpgoldman** [comment]
Yes, I believe so. I don't know yet about the variable selection -- I haven't had time to figure out the dependency tail (xdarray) yet.

**Comment by canyon289** [comment]
Based on latest response closing. We can reopen if needed
