### ISSUE TITLE
Pip installation broken

### ISSUE THREAD

**Issue by Bonnevie** [arviz-devs/arviz#41]
Simple problem: the pip install in the readme does not work at the moment. It seems to be a problem with the two relative import statements in `__init__.py`:

```
from .plots import *
from .stats import *
```

**Comment by aloctavodia** [comment]
Thanks for the report. Last time I check it works for me, I will test it again ASAP. In the meantime feel free to send a PR if you want.

**Comment by ahartikainen** [comment]
Needs update for packages in `setup.py`

    packages=['arviz', 
              'arviz.plots', 
              'arviz.stats',
              'arviz.utils',
             ],
