### ISSUE TITLE
Do not push docs if they are broken

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#416]
**Describe the bug**
If the example suite breaks, this brings down https://arviz-devs.github.io/arviz/

**Suggestions to fix**
- Add `make html` to the test suite somehow?
- Figure out how to make travis-sphinx only push on success?

**Comment by canyon289** [comment]
My half baked suggestion
* Try catch in example generator

**Comment by OriolAbril** [comment]
Is this still an issue?

**Comment by ColCarroll** [comment]
I _think_ it is, but I also think without checking:
- Docs are built on merge
- There is no rollback logic when building docs

In PyMC3 we do not build on merge, and someone just remembers to build and push docs every once in a while (like, after a release). You could imagine automating this, though!
