### ISSUE TITLE
Allow normalization in plot_parallel

### ISSUE THREAD

**Issue by aseyboldt** [arviz-devs/arviz#419]
It would be great if plot_parallel had a keyword arg `normalize` (or standardize), that centers and rescales the variables before plotting. That would make it easier to see things if some posteriors are much more tight than others:
![grafik](https://user-images.githubusercontent.com/1882397/48769279-83424d00-ecbb-11e8-8bf3-f1df15455cd0.png)

**Comment by ahartikainen** [comment]
normalize --> `(x -np.mean(x))/np.std(x)`

minmax --> `(x-min(x))/(max(x)-min(x))`

uniform --> `ecdf(x)[x]`  <-- `inverse_ecdf_x(x)`

**Comment by aseyboldt** [comment]
So we add a kwarg with those three options as string? What should it be called? Maybe `rescale`? We could use `normalize` if it is `True`.
`bayesplot` supports arbitrary transformations passed as a list of functions, I guess we could do the same. But calling it `transformation` could be confusing because we already have transformed variables, and we might want a log transform *and* a normalization in some cases.

**Comment by aseyboldt** [comment]
Oh, and maybe instead of a `uniform` we could use `quantile` and also change the y-axis labels appropriately.

**Comment by ahartikainen** [comment]
Oh: uniform --> ecdf(x)[x] <-- inverse_ecdf_x(x) --> is named as `rank`
