### ISSUE TITLE
Add more instructions on how to use docker for local dev

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#421]
## Tell us about it
Docker helps install ArviZ consistently across environments and can be used for local dev.

Adding instructions on how to use the container would be great.
Adding to the bash script to automatically start a notebook on a port would be better

**Comment by OriolAbril** [comment]
I will restart work on this issue soon with the goal of definitely closing it. Here is the list of changes I have in mind, feel free to add some more to the list:

* Change the option of `container.sh` from `--clear_cache` to `--clear-cache`: I think it is much more intuitively like this, as it follows the usual style for this kind of commands. I still have to decide between leaving the current option like this anyways, or make `--clear_cache` print something like "Please run --clear-cache".
* Remove the section about docker in README and leave a single line referring to CONTRIBUTING
* Add explanation about copying files from the container to the host machine. Thus, it will be possible to use docker for development.

Also, I have found that in some cases I cannot execute `pip install .` even though I have created the container with a clear cache before, but running `container.sh --clear_cache` again solves the problem. Has anybody experienced this problem, I am not sure if it is worth mentioning (as there is always the possibility of my memory betraying me).
