### ISSUE TITLE
Incompatibility with emcee3 pre-release

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#425]
Trying to use the `from_emcee()` function raises the following error for `emcee3`:

> AttributeError: 'EnsembleSampler' object has no attribute 'args'

This is due to line 29 in `io_emcee.py`:

    num_args = len(sampler.args)

In version 2, the EnsembleSampler class stored this information, but only to pass this to `_function_wrapper` class, which also stored the same information. This wrapper was for the posterior probability, so, `sampler.args` is equivalent to `sampler.lnprobfn.args`.

In version 3, this has been slightly modified, and now only the `_FunctionWrapper` class stores this information, however, its name has also been modified, so in this case it should be retrieved with `sampler.log_prob_fn.args`.

**Comment by ahartikainen** [comment]
Are there any other changes? Is `hasattr` enough to extract correct information?

**Comment by OriolAbril** [comment]
I modified 2 lines of the `io_emcee.py` and now it seems to work also with `emcee` version 3. I changed line 30 to:

    num_args = len(sampler.args) if hasattr(sampler,'args') else len(sampler.log_prob_fn.args)

and line 78 to:

    data[var_name] = self.sampler.args[idx] if hasattr(self.sampler,'args') else self.sampler.log_prob_fn.args[idx]

I don' know if this would be the preferred way, or a `try` statement.

**Comment by canyon289** [comment]
I think this is fine! Feel free to make a PR if you'd like
