### ISSUE TITLE
Add testing for emcee3

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#427]
**Describe the bug**
A feature was recently merged that allows for emcee3 models to be converted to InferenceData but a test was not implemented

**Expected behavior**
A test environment for emcee3 should potentially be added. One challenge to consider is the number of environments we need to test in, it may get out of hand quickly. Opening this issue for discussion,

**Additional context**
https://github.com/arviz-devs/arviz/pull/426

**Comment by ahartikainen** [comment]
Can we do this with other special libs?

**Comment by OriolAbril** [comment]
It looks like this was already fixed in #564
