### ISSUE TITLE
Doc generation process is broken

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#429]
**Describe the bug**
ArviZ docs are failing to build locally, and on TravisCI. I believe a recent change to our styles may have caused this. Really not sure though https://github.com/arviz-devs/arviz/pull/414

**To Reproduce**
run `make clean && make html` in docs folder

**Expected behavior**
Docs are generated

**Additional context**
ArviZ commit hash used for testing is e7315e5

> (arviz) arviz_user@arviz_user-MS-7A59:~/repos/arviz/doc$ make clean && make html
> Removing everything under '_build'...
> Running Sphinx v1.8.1
> making output directory...
> [autosummary] generating autosummary for: about.rst, api.rst, examples/index.rst, examples/plot_autocorr.rst, examples/plot_compare.rst, examples/plot_density.rst, examples/plot_energy.rst, examples/plot_forest.rst, examples/plot_forest_ridge.rst, examples/plot_joint.rst, ..., generated/arviz.psislw.rst, generated/arviz.r2_score.rst, generated/arviz.summary.rst, generated/arviz.waic.rst, index.rst, notebooks/InferenceDataCookbook.ipynb, notebooks/Introduction.ipynb, notebooks/XarrayforArviZ.ipynb, roadmap.rst, usage.rst
> skipping /home/arviz_user/repos/arviz/examples/plot_autocorr.py
> skipping /home/arviz_user/repos/arviz/examples/plot_compare.py
> skipping /home/arviz_user/repos/arviz/examples/plot_density.py
> skipping /home/arviz_user/repos/arviz/examples/plot_energy.py
> skipping /home/arviz_user/repos/arviz/examples/plot_forest.py
> skipping /home/arviz_user/repos/arviz/examples/plot_forest_ridge.py
> skipping /home/arviz_user/repos/arviz/examples/plot_joint.py
> skipping /home/arviz_user/repos/arviz/examples/plot_kde.py
> skipping /home/arviz_user/repos/arviz/examples/plot_kde_2d.py
> skipping /home/arviz_user/repos/arviz/examples/plot_pair.py
> skipping /home/arviz_user/repos/arviz/examples/plot_pair_hex.py
> skipping /home/arviz_user/repos/arviz/examples/plot_pair_kde.py
> skipping /home/arviz_user/repos/arviz/examples/plot_parallel.py
> skipping /home/arviz_user/repos/arviz/examples/plot_posterior.py
> skipping /home/arviz_user/repos/arviz/examples/plot_ppc.py
> skipping /home/arviz_user/repos/arviz/examples/plot_ppc_cumulative.py
> skipping /home/arviz_user/repos/arviz/examples/plot_trace.py
> skipping /home/arviz_user/repos/arviz/examples/plot_violin.py
> running /home/arviz_user/repos/arviz/examples/styles.py
> 
> Exception occurred:
>   File "/home/arviz_user/miniconda3/envs/arviz/lib/python3.6/site-packages/matplotlib/style/core.py", line 117, in use
>     "available styles".format(style))
> OSError: 'arviz-colors' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
> The full traceback has been saved in /tmp/sphinx-err-9n0htm8r.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:20: recipe for target 'html' failed
> make: *** [html] Error 2
> (arviz) arviz_user@arviz_user-MS-7A59:~/repos/arviz/doc$ 
>

**Comment by canyon289** [comment]
This work on my macbook, but not my desktop.......

Will dig in further

**Comment by ahartikainen** [comment]
Are we missing sys.insert in `doc/conf.py`

https://stackoverflow.com/questions/10324393/sphinx-build-fail-autodoc-cant-import-find-module

**Comment by canyon289** [comment]
Good lead! I will try this.

In regards your ask for 
`print(plt.style.available)`

The output includes the ArviZ styles
> ['seaborn-poster', 'fast', 'seaborn-ticks', 'dark_background', 'seaborn-paper', 'seaborn', 'seaborn-dark-palette', 'seaborn-whitegrid', 'ggplot', 'seaborn-white', 'seaborn-colorblind', 'Solarize_Light2', 'seaborn-talk', 'seaborn-dark', 'tableau-colorblind10', 'classic', 'fivethirtyeight', 'seaborn-muted', 'seaborn-notebook', 'seaborn-darkgrid', 'seaborn-pastel', 'seaborn-deep', 'seaborn-bright', '_classic_test', 'grayscale', 'bmh', 'arviz-darkgrid', 'arviz-whitegrid']

I have enough leads to work through this now and will report back if I have more questions!

**Comment by canyon289** [comment]
Annddd it turns out that I messed up my environment. Everything is fine. I apologize for the trouble.
