### ISSUE TITLE
Arviz Cookbook missing example for cmdstan

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#437]
## Tell us about it

ArviZ cookbook is missing examples for cmdstan.

## Thoughts on implementation
Add an example to this notebook https://arviz-devs.github.io/arviz/notebooks/InferenceDataCookbook.html

**Comment by ahartikainen** [comment]
I think I will try to do small example later this week.

**Comment by OriolAbril** [comment]
I'm closing this as it was fixed in #783

**Comment by jsevo** [comment]
This should be reopened. The referenced fix in #783 contains a dead link.

https://arviz-devs.github.io/arviz/generated/arviz.from_cmdstan.html#arviz.from_cmdstan

**Comment by ahartikainen** [comment]
Our docs have been updated

Correct link is

https://arviz-devs.github.io/arviz/getting_started/InferenceDataCookbook.html#from-cmdstan
