### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#44]
Probably a little bit too early, but is nice to have a logo. What do you think? @twiecki @ahartikainen 

![arviz_logo_00](https://user-images.githubusercontent.com/1338958/38386529-4a4a87ee-38eb-11e8-95a0-0cdd46c8d50e.png)

This logo gets 3 :100: at PyMC3's slack channel and I did not vote! :smile:

**Comment by ahartikainen** [comment]
Looks cool. 

Shape: ok, color: not sure

**Comment by aloctavodia** [comment]
I generally like strong-vivid colors (and also black), but for some reason I like this cyan-white combination :-) 

other options I tried were:

![arviz_logo_00b](https://user-images.githubusercontent.com/1338958/38388041-61505676-38f0-11e8-81b4-777ee1aea089.png)
![arviz_logo_00n](https://user-images.githubusercontent.com/1338958/38387770-59626ca2-38ef-11e8-871f-7ceb4fe9ade8.png)
![arviz_logo_00r](https://user-images.githubusercontent.com/1338958/38387771-598d91ac-38ef-11e8-9dfe-73de94b37f83.png)
![arviz_logo_00v](https://user-images.githubusercontent.com/1338958/38387772-59bb5f38-38ef-11e8-85fb-6085f2fd5c16.png)

**Comment by ahartikainen** [comment]
Cyan is the best from those. It's ok for me.

**Comment by aloctavodia** [comment]
The hex code is #17becf (C10 using  the default matplotlib's color cycle)

This is the code. 

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.transforms import Bbox
from scipy import stats

distri = stats.beta(2, 5)
x = np.linspace(0, 1, 200)
pdfx = distri.pdf(x)

plt.fill_between(x, pdfx, color='C10', lw=0)
plt.text(x=0.04, y=-0.01, s='ArviZ', fontdict={'name':'ubuntu mono', 'fontsize':62}, color='w')
plt.axis('off')
plt.ylim(0, 5.5)
plt.xlim(0, 0.9)

bbox = Bbox([[0.75, 0.5], [5.4, 2.2]])
plt.savefig('logo_00.png', dpi=300,  bbox_inches=bbox)
```

**Comment by ColCarroll** [comment]
This is using "PyMC3 blue" (#12698A), though I think I still prefer the cyan

![logo_00](https://user-images.githubusercontent.com/2295568/38468335-2c71bca0-3b12-11e8-9206-800137e1762b.png)

**Comment by aloctavodia** [comment]
Against all odds, cyan seems unbeatable! :-)

**Comment by ColCarroll** [comment]
Was playing with ObservableHQ today and built this: https://beta.observablehq.com/@colcarroll/arviz-logo

**Comment by aloctavodia** [comment]
Cool! I can't change the font size

**Comment by twiecki** [comment]
I like Cyan but also "PyMC3 blue" actually.

**Comment by aloctavodia** [comment]
Given that ArviZ is intended to be used beyond PyMC3, I suggest to avoid using "PyMC3 blue".

**Comment by twiecki** [comment]
But that's very subtle,no one would notice and I think it's a nice Easter
egg to show its origin.

**Comment by aloctavodia** [comment]
You are right, is just a minor detail.

**Comment by twiecki** [comment]
I like that one a lot!

**Comment by aloctavodia** [comment]
So, we have a winner! Thanks you all, guys.

```python
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.transforms import Bbox
from matplotlib.path import Path
from matplotlib.patches import PathPatch
from scipy import stats

distri = stats.beta(2, 5)
x = np.linspace(0, 1, 200)
pdfx = distri.pdf(x)

path = Path(np.array([x, pdfx]).transpose())
patch = PathPatch(path, facecolor='none', alpha=0)
plt.gca().add_patch(patch)

cmap = matplotlib.colors.LinearSegmentedColormap.from_list('', ["#00bfbf", "#00bfbf", "#126a8a"])

im = plt.imshow(np.array([[1, 0, 0], [1, 1, 0]]),
                cmap=cmap, interpolation='bicubic',
                origin='lower',extent=[0,1, 0.0, 5],
                aspect="auto", clip_path=patch, clip_on=True)
plt.text(x=0.04, y=-0.01, s='ArviZ', fontdict={'name':'ubuntu mono', 'fontsize':62}, color='w')

plt.axis('off')
plt.ylim(0, 5.5)
plt.xlim(0, 0.9)

bbox = Bbox([[0.75, 0.5], [5.4, 2.2]])

plt.savefig('logo.png', dpi=300,  bbox_inches=bbox, transparent=True)
```
