### ISSUE TITLE
Introduce burn-in parameter in `from_emcee`

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#451]
Most of the mcmc sampling functions have some kind of _tune_ or _warmup_ phase before the actual sampling, whereas in emcee, the burn-in is done after the sample discarding some of them, cutting the resulting array in the draws dimension. 

It may also be interesting to allow a thinning coefficient, because the samples are not independent, in order to be able to mimic completely the emcee3 `get_chain()` method.

I don't think it should be much of a problem because the array returned by emcee always has 3 dimensions: `(nwalkers, draws, ndim)`. I can give it a go.

**Comment by ahartikainen** [comment]
Burn-in sounds good. 

Thinning also, but are the cases where it is a good idea? Thinning just hides the problems with sampling.

**Comment by kyleabeauchamp** [comment]
IIRC, thinning is the least bad idea when you are RAM-limited and want to fill system memory with `n_effective` decorrelated samples rather than `n` samples.
