### ISSUE TITLE
Show rugplot example in plot_kde

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#468]
## Tell us about it
For plot_kde, a demo of rugplot in the inline docs would be helpful.

Current docs
https://arviz-devs.github.io/arviz/generated/arviz.plot_kde.html#arviz.plot_kde

PR demoing functionality is here
https://github.com/arviz-devs/arviz/pull/398

## Thoughts on implementation
Modify the sphinx code in `az.plot_kde` to add a rugplot example

**Comment by Shashankjain12** [comment]
Is this issue still open!?

**Comment by ColCarroll** [comment]
Thanks for catching -- looks like it was fixed by #565
