### ISSUE TITLE
Improve API for plot_kde when used with inference data

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#470]
## Tell us about it
Two issues
1. `plot_kde` is awkward to use with `az.InferenceData` objects as it requires a coercion to a numpy array to work
2. Rug plots cause an exception in the following

Code to reproduce
```
import arviz as az
eight = az.load_arviz_data("centered_eight")
az.plot_kde(eight.posterior.to_array(), rug=True)

```
## Thoughts on implementation
Would be nice to implement a group and fix rugplot exception

**Comment by Ban-zee** [comment]
A few questions:
1)Will the group be specified by the user ? (I guess it will be) 
2)For a given group with n data variables, there should be n rugplots included in the same plot, right?

**Comment by aloctavodia** [comment]
Not sure changing `plot_kde` is the best approach, why not adapting `plot_posterior`?

**Comment by Ban-zee** [comment]
Maybe raise an exception when the user tries to use `plot_kde` on an inference data object, directing them to use the `plot_posterior` instead?
