### ISSUE TITLE
README doesn't mention non-master installation instructions.

### ISSUE THREAD

**Issue by malmaud** [arviz-devs/arviz#481]
In the README installation section, you don't mention `pip install arviz` as the way of installing the release version. I know it seems trivial, but some people might not realize if the instructions aren't explicit.

**Comment by ahartikainen** [comment]
Oh, we have forgot to update readme.

Do you want to do a PR?

**Comment by canyon289** [comment]
Definitely not trivial. This is a good suggestion.

**Comment by canyon289** [comment]
Closed by https://github.com/arviz-devs/arviz/pull/482
