### ISSUE TITLE
Better behavior with empty InferenceData

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#486]
**Describe the bug**
An empty `InferenceData` object does not save at all, but will act as though it saved something. I think, but haven't checked, that this is because there is a loop over groups, and if there are no groups, we never save anything. 

**To Reproduce**
```
import arviz as az
import os

filename = 'test.nc'
print(os.path.exists(filename))  # False
data = az.InferenceData()
filename = data.to_netcdf(filename)
print(os.path.exists(filename))  # False
print(filename)  # test.nc
```
**Expected behavior**
I would expect `test.nc` to exist on disk, as an empty netcdf file (or whatever happens when `save` is called on an empty netcdf file).

**Comment by vishal3410** [comment]
Hi, @ColCarroll  I would like to take up this issue

**Comment by LakshyAAAgrawal** [comment]
Hey, is this issue still unresolved. If it is, I would like to take it up. Could someone point me in the right direction please?

**Comment by canyon289** [comment]
@LakshyAAAgrawal This was closed by https://github.com/arviz-devs/arviz/pull/577

Apologies on not closing this issue
