### ISSUE TITLE
Normalize loading of data

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#487]
All `from_xyz` should follow approximately the same format.

    az.from_xyz(posterior=None, *, posterior_predictive=None, prior=None, prior_predictive=None, log_likelihood=None, ...)

I think library dependent names are okay, but I would prefer names posterior/prior for objects containing samples. (Open for discussion)

Also `az.from_netcdf(path)`/`az.to_netcdf(obj, path, compress)` might be good functions to have.

**Comment by canyon289** [comment]
This issue can be referred to as well  

https://github.com/arviz-devs/arviz/issues/391

**Comment by ahartikainen** [comment]
Fixed by #490
