### ISSUE TITLE
All docstring should contain example usage

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#491]
All docstring should show example usage.

For `from_xyz` should contain some simple model (8-schools?), which would show the simplest use case (create `posterior`) and then more advanced example (`log_likelihood`, e.g.)

This (`from_xyz` docstring) then could show example how to plot trace and calculate summary for these models (`inference_data = az.from_xyz(posterior); az.summary(inference_data)`.

I think docstring can be long if `Examples` block comes after the `Parameters` & `Returns` blocks.

**Comment by canyon289** [comment]
Agreed, the docstring from `az.plot_posterior` is a good example

**Comment by OriolAbril** [comment]
@ahartikainen @canyon289 would [these examples](https://github.com/OriolAbril/arviz/tree/from_emcee_docs/doc/usage_examples) serve this purpose? I have trouble seeing the difference with the basic example and the cookbook. 

I know that emcee and ess is not the most easy-going combination, but I had it half done it already.

**Comment by OriolAbril** [comment]
I think this can be closed. 

Only methods missing example in docstring are `from_xyz` but they do redirect to the cookbook. We could add an issue to extend the cookbook to a notebook per library to explain the nits of each converter.
