### ISSUE TITLE
plot_joint() may have an error

### ISSUE THREAD

**Issue by rouninnomi** [arviz-devs/arviz#492]
Hello, I'm a newbie of Bayesian analysis, and I'm studying hard with a Osvaldo Martin's book. He provides codes on "https://github.com/aloctavodia/BAP/blob/master/code/Chp2/02%20Programming%20probabilistically.ipynb" and I executed, 

az.plot_joint(trace_g, kind='kde', fill_last=False)

in **Google Colaboratory**, but it failed with error messages like,

---> 86     fig, _ = plt.subplots(0, 0, figsize=figsize, constrained_layout=True)
TypeError: __init__() got an unexpected keyword argument 'constrained_layout'

Is it an error by plt.subplots function? I would be happy if you reply. Thank you.

**Comment by ahartikainen** [comment]
Matplotlib version should be 3.x? 

    import matplotlib
    matplotlib.__version__

**Comment by rouninnomi** [comment]
Dear Mr. Ahartikaine,

Thank you for your fast and kind reply! The codes you presented showed, '2.1.2'. 
I will re-import matplotlib ver 3.x!!

**Comment by ahartikainen** [comment]
To update matplotlib on Google Colab run following on the first cell before any imports

    !pip install matplotlib -U

**Comment by rouninnomi** [comment]
Wow! I appreciate your huge kindness!! 
I'll try this. Thank you very much again!
