### ISSUE TITLE
Examples and tests for stats.psislw and plot_khat

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#497]
khat functionality needs better documentation and examples.

**Comment by Ban-zee** [comment]
which dataset would be appropriate for documentation?

**Comment by ahartikainen** [comment]
I think we can start with 8-schools? Maybe wait until loo PR is done.

Also, we probably need to update `plot_khat` before we add these examples.

**Comment by Ban-zee** [comment]
Any good reading material about khat and Pareto's indices?

**Comment by ahartikainen** [comment]
See http://mc-stan.org/loo/articles/loo2-example.html and references mentioned there

**Comment by Ban-zee** [comment]
Thank you.
