### ISSUE TITLE
plot_posterior ref_val (and rope) format is weird

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#513]
I don't get this format. Can someone explain what is going on?

~~ref_val = {"mu" : {"school" : "Choate", "ref_val" : 0.3}~~

    ref_val = {"theta" : {"school" : "Choate", "ref_val" : 0.3}

It is not even possible to pass that `all`?

    elif isinstance(ref_val, dict):
        for sel in ref_val.get(var_name, []):
            if all(k in selection and selection[k] == v for k, v in sel.items()):
                val = sel["ref_val"]
                break

**Comment by canyon289** [comment]
@ColCarroll for this one

**Comment by canyon289** [comment]
Im planning on applying to Recurse Center. I'd like to use this issue as the pair program exercise. Is that alright by everyone?

**Comment by ahartikainen** [comment]
I think there could be different ways to do this

ref_val and rope should probably follow the same format (instead of number it uses (number, number)

    number <-- numbers.Number() # so any number
    var <-- variable name
    # global setting
    ref_val --> number --> all variables


    ref_val --> (var, number) --> var only (for all coords)
    ref_val --> (var, (coord, coord_val), number) --> var with specific coord
    ref_val --> (var, ((coord1, coord1_val), (coord2, coord2_val), ... ), number) --> var with specific coord combination

Then it could support multiple vars

    ref_val --> ((var1, var2, ...), number) --> (var1, var2, ... ) only (for all coords)
    ref_val --> ((var1, var2, ...), (coord, coord_val), number) --> (var1, var2, ... ) with specific coord
    ref_val --> ((var1, var2, ...), ((coord1, coord1_val), (coord2, coord2_val), ... ), number) --> (var1, var2, ... ) with specific coord combination

Then there is the problem how to combine these in a meaningful way. Like what if user wants to have a global setting + some specific ones... Can we use dictionary, and what if user uses the default key?

**Comment by canyon289** [comment]
I got rejected from Recurse Center so this one is up for grabs again. I may work on it when time allows

**Comment by ColCarroll** [comment]
Oops, just saw I was tagged on this 😬 . I will take a look again!

**Comment by aloctavodia** [comment]
pymc-devs/pymc3#3498
