### ISSUE TITLE
Add more documentation for how `--save` can be used with examples

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#516]
## Tell us about it

The functionality to save plots during tests exists. The documentation to make it clear doesn't

## Thoughts on implementation

Copying and pasting prior discussion here 

`pytest arviz/tests --save -k plot_forest`
the -k keyword will string match test function, class, and i think module names to just test those

https://docs.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-
their-name

**Comment by OriolAbril** [comment]
with #1331 maybe this could be added to the `testing arviz code` of the restructured docs?

**Comment by michaelraczycki** [comment]
@OriolAbril since #1331 is closed, should it also be closed or it's still open? If it's open I can do it

**Comment by OriolAbril** [comment]
it is still open, we did restructure the docs, but there are still many pages that were listed as potential additions that are missing. Here I would create a how-to page similar to https://python.arviz.org/en/latest/contributing/sphinx_doc_build.html but for tests and explain the use of --save there

**Comment by OriolAbril** [comment]
Also just realized this comment (and whole discussion in general) are related to this, and will be helpful for the "how to run the test suite" page: https://github.com/arviz-devs/arviz/discussions/2110#discussioncomment-3597958

**Comment by OriolAbril** [comment]
I documented that in arviz-plots: https://arviz-plots.readthedocs.io/en/latest/contributing/testing.html#saving-matplotlib-figures-generated-by-tests
