### ISSUE TITLE
Combine InferenceData object

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#519]
## Tell us about it

We should have the possibility to combine/merge inference data objects.

## Thoughts on implementation

We could support both `__add__` and specific function.

    posterior = az.convert_to_inference_data({'mu' : np.array([...])}, "posterior")
    posterior_predictive = az.convert_to_inference_data({'y_hat' : np.array([...])}, "posterior_predictive")
    inference_data = posterior + posterior_predictive

    inference_data = az.concat(posterior, posterior_predictive)

Easiest this would be if we by default support only combining individual groups (combine only if no groups overlap).
We could also have a possibility to add chains/draws or both.

**Comment by canyon289** [comment]
This is a great idea actually. I'm very in favor of this

**Comment by ahartikainen** [comment]
So some thoughts about implementation details

# ################
# Independent groups

## `A`
- `posterior`
- `posterior_predictive`

## `B`
- `prior`
- `prior_predictive`

## `C` = `A + B` / `az.concat((A, B), type="merge")`
- `posterior`
- `posterior_predictive`
- `prior`
- `prior_predictive`

# ##############
# Dependent groups

## `A`
- `posterior`

## `B`
- `posterior`

## `A + B` / `az.concat((A, B), type="merge")`
`ValueError("InferenceData groups need to be unique")`

# #################
# Append chains

## `A`
- `posterior`
    - mu (3 chains, 2000 draws)

## `B`
- `posterior`
    - mu (1 chain, 2000 draws)
- `posterior_predictive`

## `A * B` /  `az.concat((A, B), type="chains")
- `posterior`
    - mu (4 chains, 2000 draws
- `posterior_predictive`

# #######################
# Append chains and trim draws

## `A`
- `posterior`
    - mu (3 chains, 2000 draws)

## `B`
- `posterior`
    - mu (1 chain, 1000 draws)
- `posterior_predictive`

## `A * B` /  `az.concat((A, B), type="chains")
- `posterior`
    - mu (4 chains, 1000 draws
- `posterior_predictive`

# #####################
# Append chains missing data

## `A`
- `posterior`
    - mu (3 chains, 2000 draws)
    - eta (3 chains, 2000 draws)

## `B`
- `posterior`
    - mu (1 chain, 2000 draws)
- `posterior_predictive`

## `A * B` /  `az.concat((A, B), type="chains")
`ValueError("groups need to be identical with merge-with-chains")`

# #############################
# Append chains missing data with force

## `A`
- `posterior`
    - mu (3 chains, 2000 draws)
    - eta (3 chains, 2000 draws)

## `B`
- `posterior`
    - mu (1 chain, 2000 draws)
- `posterior_predictive`

## `A @ B` /  `az.concat((A, B), type="chains_nans")
- `posterior`
    - mu (4 chains, 2000 draws)
    - eta (4 chains, 2000 draws with 1 chain filled with NaN)
- `posterior_predictive`

# #############################
# Append chains missing data with force and do not trim draws

## `A`
- `posterior`
    - mu (3 chains, 2000 draws)
    - eta (3 chains, 2000 draws)

## `B`
- `posterior`
    - mu (1 chain, 1000 draws)
- `posterior_predictive`

## `A @ B` /  `az.concat((A, B), type="chains_nans")
- `posterior`
    - mu (4 chains, 2000 draws, 1 has 1000 draws filled with NaN)
    - eta (4 chains, 2000 draws,1 chain filled with NaN)
- `posterior_predictive`

**Comment by Ban-zee** [comment]
Should a value error be raised if there are two objects having the same group but different number of chains?

**Comment by ahartikainen** [comment]
Maybe. I don't think we have not decided which structure is simple enough to be useful.

**Comment by ahartikainen** [comment]
Partially closed by https://github.com/arviz-devs/arviz/pull/709

Other cases are "too hard" to have general solution.

For example, how should variables behave if they are missing the selected axis.

In future, if there is demand, we can create a convenience function to handle concat, where user supplied function is applied against all groups ::: not sure if this is really doable.
