### ISSUE TITLE
Include Zenodo and JOSS Badges in README and docs

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#535]
## Tell us about it

Add badge labels for Zenodo and JOSS to README and docs

https://zenodo.org/record/2540945#.XD5DP9-YXmE
https://github.com/openjournals/joss-reviews/issues/1143#issuecomment-454512886

## Thoughts on implementation

Code and be copied and pasted from both sources

**Comment by canyon289** [comment]
Closed by https://github.com/arviz-devs/arviz/pull/537

**Comment by canyon289** [comment]
Still need them on docs. Reopening.

I can do this unless someone beats me to it

**Comment by ahartikainen** [comment]
Fixed by #543
