### ISSUE TITLE
`SyntaxError: invalid syntax` upon import for arviz 0.3.2 Python==3.5.2

### ISSUE THREAD

**Issue by MFreidank** [arviz-devs/arviz#539]
**Describe the bug**
Simply importing `arviz` fails for the new release (< 1 day ago) `0.3.2`. Reverting to `0.3.1` makes the bug disappear. 

**To Reproduce**
`pip install arviz==0.3.2`
`python -c "import arviz"`

Fails with the following trace:
```
/home/moritz/projects/venv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/moritz/projects/venv/lib/python3.5/site-packages/arviz/__init__.py", line 22, in <module>
    from .data import *
  File "/home/moritz/projects/venv/lib/python3.5/site-packages/arviz/data/__init__.py", line 8, in <module>
    from .io_dict import from_dict
  File "/home/moritz/projects/venv/lib/python3.5/site-packages/arviz/data/io_dict.py", line 28
    ):
    ^
SyntaxError: invalid syntax
``` 

**Expected behavior**
The import should go through without error.

**Additional context**

`python --version`
Python 3.5.2
Arviz version: `0.3.2`
OS: Ubuntu 16.04 xenial

**Comment by MFreidank** [comment]
UPDATE: I believe that this is somehow related to *keyword-only* function definitions (as in `arviz.data.io_dict.DictConverter.__init__`. However, the following minimal example works with the same interpreter: 

```
#!/usr/bin/python3
# -*- coding: iso-8859-15 -*-
def f(
    a=None,
    *,
    b=None,
    c=None
):
    return a + b +c

print(f(10, b=20, c=30))  # prints `60` without error
```
Quite confused as to what is going on..

**Comment by ahartikainen** [comment]
Is there a trailing comma in arviz code?

**Comment by MFreidank** [comment]
@ahartikainen Yes! And I think you are on to something, because my minimal example (function `f` above) fails if I add a trailing comma. Should I quickly do a PR for this?

**Comment by ahartikainen** [comment]
Thanks, this is probably due to that we had this problem before, but travis told us to clean up this problem, then we changed to docker (which is great) but apparently we have failed with 3.5.

We have also a small problem with requirements.txt so it is good that we can fix this at the same time and make quickly a new bugfix release.

**Comment by MFreidank** [comment]
Cool, thanks a lot for your help and the idea to check for trailing commas. 
PR for this set of changes is out (#541).

**Comment by ahartikainen** [comment]
I will merge your PR and then rebase mine after master.

Thanks for noticing this.

**Comment by MFreidank** [comment]
Thanks again!
