### ISSUE TITLE
Testing without needed all libraries

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#553]
## Tell us about it

See if there's a way to test specific `io_functions` without requiring everything library

https://github.com/arviz-devs/arviz/pull/550

Implementation must require that if all tests are run, all libs must be installed. But there may be a clever way to test certain `to_xyz` methods without needing every dependency

## Thoughts on implementation
fixtures or skipifs could be helpful

**Comment by ahartikainen** [comment]
All imports just inside the class. (For test_xyz)

And try except for loading data file (both import and function where we iterate them).

Also need to change module names to str (in the loop) and then just check if global has that imported.

**Comment by ahartikainen** [comment]
And for plots let's use from dict (and save the data somewhere in json)?

**Comment by canyon289** [comment]
> And for plots let's use from dict (and save the data somewhere in json)?

I agree with this one. It's probably time to

**Comment by ahartikainen** [comment]
Closed by https://github.com/arviz-devs/arviz/pull/691
