### ISSUE TITLE
Variable order in forestplot and traceplot

### ISSUE THREAD

**Issue by denadai2** [arviz-devs/arviz#568]
I am using pystan to fit a multi-variate regression where y ~ Xb + a, and X is a n x p matrix.

Using arviz I plot the traces and the forestplot. 

    data = az.from_pystan(posterior=fit,
                          observed_data=['y'],
                          log_likelihood='log_lik',
                          posterior_predictive='y_pred',
                          coords={'features': features},
                          dims={'b': ['features']})

    # RESULTS
    model_name = make_model_name(args)

    print("PLOTTING")
    az.plot_trace(data, var_names=['b', 'a'])

However, the order of names of b (store in features) in the plot is never the same when I run the fit multiple times. How can impose it? Shouldn't the library impose an order? 

Thanks

**Comment by ahartikainen** [comment]
I think this is duplicate of this https://github.com/arviz-devs/arviz/issues/554

Current master has fixed the problem.

Still, thanks for reporting the bug.

**Comment by denadai2** [comment]
ahah nice, I'm too slow :P
