### ISSUE TITLE
Names of variables are weird in the traceplot

### ISSUE THREAD

**Issue by rosgori** [arviz-devs/arviz#580]
**Describe the bug**
The names of the variables are weird, at least when they are shown in plots.

**To Reproduce**
Go to this [site](https://github.com/aloctavodia/BAP/blob/master/code/Chp3/03_Modeling%20with%20Linear%20Regressions.ipynb). Search for `az.plot_trace(trace_mlr, var_names=varnames)`;  the plot is 
![trace_mlr](https://user-images.githubusercontent.com/33338133/52158527-15c17e00-2667-11e9-869b-51728c06fbda.png).

Now loot at this
![pp](https://user-images.githubusercontent.com/33338133/52158535-2eca2f00-2667-11e9-9684-67613eab7354.png)

**Expected behavior**
The variable should be shown as `a[0]` or `a_0` or `b[0]` or `b_1` in the trace plot. The names of each variable should be consistent with the names given in the summary.

**Additional context**
Version of `arviz`: 0.3.2

**Comment by ahartikainen** [comment]
Yeah, there is no one correct answer to this one.

What happens if you use 

    dims = {'alpha' : ["loc1"]}
    coordinates = {"loc1" : ["Hämeenkyrö", "Pietarsaari"]

And you have could have even more items.

**Comment by ahartikainen** [comment]
This needs more flexibility, some "hidden" kwarg or global kw that defines what information should go with the variable.

**Comment by OriolAbril** [comment]
Hi @rosgori, you can now customize the labels shown by ArviZ at will. See the [label guide](https://arviz-devs.github.io/arviz/user_guide/label_guide.html) for examples and usage. We have kept same default, plots use two lines for the variable name plus coordinate values, but you could use a custom labeller to have always the same labels you could use something like:

```
from arviz.labels import BaseLabeller

class OnlyFlatLabeller(BaseLabeller):
    def make_label_vert(self, var_name, sel, isel):
        return self.make_label_flat(self, var_name, sel, isel)
```
