### ISSUE TITLE
Option to draw line through zero in `plot_forest`

### ISSUE THREAD

**Issue by AlexIoannides** [arviz-devs/arviz#593]
Some models may have many parameters and `plot_forest` is a great way of visualising their posterior densities.

I often find it useful to know how far away from the origin (i.e. zero) the credible interval is. Although this is easy to do when the axis is visible on the screen, when there are many parameters involved this isn't the case.

Having the option to plot a vertical dashed-line through zero, would be really useful here (and greatly appreciated).

**Comment by ColCarroll** [comment]
Here are two ways of doing that right now. I tend to think the API is already a bit complicated, but would definitely agree that the first way (`rope=(0, 0)`) is a hack, and the second requires more matplotlib knowledge. 

I'm in favor of recommending one of these two approaches, but I'd be interested if you or others have an opinion about providing this as a "proper" argument.

![image](https://user-images.githubusercontent.com/2295568/53132291-54977500-353d-11e9-9ec2-b837d67c58f5.png)

**Comment by AlexIoannides** [comment]
The approach based on `rope=(0, 0)` works perfectly, but to be honest I didn't understand the definition of `rope` in order to be able to hack it.

Now that you point it out (it has been a long day), the `matplotlib` approach is pretty intuitive. If I had to recommend an approach, I'd go with this one.

Many thanks!

**Comment by canyon289** [comment]
@AlexIoannides Glad you got a solution

**Comment by aloctavodia** [comment]
Adding vertical lines at arbitrary values is a pretty common scenario, thus `plot_forest` should have an argument or we should add an example on how to do this using `axvline`

**Comment by clausherther** [comment]
Just found this issue googling for an answer to this same question. It doesn't seem `rope=(0, 0)` works anymore as a hack in the latest arviz (`0.15.1`). Was this closed but never implemented?
