### ISSUE TITLE
When using deterministic pymc3

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#598]
**Describe the bug**
When using `az.to_pymc3` on models that include `pm.Deterministic` with multiplication an extra coordinate appears in the trace data. This hampers plotting and other functionality.

@ColCarroll @aloctavodia any pointers as to what might be causing this issue? I can work on a fix

```
Dimensions:   (chain: 2, draw: 10, mu_dim_0: 2)
Coordinates:
  * chain     (chain) int64 0 1
  * draw      (draw) int64 0 1 2 3 4 5 6 7 8 9
  * mu_dim_0  (mu_dim_0) int64 0 1
Data variables:
    β         (chain, draw) float64 1.586 2.07 0.9763 ... 0.1682 -0.4153 0.5474
    mu        (chain, draw, mu_dim_0) float64 1.586 3.172 2.07 ... 0.5474 1.095
Attributes:
    created_at:                 2019-02-26T05:11:58.424637
    inference_library:          pymc3
    inference_library_version:  3.6
```

**To Reproduce**
```
import arviz as az
import pymc3 as pm
import numpy as np

x = [1,2]
y_real = x

with pm.Model() as model_g:
    β = pm.Normal('β', mu=0, sd=1)
    μ = pm.Deterministic('mu', x*β)
    y_pred = pm.Normal('y_pred', mu=μ, sd=1, observed=y_real)
    trace_g_non_centered_nuts = pm.sample(10)

non_centered_nuts = az.from_pymc3(trace=trace_g_non_centered_nuts)
print(non_centered_nuts.posterior)
```
**Expected behavior**
`mu_dim_0` should not appear

**Additional context**
ArviZ .3.3

**Comment by ahartikainen** [comment]
Jf the result is a column vector, it will create an extra dimensions. There is no nice way to handle this (for example pyro returns column vectors by default).

You need some way to make sure that the variable should be scalar and then you can trim extra dimensions.

This is also a problem with PyStan (all 1 dimensional axis are removed --> scalar / 1 item vector / 1 item row_vector / 1 item array >> look the same, until we get these informations explicitly from Stan).

All pplanguages should be explicit with the shapes of the variables.

**Comment by canyon289** [comment]
Thanks for the thoughtful response. I wonder if on the pymc3 side there's some way to inspect that the variable and "do the right thing" Clearly I'm vague on how that would happen
