### ISSUE TITLE
Changelog Tracking per PR

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#604]
## Tell us about it
It would be great to have a changelog line required for each PR. This would make releases much easier, and more complete

## Thoughts on implementation
Two ideas have been proposed
1. Wiki https://github.com/arviz-devs/arviz/wiki/Release-notes
Pros
* No merge conflicts
Cons
* Doesn't fit in PR process

2. Changelog MD
Pros and cons
* Opposite of wiki

**Comment by OriolAbril** [comment]
Changelog as a markdown file was added in #1011
