### ISSUE TITLE
Restrict the max number of plots by default

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#609]
Following discussion in #94, naively or inadvertently calling plotting functions for models with a large number of variables can easily hang a computer. Thus we may want to restrict by default the max number of plots. 

If possible it would be nice to set this at a global level and not per plot function

**Comment by ahartikainen** [comment]
So env variable

    ARVIZ_MAX_AXES

**Comment by canyon289** [comment]
ENV works. I want to throw in pandas style options as a proposal design as well
https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

**Comment by aloctavodia** [comment]
Notice that #679 addressed this for the particular case of traceplots

**Comment by ahartikainen** [comment]
Is this fixed?

**Comment by OriolAbril** [comment]
Not really, it is only fixed for `plot_trace` and should be done with all plots and with global options, not function specific.

**Comment by OriolAbril** [comment]
For future reference, this issue was actually fixed in #787.
