### ISSUE TITLE
plot_forest() should maintain the order of azdata

### ISSUE THREAD

**Issue by GWeindel** [arviz-devs/arviz#613]
**Describe the bug**
When using plot_forest the ordering of variable is not the same as the one in azdata. In my opinion order should be maintained across methods. I can take a look when I have a few spare minutes but currently I don't even understand how the order is determined.

**To Reproduce**
```
data = az.load_arviz_data('centered_eight')

data.posterior

<xarray.Dataset>
Dimensions:  (chain: 4, draw: 500, school: 8)
Coordinates:
  * chain    (chain) int64 0 1 2 3
  * draw     (draw) int64 0 1 2 3 4 5 6 7 8 ... 492 493 494 495 496 497 498 499
  * school   (school) object 'Choate' 'Deerfield' ... "St. Paul's" 'Mt. Hermon'
Data variables:
    mu       (chain, draw) float64 ...
    theta    (chain, draw, school) float64 ...
    tau      (chain, draw) float64 ...
Attributes:
    created_at:                 2018-10-03T14:26:54.822913
    inference_library:          pymc3
    inference_library_version:  3.5

_ = az.plot_forest(data=data, rope=(0,0), combined=True)
```
![demo](https://user-images.githubusercontent.com/28750455/54210026-0ee81f80-44df-11e9-9a4e-3feee9c74f48.png)

**Expected behavior**
The plot should begin with mu, then theta (starting with Choate school and ending with Mt. Hermon) and tau

**Additional context**
arviz 0.3.3

**Comment by GWeindel** [comment]
After some investigations I saw that the ordering is quasi random... when not specifying var_names. Hence the **first** problem is that :
```
if var_names is None:
     self.var_names = list(set.union(*[set(datum.data_vars) for datum in self.data]))
else:
     self.var_names = list(reversed(var_names))  # y-values are upside down
```
Here ```list(set.union)``` Breaks var_names order when var_names is not specified by the user (ordering of tau, mu and theta is random).

**Second** the same thing seems to happen for the sub_level (schools in this example) and I don't know where it comes from for now.
By the way the randomness also affects issue #614 so they could be linked.

**Comment by aloctavodia** [comment]
Thanks @GWeindel. Do you want to send a PR to fix this issue?

**Comment by GWeindel** [comment]
Sure, I just have to find a bit time to investigate the sub_level ordering and I send a PR for both.
