### ISSUE TITLE
add example about transforming and/or creating variables

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#641]
We should have at least one example about modifying, transforming and/or creating a variable before plotting, something like 

`data.posterior['log_temperature'] = np.log(data.posterior.temperature)`

`data.posterior['diff_temperature'] = data.posterior.temperature1 - data.posterior.temperature2`

**Comment by canyon289** [comment]
@aloctavodia I'll add an example in the xarray section of tutorial in the meanwhile

**Comment by corriebar** [comment]
Hey, I recently went through a few xarray tutorials to understand how to best modify and transform my posterior, so I would love to take this issue on to make it easier for the next one.
I can write something transformations such as @aloctavodia mentioned above, but also how to stack dimensions, group by dimension + aggregate, e.g. mean/median per group.

Where would be a good start for this? Just extend the section about inference data? Or the cookbook? Or better a new tutorial/notebook?

**Comment by ahartikainen** [comment]
Hi, sound great

Maybe a new notebook? e.g. "Working with the InferenceData" or something similar?

**Comment by corriebar** [comment]
Okay good, will do :)

**Comment by OriolAbril** [comment]
From a conversation in slack and wanted to suggest using `idata.posterior = idata.posterior.assign(...)` also, in addition to `idata.posterior["new_var"] = ...`, as assign allows to add multiple variables at the same time. Moreover, it could also be interesting to add some examples on using [`idata.map`](https://arviz-devs.github.io/arviz/generated/arviz.InferenceData.map.html#arviz.InferenceData.map) to transform variables in several groups at the same time and add them to the corresponding group.

**Comment by OriolAbril** [comment]
Closing in favour of #1486
