### ISSUE TITLE
Incorrect calculation of weight in `compare`

### ISSUE THREAD

**Issue by fonnesbeck** [arviz-devs/arviz#649]
There appears to be an issue when comparing models that have similar loo or waic values. The top two should have similar weights, but the slightly smaller one ends up with zero. 

<img width="506" alt="Screenshot 2019-04-22 11 42 33" src="https://user-images.githubusercontent.com/81476/56512065-eb5bc000-64f3-11e9-8126-a697a2711ff5.png">

I can't share this example, but will try to put together a reproducible one.

Running version 0.3.3.

**Comment by fonnesbeck** [comment]
OK, [here is a simple reproducible example](https://gist.github.com/f8b6d485b67436cbd08ed46e35bb22bb
). The models are almost identical, but the weight for the better one goes to one. If you change the second model to be a little more different (eg. change the sd to 2 instead of 1.1), it gets a more reasonable weight.

**Comment by fonnesbeck** [comment]
Easiest short-term solution is to make BB-pseudo-BMA the default; I think that's the most common approach anyhow.

**Comment by aloctavodia** [comment]
I always use "BB-pseudo-BMA" because "stacking" tends to add too much weight to a single model. Nevertheless, this example seems quite dramatic. I agree about making "BB-pseudo-BMA" the default, But I am also going to check if there is some error with the stacking implementation...

**Comment by fonnesbeck** [comment]
My example is dramatic because I intentionally made it that way. It occurs pretty routinely for me with real data (e.g. the screen shot above). 

I assume the problem has to do with numerical issues in `minimize`(?)

**Comment by canyon289** [comment]
@fonnesbeck Give it a try now and see if Osvaldo made your day :)
