### ISSUE TITLE
Default credible_interval clarification

### ISSUE THREAD

**Issue by hectormz** [arviz-devs/arviz#659]
This isn't exactly a proper issue, but wasn't sure where to put it. (Is there a place for discussion for Arviz like PyMC3's discourse?)

Is there a documented place on the Arviz site or documentation that details the default `credible_interval` of 0.94? I was confused about this until I read in @aloctavodia 's book that, "This is a friendly reminder of the arbitrary nature of the 95% value."

It would be nice to include this somewhere in public documentation. I thought I was missing something about the importance of 0.94.

**Comment by aloctavodia** [comment]
Hi @HectorM14 thanks for reporting this issue. We consider documentation an important part of a project, thus this a proper issue for us. We will address this issue.

**Comment by HectorM14** [comment]
Great, thanks!

**Comment by hectormz** [comment]
@aloctavodia @OriolAbril I forgot I brought this up! Since the introduction of `rcParam`, would updating the documentation be as simple as adding an inline comment in `arvizrc.template` for `stats.credible_interval` stating that it is just an arbitrarily selected value? If not set by the user, this value would be propagated to many functions, but if they went looking for the source, they might find it.

**Comment by OriolAbril** [comment]
I think rcparams template is a good place for the comment. We should probably also make sure docstrings of functions using credible interval say that default comes from rcParams, and maybe also find a way to add rcparams in the documentation.
