### ISSUE TITLE
Set Numpy Random Seed in one place for tests

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#661]
## Tell us about it
For test suite put `np.random.seed` in conftest.py so its available in all tests, eliminating duplication across various different tests

![image](https://user-images.githubusercontent.com/7213793/57230716-d8ee8580-6fcd-11e9-8ec1-b79c36cbf597.png)

## Thoughts on implementation
See above

**Comment by ahartikainen** [comment]
`np.seed` or `np.RandomState`?

Seed is probably safer option.

**Comment by canyon289** [comment]
Do those methods exist? I can only find this one ?
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html

**Comment by aloctavodia** [comment]
@canyon289 see here https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html
