### ISSUE TITLE
Issue with plot_posterior and pymc3

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#663]
**Describe the bug**
I get only empty plots when I try to plot a posterior predictive for more than one variable from an arviz data object created from pymc3.
**To Reproduce**
See [this gist](https://gist.github.com/rpgoldman/79286f8298fcffb9d790867a38ce6043)

**Expected behavior**
Expected to see plots of posterior predictive trace samples, but got empty axes.

**Additional context**

I have a conjecture about why this happened -- I believe it happens when there are 2D random variables.  In order to handle a multi-variable hierarchical model through a mixture of Gaussians, I have ended up with hyperparameter variables for different cases (e.g., there is one input with three values, one with four).  This means the preposterior sample trace for the variable has a 2000 (number of samples) by four by three matrix, which AFAICT Arviz can't plot.

**Comment by ahartikainen** [comment]
This sounds like a weird bug.

(We need to add more testing with nD structures)

**Comment by rpgoldman** [comment]
@ahartikainen TBQH, it's not clear to me from the documentation which plotting functions are compatible with/interact with which bits of the data object that are created by translation from pymc3.

I wonder if Arviz is having trouble because this is a dictionary produced by `sample_posterior_predictive` instead of a `MultiTrace` from the normal sampling process?

**Comment by rpgoldman** [comment]
Whoops. I'm sorry -- the backtrace is from me attempting to recreate the plotting "by hand".  Sorry. I will remove it.

**Comment by rpgoldman** [comment]
I'm going to close this issue: I think I mis-managed the interaction between matplotlib and arviz.  Sorry to bother you all.

**Comment by ahartikainen** [comment]
No worries, I was sleeping this time.

Good that it works. Maybe we could add some more documentation / tutorial to make it easier to use our package.
