### ISSUE TITLE
Add method to delete groups from InferenceData

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#666]
## Tell us about it
Add a method to delete groups from InferenceData

With many groups InferenceData can get quite large, making it hard to add to VCS or email. Things like sample_stats might not be needed for all results sharing. 

## Thoughts on implementation
1. Delete the object from `az.InferenceData` with `del` method in python
2. Remove string in `az.InferenceData._groups`

**Comment by ahartikainen** [comment]
Was this fixed?

**Comment by canyon289** [comment]
This is not fixed
