### ISSUE TITLE
Plot posterior gives anomalous results for small values

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#672]
**Describe the bug**
I have a model with a small parameter, and on plot posterior the variable is displayed (incorrectly) as having a mean of "0.0" and an HPD between 0.0 and 0.0.

Here's a snippet of the picture:
![image](https://user-images.githubusercontent.com/3274/57955617-f835be80-78bb-11e9-921d-6d710719354f.png)

**To Reproduce**

Attached a Jupyter notebook sufficient to reproduce the issue (had to attach it as a `.txt` file, but should simply be rename-able to run).

[Wood Model.ipynb.txt](https://github.com/arviz-devs/arviz/files/3193069/Wood.Model.ipynb.txt)

**Expected behavior**
Expected the values displayed to be scaled appropriately.

**Additional context**
`arviz` version 0.3.3
MacOS Mojave

**Comment by aloctavodia** [comment]
Hi @rpgoldman. By default `plot_posterior` will round up the point_estimate and HPD bounds to the first decimal point. You can change that using the `round_to` argument.

**Comment by ahartikainen** [comment]
Should we add some rules there? Like if values are less than x use scientific notation?

**Comment by rpgoldman** [comment]
@aloctavodia Is this something that could be controlled somehow using the `dims`?
The documentation on `dims` in xarray is very sparse.  The `dims` somehow are always a list of discrete values, and there's little guidance about what that will mean when the variable with the dimension is continuous.  Should we be controlling the default plotting of our variables by putting ranges on these dimensions?  If so, would that solve this problem?

**Comment by rpgoldman** [comment]
@aloctavodia One more, if you don't mind -- if we are plotting a number of variables using `plot_posterior`, and they are on different scales, how should we be using `round_to`?  It seems like it is applied uniformly across all subplots, yes?

**Comment by rpgoldman** [comment]
@ahartikainen 
> Should we add some rules there? Like if values are less than x use scientific notation?

Could this be done by comparing the min and max computed for the HPD, and choosing a scale accordingly?

**Comment by OriolAbril** [comment]
> Should we add some rules there? Like if values are less than x use scientific notation?

What about allowing a custom format string? We could change the [`hpd[0].round(round_to)`](https://github.com/arviz-devs/arviz/blob/b6007685f985f20823e21edce945a883aa0fc24f/arviz/plots/posteriorplot.py#L323) to `format_str.format(hpd[0])` if `format_string` is present, otherwise, the round_to argument would be used. It could also allow the option of using a list instead of a string to use different format for every plot.

**Comment by OriolAbril** [comment]
> @aloctavodia One more, if you don't mind -- if we are plotting a number of variables using `plot_posterior`, and they are on different scales, how should we be using `round_to`? It seems like it is applied uniformly across all subplots, yes?

Yes, round_to must be an integer, and this same value is used in all plots.

**Comment by rpgoldman** [comment]
Should we use significant digits instead of rounding?

**Comment by canyon289** [comment]
@aloctavodia or @rpgoldman 
Is this still an issue?
