### ISSUE TITLE
Confidence Level in plot_forest() - A bit confusing label

### ISSUE THREAD

**Issue by NicolaBernini** [arviz-devs/arviz#680]
Hi everybody, 

I'm a bit confused by the az.plot_forest() result : the default label is "94% Credible Interval" hence I was expecting this to be the confidence interval for the mean, like the one returned by [`scipy.stats.bayes_mvs()`](https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.stats.bayes_mvs.html) whose size scales as the inverse square root of `N` (number of samples) and in fact I got a bit surprised seeing that increasing the number of samples was not affecting the actual size 

Eventually I realized what gets plot is the 94% of samples distribution centered on the mean 

Here is an example to better clarify what I mean 

- Create Dataset 

```python 
n = 10000
data = np.random.randn(n)
```

- Visualize it 

```python 
az.plot_posterior(data)
az.plot_forest({'data': data})
```

![Img1](https://i.paste.pics/034b8073e621d84e04be8faebc41605a.png)

![Img3](https://i.paste.pics/4e519d439ad35bc441f008e1eae46765.png)

- Compute the confidence interval for the mean using Scipy 

```python
sp.stats.bayes_mvs(data, 0.94)
```

Result 

```
(Mean(statistic=0.00037999710190597896, minmax=(-0.018424873116622192, 0.019184867320434153)),
 Variance(statistic=0.9996740085579396, minmax=(0.973084241134472, 1.0262637759814073)),
 Std_dev(statistic=0.9998369909930016, minmax=(0.9865399397421474, 1.0131340422438557)))
```

**Comment by ahartikainen** [comment]
It's (marginal) credible interval for the sample. 

You can calculate Markov Chain Standard Error with `az.mcse` with `method="mean"`.

**Comment by aloctavodia** [comment]
In this example `data` is distributed as a normal with mean 0 and standard deviation 1, a 94% credible interval is approximatelly 2 standard deviation (around the mean), and that's exactly what you are observing here. 

Your confusion arise because you are expecting to get the hpd of the **distribution of the mean** of `data`, but you are computing the hpd of **the distribution of `data`**.

**Comment by aloctavodia** [comment]
closing this but @NicolaBernini feel free to ask more questions if you want.
