### ISSUE TITLE
Adopt (or not) plot strategies used by bayesplot

### ISSUE THREAD

**Issue by ariddell** [arviz-devs/arviz#7]
I just wanted to make sure folks saw the very nice plots being generated (in R) in bayesplot:

https://github.com/stan-dev/bayesplot

Here's one:

![mcmc_areas-rstanarm](https://github.com/stan-dev/bayesplot/raw/master/images/mcmc_areas-rstanarm.png)

Edit: add image

**Comment by aloctavodia** [comment]
Nice, thanks!

**Comment by twiecki** [comment]
Would be really nice to pool efforts with pystan, edward and pymc3. CC @dustintran.

**Comment by aloctavodia** [comment]
We will certainly keep an eye on Bayesplot.
