### ISSUE TITLE
compact is unexpected key word in traceplot

### ISSUE THREAD

**Issue by pindapuj** [arviz-devs/arviz#704]
When I run: `arviz.plot_trace(data,compact=True)`, I receive the following error `plot_trace() got an unexpected keyword argument 'compact'`. However, this argument is clearly listed in the docs and source code. 

Would appreciate some insight. Thanks!

**Comment by ahartikainen** [comment]
Hi, what version do you have? Try updating your version.

    pip install arviz -U

or

    conda update arviz -c conda-forge

**Comment by pindapuj** [comment]
Updated version and fine! The project's requirements.txt referenced a previous version. Thanks!
