### ISSUE TITLE
ArviZ global level options

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#706]
## Feature Description

There are many options in ArviZ which would be easier to handle as global options. Moreover, having global options in a style similar to matplotlib or pandas can make the experience of using ArviZ easier and better tailored to the end users. These options go from the maximum number of plots (#609) to text formatting options or even the default information criterion.

I believe that this can end up containing many different parameters, so with this in mind, environment variables are probably not ideal on the long run. Having something similar to matplotlib rcParams or pandas options seems more adient.

### pandas-like

The first implementation option is to have some pandas-like API. That is, setting the variables from some `config.py` file (a priori not user friendly) and expose some functions to modify these options.

### matplotlib-like

This second option is similar to the first one, but options are read from a json or json like configuration file, which is though to be used and modified by the end user. In addition to this, there are some functions exposed to modify these options too.

---

I prefer the matplotlib like version, because I think it is more convenient to ArviZ (i.e. someone who prefers LOO over WAIC can modify the rcparams file and forget about it instead of calling the option modifier function at the start of every script or python/ipython startup scripts). 

I propose to start with a simple json file (preferably 2 level) as configuration file and a custom class (children of dict for example) where all the options would be stored once read from the file for easy access.

**Comment by aloctavodia** [comment]
I agree with the matplotlib-like version.
