### ISSUE TITLE
az.compare fails for pymc3 mixture models

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#740]
**Describe the bug**
<img width="840" alt="image" src="https://user-images.githubusercontent.com/7213793/61141152-c5eeaa80-a481-11e9-87f3-03eedfc23b78.png">

I believe it's because of the extra coord in ic
<img width="587" alt="image" src="https://user-images.githubusercontent.com/7213793/61141476-8aa0ab80-a482-11e9-8ad5-6441f7d514e9.png">
**To Reproduce**
```
import arviz as az
import pymc3 as pm
import numpy as np

vals=np.array([1,2,3])
with pm.Model() as m:
    mu = pm.Normal("mu", mu=0, sd=1)
    y = pm.Normal("y", mu=mu, sd=1, observed=vals)
    trace=pm.sample(draws=100, tune=100)

data = az.from_pymc3(trace=trace)
comp = az.compare({"trace": data, "trace_2":data})
print(comp)

# Mixture model
with pm.Model() as two_components:
    p = pm.Dirichlet("p", a=np.ones(2))

    # Each mean of the mixture data has its own estimate of a mean with a fixed SD in this case
    means = pm.Normal("means", mu=vals.mean(), sd=10, shape=2)

    # Estimate of the standard deviation of what?
    sd = pm.HalfCauchy("sd", 1)
    y = pm.NormalMixture("y", w=p, mu=means, sd=sd, observed=vals)
    trace_mixture = pm.sample(draws=10, tune=10)

data_mixture = az.from_pymc3(trace=trace_mixture)

# Failing line
comp = az.compare({"trace": data_mixture, "trace_2":data_mixture})

```

**Expected behavior**
Comparison dataframe generated

**Additional context**
Appear on 0.4.1

**Comment by OriolAbril** [comment]
@canyon289 I was thinking today, and do we really want `from_xyz` methods to return datasets with length 1 dimensions? We could add a squeeze in `from_pymc3` before converting to dataset.
