### ISSUE TITLE
AttributeError: module 'arviz' has no attribute 'plot_mcse'

### ISSUE THREAD

**Issue by StevenLi-DS** [arviz-devs/arviz#745]
`version: '0.4.1'`

The following code:
```python
import arviz as az

data = az.load_arviz_data('centered_eight')
az.plot_mcse(data, var_names=['tau', 'mu'],
             rug=True, extra_methods=True)
```
Returns:
```python
AttributeError: module 'arviz' has no attribute 'plot_mcse'
```

I checked `dir(az)`, and it seems like there's no `plot_mcse` function.

**Comment by OriolAbril** [comment]
For now, `plot_mcse` is only present in the development version, it is not yet in the stable version.

There are instruccions on how to install the development version in the [README](https://github.com/arviz-devs/arviz/blob/master/README.md#development)
