### ISSUE TITLE
Prior-Posterior Plot

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#749]
Worked on an example with @raulpl to display how the prior changes after running inference. Here is an example with code!

```python
rugby = az.load_arviz_data('rugby')

prior_def = rugby.prior.defs.sel(team='Italy')
post_def = rugby.posterior.defs.sel(team='Italy')


fig = plt.figure(figsize=(10, 7))
ax1 = plt.subplot2grid((2, 2), (0, 0), fig=fig)
ax2 = plt.subplot2grid((2, 2), (0, 1), fig=fig)
ax3 = plt.subplot2grid((2, 2), (1, 0), colspan=2, fig=fig)


az.plot_kde(prior_def, ax=ax1)
ax1.set_title("Prior")

az.plot_kde(post_def, ax=ax2)
ax2.set_title("Posterior")

az.plot_kde(prior_def, ax=ax3)
az.plot_kde(post_def.values, ax=ax3)
ax3.set_title("Both");
```
![image](https://user-images.githubusercontent.com/2295568/61176070-27953e80-a580-11e9-952e-b5c4bc568760.png)

**Comment by ColCarroll** [comment]
Note this also might be used for something like prior/posterior predictive/observed. Here we see that the Cauchy prior for number of goals scored might be inappropriate!


![image](https://user-images.githubusercontent.com/2295568/61176152-34666200-a581-11e9-8124-b76be09f4266.png)

**Comment by percygautam** [comment]
I'll like to work on this.

**Comment by ColCarroll** [comment]
Feel free to ping me if you want any help! I think the scales and the layout will be the hardest thing...

**Comment by percygautam** [comment]
This is to keep my progress in check ( https://github.com/percygautam/arviz-examples/blob/master/Prior_Posterior_plot.ipynb ). Please free to review along the way.
