### ISSUE TITLE
Use `njit` instead of `jit` for numba functions

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#754]
Numba devs suggested using `numba.njit` (which is shorthand for `numba.jit(nopython=True)`), especially if we are only optionally activating numba.  @Ban-zee, not sure if you have looked at this?

**Comment by Ban-zee** [comment]
The conditional jit uses it by default.

**Comment by ColCarroll** [comment]
https://github.com/arviz-devs/arviz/blob/master/arviz/utils.py#L88

Maybe I broke it then? Looks like it is regular jit.

**Comment by Ban-zee** [comment]
We should leave it as such as I use object mode to lift the loops. I'll just pass `no-python=True` in the required places.(This is also not needed as Numba defautls to `no-python` mode and throws a warning if it falls back on object mode).

**Comment by ColCarroll** [comment]
:+1: i'll close this then -- thanks for looking at it.
