### ISSUE TITLE
plot_forest extension to allow plot_kde with quantiles

### ISSUE THREAD

**Issue by jsevo** [arviz-devs/arviz#756]
Hi,

Thanks for your great work on this. I am happy to help in the future. I think a great addition to the plot_forest function using ridge plot would be to allow plotting KDEs with quantiles indicated. 

With any simple trace, this code would get at it but is not polished:

```
import arviz as az
import matplotlib.pyplot as plt
import seaborn as sns

fig, axs = plt.subplots(nrows=len(trace.varnames), sharex=True, sharey=True, figsize=(5,9))
for ax, n in zip(axs,trace.varnames) :

    az.plot_kde(trace.get_values(n), quantiles=[0.25, 0.5, 0.75], ax=ax, contour=False)
    ax.set_ylabel(n, rotation=0)
    ax.set_yticks([])
 
sns.despine(left=True, right=True, bottom=False, top=True)

```

**Comment by amukh18** [comment]
I would like to work on this issue

**Comment by percygautam** [comment]
@amukh18  I am working on this issue for some days now, and have completed `matplotlib` implementation. I was waiting for my other PRs to be merged.
I deeply apologize for not specifying beforehand that I am working on this issue. I will be careful to not repeat this behavior in the future. Hope you understand.

**Comment by amukh18** [comment]
Alright
