### ISSUE TITLE
outdated docstring for io_cmdstanpy.from_cmdstanpy

### ISSUE THREAD

**Issue by mitzimorris** [arviz-devs/arviz#760]
**Describe the bug**

The docstring comments need to be updated to current (and relatively stable) version
of CmdStanPy -  comments on lines 294 - 303 refer to PyCmdStan

The code itself is correct and tested by PRs https://github.com/arviz-devs/arviz/pull/758 and https://github.com/arviz-devs/arviz/pull/759

**Comment by ahartikainen** [comment]
Hi, thanks for noticing. Let's fix these.
