### ISSUE TITLE
remove mc_error from summary?

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#78]
Should we include `mc_error` as part of summary? Is this still a useful measure?

**Comment by ColCarroll** [comment]
Interesting -- `mc_error` is [not defined here](https://github.com/arviz-devs/arviz/blob/master/arviz/stats/stats.py#L701), so I am not sure how it runs at all...  do you know if that should be `_mc_error`?

**Comment by aloctavodia** [comment]
You are right It should be _mc_error. I guess it will never fail because variables passed to mc_error has dimension 1.

**Comment by aloctavodia** [comment]
@fonnesbeck I will appreciate your input here, is `mc_error` still a useful measure?

**Comment by fonnesbeck** [comment]
I think its still broadly useful as a simple diagnostic -- if the mc error is of the same order of magnitude as your sd, then you still have work to do. Its not a critical one, but it does not hurt to have it in the summary.

**Comment by aloctavodia** [comment]
Thanks @fonnesbeck
