### ISSUE TITLE
A better way to benchmark the speed tests

### ISSUE THREAD

**Issue by Ban-zee** [arviz-devs/arviz#782]
The benchmark tests which are in use now can be improved much more. Importing arviz into the benchmark tests throws the following error: 

![Screenshot from 2019-08-01 21-45-25](https://user-images.githubusercontent.com/29407246/62310652-9858b800-b4a7-11e9-8af1-1d4692b6a096.png)

The workaround right now is to include only the jitted methods in `benchmarks.py`. It is indicative of the extent of the speedup but isn't very accurate.

**Comment by canyon289** [comment]
@Ban-zee Is this still an open issue?

**Comment by Ban-zee** [comment]
Yes
