### ISSUE TITLE
Move pointwise log likelihood data to log_likelihood group

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#796]
Following #794,  log likelihood data should be moved to the new `log_likelihood` group of the inference data objects. PyStan, PyMC3, emcee and dict have been updated in the PR, cmdstan, cmdstanpy, pyro and numpyro are still pending. For users familiar with the libraries it should be an achievable issue.

**Comment by ahartikainen** [comment]
I can probably fix cmdstanpy / cmdstan after 794 is merged

**Comment by VincentBt** [comment]
#1044 does it for numpyro and pyro

**Comment by OriolAbril** [comment]
#1064 did this for cmdstan and cmdstanpy. Only tensorflow_probability is missing

**Comment by OriolAbril** [comment]
Closing as `from_tfp` needs a thorough rewrite. I have made sure using `log_likelihood` group is explicitly stated in #812
