### ISSUE TITLE
shape problem while calculating WAIC values by arviz.compare command

### ISSUE THREAD

**Issue by aakhmetz** [arviz-devs/arviz#800]
There is something wrong with shape while calculating WAIC values. The code works when I use ```pm.compare``` command from pymc3, but it does not if use arviz package. 

The error happens because the considered models contain a parameter that is different in dimmensions between models (e.g. it has a changepoint, so for some models with one changepoint that parameter is with shape (,2), for some models with no changepoint is a scalar).

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import arviz as az

models = []; traces = []
for distr_ in ['Weibull','Gamma','Lognormal']:
    model, trace = makeModel(distr_)
    models.append(model); traces.append(trace)

az.compare(dict([(models[x].name, traces[x]) for x in range(len(models))]))
```
where the model has the following form:
```python
model = pm.Model()
K = Df.shape[0]
    
with model:
     start = pm.Uniform('start',Df.time_start,Df.time_start+1,shape=(K,))
     report = pm.Uniform('report',Df.time_report_lower,Df.time_report_upper,shape=(K,))
     delta = pm.Deterministic('delta', report-start)

     dmean = pm.HalfNormal('dmean', sd=20)
     dsd = pm.HalfNormal('dsd', sd=20)
     pm.Gamma('like', mu=dmean, sd=dsd, observed=delta)

     trace = pm.sample(6000, tune=4000, cores = 4, init="advi", nuts_kwargs=dict(target_accept=0.95))

model.name = modeldistribution
```

**Please provide the full traceback.**
```python
<ipython-input-61-d58062cc2fa5> in <module>
----> 1 az.compare(dict([(models[x].name, traces[x]) for x in range(len(models))]))

~/anaconda3/lib/python3.6/site-packages/arviz/stats/stats.py in compare(dataset_dict, ic, method, b_samples, alpha, seed, scale)
    205 
    206     elif method.lower() == "bb-pseudo-bma":
--> 207         rows, cols, ic_i_val = _ic_matrix(ics, ic_i)
    208         ic_i_val = ic_i_val * rows
    209 

~/anaconda3/lib/python3.6/site-packages/arviz/stats/stats.py in _ic_matrix(ics, ic_i)
    264             raise ValueError("The number of observations should be the same across all models")
    265 
--> 266         ic_i_val[:, idx] = ic
    267 
    268     return rows, cols, ic_i_val

ValueError: could not broadcast input array from shape (148,1) into shape (148)
```

## Versions and main components

* PyMC3 Version: 3.7
* arviz Version: 0.4.1
* Theano Version: 1.0.4
* Python Version: 3.6.9
* Operating system: lubuntu
* How did you install PyMC3/arviz: (conda/pip) latest from github by pip

**Comment by OriolAbril** [comment]
I am reading from my mobile so I am not really sure, but it looks like the same issue as #740. Have you tried executing this on the development version of ArviZ?

**Comment by aakhmetz** [comment]
@OriolAbril Thank you - I will check tomorrow (I thought that I had the developmental version, and the error disappeared at one moment, but then re-appeared. However, today I had kind of mess with my packages at work). 

#740 looks quite relevant

**Comment by aakhmetz** [comment]
Yes, it looks working fine after the update. @OriolAbril, thank you for checking!

**Comment by OriolAbril** [comment]
Happy to help!
