### ISSUE TITLE
TypeError: convolve() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by MiloVentimiglia** [arviz-devs/arviz#802]
When I try to plot a traceplot with arviz I get an error. I have updated all packages and dependencies but to no avail.

For example, if I run the following script:
-----------------------------------------------------------------------------------------------------------------------
import numpy as np
import pymc3 as pm
import matplotlib.pyplot as plt
from scipy.stats import norm
import arviz as az
import seaborn as sns

k = 100 #number of data points
x_data = norm(0,1).rvs(k)
y_data = x_data + norm(0,0.35).rvs(k) + 0.5

with pm.Model() as model:
    
    alpha = pm.Uniform('alpha', lower=-5, upper=5)
    beta = pm.Uniform('beta', lower=-5, upper=5)
    mu = pm.Deterministic('mu', alpha + beta * x_data)
    
    y_pred = pm.Normal('y_pred', mu=mu, observed=y_data)
    
    start = pm.sample() 
    step = pm.NUTS()
    trace = pm.sample(10000, step, start)

az.plot_trace(trace, var_names=('beta'))
------------------------------------------------------------------------------------------------------------------------

I get the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-ba145b7100ab> in <module>()
----> 1 az.plot_trace(trace, var_names=('beta'))

~/anaconda3/lib/python3.6/site-packages/arviz/plots/traceplot.py in plot_trace(data, var_names, coords, divergences, figsize, textsize, lines, compact, combined, legend, plot_kwargs, fill_kwargs, rug_kwargs, hist_kwargs, trace_kwargs, max_plots)
    202                 plot_kwargs,
    203                 fill_kwargs,
--> 204                 rug_kwargs,
    205             )
    206         else:

~/anaconda3/lib/python3.6/site-packages/arviz/plots/traceplot.py in _plot_chains(axes, idx, value, data, colors, combined, xt_labelsize, trace_kwargs, hist_kwargs, plot_kwargs, fill_kwargs, rug_kwargs)
    323                 plot_kwargs=plot_kwargs,
    324                 fill_kwargs=fill_kwargs,
--> 325                 rug_kwargs=rug_kwargs,
    326             )
    327 

~/anaconda3/lib/python3.6/site-packages/arviz/plots/distplot.py in plot_dist(values, values2, color, kind, cumulative, label, rotated, rug, bw, quantiles, contour, fill_last, textsize, plot_kwargs, fill_kwargs, rug_kwargs, contour_kwargs, hist_kwargs, ax)
    133             rug_kwargs=rug_kwargs,
    134             contour_kwargs=contour_kwargs,
--> 135             ax=ax,
    136         )
    137     return ax

~/anaconda3/lib/python3.6/site-packages/arviz/plots/kdeplot.py in plot_kde(values, values2, cumulative, rug, label, bw, quantiles, rotated, contour, fill_last, textsize, plot_kwargs, fill_kwargs, rug_kwargs, contour_kwargs, contourf_kwargs, pcolormesh_kwargs, ax, legend)
    184         rug_kwargs.setdefault("markersize", 2 * markersize)
    185 
--> 186         density, lower, upper = _fast_kde(values, cumulative, bw)
    187 
    188         rug_space = max(density) * rug_kwargs.pop("space")

~/anaconda3/lib/python3.6/site-packages/arviz/plots/kdeplot.py in _fast_kde(x, cumulative, bw, xmin, xmax)
    321     npad = min(n_bins, 2 * kern_nx)
    322     grid = np.concatenate([grid[npad:0:-1], grid, grid[n_bins : n_bins - npad : -1]])
--> 323     density = convolve(grid, kernel, mode="same", method="direct")[npad : npad + n_bins]
    324     norm_factor = len_x * d_x * (2 * np.pi * log_len_x ** 2 * scotts_factor ** 2) ** 0.5
    325 

TypeError: convolve() got an unexpected keyword argument 'method'

----------------------------------------------------------------------------------------------------------------------

Is anyone familiar with this error? Thanks!

**Comment by ahartikainen** [comment]
What scipy version do you have?

    import scipy
    print(scipy.__version__)

**Comment by MiloVentimiglia** [comment]
print(scipy.__version__)

0.18.1

**Comment by MiloVentimiglia** [comment]
pymc3 version: 3.7
arviz version: 0.4.1

**Comment by AlexAndorra** [comment]
Hi! I think @ahartikainen is spot on: I just tried your code with scipy 1.2.1 and it runs smoothly. Does it work for you when you update scipy?

Also, I'm not sure you need the `start = pm.sample()` and `step = pm.NUTS()` lines: I think the first one is already runing MCMC a first time, and the second one is redundant in the sense that NUTS is PyMC's default sampler. So I'd say just `trace = pm.sample(10000)` will do the job you want 😉

**Comment by MiloVentimiglia** [comment]
It works! Many thanks!
