### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#803]
Update minimum requirements

- scipy: `convolve(..., method)`

Add optional options for pip
- test
- all (?)

Do we have optional dependencies? Numba?

**Comment by Ban-zee** [comment]
Numba can be added as an optional depedency.

**Comment by OriolAbril** [comment]
I think this was already solved in #804 actually. @ahartikainen

**Comment by ahartikainen** [comment]
Still need fix here 

https://github.com/arviz-devs/arviz/blob/master/setup.py

**Comment by canyon289** [comment]
I think were good on this now? If no one corrects me in 48 hours will close
