### ISSUE TITLE
[FR] Support data from NumPyro 

### ISSUE THREAD

**Issue by fehiepsi** [arviz-devs/arviz#810]
## Tell us about it

Currently, we developed [numpyro](https://github.com/pyro-ppl/numpyro) as an alternative back-end to Pyro. The output of MCMC in numpyro is a numpy array so we can use `from_dict` api to convert to arviz inference data. However, we also allow users collect other fields such as `potential_energy`, `step_size`, `num_steps`,... which have different names in arviz. So it would be convenient for users to have a utility `from_numpyro`, which closes that gap.

I can work on a PR if arviz devs find this FR useful. :)

## Thoughts on implementation

I guess the implementation should be straightforward (because all objects from numpyro are numpy arrays) and similar to other `from_...` utilities .

cc @neerajprad

**Comment by ahartikainen** [comment]
Yes, this sounds great.

**Comment by fehiepsi** [comment]
Update TODO tasks from #811 

- [ ] compute obs's log_likelihood from posterior
- [ ] get observed data from posterior
- [ ] improve the schools test (the fix is available at https://github.com/pyro-ppl/numpyro/pull/332)

All of these are blocked by the next NumPyro release.

**Comment by canyon289** [comment]
I think this one has been addressed. Thanks @fehiepsi
