### ISSUE TITLE
Clean up TFP io

### ISSUE THREAD

**Issue by junpenglao** [arviz-devs/arviz#812]
- [ ] Update `io_tfp` to TF2.
- [ ] Use official TFP API like jointdistribution* and move Edward to `io_edward2`
- [ ] Ordering of chain and sample (see also https://github.com/arviz-devs/arviz/issues/456)
- [ ] Mapping of sample/diagnostics to a dict, currently it is possible with user code like https://gist.github.com/junpenglao/51cd25c6372f8d2ab3490d4af8f97401, however, the difficult here is that user can specify the diagnostic output using `trace_fn`, which likely does not have the same structure.
- [ ] Add tests using a multiple chains model (once #456 has been fixed)
- [ ] Make sure pointwise log likelihood is stored in `log_likelihood` group (if getting pointwise log likelihood is possible at all)
- [ ] Enforce ArviZ schema: group names and sample stats naming convention as much as possible

**Comment by junpenglao** [comment]
Updating the TODOs.

**Comment by percygautam** [comment]
@junpenglao @OriolAbril Do we just need to upgrade TF1 to TF2 in first task? Can we follow this [guide?](https://www.tensorflow.org/guide/migrate)

**Comment by OriolAbril** [comment]
Yes, this guide is great reference

**Comment by percygautam** [comment]
Okay, thanks

**Comment by percygautam** [comment]
@OriolAbril @junpenglao I have some doubts. Since there is no concept of placeholders in TF2. How are we going to work with data having placeholders?  We can simply convert a tensor object to ndarray using `tf.make_ndarray` if it do not contain any placeholders. Kindly guide me through it.

**Comment by OriolAbril** [comment]
closing in favour of #1890
