### ISSUE TITLE
Clarify usage of `plot_joint`

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#821]
## Short Description

The description of how to use `plot_joint` is not very clear about the use and meaning of parameters.

This is partly a usage question and partly a request for documentation improvement.

## Code Example or link

Looking at the docs for `arviz.plot_joint`, I see this: 
```
var_names : Iter of 2 e.g. (var_1, var_2)
    Variables to be plotted, two variables are required.
```
But then when I look at the example, I see this:
```
az.plot_joint(data,
>>>                 var_names=['theta'],
....
```
So … what is an “iter of 2”? `['theta']` is not obviously one, and the example gives a tuple of length 2.
I think what happens in this example is that you are plotting the *single* variable `theta` across a *coordinate* of dimension 2, but this is really quite confusing, and could use a much better explanation.

arviz 0.4.1 (will update!)

**Comment by percygautam** [comment]
@OriolAbril I'd like to complete this task. I'd worked with jointplot before and am familiar with its params. Do I need to only update docstring or also add extra examples? I personally think examples are good enough, we just need to provide an explanation.

**Comment by OriolAbril** [comment]
Only docstring needs to be updated

**Comment by percygautam** [comment]
Okay I'll update it as soon as I can.
