### ISSUE TITLE
Effective sample size computation

### ISSUE THREAD

**Issue by fehiepsi** [arviz-devs/arviz#841]
## Short Description

The effective sample size in ArviZ is quite different from the reported one in Stan.

## Code Example or link

This [gist](https://nbviewer.jupyter.org/gist/fehiepsi/fe5fc248c3bfd0b1337b0b053f1245dc) shows this inconsistency, where n_eff in Stan is 2-3 times greater than ArviZ.

We are not sure if it is expected and which number we should report. Could someone provide us some insight about this issue? Thanks for your help!

cc @null-a @neerajprad

**Comment by ahartikainen** [comment]
PyStan has the old Jeff, ArviZ uses the latest recommended (rank based) procedure.

https://arxiv.org/abs/1903.08008

https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/monitor.R

**Comment by fehiepsi** [comment]
Thanks, @ahartikainen ! I just noticed that PyStan `stan_fit.extract()` permutes samples by default. I should set `permute=False` to get a comparable result.
