### ISSUE TITLE
Create bokeh backend plots from test_plots

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#869]
Ari: future backend test (excluding mpl) should create a new file and run at least the mpl tests (maybe more)

**Comment by canyon289** [comment]
@ahartikainen This one is a bit different. Eventually `test_plots` should be deprecated and replaced with `test_bokeh` and `test_matplotlib` that just test private interface and not public interface. I can create examples to highlight what I mean

**Comment by OriolAbril** [comment]
I think this is done?
