### ISSUE TITLE
Add backend plot defaulting into rcparams

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#877]

**Comment by ahartikainen** [comment]
Did we already implement this or do we need to update the plotting code? Maybe some util function

    def sanitize_backend(backend=None):
        if backend is None:
            backend  = rcParams["backend"]
        elif backend not in supported_backends:
            raise TypeError('Backend not supported {}. Select backend from {{"matplotlib", "bokeh"}}'.format(str(backend))
        return backend

**Comment by OriolAbril** [comment]
I think @canyon289 was working on this in #949

**Comment by ahartikainen** [comment]
Yes,  of course :laughing:

**Comment by canyon289** [comment]
I think this is good now between Aris PR and mine.
