### ISSUE TITLE
Plot_PPC not showing histogram when it should

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#902]
**Describe the bug**
Plot PPC should default to histogram when given integer numbers

**To Reproduce**

```
import matplotlib.pyplot as plt
import numpy as np
import arviz as az
import pymc3 as pm

az.style.use("arviz-darkgrid")

sales = np.random.poisson(4, 1000)

with pm.Model() as newspaper_model:
    _lambda = pm.Normal("λ", sales.mean(), 10)

    sales = pm.Poisson("sales", _lambda, observed=sales)
    trace = pm.sample(draws=2000)
    ppc = pm.sample_posterior_predictive(trace)

data = az.from_pymc3(trace=trace, posterior_predictive=ppc)
plt.show()
```

**Expected behavior**
Histogram should appear not KDE plot

**Additional context**

ArviZ Master 699e0acdc88fa2927d7c47f47ec79d5f39fb2800
PyMC3 Version 3.7
Xarray Version 0.12.3

**Comment by ahartikainen** [comment]
Is `data.posterior.sales` an `int`?

**Comment by aloctavodia** [comment]
`pm.sample_posterior_predictive` is returning floats.

**Comment by aloctavodia** [comment]
I will try to fix this on pymc3

**Comment by aloctavodia** [comment]
This pymc-devs/pymc3#3683 should fix this issue

**Comment by canyon289** [comment]
This is fixed
