### ISSUE TITLE
Concat fails with empty InferenceData

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#907]
**Describe the bug**
`arviz.concat` produces incorrect outputs when one of the arguments is an `InferenceData` with no groups.

**To Reproduce**
```python
>>> import arviz as az

>>> idata = az.load_arviz_data("centered_eight")

>>> idata
Inference data with groups:
    > posterior
    > sample_stats
    > posterior_predictive
    > prior
    > observed_data

>>> az.concat(idata, az.InferenceData())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/arviz/data/inference_data.py", line 307, in concat
    group_data = getattr(arg, group)
UnboundLocalError: local variable 'group' referenced before assignment

>>> az.concat(az.InferenceData(), idata)
Inference data with groups:
    > observed_data
```

**Expected behavior**
Both `concat` commands should have produced an `InferenceData` with the same groups and data as `idata`.

**Additional context**
Using master branch on OS X.

**Comment by sethaxen** [comment]
I suspect the issue is that these 2 lines need to be indented

https://github.com/arviz-devs/arviz/blob/41279495780f2a3a6f0a8908253753078565c490/arviz/data/inference_data.py#L307-L308

**Comment by anzelpwj** [comment]
I've replicated the problem on my MacOSX computer, and it appears @sethaxen 's solution will fix. Will submit a PR.
