### ISSUE TITLE
Cannot install without matplotlib

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#91]
On a fresh virtual environment, 

```
pip install -e .
```

fails with 

```
Obtaining file:///home/colin/projects/arviz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/colin/projects/arviz/setup.py", line 7, in <module>
        from matplotlib import get_configdir
    ModuleNotFoundError: No module named 'matplotlib'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/colin/projects/arviz/
```

I wonder if we can do some matplotlib magic after installing the requirements, or maybe just on import?

**Comment by aloctavodia** [comment]
I was under the impression I had solved this before... I mean to ensure dependencies are installed before trying to copy the files :(

**Comment by ColCarroll** [comment]
Yeah, I remember being impressed when you had figured it out!

**Comment by ahartikainen** [comment]
On osx installation fails. Is this failing silently on linux? This would explain the problem.

    with open(REQUIREMENTS_FILE) as buff:
        install_reqs = buff.read.splitlines()

it should be (see missing `()` after `read`

    with open(REQUIREMENTS_FILE) as buff:
        install_reqs = buff.read().splitlines()

**Comment by ColCarroll** [comment]
You caught me!  I added a sneaky fix in #92.

**Comment by ColCarroll** [comment]
More broadly though, it might make sense to change the CI script to run `pip install -e .` first, to make sure the `setup.py` runs, and then pip/conda install non-required packages. It would catch both issues here (but we should figure out the matplotlib stuff first).

**Comment by aloctavodia** [comment]
I solved and then I ruined! 

`from matplotlib import get_configdir` should be inside the function `copy_styles():`
