### ISSUE TITLE
Tag releases on github please

### ISSUE THREAD

**Issue by OmnipotentEntity** [arviz-devs/arviz#918]
## Tell us about it

Hi, I'm a NixOS maintainer, and I am [attempting to package Arviz for distribution via the nixpkgs repository.](https://github.com/NixOS/nixpkgs/pull/73988)

As a part of this, I'm setting up an automated build process; however, the tests do not run because the `saved_models` directory is missing from the PyPi distribution.  Seeing as this seems to be the only tagged release, this means I cannot run many of the tests and ensure that the package is functioning correctly.

If you tag releases on Github, I can download the repository for that version, and ensure that the tests run correctly.  It would really help!

Thanks!

**Comment by OmnipotentEntity** [comment]
Actually, I'm an idiot.  You simply changed the tagging scheme at v0.3.2 to lose the v.  I'm going to close this.

**Comment by ahartikainen** [comment]
Thanks for using our package.

What is nixOS?

**Comment by OmnipotentEntity** [comment]
NixOS is a linux distribution that focuses on declarative system setup and deterministic behavior of packages.  You can see more details at https://nixos.org/nixos/about.html
