### ISSUE TITLE
Unnecessary warning while running SMC via pymc3

### ISSUE THREAD

**Issue by aakhmetz** [arviz-devs/arviz#924]
When I do SMC on pymc3 with the command:
```python
with pm.Model() as model:
        ...
        trace = pm.sample_smc(2000, cores=48, parallel=True, random_seed=123)
```
I receive the warning:
```python
WARNING:arviz.stats.stats_utils:Shape validation failed: input_shape: (1, 2000), minimum_shape: (chains=2, draws=4)
```
Although, as it was adviced by @aloctavodia in https://github.com/pymc-devs/pymc3/issues/3697, it could be just one chain in SMC

(PyMC ver 3.8, arviz ver is latest from github)

**Comment by ColCarroll** [comment]
This is tough to track down - I would _guess_ the fix will be applied to PyMC3, since it looks like the warning is correct, and something in PyMC3 is being too eager at running convergence checks. 

We can leave the issue open here, though.

**Comment by aloctavodia** [comment]
This is superweird as `pm.sample_smc` does not run any convergence checks. Also I am unable to reproduce this warning message

**Comment by aakhmetz** [comment]
@aloctavodia and @ColCarroll, please excuse me, I think I missed that the error arises when I do ```az.summary``` (I was a bit too quick)

**Comment by aloctavodia** [comment]
Hi @aakhmetz, that's OK, nos this error sounds more reasonable. Although is still a little bit annoying when using SMC.

At this point ArviZ is more focused on working with samples coming from MCMC samplers, and this error is a reflection of that. In the near future we have plans to introduce diagnostics specifically tailored for other methods like SMC and Variational Inference. In the meantime you can safely ignore this warning message.

**Comment by aakhmetz** [comment]
Dear @aloctavodia, thanks! It looks good, so I will wait for some update!

ps: today I checked my previous code which had an error https://discourse.pymc.io/t/pm-smc-how-to-deal-with-numpy-linalg-linalgerror-xx-th-leading-minor-of-the-array-is-not-positive-definite/3643/6, and it worked smoothly with the latest version. Let's see how it goes :-)
