### ISSUE TITLE
Gallery examples don't pop up the window with the plot

### ISSUE THREAD

**Issue by yurivict** [arviz-devs/arviz#927]
For example, https://arviz-devs.github.io/arviz/examples/plot_pair.html just exits silently.

**Comment by OriolAbril** [comment]
When using matplotlib backend, depending on the context you will need to `import matplotlib.pyplot as plt` and run `plt.show()`.

**Comment by yurivict** [comment]
This works, thanks!

Maybe you can mention this somewhere on the Gallery page.

**Comment by ahartikainen** [comment]
For now, we should probably add `plt.show` for the plots, but in future, we could call plt.show inside the function (as we do for the bokeh).

**Comment by percygautam** [comment]
@OriolAbril @ahartikainen Should we add `plt.show()` for the example matplotlib files for now?

**Comment by ahartikainen** [comment]
@OriolAbril should we set `show=True` for the last arviz plot function or call `plt.show` if plots are further customized?

**Comment by OriolAbril** [comment]
I think `plt.show` will be better. It would have to be removed when building docs so it is probably better to stick always to the same pattern.
