### ISSUE TITLE
plot_trace lines is unclear and it may yield unexpected results

### ISSUE THREAD

**Issue by JackCaster** [arviz-devs/arviz#929]
**Describe the bug**
The argument `lines` for the function `plot_trace` can give unexpected results. Moreover, the documentation is a bit nebulous.
 
**To Reproduce**
A toy example is defined
```python
import pymc3 as pm
import arviz as az
import numpy as np

# fake data
mu_real = 0
sigma_real = 1
n_samples = 150

Y = np.random.normal(loc=mu_real, scale=sigma_real, size=n_samples)

with pm.Model() as model:
    mu = pm.Normal('mu', mu=0, sigma=10)  
    sigma = pm.HalfNormal('sigma', sigma=10)
    likelihood = pm.Normal('likelihood', mu=mu, sigma=sigma, observed=Y)
    trace = pm.sample()
```
As per [documentation](https://arviz-devs.github.io/arviz/generated/arviz.plot_trace.html#arviz.plot_trace), the argument `lines` accepts a tuple in the form `(var_name, {‘coord’: selection}, [line, positions])`. So, the command 
```python
az.plot_trace(trace, lines=(('mu', {}, mu_real),))
```
yields correctly 
![image](https://user-images.githubusercontent.com/18400141/69927034-b7327f80-1484-11ea-8f4c-5f52563413be.png)

I can also pass a list of tuples or a list of tuples and lists and it will work fine:
```
az.plot_trace(trace, lines=[('mu', {}, mu_real)]) # list of tuples
az.plot_trace(trace, lines=[['mu', {}, mu_real]]) # list of lists
az.plot_trace(trace, lines=[['mu', {}, mu_real], ('sigma', {}, sigma_real)]) # list of lists and tuples
```
however, I cannot pass a simple tuple because I will get a `KeyError: 0`
```python
az.plot_trace(trace, lines=(['mu', {}, mu_real]))
az.plot_trace(trace, lines=(('mu', {}, mu_real)))
```
Also, I can pass a variable or coordinate name that do not exist and Arviz will not complain---but not lines will be plotted (here I would expect a warning)
```python
az.plot_trace(trace, lines=[('hey', {}, mu_real)])
az.plot_trace(trace, lines=[('mu', {'hey'}, mu_real)])
```
![image](https://user-images.githubusercontent.com/18400141/69927389-d251bf00-1485-11ea-8d5c-7630a6763728.png)
The weird behavior happens when I pass a string:
```python
az.plot_trace(trace, lines=[('mu', {}, 'hey')])
```
![image](https://user-images.githubusercontent.com/18400141/69927502-32e0fc00-1486-11ea-8f6a-3f012017e932.png)

**Expected behavior**
The [documentation](https://arviz-devs.github.io/arviz/generated/arviz.plot_trace.html#arviz.plot_trace) could be improved and the function could check the inputs. In addition to what described above, the placeholder `[line, positions]` in `(var_name, {‘coord’: selection}, [line, positions])` should be something like `[line_positions]` otherwise one may think (like myself :) ) that two values should be inserted (one for `line` and one for `positions`).

**Additional context**
I am using Win10, fresh conda environment with PyMC3 and Arviz from master.

Possibly related https://github.com/pymc-devs/pymc3/issues/3495, https://github.com/pymc-devs/pymc3/issues/3497

**Comment by ahartikainen** [comment]
Thanks for the feedback.

We are on our way to update the interface a bit so I hope we can fix this issue at the same time and the usage would be intuitive.

**Comment by JackCaster** [comment]
Thank you for your good work 🙌

**Comment by percygautam** [comment]
@ahartikainen I don't understand, why we are plotting line if a string is passed `[lines, positions]`. Is this the required behavior? I understand that lines are used to check some behaviors (deviation of kde from one point (say mean, median, etc)), but for what cases, we'll need to pass the string for positions?

**Comment by OriolAbril** [comment]
Sounds gook, one option for checking the list is to check the dtype of `line_values` after the atleast_1d to make sure the array contains numeric values. One possibility is to follow this [SO answer](https://stackoverflow.com/questions/29518923/numpy-asarray-how-to-check-up-that-its-result-dtype-is-numeric).

**Comment by percygautam** [comment]
Okay, I'd go with that. Also, I'd add the warning for the case of variable or coordinate name that do not exist (as pointed in issue description)
> Also, I can pass a variable or coordinate name that do not exist and Arviz will not complain---but > not lines will be plotted (here I would expect a warning)
> ``` 
> az.plot_trace(trace, lines=[('hey', {}, mu_real)])
> az.plot_trace(trace, lines=[('mu', {'hey'}, mu_real)])
> ```
