### ISSUE TITLE
Docker image is missing some important packages

### ISSUE THREAD

**Issue by anzelpwj** [arviz-devs/arviz#936]
Hi all,

I'm trying to open a Jupyter notebook in the Docker image as per `CONTRIBUTING.md`, and when running from a (relatively new) Docker image I am finding that I cannot run `import arviz as az` without finding that we are missing the following packages:
- `scipy`
- `xarray`
- `matplotlib`
- `netCDF4`

Once I installed these for packages, I was finally able to import the package.

**To Reproduce**
- Download docker image.
- Open Docker Jupyter notebook.
- Try to import `arviz` package.
- For whatever module it complains its missing, go back, pip install in the Docker image, and then restart.
- Repeat this and you get the 4 missing packages above.

**Expected behavior**
I should be able to import the package without any trouble from a clean Docker image.

**Additional context**
MacOSX 10.14 computer, Docker image downloaded on 2019-12-03 at around 3 PM PST.

**Comment by anzelpwj** [comment]
I did see that all of these packages are in the `requirements.txt` - is this not getting properly installed?

**Comment by OriolAbril** [comment]
How did you download the Docker image? Could you share the commands?

I am currently trying to reproduce the issue, as I _think_ i used Docker out of the box the first time.

**Comment by anzelpwj** [comment]
I ran `./scripts/container.sh --build` to create the image (I did not run the `--clear_cache` command, FWIW). I did some testing for PR #934  (which did work without any trouble), but when I tried to open a Jupyter notebook to test things I ran into trouble.

Currently trying to trash my current Docker image and rebuild to see if I can reproduce.

**Comment by anzelpwj** [comment]
Alternately, is this more a problem with `jupyter-dock`? (`CONTRIBUTING.md:Developing in Docker`). Apologies, my understanding of docker is a little weak.

**Comment by anzelpwj** [comment]
So:
- Deleted old `arviz` image.
- Ran `./scripts/container.sh --clear_cache` and `./scripts/container.sh --build`
- Saw all the `requirements.txt` packages get installed.
- Ran `docker run --mount type=bind,source="$(pwd)",target=/opt/arviz/ -it arviz bash` and ran `pip freeze`. Noted that the `requirements.txt` packages are listed.
- Ran:
```
$ docker run --mount type=bind,source="$(pwd)",target=/opt/arviz/ --name jupyter-dock -it -d -p 8888:8888 arviz
$ docker exec -it jupyter-dock pip install jupyter
$ docker exec -it jupyter-dock jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
```
- Opened up Jupyter browser in computer.
- Opened notebook.
- Ran `import arviz as az`
- Got error message that matplotlib is missing.

Maybe something is happening with `jupyter-dock`.

**Comment by OriolAbril** [comment]
what packages are listed if you do a `!pip freeze` from the jupyter notebook?

**Comment by OriolAbril** [comment]
I managed to reproduce the issue and I am completely lost. It looks like containers built with the detach flag `-d` (to create a started container) only has a very limited subset of the packages. @canyon289 

Creating a container and executing pip freeze inside the container results in only a handful of packages:

```
oriol@oriol-ProDesk:~/Public/arviz$ docker run --mount type=bind,source="$(pwd)",target=/opt/arviz/ -it -d --name bash-dock arviz 
34868837448d9a314a85069abcae480760440cc2c53e7c956615929de069fa2e
oriol@oriol-ProDesk:~/Public/arviz$ docker exec -it bash-dock pip freeze
asn1crypto==0.24.0
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
conda==4.6.11
cryptography==2.4.2
idna==2.8
pycosat==0.6.3
pycparser==2.19
pyOpenSSL==18.0.0
PySocks==1.6.8
requests==2.21.0
ruamel-yaml==0.15.46
six==1.12.0
urllib3==1.24.1
```

Whereas running bash on a new container (not detached) and there running `pip freeze` yields:

<details>
 <summary>Command line output</summary>
```
oriol@oriol-ProDesk:~/Public/arviz$ docker run --mount type=bind,source="$(pwd)",target=/opt/arviz/ -it arviz bash
(testenv_3.6_PYSTAN_latest_PYRO_latest_EMCEE_latest_TF_latest) root@581a52afc0d2:/opt/arviz# pip freeze
absl-py==0.8.1
alabaster==0.7.12
appdirs==1.4.3
arviz==0.5.1
astor==0.8.0
astroid==2.3.3
attrs==19.3.0
Babel==2.7.0
backcall==0.1.0
black==19.10b0
bleach==3.1.0
bokeh==1.4.0
cachetools==3.1.1
certifi==2019.11.28
cftime==1.0.4.2
chardet==3.0.4
Click==7.0
cloudpickle==1.1.1
cmdstanpy==0.6.0
coverage==4.5.4
cycler==0.10.0
Cython==0.29.14
decorator==4.4.1
defusedxml==0.6.0
docutils==0.15.2
emcee==3.0.2
entrypoints==0.3
fastcache==1.1.0
gast==0.2.2
ghp-import==0.5.5
google-auth==1.7.1
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
graphviz==0.13.2
grpcio==1.25.0
h5py==2.10.0
idna==2.8
imagesize==1.1.0
importlib-metadata==1.1.0
ipython==7.10.1
ipython-genutils==0.2.0
isort==4.3.21
jax==0.1.49
jaxlib==0.1.32
jedi==0.15.1
Jinja2==2.10.3
jsonschema==3.2.0
jupyter-core==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
llvmlite==0.30.0
m2r==0.2.1
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.0.0
nbconvert==5.6.1
nbformat==4.4.0
nbsphinx==0.5.0
netCDF4==1.5.3
numba==0.46.0
numpy==1.17.4
numpydoc==0.9.1
numpyro==0.2.1
oauthlib==3.1.0
opt-einsum==3.1.0
packaging==19.2
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.1
pathspec==0.6.0
patsy==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.1
pluggy==0.13.1
prompt-toolkit==3.0.2
protobuf==3.11.1
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pydocstyle==4.0.1
Pygments==2.5.2
pylint==2.4.4
pymc3==3.8
pyparsing==2.4.5
pyro-api==0.1.1
pyro-ppl==1.0.0
pyrsistent==0.15.6
pystan==2.19.1.1
pytest==5.3.1
pytest-cov==2.8.1
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.2
regex==2019.11.1
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
scipy==1.3.3
six==1.13.0
snowballstemmer==2.0.0
Sphinx==2.2.2
sphinx-bootstrap-theme==0.7.1
sphinx-gallery==0.5.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
tensorboard==2.0.2
tensorflow==2.0.0
tensorflow-estimator==2.0.1
tensorflow-probability==0.8.0
termcolor==1.1.0
testpath==0.4.4
Theano==1.0.4
toml==0.10.0
torch==1.3.1+cpu
torchvision==0.4.2+cpu
tornado==6.0.3
tqdm==4.40.0
traitlets==4.3.3
typed-ast==1.4.0
urllib3==1.25.7
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
wrapt==1.11.2
xarray==0.14.1
zipp==0.6.0
```
</details>

Both containers are built on top of the same image, I would expect them to be the same environment.

**Comment by OriolAbril** [comment]
I will update the contributing guide. I don't really understand why (I am guessing the default container interpreter behaves mysteriously) but this seems to do the trick.

```
$ docker run --mount type=bind,source="$(pwd)",target=/opt/arviz/ --name jupyter-dock -it -d -p 8888:8888 arviz
$ docker exec jupyter-dock bash -c "pip install jupyter"
$ docker exec -it jupyter-dock bash -c "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root"
```

Can you confirm @anzelpwj ?

**Comment by anzelpwj** [comment]
That resolves it @OriolAbril , thanks for figuring it out!

**Comment by OriolAbril** [comment]
Great, I'll leave the issue open as a remainder to update the contributing guide. Unless someone does it first, I will probably have time to do it in some days.

**Comment by anzelpwj** [comment]
I mean, I'm trying to contribute as part of PyDataLA, so I'm happy to swap out the commands.

**Comment by OriolAbril** [comment]
That would be great! Thanks!

**Comment by ahartikainen** [comment]
Do we have multiple python installations on the docker?

**Comment by OriolAbril** [comment]
It turns out we do.

```
oriol@oriol-ProDesk:~$ docker run --mount type=bind,source="$(pwd)",target=/opt/arviz/ -it -d --name bash-dock arviz
b38d84064303781691806510c25c985314ef653d1b32e34c0d094b0a037dc90a
oriol@oriol-ProDesk:~$ docker exec bash-dock which pip
/usr/local/bin/pip
oriol@oriol-ProDesk:~$ docker exec bash-dock bash -c "which pip"
/usr/local/envs/testenv_3.6_PYSTAN_latest_PYRO_latest_EMCEE_latest_TF_latest/bin/pip
oriol@oriol-ProDesk:~$ docker exec bash-dock dash -c "which pip"
/usr/local/bin/pip
oriol@oriol-ProDesk:~$ docker exec bash-dock which python
/usr/local/bin/python
oriol@oriol-ProDesk:~$ docker exec bash-dock bash -c "which python"
/usr/local/envs/testenv_3.6_PYSTAN_latest_PYRO_latest_EMCEE_latest_TF_latest/bin/python
oriol@oriol-ProDesk:~$ docker exec bash-dock python -V
Python 3.7.3
oriol@oriol-ProDesk:~$ docker exec bash-dock bash -c "python -V"
Python 3.6.9 :: Anaconda, Inc.
```

Running commands using `dash` (which is the default where `/bin/sh` points) runs them outside the conda environment created where all packages are installed.
