### ISSUE TITLE
Improve assignment of pm.Deterministic to InferenceData groups

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#947]
## Tell us about it

In PyMC3 `pm.Deterministic` can be used either to compute a quantity that varies over the trace, or to store or compute the value of a predictor variable (independent variable).  In this case, when `from_pymc3` encounters such a variable, it will try to prepend `chains` and `draws` to its dimensions, and then error out.

A reasonable thing to do when interpreting a `pm.Deterministic` in translation to `InferenceData` would be to inspect its shape, and if its shape is *d - 2* where *d* is the expected number of dimensions (or *d - 1* for `prior_predictive` or `posterior_predictive`, shunt that variable into `constant_data` and out of whatever trace group we were trying to push it into.

I suppose there is a potential that this DWIM transformation could go wrong, and mask a real shape mismatch, but it seems worth trying.

(h/t to @ColCarroll for brainstorming some `from_pymc3` issues.

**Comment by ahartikainen** [comment]
Maybe assume something and add option to overwrite this assumption

**Comment by rpgoldman** [comment]
Brandon Willard offered me enough information to get the PyMC3 deterministics allocated properly. See #983 (temporarily messed up by upstream bug in PyMC3 that has been fixed and merged, but not released).

**Comment by OriolAbril** [comment]
Was this solved eventually? @rpgoldman

**Comment by rpgoldman** [comment]
@OriolAbril Yes, I believe so.  The key step was to employ the model object, at which point we could use the theano graph to answer this question.

I'll close this ticket.
