### ISSUE TITLE
Bokeh marker options

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#950]
Each plot needs a marker option implemented for the bokeh backend.

http://docs.bokeh.org/en/1.3.2/docs/reference/models/markers.html

Ideally, we have a marker option somewhere and helper function that takes in {marker as a string, marker name, marker function, custom js for marker} and outputs correct function.

These markers should also be added to docstrings or at least give some link for supported markers.

**Comment by percygautam** [comment]
@ahartikainen Should the new marker param takes only string as value(like `*` for asterisk and so on) or other values also like marker_name etc?
 I thinking of using switch call to different marker functions, as they all have same params, in `function_generator` helper function. Is my approach viable or is there any other method of doing it?

**Comment by ahartikainen** [comment]
We are currently using methods from `bokeh.plotting.figure` to plot different markers.

I think we could change our way of plotting so we would use explicitly `bokeh.models.markers`

https://docs.bokeh.org/en/latest/docs/reference/models/markers.html

So I think switch (btw, in python just use dictionary with `.get` method adding a default value) could work. We would have a function that takes in the marker given for the plot, checks if it is a `str` and if it is, then it would translate it to a marker object, we could have some predefined markers similar to matplotlib / `bokeh.figure.scatter`.

So in the end user could define a custom marker and just pass that to our function. (This could be arbitrary shape e.g.)

We also need to think that the use of the default parameters are compatible with `bokeh.models.markers`

**Comment by percygautam** [comment]
@ahartikainen @OriolAbril I have implemented the Marker option for `eloped_plot` (type of scatter plot). I am getting something like this:
![Screenshot 2020-01-29 at 2 54 46 AM](https://user-images.githubusercontent.com/20489158/73307164-b11e0c80-4243-11ea-808e-624c7a0b64d9.png)
![Screenshot 2020-01-29 at 2 55 28 AM](https://user-images.githubusercontent.com/20489158/73307221-cd21ae00-4243-11ea-9460-159090aaa3b6.png)

I am confused about some plots whether the marker option needs to be added to them or not (like kde plots, energy plots, dist plot, etc). Can you specify the plots on which markers to be added?
