### ISSUE TITLE
Bokeh hover tooltip

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#952]
We need to implement better default hover settings.

https://docs.bokeh.org/en/1.4.0/docs/reference/models/tools.html#bokeh.models.tools.HoverTool

**Comment by amukh18** [comment]
@ahartikainen I am unable to find the current default hover settings. I looked in the bokeh backend files but I wasn't able to find them. Do you know where I could find them?

**Comment by ahartikainen** [comment]
It uses default by bokeh. We would nedd to create a custom hover tooltip. I think it needs to use ColumnDataSource.

**Comment by amukh18** [comment]
Do you mean something like this ?: https://www.programcreek.com/python/example/106843/bokeh.models.HoverTool So I think I would have to add similar code to all the bokeh backend files

**Comment by amukh18** [comment]
@ahartikainen I am also not sure about what sort of defaults I should add for each plot

**Comment by ahartikainen** [comment]
I guess it depends on the plot.

At least draw, chain and value info for plots with "raw" data.

**Comment by amukh18** [comment]
@ahartikainen I was going to work on the plot_ppc function as a function to start with but I don't understand how to extract the coordinates for the InferenceData object since it already seems to be heavily processed when it gets to using the bokeh backend file(especially the xarray_var_iter part). Could you please help me?

**Comment by amukh18** [comment]
More specifically, I am unable to understand how the coordinates are stored after the iterator has been created and passed to the backend file

**Comment by ahartikainen** [comment]
I would start from a function that already uses ColumnDataSource, and see how that can be used. First demo does not need chain and draw info first.

**Comment by amukh18** [comment]
Do you mean I should begin with special fields like $x and $y for the canvas coordinates?

**Comment by ahartikainen** [comment]
Ok, let's think about how we could implement this for `plot_pair` for (for scatter)

https://github.com/arviz-devs/arviz/blob/master/arviz/plots/backends/bokeh/pairplot.py

Currently hover just shows coordinate information, what is not optimal, in optimal case we want to see the value information + draw and chain info ( maybe some other info too)

So to start with point location against both variables

```
TOOLTIPS  = [
    (flat_var_names[0], "@{}".format(flat_var_names[0])),
    (flat_var_names[1], "@{}".format(flat_var_names[1]),
]
```

And then we need a way to add this information for hover.

ax = bkp.figure(
                width=int(figsize[0] * dpi), height=int(figsize[1] * dpi), tooltips=TOOLTIPS, **backend_kwargs
            )

It would be also good idea to check if backend_kwargs has tooltips already defined.

Also, if there is a way to check / add this after the figure is created, that would be great.
