### ISSUE TITLE
Add (pan/zoom) limits for Bokeh

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#959]
Some plots might need suitable panning / zoom limits.

Also we can restrict movement on an axis. (Move only on x axis)

I'm not sure can we limit zooming.

**Comment by nitishp25** [comment]
Is this resource helpful? https://stackoverflow.com/questions/23277066/limit-bokeh-plot-pan-to-defined-range

**Comment by ahartikainen** [comment]
Yes, that is one way to do it.

We should probably list the plots that needs these limits (either x-axis, y-axis or both).

Some plots don't need these limits (pair_plot for example)

**Comment by nitishp25** [comment]
Which plots do you think need this feature?

**Comment by nitishp25** [comment]
I'll be happy to solve if you can assist me @ahartikainen @OriolAbril :)

**Comment by ahartikainen** [comment]
min-max for x and y:
- autocorrplot
- forestplot
- parallelplot
- traceplot (second axis)

Maybe others, but let's start with those.

Also there should be option to use limits or not to use.

@OriolAbril should we use `backend_config` or something similar as a keyword?

**Comment by OriolAbril** [comment]
Sounds good

**Comment by nitishp25** [comment]
So for autocorrplot, if we set ```axes[0, 0].x_range = DataRange1d(bounds="auto")``` and ```axes[0, 0].y_range = DataRange1d(bounds="auto")``` in line 62 [here](https://github.com/arviz-devs/arviz/blob/master/arviz/plots/backends/bokeh/autocorrplot.py#L62), will this be applicable to all the plots in the gridplot?
