### ISSUE TITLE
Converting PyStan records to dataframe

### ISSUE THREAD

**Issue by ColCarroll** [arviz-devs/arviz#96]
@ahartikainen Working on adding quick start examples in #95, and would love to include `pystan` examples.  

Do you have any examples of turning the `pystan` fit to a dataframe?  I think `xarray` is a better answer long term (https://github.com/arviz-devs/arviz/issues/4#issuecomment-374933062), but for a first release, hacking a small function around dataframes seems doable.

**Comment by ahartikainen** [comment]
Hi, I am currently doing a wrapper for arviz. It will go in pystan/plots so one can more or less natively call `fit.autocorrplot()`. 

And if arviz is not installed I will only implement the traceplot (probably add arviz traceplot to external files that comes with pystan)

I need to do some small hacks for `energyplot`, `parallelplot` and `traceplot` with `combine` kw. After the hacks everything works quite nicely (excluding stuff needing pymc3 model).

But you can call (next version 2.18 will have this, but it is already in the github version)

    dataframe = fit.to_dataframe(inc_warmup=False, diagnostics=False)

It will also include diagnostic stuff (if `diagnostics=True`) for sampler, chain information and warmup information.

Also our naming convention is `x`, `x[1]`, `x[1,1]`, `x[1,1,1]` and so on.

**Comment by ColCarroll** [comment]
Closed by converting to xarray instead (plus built into next version if you want a dataframe)
