### ISSUE TITLE
WIP: Error in WAIC computation from PyMC3

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#974]
**Describe the bug**
I have a script comparing a bunch of slightly different models that I was running overnight, and this morning I came back to see the following error message:

```
TypeError: Got an NumPy-like array type providing the __array_function__ protocol but NEP18 is not enabled. Check that numpy >= v1.16 and that the environment variable "NUMPY_EXPERIMENTAL_ARRAY_FUNCTION" is set to "1"
```
Full backtrace is attached.  [backtrace.txt](https://github.com/arviz-devs/arviz/files/4000804/backtrace.txt) This *may* be a bug in `xarray`, rather than in Arviz proper.

It will take me some time to try to figure out how to reproduce this error, so this is a "work in progress" bug report. I'm hoping that someone will recognize something about this error, so that I can narrow it down.

Thanks, and happy holidays!

**To Reproduce**

Working on it!

**Expected behavior**

**Additional context**
Arviz 0.5.1
Xarray 0.13.0

Possible concern: I have both `intel-numpy` and `numpy` installed. The former I installed because it was the only way I could figure out to get the `mkl` libraries in my virtualenv.  The latter lays on top of the former because the Intel version of numpy is so out of date.

**Comment by rpgoldman** [comment]
Still working on this -- ran with pdb and... when I tried to examine the data that, according to xarray, is not a numpy ndarray, but supplies `__array_function__`, I got a segfault. 😢

**Comment by ColCarroll** [comment]
What version of numpy and xarray? `NEP18` refers [to this](https://numpy.org/neps/nep-0018-array-function-protocol.html), and I know at least the first two authors are involved in xarray/dask.

**Comment by rpgoldman** [comment]
```
xarray==0.13.0
intel-numpy==1.15.1
numpy==1.17.2
```

I'm not sure that this is relevant, but I find it suspicious that `htop` shows this server having allocated 27 cores (if I'm understanding the output correctly), but all but four are idle while I'm using `pm.sample`.  This makes me wonder if the numpy operations are being properly vectorized.

I suspect, in turn, that I botched things by putting in both `intel-numpy` and `numpy`, but am not sure how else I would have gotten the mkl libraries.

Also it seems suspicious that there would be some data that we're trying to put into xarray that is _not_ an ndarray (although I can't yet figure out how to find out what it _is_).

**Comment by ahartikainen** [comment]
Sounds like something from pymc is not transformed to numpy array? We had similar problem with pm.Data?

**Comment by rpgoldman** [comment]
I'm not sure what's wrong, because the call in Arviz is:

    vars_lpd = log_likelihood.var(dim="sample")

where `log_likelihood` is an `xarray` `DataArray`.

Here is the context:
```
    lppd_i = _wrap_xarray_ufunc(
        _logsumexp,
        log_likelihood,
        func_kwargs={"b_inv": n_samples},
        ufunc_kwargs=ufunc_kwargs,
        **kwargs,
    )

    vars_lpd = log_likelihood.var(dim="sample") # <--- this call raises the error
    warn_mg = False
    if np.any(vars_lpd > 0.4):
        warnings.warn(
            (
                "For one or more samples the posterior variance of the log predictive "
                "densities exceeds 0.4. This could be indication of WAIC starting to fail. \n"
                "See http://arxiv.org/abs/1507.04544 for details"
            )
        )
        warn_mg = True
```


In this we call a `wrapped_func` where the `func` is `<function _create_nan_agg_method.<locals>.f at 0x7f68b05e9d90>` (I guess `_logsumexp`?).

What's confusing is that I'm getting an error that claims to be because we are inside a branch guarded by `if not isinstance(data, np.ndarray)` but according to pdb, `data` _is_ an ndarray.  This seems deeply weird:

```
(Pdb) p type(data)
<class 'numpy.ndarray'>
(Pdb) p isinstance(data, np.ndarray)
False
```

Unfortunately, because `xarray.variable.as_compatible_data` changes the value of `data`, I'm not sure what it's value was coming *in*, only what it is *now*.

This whole thing is kind of confusing:

```
    if not isinstance(data, np.ndarray):
        if hasattr(data, "__array_function__"):
            if IS_NEP18_ACTIVE:
                return data
            else:
                raise TypeError(
                    "Got an NumPy-like array type providing the "
                    "__array_function__ protocol but NEP18 is not enabled. "
                    "Check that numpy >= v1.16 and that the environment "
                    'variable "NUMPY_EXPERIMENTAL_ARRAY_FUNCTION" is set to '
                    '"1"'
                )
```

because:
```
(Pdb) os.getenv("NUMPY_EXPERIMENTAL_ARRAY_FUNCTION")
'1'
```

...although, indeed `IS_NEP18_ACTIVE` is `False`.

I think that something must be going horribly wrong with numpy, because the following seems to be the  essence of the problem:

```
(Pdb) p data.__class__
<class 'numpy.ndarray'>
(Pdb) p data.__class__ == np.ndarray
False
(Pdb) p np.ndarray, data.__class__
(<class 'numpy.ndarray'>, <class 'numpy.ndarray'>)
```

So there are _two_ classes that print as ` <class 'numpy.ndarray'>` that are not the same thing.

**Comment by OriolAbril** [comment]
Any updates on this?

**Comment by rpgoldman** [comment]
I'm going to close this, because it's based on old versions of the code, and me using a sub-optimal way to install PyMC3 and ArviZ.
