### ISSUE TITLE
Keeping a Changelog

### ISSUE THREAD

**Issue by michaelosthege** [arviz-devs/arviz#980]
## Tell us about it

I just wanted to check if a bug (ess did not ignore tuned samples)  that we recently chatted about in the pymc Slack is already fixed. 

I'm just on my phone, ~~but couldn't find a changelog or release notes~~ and didn't find the release notes that are attached to the releases right away. .

## Thoughts on implementation
In addition to having release notes on the releases, the current unreleased changes could be tracked in a dedicated changelog file. 

I like the format that we use on pymc3, but there's also https://keepachangelog.com

**Comment by ahartikainen** [comment]
This is something we need. How would keepachangelog work?

**Comment by michaelosthege** [comment]
> This is something we need. How would keepachangelog work?

They give solid advice. Just like https://semver.org/

**Comment by OriolAbril** [comment]
Related to #604

**Comment by OriolAbril** [comment]
Changelog added in #1011
