### ISSUE TITLE
Integrate ic_scale rcParam

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#985]
## Tell us about it

`stats.ic_scale` has a default value in rcParams which is not yet used. 

Part of #792 

## Thoughts on implementation

`compare`, `waic` and `loo` should have `None` as default for `ic_scale` and use the default set in rcParams. The implementation should be very similar to
 `stats.information_criterion` integration with `ic` argument

**Comment by Shashankjain12** [comment]
@OriolAbril Can you assign me this issue I would be happy to work on that

**Comment by OriolAbril** [comment]
@Shashankjain12 you can work on that, there is no need to be assigned. It is great that you comment on the issue you plan to work on. 

One useful piece of advise in order to make sure you are not working on the same topic as somebody else (this is especially useful now that many of you are working on ArviZ to familiarize yourselves with it before GSoC), is to start by commenting on the issue just like you did and then once you start coding, send the pull request right away (even though it will probably not be finished). As said in the [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md), if you add `[WIP]` to the PR title and indicate the issue it fixes, it shows that work is currently ongoing.

Regarding your comment on Gitter, it looks like you are confusing `ic` (acronym for information criterion) with `ic_scale`. Working on rcParams can be quite confusing because the name of the rcParam may not always match exactly the argument used when calling ArviZ functions. I will try to clarify the issue description below, sorry about that.

 In this case, the two arg/rcParam pairs are `ic`/`information_criterion` and `scale`/`ic_scale`. These arguments are relevant for several functions like `loo`, `waic`, `compare` and `plot_elpd`. `ic` already uses `None` as default, which means that the used can customize the default using the `stats.information_criterion` rcParam. However, `scale` has `"deviance"` hardcoded as a default, instead of using the `stats.ic_scale` rcParam. 

The aim of the issue is to update `scale`/`ic_scale` to mimic the behaviour of `ic`/`information_criterion`

**Comment by Shashankjain12** [comment]
Sure @OriolAbril Thanks for sorting that out I will start working on this issue..👍

**Comment by Shashankjain12** [comment]
@OriolAbril I am not able to understand why my Travis CLI fails with
Bash exited with code '1'. Could you please help me what I can do to remove this error and pass all the checks
