### ISSUE TITLE
integrate credible_interval rcParam

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#986]
## Tell us about it

`stats.credible_interval` has a default value in rcParams which is not yet used. 

Part of #792 

## Thoughts on implementation

All `credible_interval` arguments should default to the value in rcParams. This affects both stats functions like `hpd` or `summary` and plotting functions. However, as most of them call `hpd` eventually, it may be possible to use `None` as default and let `hpd` handle the rcParam defaulting.

Also, tangentially related to #659

**Comment by Anjali167-sopho** [comment]
Can I start working on it?

**Comment by OriolAbril** [comment]
Yes! That would be great. When you create the PR link to this issue so other people reading the issue can see work on this is being done

Also, if there is anything not clear enough in the issues or in the contributing guide ask on gitter.

**Comment by percygautam** [comment]
Hey @OriolAbril , I am working on this issue as there is no response from @Anjali167-sopho yet !
Can you please provide more description of issue?

**Comment by OriolAbril** [comment]
rcParams allow ArviZ to have user customizable defaults like matplotlib. A more in depth description on how are they implemented in ArviZ can be found in #792. This issue indicates that `stats.credible_interval` is half-way of being usable. rcParams already contains a default value for it, but this value is only stored there. No plotting nor stats functions use it yet.

The aim of this issue is to change the default in ArviZ functions to `None` and that in the cases where users do not enter a value for credible interval, the value in rcParams is used. 

One example is [`plot_density`](https://arviz-devs.github.io/arviz/generated/arviz.plot_density.html#arviz.plot_density). It currently defaults to `0.94`, which is hardcoded. Instead, the desired behaviour would be:

* calling `plot_density(...)` uses as credible interval the value stored in rcParam `stats.credible_interval`
* calling `plot_density(..., credible_interval=0.94)` uses 0.94 independently of the rcParam value

**Comment by OriolAbril** [comment]
Regarding @Anjali167-sopho, maybe it is best to wait some days before taking over in case she already started working on it. #992 is a very similar issue with nobody assigned for now.

**Comment by percygautam** [comment]
Thanks @OriolAbril , I have started working on #992 . I have also partially completed this issue. Let's see if @Anjali167-sopho is working or not. After some weeks I'll come back to this issue.
