### ISSUE TITLE
integrate point_estimate rcParam

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#992]
## Tell us about it

`plot.point_estimate` has a default value in rcParams which is not yet used. Some plotting functions include a `point_estimate` kwarg to summarize the distribution and help its interpretation. `point_estimate` can take 4 possible values: mean, median, mode or `None`. 

Part of #792 

## Thoughts on implementation

`point_estimate` is currently hardcoded to have mean as its default, however, it would be interesting to change this default on a user or project basis. 

Appearances of `point_estimate` as argument should be set to have `"auto"` as a default, and in this case, to get the value from rcParams. This would allow users to still use `point_estimate=None` to indicate no point is to be plotted.

**Comment by nitishp25** [comment]
I would like to work on this :)

**Comment by percygautam** [comment]
I'll like to work on this issue

**Comment by nitishp25** [comment]
Oh I wasn't aware of that. Please go ahead.

**Comment by percygautam** [comment]
Hey @OriolAbril , I only found  densityplot() and posteriorplot() functions to have plot.point_estimate kwarg. Are there other plotting function that need to be changed?
